/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_ssi.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the SOC_APB_SSI core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_SSI_H__
#define __REG_SSI_H__

// Core register map
#define HAL_APB_SSI_VERSION 7.142
#define HAL_APB_SSI_BaseAddress 0xCF000000
#define HAL_APB_SSIREG_MAP ((struct halAPB_SSIReg_Map*) (void *) HAL_APB_SSI_BaseAddress)
__packed struct halAPB_SSIReg_Map
{
	HAL_Reg8  ReservedBlk0[1024];             //00000000
	HAL_Reg8  XWSRDADD;                       //00000400
	HAL_Reg8  ReservedBlk1[3];                //00000401
	HAL_Reg8  XWSRDDAT;                       //00000404
	HAL_Reg8  ReservedBlk2[3];                //00000405
	HAL_Reg8  XWSCLKDIV;                      //00000408
	HAL_Reg8  ReservedBlk3[3];                //00000409
	HAL_Reg8  XWSCFG0;                        //0000040C
	HAL_Reg8  ReservedBlk4[3];                //0000040D
	HAL_Reg8  XWSINT;                         //00000410
	HAL_Reg8  ReservedBlk5[3];                //00000411
	HAL_Reg8  XWSINTEN;                       //00000414
	HAL_Reg8  ReservedBlk6[3];                //00000415
	HAL_Reg8  XWSCFG1;                        //00000418
	HAL_Reg8  ReservedBlk7[3];                //00000419
	HAL_Reg8  XWSCFG2;                        //0000041C
	HAL_Reg8  ReservedBlk8[2019];             //0000041D
	HAL_Reg8  SSIRDADD;                       //00000C00
	HAL_Reg8  ReservedBlk9[3];                //00000C01
	HAL_Reg8  SSIRDDAT;                       //00000C04
	HAL_Reg8  ReservedBlk10[3];               //00000C05
	HAL_Reg8  SSICLKDIV;                      //00000C08
	HAL_Reg8  ReservedBlk11[3];               //00000C09
	HAL_Reg8  SSICFG0;                        //00000C0C
	HAL_Reg8  ReservedBlk12[3];               //00000C0D
	HAL_Reg8  SSIINT;                         //00000C10
	HAL_Reg8  ReservedBlk13[3];               //00000C11
	HAL_Reg8  SSIINTEN;                       //00000C14
	HAL_Reg8  ReservedBlk14[3];               //00000C15
	HAL_Reg8  SSICFG1;                        //00000C18
	HAL_Reg8  ReservedBlk15[3];               //00000C19
	HAL_Reg8  SSICFG2;                        //00000C1C
	HAL_Reg8  ReservedBlk16[2019];            //00000C1D
	HAL_Reg8  LCDRDADD;                       //00001400
	HAL_Reg8  ReservedBlk17[3];               //00001401
	HAL_Reg8  LCDRDDAT;                       //00001404
	HAL_Reg8  ReservedBlk18[3];               //00001405
	HAL_Reg8  LCDCLKDIV;                      //00001408
	HAL_Reg8  ReservedBlk19[3];               //00001409
	HAL_Reg8  LCDCFG0;                        //0000140C
	HAL_Reg8  ReservedBlk20[3];               //0000140D
	HAL_Reg8  LCDINT;                         //00001410
	HAL_Reg8  ReservedBlk21[3];               //00001411
	HAL_Reg8  LCDINTEN;                       //00001414
	HAL_Reg8  ReservedBlk22[3];               //00001415
	HAL_Reg8  LCDCFG1;                        //00001418
	HAL_Reg8  ReservedBlk23[3];               //00001419
	HAL_Reg8  LCDCFG2;                        //0000141C
	HAL_Reg8  ReservedBlk24[995];             //0000141D
	HAL_Reg8  SVCFG;                          //00001800
	HAL_Reg8  ReservedBlk25[3];               //00001801
	HAL_Reg8  SSISPARE;                       //00001804
};
// Register XWSRDADD
#define HAL_APB_SSI_XWSRDADD_REGISTER    (HAL_APB_SSIREG_MAP->XWSRDADD)
#define HAL_APB_SSI_XWSRDADD_LSB         0
#define HAL_APB_SSI_XWSRDADD_MSB         7
#define HAL_APB_SSI_XWSRDADD_MASK        0x000000FF
#define HAL_APB_SSI_XWSRDADD_TYPE        UByte
#define HAL_APB_SSI_XWSRDADD             HAL_APB_SSI_XWSRDADD_MASK
#define HAL_APB_SSI_XWSRDADD_READABLE    1
#define HAL_APB_SSI_XWSRDADD_WRITABLE    1
#define HAL_APB_SSI_XWSRDADD_SIGNED      0
#define HAL_APB_SSI_XWSRDADD_ADR         0xCF000400

// Register XWSRDDAT
#define HAL_APB_SSI_XWSRDDAT_REGISTER    (HAL_APB_SSIREG_MAP->XWSRDDAT)
#define HAL_APB_SSI_XWSRDDAT_LSB         0
#define HAL_APB_SSI_XWSRDDAT_MSB         7
#define HAL_APB_SSI_XWSRDDAT_MASK        0x000000FF
#define HAL_APB_SSI_XWSRDDAT_TYPE        UByte
#define HAL_APB_SSI_XWSRDDAT             HAL_APB_SSI_XWSRDDAT_MASK
#define HAL_APB_SSI_XWSRDDAT_READABLE    1
#define HAL_APB_SSI_XWSRDDAT_WRITABLE    0
#define HAL_APB_SSI_XWSRDDAT_SIGNED      0
#define HAL_APB_SSI_XWSRDDAT_ADR         0xCF000404

// Register XWSCLKDIV
#define HAL_APB_SSI_XWSCLKDIV_REGISTER    (HAL_APB_SSIREG_MAP->XWSCLKDIV)
#define HAL_APB_SSI_XWSCLKDIV_LSB         0
#define HAL_APB_SSI_XWSCLKDIV_MSB         7
#define HAL_APB_SSI_XWSCLKDIV_MASK        0x000000FF
#define HAL_APB_SSI_XWSCLKDIV_TYPE        UByte
#define HAL_APB_SSI_XWSCLKDIV             HAL_APB_SSI_XWSCLKDIV_MASK
#define HAL_APB_SSI_XWSCLKDIV_READABLE    1
#define HAL_APB_SSI_XWSCLKDIV_WRITABLE    1
#define HAL_APB_SSI_XWSCLKDIV_SIGNED      0
#define HAL_APB_SSI_XWSCLKDIV_ADR         0xCF000408

// Register XWSCFG0

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_WSDATADEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_WSDATADEN_LSB         7
#define HAL_APB_SSI_WSDATADEN_MSB         7
#define HAL_APB_SSI_WSDATADEN_MASK        0x00000080
#define HAL_APB_SSI_WSDATADEN_TYPE        Bool
#define HAL_APB_SSI_WSDATADEN             HAL_APB_SSI_WSDATADEN_MASK
#define HAL_APB_SSI_WSDATADEN_READABLE    1
#define HAL_APB_SSI_WSDATADEN_WRITABLE    1
#define HAL_APB_SSI_WSDATADEN_SIGNED      0
#define HAL_APB_SSI_WSDATADEN_ADR         0xCF00040C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_WTRNSHLD_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_WTRNSHLD_LSB         6
#define HAL_APB_SSI_WTRNSHLD_MSB         6
#define HAL_APB_SSI_WTRNSHLD_MASK        0x00000040
#define HAL_APB_SSI_WTRNSHLD_TYPE        Bool
#define HAL_APB_SSI_WTRNSHLD             HAL_APB_SSI_WTRNSHLD_MASK
#define HAL_APB_SSI_WTRNSHLD_READABLE    1
#define HAL_APB_SSI_WTRNSHLD_WRITABLE    1
#define HAL_APB_SSI_WTRNSHLD_SIGNED      0
#define HAL_APB_SSI_WTRNSHLD_ADR         0xCF00040C

#define HAL_APB_SSI_WALSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_WALSB2MSB_LSB         5
#define HAL_APB_SSI_WALSB2MSB_MSB         5
#define HAL_APB_SSI_WALSB2MSB_MASK        0x00000020
#define HAL_APB_SSI_WALSB2MSB_TYPE        Bool
#define HAL_APB_SSI_WALSB2MSB             HAL_APB_SSI_WALSB2MSB_MASK
#define HAL_APB_SSI_WALSB2MSB_READABLE    1
#define HAL_APB_SSI_WALSB2MSB_WRITABLE    1
#define HAL_APB_SSI_WALSB2MSB_SIGNED      0
#define HAL_APB_SSI_WALSB2MSB_ADR         0xCF00040C

#define HAL_APB_SSI_WDLSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_WDLSB2MSB_LSB         4
#define HAL_APB_SSI_WDLSB2MSB_MSB         4
#define HAL_APB_SSI_WDLSB2MSB_MASK        0x00000010
#define HAL_APB_SSI_WDLSB2MSB_TYPE        Bool
#define HAL_APB_SSI_WDLSB2MSB             HAL_APB_SSI_WDLSB2MSB_MASK
#define HAL_APB_SSI_WDLSB2MSB_READABLE    1
#define HAL_APB_SSI_WDLSB2MSB_WRITABLE    1
#define HAL_APB_SSI_WDLSB2MSB_SIGNED      0
#define HAL_APB_SSI_WDLSB2MSB_ADR         0xCF00040C

#define HAL_APB_SSI_WSCLKINV_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_WSCLKINV_LSB         3
#define HAL_APB_SSI_WSCLKINV_MSB         3
#define HAL_APB_SSI_WSCLKINV_MASK        0x00000008
#define HAL_APB_SSI_WSCLKINV_TYPE        Bool
#define HAL_APB_SSI_WSCLKINV             HAL_APB_SSI_WSCLKINV_MASK
#define HAL_APB_SSI_WSCLKINV_READABLE    1
#define HAL_APB_SSI_WSCLKINV_WRITABLE    1
#define HAL_APB_SSI_WSCLKINV_SIGNED      0
#define HAL_APB_SSI_WSCLKINV_ADR         0xCF00040C

#define HAL_APB_SSI_SENINV_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_SENINV_LSB         2
#define HAL_APB_SSI_SENINV_MSB         2
#define HAL_APB_SSI_SENINV_MASK        0x00000004
#define HAL_APB_SSI_SENINV_TYPE        Bool
#define HAL_APB_SSI_SENINV             HAL_APB_SSI_SENINV_MASK
#define HAL_APB_SSI_SENINV_READABLE    1
#define HAL_APB_SSI_SENINV_WRITABLE    1
#define HAL_APB_SSI_SENINV_SIGNED      0
#define HAL_APB_SSI_SENINV_ADR         0xCF00040C

#define HAL_APB_SSI_EXTSEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_EXTSEN_LSB         1
#define HAL_APB_SSI_EXTSEN_MSB         1
#define HAL_APB_SSI_EXTSEN_MASK        0x00000002
#define HAL_APB_SSI_EXTSEN_TYPE        Bool
#define HAL_APB_SSI_EXTSEN             HAL_APB_SSI_EXTSEN_MASK
#define HAL_APB_SSI_EXTSEN_READABLE    1
#define HAL_APB_SSI_EXTSEN_WRITABLE    1
#define HAL_APB_SSI_EXTSEN_SIGNED      0
#define HAL_APB_SSI_EXTSEN_ADR         0xCF00040C

#define HAL_APB_SSI_PSEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG0)
#define HAL_APB_SSI_PSEN_LSB         0
#define HAL_APB_SSI_PSEN_MSB         0
#define HAL_APB_SSI_PSEN_MASK        0x00000001
#define HAL_APB_SSI_PSEN_TYPE        Bool
#define HAL_APB_SSI_PSEN             HAL_APB_SSI_PSEN_MASK
#define HAL_APB_SSI_PSEN_READABLE    1
#define HAL_APB_SSI_PSEN_WRITABLE    1
#define HAL_APB_SSI_PSEN_SIGNED      0
#define HAL_APB_SSI_PSEN_ADR         0xCF00040C

// Register XWSINT
#define HAL_APB_SSI_WFIFHLF_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WFIFHLF_LSB         6
#define HAL_APB_SSI_WFIFHLF_MSB         6
#define HAL_APB_SSI_WFIFHLF_MASK        0x00000040
#define HAL_APB_SSI_WFIFHLF_TYPE        Bool
#define HAL_APB_SSI_WFIFHLF             HAL_APB_SSI_WFIFHLF_MASK
#define HAL_APB_SSI_WFIFHLF_READABLE    1
#define HAL_APB_SSI_WFIFHLF_WRITABLE    1
#define HAL_APB_SSI_WFIFHLF_SIGNED      0
#define HAL_APB_SSI_WFIFHLF_ADR         0xCF000410

#define HAL_APB_SSI_WFIFFUL_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WFIFFUL_LSB         5
#define HAL_APB_SSI_WFIFFUL_MSB         5
#define HAL_APB_SSI_WFIFFUL_MASK        0x00000020
#define HAL_APB_SSI_WFIFFUL_TYPE        Bool
#define HAL_APB_SSI_WFIFFUL             HAL_APB_SSI_WFIFFUL_MASK
#define HAL_APB_SSI_WFIFFUL_READABLE    1
#define HAL_APB_SSI_WFIFFUL_WRITABLE    1
#define HAL_APB_SSI_WFIFFUL_SIGNED      0
#define HAL_APB_SSI_WFIFFUL_ADR         0xCF000410

#define HAL_APB_SSI_WFIFEMP_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WFIFEMP_LSB         4
#define HAL_APB_SSI_WFIFEMP_MSB         4
#define HAL_APB_SSI_WFIFEMP_MASK        0x00000010
#define HAL_APB_SSI_WFIFEMP_TYPE        Bool
#define HAL_APB_SSI_WFIFEMP             HAL_APB_SSI_WFIFEMP_MASK
#define HAL_APB_SSI_WFIFEMP_READABLE    1
#define HAL_APB_SSI_WFIFEMP_WRITABLE    1
#define HAL_APB_SSI_WFIFEMP_SIGNED      0
#define HAL_APB_SSI_WFIFEMP_ADR         0xCF000410

#define HAL_APB_SSI_WRDVALD_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WRDVALD_LSB         3
#define HAL_APB_SSI_WRDVALD_MSB         3
#define HAL_APB_SSI_WRDVALD_MASK        0x00000008
#define HAL_APB_SSI_WRDVALD_TYPE        Bool
#define HAL_APB_SSI_WRDVALD             HAL_APB_SSI_WRDVALD_MASK
#define HAL_APB_SSI_WRDVALD_READABLE    1
#define HAL_APB_SSI_WRDVALD_WRITABLE    1
#define HAL_APB_SSI_WRDVALD_SIGNED      0
#define HAL_APB_SSI_WRDVALD_ADR         0xCF000410

#define HAL_APB_SSI_WFIFERR_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WFIFERR_LSB         2
#define HAL_APB_SSI_WFIFERR_MSB         2
#define HAL_APB_SSI_WFIFERR_MASK        0x00000004
#define HAL_APB_SSI_WFIFERR_TYPE        Bool
#define HAL_APB_SSI_WFIFERR             HAL_APB_SSI_WFIFERR_MASK
#define HAL_APB_SSI_WFIFERR_READABLE    1
#define HAL_APB_SSI_WFIFERR_WRITABLE    1
#define HAL_APB_SSI_WFIFERR_SIGNED      0
#define HAL_APB_SSI_WFIFERR_ADR         0xCF000410

#define HAL_APB_SSI_WRDERR_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WRDERR_LSB         1
#define HAL_APB_SSI_WRDERR_MSB         1
#define HAL_APB_SSI_WRDERR_MASK        0x00000002
#define HAL_APB_SSI_WRDERR_TYPE        Bool
#define HAL_APB_SSI_WRDERR             HAL_APB_SSI_WRDERR_MASK
#define HAL_APB_SSI_WRDERR_READABLE    1
#define HAL_APB_SSI_WRDERR_WRITABLE    1
#define HAL_APB_SSI_WRDERR_SIGNED      0
#define HAL_APB_SSI_WRDERR_ADR         0xCF000410

#define HAL_APB_SSI_WCMDERR_REGISTER    (HAL_APB_SSIREG_MAP->XWSINT)
#define HAL_APB_SSI_WCMDERR_LSB         0
#define HAL_APB_SSI_WCMDERR_MSB         0
#define HAL_APB_SSI_WCMDERR_MASK        0x00000001
#define HAL_APB_SSI_WCMDERR_TYPE        Bool
#define HAL_APB_SSI_WCMDERR             HAL_APB_SSI_WCMDERR_MASK
#define HAL_APB_SSI_WCMDERR_READABLE    1
#define HAL_APB_SSI_WCMDERR_WRITABLE    1
#define HAL_APB_SSI_WCMDERR_SIGNED      0
#define HAL_APB_SSI_WCMDERR_ADR         0xCF000410

// Register XWSINTEN
#define HAL_APB_SSI_WFIFHLFEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WFIFHLFEN_LSB         6
#define HAL_APB_SSI_WFIFHLFEN_MSB         6
#define HAL_APB_SSI_WFIFHLFEN_MASK        0x00000040
#define HAL_APB_SSI_WFIFHLFEN_TYPE        Bool
#define HAL_APB_SSI_WFIFHLFEN             HAL_APB_SSI_WFIFHLFEN_MASK
#define HAL_APB_SSI_WFIFHLFEN_READABLE    1
#define HAL_APB_SSI_WFIFHLFEN_WRITABLE    1
#define HAL_APB_SSI_WFIFHLFEN_SIGNED      0
#define HAL_APB_SSI_WFIFHLFEN_ADR         0xCF000414

#define HAL_APB_SSI_WFIFFULEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WFIFFULEN_LSB         5
#define HAL_APB_SSI_WFIFFULEN_MSB         5
#define HAL_APB_SSI_WFIFFULEN_MASK        0x00000020
#define HAL_APB_SSI_WFIFFULEN_TYPE        Bool
#define HAL_APB_SSI_WFIFFULEN             HAL_APB_SSI_WFIFFULEN_MASK
#define HAL_APB_SSI_WFIFFULEN_READABLE    1
#define HAL_APB_SSI_WFIFFULEN_WRITABLE    1
#define HAL_APB_SSI_WFIFFULEN_SIGNED      0
#define HAL_APB_SSI_WFIFFULEN_ADR         0xCF000414

#define HAL_APB_SSI_WFIFEMPEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WFIFEMPEN_LSB         4
#define HAL_APB_SSI_WFIFEMPEN_MSB         4
#define HAL_APB_SSI_WFIFEMPEN_MASK        0x00000010
#define HAL_APB_SSI_WFIFEMPEN_TYPE        Bool
#define HAL_APB_SSI_WFIFEMPEN             HAL_APB_SSI_WFIFEMPEN_MASK
#define HAL_APB_SSI_WFIFEMPEN_READABLE    1
#define HAL_APB_SSI_WFIFEMPEN_WRITABLE    1
#define HAL_APB_SSI_WFIFEMPEN_SIGNED      0
#define HAL_APB_SSI_WFIFEMPEN_ADR         0xCF000414

#define HAL_APB_SSI_WRDVALDEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WRDVALDEN_LSB         3
#define HAL_APB_SSI_WRDVALDEN_MSB         3
#define HAL_APB_SSI_WRDVALDEN_MASK        0x00000008
#define HAL_APB_SSI_WRDVALDEN_TYPE        Bool
#define HAL_APB_SSI_WRDVALDEN             HAL_APB_SSI_WRDVALDEN_MASK
#define HAL_APB_SSI_WRDVALDEN_READABLE    1
#define HAL_APB_SSI_WRDVALDEN_WRITABLE    1
#define HAL_APB_SSI_WRDVALDEN_SIGNED      0
#define HAL_APB_SSI_WRDVALDEN_ADR         0xCF000414

#define HAL_APB_SSI_WFIFERREN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WFIFERREN_LSB         2
#define HAL_APB_SSI_WFIFERREN_MSB         2
#define HAL_APB_SSI_WFIFERREN_MASK        0x00000004
#define HAL_APB_SSI_WFIFERREN_TYPE        Bool
#define HAL_APB_SSI_WFIFERREN             HAL_APB_SSI_WFIFERREN_MASK
#define HAL_APB_SSI_WFIFERREN_READABLE    1
#define HAL_APB_SSI_WFIFERREN_WRITABLE    1
#define HAL_APB_SSI_WFIFERREN_SIGNED      0
#define HAL_APB_SSI_WFIFERREN_ADR         0xCF000414

#define HAL_APB_SSI_WRDERREN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WRDERREN_LSB         1
#define HAL_APB_SSI_WRDERREN_MSB         1
#define HAL_APB_SSI_WRDERREN_MASK        0x00000002
#define HAL_APB_SSI_WRDERREN_TYPE        Bool
#define HAL_APB_SSI_WRDERREN             HAL_APB_SSI_WRDERREN_MASK
#define HAL_APB_SSI_WRDERREN_READABLE    1
#define HAL_APB_SSI_WRDERREN_WRITABLE    1
#define HAL_APB_SSI_WRDERREN_SIGNED      0
#define HAL_APB_SSI_WRDERREN_ADR         0xCF000414

#define HAL_APB_SSI_WCMDERREN_REGISTER    (HAL_APB_SSIREG_MAP->XWSINTEN)
#define HAL_APB_SSI_WCMDERREN_LSB         0
#define HAL_APB_SSI_WCMDERREN_MSB         0
#define HAL_APB_SSI_WCMDERREN_MASK        0x00000001
#define HAL_APB_SSI_WCMDERREN_TYPE        Bool
#define HAL_APB_SSI_WCMDERREN             HAL_APB_SSI_WCMDERREN_MASK
#define HAL_APB_SSI_WCMDERREN_READABLE    1
#define HAL_APB_SSI_WCMDERREN_WRITABLE    1
#define HAL_APB_SSI_WCMDERREN_SIGNED      0
#define HAL_APB_SSI_WCMDERREN_ADR         0xCF000414

// Register XWSCFG1
#define HAL_APB_SSI_WMANEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG1)
#define HAL_APB_SSI_WMANEN_LSB         4
#define HAL_APB_SSI_WMANEN_MSB         4
#define HAL_APB_SSI_WMANEN_MASK        0x00000010
#define HAL_APB_SSI_WMANEN_TYPE        Bool
#define HAL_APB_SSI_WMANEN             HAL_APB_SSI_WMANEN_MASK
#define HAL_APB_SSI_WMANEN_READABLE    1
#define HAL_APB_SSI_WMANEN_WRITABLE    1
#define HAL_APB_SSI_WMANEN_SIGNED      0
#define HAL_APB_SSI_WMANEN_ADR         0xCF000418

#define HAL_APB_SSI_WMODEPOL_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG1)
#define HAL_APB_SSI_WMODEPOL_LSB         3
#define HAL_APB_SSI_WMODEPOL_MSB         3
#define HAL_APB_SSI_WMODEPOL_MASK        0x00000008
#define HAL_APB_SSI_WMODEPOL_TYPE        Bool
#define HAL_APB_SSI_WMODEPOL             HAL_APB_SSI_WMODEPOL_MASK
#define HAL_APB_SSI_WMODEPOL_READABLE    1
#define HAL_APB_SSI_WMODEPOL_WRITABLE    1
#define HAL_APB_SSI_WMODEPOL_SIGNED      0
#define HAL_APB_SSI_WMODEPOL_ADR         0xCF000418

#define HAL_APB_SSI_WMODELOC_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG1)
#define HAL_APB_SSI_WMODELOC_LSB         2
#define HAL_APB_SSI_WMODELOC_MSB         2
#define HAL_APB_SSI_WMODELOC_MASK        0x00000004
#define HAL_APB_SSI_WMODELOC_TYPE        Bool
#define HAL_APB_SSI_WMODELOC             HAL_APB_SSI_WMODELOC_MASK
#define HAL_APB_SSI_WMODELOC_READABLE    1
#define HAL_APB_SSI_WMODELOC_WRITABLE    1
#define HAL_APB_SSI_WMODELOC_SIGNED      0
#define HAL_APB_SSI_WMODELOC_ADR         0xCF000418

#define HAL_APB_SSI_WDATA1ST_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG1)
#define HAL_APB_SSI_WDATA1ST_LSB         1
#define HAL_APB_SSI_WDATA1ST_MSB         1
#define HAL_APB_SSI_WDATA1ST_MASK        0x00000002
#define HAL_APB_SSI_WDATA1ST_TYPE        Bool
#define HAL_APB_SSI_WDATA1ST             HAL_APB_SSI_WDATA1ST_MASK
#define HAL_APB_SSI_WDATA1ST_READABLE    1
#define HAL_APB_SSI_WDATA1ST_WRITABLE    1
#define HAL_APB_SSI_WDATA1ST_SIGNED      0
#define HAL_APB_SSI_WDATA1ST_ADR         0xCF000418

#define HAL_APB_SSI_USEBUSY_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG1)
#define HAL_APB_SSI_USEBUSY_LSB         0
#define HAL_APB_SSI_USEBUSY_MSB         0
#define HAL_APB_SSI_USEBUSY_MASK        0x00000001
#define HAL_APB_SSI_USEBUSY_TYPE        Bool
#define HAL_APB_SSI_USEBUSY             HAL_APB_SSI_USEBUSY_MASK
#define HAL_APB_SSI_USEBUSY_READABLE    1
#define HAL_APB_SSI_USEBUSY_WRITABLE    1
#define HAL_APB_SSI_USEBUSY_SIGNED      0
#define HAL_APB_SSI_USEBUSY_ADR         0xCF000418

// Register XWSCFG2

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_WDATAIDEN_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG2)
#define HAL_APB_SSI_WDATAIDEN_LSB         3
#define HAL_APB_SSI_WDATAIDEN_MSB         3
#define HAL_APB_SSI_WDATAIDEN_MASK        0x00000008
#define HAL_APB_SSI_WDATAIDEN_TYPE        Bool
#define HAL_APB_SSI_WDATAIDEN             HAL_APB_SSI_WDATAIDEN_MASK
#define HAL_APB_SSI_WDATAIDEN_READABLE    1
#define HAL_APB_SSI_WDATAIDEN_WRITABLE    1
#define HAL_APB_SSI_WDATAIDEN_SIGNED      0
#define HAL_APB_SSI_WDATAIDEN_ADR         0xCF00041C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_WSCLKDLY_REGISTER    (HAL_APB_SSIREG_MAP->XWSCFG2)
#define HAL_APB_SSI_WSCLKDLY_LSB         0
#define HAL_APB_SSI_WSCLKDLY_MSB         2
#define HAL_APB_SSI_WSCLKDLY_MASK        0x00000007
#define HAL_APB_SSI_WSCLKDLY_TYPE        UByte
#define HAL_APB_SSI_WSCLKDLY             HAL_APB_SSI_WSCLKDLY_MASK
#define HAL_APB_SSI_WSCLKDLY_READABLE    1
#define HAL_APB_SSI_WSCLKDLY_WRITABLE    1
#define HAL_APB_SSI_WSCLKDLY_SIGNED      0
#define HAL_APB_SSI_WSCLKDLY_ADR         0xCF00041C

// Register SSIRDADD
#define HAL_APB_SSI_SSIRDADD_REGISTER    (HAL_APB_SSIREG_MAP->SSIRDADD)
#define HAL_APB_SSI_SSIRDADD_LSB         0
#define HAL_APB_SSI_SSIRDADD_MSB         7
#define HAL_APB_SSI_SSIRDADD_MASK        0x000000FF
#define HAL_APB_SSI_SSIRDADD_TYPE        UByte
#define HAL_APB_SSI_SSIRDADD             HAL_APB_SSI_SSIRDADD_MASK
#define HAL_APB_SSI_SSIRDADD_READABLE    1
#define HAL_APB_SSI_SSIRDADD_WRITABLE    1
#define HAL_APB_SSI_SSIRDADD_SIGNED      0
#define HAL_APB_SSI_SSIRDADD_ADR         0xCF000C00

// Register SSIRDDAT
#define HAL_APB_SSI_SSIRDDAT_REGISTER    (HAL_APB_SSIREG_MAP->SSIRDDAT)
#define HAL_APB_SSI_SSIRDDAT_LSB         0
#define HAL_APB_SSI_SSIRDDAT_MSB         7
#define HAL_APB_SSI_SSIRDDAT_MASK        0x000000FF
#define HAL_APB_SSI_SSIRDDAT_TYPE        UByte
#define HAL_APB_SSI_SSIRDDAT             HAL_APB_SSI_SSIRDDAT_MASK
#define HAL_APB_SSI_SSIRDDAT_READABLE    1
#define HAL_APB_SSI_SSIRDDAT_WRITABLE    0
#define HAL_APB_SSI_SSIRDDAT_SIGNED      0
#define HAL_APB_SSI_SSIRDDAT_ADR         0xCF000C04

// Register SSICLKDIV
#define HAL_APB_SSI_SSICLKDIV_REGISTER    (HAL_APB_SSIREG_MAP->SSICLKDIV)
#define HAL_APB_SSI_SSICLKDIV_LSB         0
#define HAL_APB_SSI_SSICLKDIV_MSB         7
#define HAL_APB_SSI_SSICLKDIV_MASK        0x000000FF
#define HAL_APB_SSI_SSICLKDIV_TYPE        UByte
#define HAL_APB_SSI_SSICLKDIV             HAL_APB_SSI_SSICLKDIV_MASK
#define HAL_APB_SSI_SSICLKDIV_READABLE    1
#define HAL_APB_SSI_SSICLKDIV_WRITABLE    1
#define HAL_APB_SSI_SSICLKDIV_SIGNED      0
#define HAL_APB_SSI_SSICLKDIV_ADR         0xCF000C08

// Register SSICFG0

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_SSDATADEN_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_SSDATADEN_LSB         7
#define HAL_APB_SSI_SSDATADEN_MSB         7
#define HAL_APB_SSI_SSDATADEN_MASK        0x00000080
#define HAL_APB_SSI_SSDATADEN_TYPE        Bool
#define HAL_APB_SSI_SSDATADEN             HAL_APB_SSI_SSDATADEN_MASK
#define HAL_APB_SSI_SSDATADEN_READABLE    1
#define HAL_APB_SSI_SSDATADEN_WRITABLE    1
#define HAL_APB_SSI_SSDATADEN_SIGNED      0
#define HAL_APB_SSI_SSDATADEN_ADR         0xCF000C0C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_STRNSHLD_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_STRNSHLD_LSB         6
#define HAL_APB_SSI_STRNSHLD_MSB         6
#define HAL_APB_SSI_STRNSHLD_MASK        0x00000040
#define HAL_APB_SSI_STRNSHLD_TYPE        Bool
#define HAL_APB_SSI_STRNSHLD             HAL_APB_SSI_STRNSHLD_MASK
#define HAL_APB_SSI_STRNSHLD_READABLE    1
#define HAL_APB_SSI_STRNSHLD_WRITABLE    1
#define HAL_APB_SSI_STRNSHLD_SIGNED      0
#define HAL_APB_SSI_STRNSHLD_ADR         0xCF000C0C

#define HAL_APB_SSI_SALSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_SALSB2MSB_LSB         5
#define HAL_APB_SSI_SALSB2MSB_MSB         5
#define HAL_APB_SSI_SALSB2MSB_MASK        0x00000020
#define HAL_APB_SSI_SALSB2MSB_TYPE        Bool
#define HAL_APB_SSI_SALSB2MSB             HAL_APB_SSI_SALSB2MSB_MASK
#define HAL_APB_SSI_SALSB2MSB_READABLE    1
#define HAL_APB_SSI_SALSB2MSB_WRITABLE    1
#define HAL_APB_SSI_SALSB2MSB_SIGNED      0
#define HAL_APB_SSI_SALSB2MSB_ADR         0xCF000C0C

#define HAL_APB_SSI_SDLSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_SDLSB2MSB_LSB         4
#define HAL_APB_SSI_SDLSB2MSB_MSB         4
#define HAL_APB_SSI_SDLSB2MSB_MASK        0x00000010
#define HAL_APB_SSI_SDLSB2MSB_TYPE        Bool
#define HAL_APB_SSI_SDLSB2MSB             HAL_APB_SSI_SDLSB2MSB_MASK
#define HAL_APB_SSI_SDLSB2MSB_READABLE    1
#define HAL_APB_SSI_SDLSB2MSB_WRITABLE    1
#define HAL_APB_SSI_SDLSB2MSB_SIGNED      0
#define HAL_APB_SSI_SDLSB2MSB_ADR         0xCF000C0C

#define HAL_APB_SSI_SSCLKINV_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_SSCLKINV_LSB         3
#define HAL_APB_SSI_SSCLKINV_MSB         3
#define HAL_APB_SSI_SSCLKINV_MASK        0x00000008
#define HAL_APB_SSI_SSCLKINV_TYPE        Bool
#define HAL_APB_SSI_SSCLKINV             HAL_APB_SSI_SSCLKINV_MASK
#define HAL_APB_SSI_SSCLKINV_READABLE    1
#define HAL_APB_SSI_SSCLKINV_WRITABLE    1
#define HAL_APB_SSI_SSCLKINV_SIGNED      0
#define HAL_APB_SSI_SSCLKINV_ADR         0xCF000C0C

#define HAL_APB_SSI_SEN2INV_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_SEN2INV_LSB         2
#define HAL_APB_SSI_SEN2INV_MSB         2
#define HAL_APB_SSI_SEN2INV_MASK        0x00000004
#define HAL_APB_SSI_SEN2INV_TYPE        Bool
#define HAL_APB_SSI_SEN2INV             HAL_APB_SSI_SEN2INV_MASK
#define HAL_APB_SSI_SEN2INV_READABLE    1
#define HAL_APB_SSI_SEN2INV_WRITABLE    1
#define HAL_APB_SSI_SEN2INV_SIGNED      0
#define HAL_APB_SSI_SEN2INV_ADR         0xCF000C0C

#define HAL_APB_SSI_EXTSEN2_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_EXTSEN2_LSB         1
#define HAL_APB_SSI_EXTSEN2_MSB         1
#define HAL_APB_SSI_EXTSEN2_MASK        0x00000002
#define HAL_APB_SSI_EXTSEN2_TYPE        Bool
#define HAL_APB_SSI_EXTSEN2             HAL_APB_SSI_EXTSEN2_MASK
#define HAL_APB_SSI_EXTSEN2_READABLE    1
#define HAL_APB_SSI_EXTSEN2_WRITABLE    1
#define HAL_APB_SSI_EXTSEN2_SIGNED      0
#define HAL_APB_SSI_EXTSEN2_ADR         0xCF000C0C

#define HAL_APB_SSI_PSEN2_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG0)
#define HAL_APB_SSI_PSEN2_LSB         0
#define HAL_APB_SSI_PSEN2_MSB         0
#define HAL_APB_SSI_PSEN2_MASK        0x00000001
#define HAL_APB_SSI_PSEN2_TYPE        Bool
#define HAL_APB_SSI_PSEN2             HAL_APB_SSI_PSEN2_MASK
#define HAL_APB_SSI_PSEN2_READABLE    1
#define HAL_APB_SSI_PSEN2_WRITABLE    1
#define HAL_APB_SSI_PSEN2_SIGNED      0
#define HAL_APB_SSI_PSEN2_ADR         0xCF000C0C

// Register SSIINT
#define HAL_APB_SSI_SFIFHLF_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SFIFHLF_LSB         6
#define HAL_APB_SSI_SFIFHLF_MSB         6
#define HAL_APB_SSI_SFIFHLF_MASK        0x00000040
#define HAL_APB_SSI_SFIFHLF_TYPE        Bool
#define HAL_APB_SSI_SFIFHLF             HAL_APB_SSI_SFIFHLF_MASK
#define HAL_APB_SSI_SFIFHLF_READABLE    1
#define HAL_APB_SSI_SFIFHLF_WRITABLE    1
#define HAL_APB_SSI_SFIFHLF_SIGNED      0
#define HAL_APB_SSI_SFIFHLF_ADR         0xCF000C10

#define HAL_APB_SSI_SFIFFUL_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SFIFFUL_LSB         5
#define HAL_APB_SSI_SFIFFUL_MSB         5
#define HAL_APB_SSI_SFIFFUL_MASK        0x00000020
#define HAL_APB_SSI_SFIFFUL_TYPE        Bool
#define HAL_APB_SSI_SFIFFUL             HAL_APB_SSI_SFIFFUL_MASK
#define HAL_APB_SSI_SFIFFUL_READABLE    1
#define HAL_APB_SSI_SFIFFUL_WRITABLE    1
#define HAL_APB_SSI_SFIFFUL_SIGNED      0
#define HAL_APB_SSI_SFIFFUL_ADR         0xCF000C10

#define HAL_APB_SSI_SFIFEMP_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SFIFEMP_LSB         4
#define HAL_APB_SSI_SFIFEMP_MSB         4
#define HAL_APB_SSI_SFIFEMP_MASK        0x00000010
#define HAL_APB_SSI_SFIFEMP_TYPE        Bool
#define HAL_APB_SSI_SFIFEMP             HAL_APB_SSI_SFIFEMP_MASK
#define HAL_APB_SSI_SFIFEMP_READABLE    1
#define HAL_APB_SSI_SFIFEMP_WRITABLE    1
#define HAL_APB_SSI_SFIFEMP_SIGNED      0
#define HAL_APB_SSI_SFIFEMP_ADR         0xCF000C10

#define HAL_APB_SSI_SRDVALD_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SRDVALD_LSB         3
#define HAL_APB_SSI_SRDVALD_MSB         3
#define HAL_APB_SSI_SRDVALD_MASK        0x00000008
#define HAL_APB_SSI_SRDVALD_TYPE        Bool
#define HAL_APB_SSI_SRDVALD             HAL_APB_SSI_SRDVALD_MASK
#define HAL_APB_SSI_SRDVALD_READABLE    1
#define HAL_APB_SSI_SRDVALD_WRITABLE    1
#define HAL_APB_SSI_SRDVALD_SIGNED      0
#define HAL_APB_SSI_SRDVALD_ADR         0xCF000C10

#define HAL_APB_SSI_SFIFERR_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SFIFERR_LSB         2
#define HAL_APB_SSI_SFIFERR_MSB         2
#define HAL_APB_SSI_SFIFERR_MASK        0x00000004
#define HAL_APB_SSI_SFIFERR_TYPE        Bool
#define HAL_APB_SSI_SFIFERR             HAL_APB_SSI_SFIFERR_MASK
#define HAL_APB_SSI_SFIFERR_READABLE    1
#define HAL_APB_SSI_SFIFERR_WRITABLE    1
#define HAL_APB_SSI_SFIFERR_SIGNED      0
#define HAL_APB_SSI_SFIFERR_ADR         0xCF000C10

#define HAL_APB_SSI_SRDERR_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SRDERR_LSB         1
#define HAL_APB_SSI_SRDERR_MSB         1
#define HAL_APB_SSI_SRDERR_MASK        0x00000002
#define HAL_APB_SSI_SRDERR_TYPE        Bool
#define HAL_APB_SSI_SRDERR             HAL_APB_SSI_SRDERR_MASK
#define HAL_APB_SSI_SRDERR_READABLE    1
#define HAL_APB_SSI_SRDERR_WRITABLE    1
#define HAL_APB_SSI_SRDERR_SIGNED      0
#define HAL_APB_SSI_SRDERR_ADR         0xCF000C10

#define HAL_APB_SSI_SCMDERR_REGISTER    (HAL_APB_SSIREG_MAP->SSIINT)
#define HAL_APB_SSI_SCMDERR_LSB         0
#define HAL_APB_SSI_SCMDERR_MSB         0
#define HAL_APB_SSI_SCMDERR_MASK        0x00000001
#define HAL_APB_SSI_SCMDERR_TYPE        Bool
#define HAL_APB_SSI_SCMDERR             HAL_APB_SSI_SCMDERR_MASK
#define HAL_APB_SSI_SCMDERR_READABLE    1
#define HAL_APB_SSI_SCMDERR_WRITABLE    1
#define HAL_APB_SSI_SCMDERR_SIGNED      0
#define HAL_APB_SSI_SCMDERR_ADR         0xCF000C10

// Register SSIINTEN
#define HAL_APB_SSI_SFIFHLFEN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SFIFHLFEN_LSB         6
#define HAL_APB_SSI_SFIFHLFEN_MSB         6
#define HAL_APB_SSI_SFIFHLFEN_MASK        0x00000040
#define HAL_APB_SSI_SFIFHLFEN_TYPE        Bool
#define HAL_APB_SSI_SFIFHLFEN             HAL_APB_SSI_SFIFHLFEN_MASK
#define HAL_APB_SSI_SFIFHLFEN_READABLE    1
#define HAL_APB_SSI_SFIFHLFEN_WRITABLE    1
#define HAL_APB_SSI_SFIFHLFEN_SIGNED      0
#define HAL_APB_SSI_SFIFHLFEN_ADR         0xCF000C14

#define HAL_APB_SSI_SFIFFULEN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SFIFFULEN_LSB         5
#define HAL_APB_SSI_SFIFFULEN_MSB         5
#define HAL_APB_SSI_SFIFFULEN_MASK        0x00000020
#define HAL_APB_SSI_SFIFFULEN_TYPE        Bool
#define HAL_APB_SSI_SFIFFULEN             HAL_APB_SSI_SFIFFULEN_MASK
#define HAL_APB_SSI_SFIFFULEN_READABLE    1
#define HAL_APB_SSI_SFIFFULEN_WRITABLE    1
#define HAL_APB_SSI_SFIFFULEN_SIGNED      0
#define HAL_APB_SSI_SFIFFULEN_ADR         0xCF000C14

#define HAL_APB_SSI_SFIFEMPEN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SFIFEMPEN_LSB         4
#define HAL_APB_SSI_SFIFEMPEN_MSB         4
#define HAL_APB_SSI_SFIFEMPEN_MASK        0x00000010
#define HAL_APB_SSI_SFIFEMPEN_TYPE        Bool
#define HAL_APB_SSI_SFIFEMPEN             HAL_APB_SSI_SFIFEMPEN_MASK
#define HAL_APB_SSI_SFIFEMPEN_READABLE    1
#define HAL_APB_SSI_SFIFEMPEN_WRITABLE    1
#define HAL_APB_SSI_SFIFEMPEN_SIGNED      0
#define HAL_APB_SSI_SFIFEMPEN_ADR         0xCF000C14

#define HAL_APB_SSI_SRDVALDEN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SRDVALDEN_LSB         3
#define HAL_APB_SSI_SRDVALDEN_MSB         3
#define HAL_APB_SSI_SRDVALDEN_MASK        0x00000008
#define HAL_APB_SSI_SRDVALDEN_TYPE        Bool
#define HAL_APB_SSI_SRDVALDEN             HAL_APB_SSI_SRDVALDEN_MASK
#define HAL_APB_SSI_SRDVALDEN_READABLE    1
#define HAL_APB_SSI_SRDVALDEN_WRITABLE    1
#define HAL_APB_SSI_SRDVALDEN_SIGNED      0
#define HAL_APB_SSI_SRDVALDEN_ADR         0xCF000C14

#define HAL_APB_SSI_SFIFERREN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SFIFERREN_LSB         2
#define HAL_APB_SSI_SFIFERREN_MSB         2
#define HAL_APB_SSI_SFIFERREN_MASK        0x00000004
#define HAL_APB_SSI_SFIFERREN_TYPE        Bool
#define HAL_APB_SSI_SFIFERREN             HAL_APB_SSI_SFIFERREN_MASK
#define HAL_APB_SSI_SFIFERREN_READABLE    1
#define HAL_APB_SSI_SFIFERREN_WRITABLE    1
#define HAL_APB_SSI_SFIFERREN_SIGNED      0
#define HAL_APB_SSI_SFIFERREN_ADR         0xCF000C14

#define HAL_APB_SSI_SRDERREN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SRDERREN_LSB         1
#define HAL_APB_SSI_SRDERREN_MSB         1
#define HAL_APB_SSI_SRDERREN_MASK        0x00000002
#define HAL_APB_SSI_SRDERREN_TYPE        Bool
#define HAL_APB_SSI_SRDERREN             HAL_APB_SSI_SRDERREN_MASK
#define HAL_APB_SSI_SRDERREN_READABLE    1
#define HAL_APB_SSI_SRDERREN_WRITABLE    1
#define HAL_APB_SSI_SRDERREN_SIGNED      0
#define HAL_APB_SSI_SRDERREN_ADR         0xCF000C14

#define HAL_APB_SSI_SCMDERREN_REGISTER    (HAL_APB_SSIREG_MAP->SSIINTEN)
#define HAL_APB_SSI_SCMDERREN_LSB         0
#define HAL_APB_SSI_SCMDERREN_MSB         0
#define HAL_APB_SSI_SCMDERREN_MASK        0x00000001
#define HAL_APB_SSI_SCMDERREN_TYPE        Bool
#define HAL_APB_SSI_SCMDERREN             HAL_APB_SSI_SCMDERREN_MASK
#define HAL_APB_SSI_SCMDERREN_READABLE    1
#define HAL_APB_SSI_SCMDERREN_WRITABLE    1
#define HAL_APB_SSI_SCMDERREN_SIGNED      0
#define HAL_APB_SSI_SCMDERREN_ADR         0xCF000C14

// Register SSICFG1
#define HAL_APB_SSI_SMANEN_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG1)
#define HAL_APB_SSI_SMANEN_LSB         4
#define HAL_APB_SSI_SMANEN_MSB         4
#define HAL_APB_SSI_SMANEN_MASK        0x00000010
#define HAL_APB_SSI_SMANEN_TYPE        Bool
#define HAL_APB_SSI_SMANEN             HAL_APB_SSI_SMANEN_MASK
#define HAL_APB_SSI_SMANEN_READABLE    1
#define HAL_APB_SSI_SMANEN_WRITABLE    1
#define HAL_APB_SSI_SMANEN_SIGNED      0
#define HAL_APB_SSI_SMANEN_ADR         0xCF000C18

#define HAL_APB_SSI_SMODEPOL_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG1)
#define HAL_APB_SSI_SMODEPOL_LSB         3
#define HAL_APB_SSI_SMODEPOL_MSB         3
#define HAL_APB_SSI_SMODEPOL_MASK        0x00000008
#define HAL_APB_SSI_SMODEPOL_TYPE        Bool
#define HAL_APB_SSI_SMODEPOL             HAL_APB_SSI_SMODEPOL_MASK
#define HAL_APB_SSI_SMODEPOL_READABLE    1
#define HAL_APB_SSI_SMODEPOL_WRITABLE    1
#define HAL_APB_SSI_SMODEPOL_SIGNED      0
#define HAL_APB_SSI_SMODEPOL_ADR         0xCF000C18

#define HAL_APB_SSI_SMODELOC_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG1)
#define HAL_APB_SSI_SMODELOC_LSB         2
#define HAL_APB_SSI_SMODELOC_MSB         2
#define HAL_APB_SSI_SMODELOC_MASK        0x00000004
#define HAL_APB_SSI_SMODELOC_TYPE        Bool
#define HAL_APB_SSI_SMODELOC             HAL_APB_SSI_SMODELOC_MASK
#define HAL_APB_SSI_SMODELOC_READABLE    1
#define HAL_APB_SSI_SMODELOC_WRITABLE    1
#define HAL_APB_SSI_SMODELOC_SIGNED      0
#define HAL_APB_SSI_SMODELOC_ADR         0xCF000C18

#define HAL_APB_SSI_SDATA1ST_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG1)
#define HAL_APB_SSI_SDATA1ST_LSB         1
#define HAL_APB_SSI_SDATA1ST_MSB         1
#define HAL_APB_SSI_SDATA1ST_MASK        0x00000002
#define HAL_APB_SSI_SDATA1ST_TYPE        Bool
#define HAL_APB_SSI_SDATA1ST             HAL_APB_SSI_SDATA1ST_MASK
#define HAL_APB_SSI_SDATA1ST_READABLE    1
#define HAL_APB_SSI_SDATA1ST_WRITABLE    1
#define HAL_APB_SSI_SDATA1ST_SIGNED      0
#define HAL_APB_SSI_SDATA1ST_ADR         0xCF000C18

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_SMODE2_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG1)
#define HAL_APB_SSI_SMODE2_LSB         0
#define HAL_APB_SSI_SMODE2_MSB         0
#define HAL_APB_SSI_SMODE2_MASK        0x00000001
#define HAL_APB_SSI_SMODE2_TYPE        Bool
#define HAL_APB_SSI_SMODE2             HAL_APB_SSI_SMODE2_MASK
#define HAL_APB_SSI_SMODE2_READABLE    1
#define HAL_APB_SSI_SMODE2_WRITABLE    1
#define HAL_APB_SSI_SMODE2_SIGNED      0
#define HAL_APB_SSI_SMODE2_ADR         0xCF000C18

#endif // #if (CHIP_REV >= 0xC0)

// Register SSICFG2

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_SDATAIDEN_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG2)
#define HAL_APB_SSI_SDATAIDEN_LSB         3
#define HAL_APB_SSI_SDATAIDEN_MSB         3
#define HAL_APB_SSI_SDATAIDEN_MASK        0x00000008
#define HAL_APB_SSI_SDATAIDEN_TYPE        Bool
#define HAL_APB_SSI_SDATAIDEN             HAL_APB_SSI_SDATAIDEN_MASK
#define HAL_APB_SSI_SDATAIDEN_READABLE    1
#define HAL_APB_SSI_SDATAIDEN_WRITABLE    1
#define HAL_APB_SSI_SDATAIDEN_SIGNED      0
#define HAL_APB_SSI_SDATAIDEN_ADR         0xCF000C1C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_SSCLKDLY_REGISTER    (HAL_APB_SSIREG_MAP->SSICFG2)
#define HAL_APB_SSI_SSCLKDLY_LSB         0
#define HAL_APB_SSI_SSCLKDLY_MSB         2
#define HAL_APB_SSI_SSCLKDLY_MASK        0x00000007
#define HAL_APB_SSI_SSCLKDLY_TYPE        UByte
#define HAL_APB_SSI_SSCLKDLY             HAL_APB_SSI_SSCLKDLY_MASK
#define HAL_APB_SSI_SSCLKDLY_READABLE    1
#define HAL_APB_SSI_SSCLKDLY_WRITABLE    1
#define HAL_APB_SSI_SSCLKDLY_SIGNED      0
#define HAL_APB_SSI_SSCLKDLY_ADR         0xCF000C1C

// Register LCDRDADD
#define HAL_APB_SSI_LCDRDADD_REGISTER    (HAL_APB_SSIREG_MAP->LCDRDADD)
#define HAL_APB_SSI_LCDRDADD_LSB         0
#define HAL_APB_SSI_LCDRDADD_MSB         7
#define HAL_APB_SSI_LCDRDADD_MASK        0x000000FF
#define HAL_APB_SSI_LCDRDADD_TYPE        UByte
#define HAL_APB_SSI_LCDRDADD             HAL_APB_SSI_LCDRDADD_MASK
#define HAL_APB_SSI_LCDRDADD_READABLE    1
#define HAL_APB_SSI_LCDRDADD_WRITABLE    1
#define HAL_APB_SSI_LCDRDADD_SIGNED      0
#define HAL_APB_SSI_LCDRDADD_ADR         0xCF001400

// Register LCDRDDAT
#define HAL_APB_SSI_LCDRDDAT_REGISTER    (HAL_APB_SSIREG_MAP->LCDRDDAT)
#define HAL_APB_SSI_LCDRDDAT_LSB         0
#define HAL_APB_SSI_LCDRDDAT_MSB         7
#define HAL_APB_SSI_LCDRDDAT_MASK        0x000000FF
#define HAL_APB_SSI_LCDRDDAT_TYPE        UByte
#define HAL_APB_SSI_LCDRDDAT             HAL_APB_SSI_LCDRDDAT_MASK
#define HAL_APB_SSI_LCDRDDAT_READABLE    1
#define HAL_APB_SSI_LCDRDDAT_WRITABLE    0
#define HAL_APB_SSI_LCDRDDAT_SIGNED      0
#define HAL_APB_SSI_LCDRDDAT_ADR         0xCF001404

// Register LCDCLKDIV
#define HAL_APB_SSI_LCDCLKDIV_REGISTER    (HAL_APB_SSIREG_MAP->LCDCLKDIV)
#define HAL_APB_SSI_LCDCLKDIV_LSB         0
#define HAL_APB_SSI_LCDCLKDIV_MSB         7
#define HAL_APB_SSI_LCDCLKDIV_MASK        0x000000FF
#define HAL_APB_SSI_LCDCLKDIV_TYPE        UByte
#define HAL_APB_SSI_LCDCLKDIV             HAL_APB_SSI_LCDCLKDIV_MASK
#define HAL_APB_SSI_LCDCLKDIV_READABLE    1
#define HAL_APB_SSI_LCDCLKDIV_WRITABLE    1
#define HAL_APB_SSI_LCDCLKDIV_SIGNED      0
#define HAL_APB_SSI_LCDCLKDIV_ADR         0xCF001408

// Register LCDCFG0

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_LDDATADEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_LDDATADEN_LSB         7
#define HAL_APB_SSI_LDDATADEN_MSB         7
#define HAL_APB_SSI_LDDATADEN_MASK        0x00000080
#define HAL_APB_SSI_LDDATADEN_TYPE        Bool
#define HAL_APB_SSI_LDDATADEN             HAL_APB_SSI_LDDATADEN_MASK
#define HAL_APB_SSI_LDDATADEN_READABLE    1
#define HAL_APB_SSI_LDDATADEN_WRITABLE    1
#define HAL_APB_SSI_LDDATADEN_SIGNED      0
#define HAL_APB_SSI_LDDATADEN_ADR         0xCF00140C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_LTRNSHLD_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_LTRNSHLD_LSB         6
#define HAL_APB_SSI_LTRNSHLD_MSB         6
#define HAL_APB_SSI_LTRNSHLD_MASK        0x00000040
#define HAL_APB_SSI_LTRNSHLD_TYPE        Bool
#define HAL_APB_SSI_LTRNSHLD             HAL_APB_SSI_LTRNSHLD_MASK
#define HAL_APB_SSI_LTRNSHLD_READABLE    1
#define HAL_APB_SSI_LTRNSHLD_WRITABLE    1
#define HAL_APB_SSI_LTRNSHLD_SIGNED      0
#define HAL_APB_SSI_LTRNSHLD_ADR         0xCF00140C

#define HAL_APB_SSI_LALSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_LALSB2MSB_LSB         5
#define HAL_APB_SSI_LALSB2MSB_MSB         5
#define HAL_APB_SSI_LALSB2MSB_MASK        0x00000020
#define HAL_APB_SSI_LALSB2MSB_TYPE        Bool
#define HAL_APB_SSI_LALSB2MSB             HAL_APB_SSI_LALSB2MSB_MASK
#define HAL_APB_SSI_LALSB2MSB_READABLE    1
#define HAL_APB_SSI_LALSB2MSB_WRITABLE    1
#define HAL_APB_SSI_LALSB2MSB_SIGNED      0
#define HAL_APB_SSI_LALSB2MSB_ADR         0xCF00140C

#define HAL_APB_SSI_LDLSB2MSB_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_LDLSB2MSB_LSB         4
#define HAL_APB_SSI_LDLSB2MSB_MSB         4
#define HAL_APB_SSI_LDLSB2MSB_MASK        0x00000010
#define HAL_APB_SSI_LDLSB2MSB_TYPE        Bool
#define HAL_APB_SSI_LDLSB2MSB             HAL_APB_SSI_LDLSB2MSB_MASK
#define HAL_APB_SSI_LDLSB2MSB_READABLE    1
#define HAL_APB_SSI_LDLSB2MSB_WRITABLE    1
#define HAL_APB_SSI_LDLSB2MSB_SIGNED      0
#define HAL_APB_SSI_LDLSB2MSB_ADR         0xCF00140C

#define HAL_APB_SSI_LSCLKINV_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_LSCLKINV_LSB         3
#define HAL_APB_SSI_LSCLKINV_MSB         3
#define HAL_APB_SSI_LSCLKINV_MASK        0x00000008
#define HAL_APB_SSI_LSCLKINV_TYPE        Bool
#define HAL_APB_SSI_LSCLKINV             HAL_APB_SSI_LSCLKINV_MASK
#define HAL_APB_SSI_LSCLKINV_READABLE    1
#define HAL_APB_SSI_LSCLKINV_WRITABLE    1
#define HAL_APB_SSI_LSCLKINV_SIGNED      0
#define HAL_APB_SSI_LSCLKINV_ADR         0xCF00140C

#define HAL_APB_SSI_SEN3INV_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_SEN3INV_LSB         2
#define HAL_APB_SSI_SEN3INV_MSB         2
#define HAL_APB_SSI_SEN3INV_MASK        0x00000004
#define HAL_APB_SSI_SEN3INV_TYPE        Bool
#define HAL_APB_SSI_SEN3INV             HAL_APB_SSI_SEN3INV_MASK
#define HAL_APB_SSI_SEN3INV_READABLE    1
#define HAL_APB_SSI_SEN3INV_WRITABLE    1
#define HAL_APB_SSI_SEN3INV_SIGNED      0
#define HAL_APB_SSI_SEN3INV_ADR         0xCF00140C

#define HAL_APB_SSI_EXTSEN3_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_EXTSEN3_LSB         1
#define HAL_APB_SSI_EXTSEN3_MSB         1
#define HAL_APB_SSI_EXTSEN3_MASK        0x00000002
#define HAL_APB_SSI_EXTSEN3_TYPE        Bool
#define HAL_APB_SSI_EXTSEN3             HAL_APB_SSI_EXTSEN3_MASK
#define HAL_APB_SSI_EXTSEN3_READABLE    1
#define HAL_APB_SSI_EXTSEN3_WRITABLE    1
#define HAL_APB_SSI_EXTSEN3_SIGNED      0
#define HAL_APB_SSI_EXTSEN3_ADR         0xCF00140C

#define HAL_APB_SSI_PSEN3_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG0)
#define HAL_APB_SSI_PSEN3_LSB         0
#define HAL_APB_SSI_PSEN3_MSB         0
#define HAL_APB_SSI_PSEN3_MASK        0x00000001
#define HAL_APB_SSI_PSEN3_TYPE        Bool
#define HAL_APB_SSI_PSEN3             HAL_APB_SSI_PSEN3_MASK
#define HAL_APB_SSI_PSEN3_READABLE    1
#define HAL_APB_SSI_PSEN3_WRITABLE    1
#define HAL_APB_SSI_PSEN3_SIGNED      0
#define HAL_APB_SSI_PSEN3_ADR         0xCF00140C

// Register LCDINT
#define HAL_APB_SSI_LFIFHLF_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LFIFHLF_LSB         6
#define HAL_APB_SSI_LFIFHLF_MSB         6
#define HAL_APB_SSI_LFIFHLF_MASK        0x00000040
#define HAL_APB_SSI_LFIFHLF_TYPE        Bool
#define HAL_APB_SSI_LFIFHLF             HAL_APB_SSI_LFIFHLF_MASK
#define HAL_APB_SSI_LFIFHLF_READABLE    1
#define HAL_APB_SSI_LFIFHLF_WRITABLE    1
#define HAL_APB_SSI_LFIFHLF_SIGNED      0
#define HAL_APB_SSI_LFIFHLF_ADR         0xCF001410

#define HAL_APB_SSI_LFIFFUL_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LFIFFUL_LSB         5
#define HAL_APB_SSI_LFIFFUL_MSB         5
#define HAL_APB_SSI_LFIFFUL_MASK        0x00000020
#define HAL_APB_SSI_LFIFFUL_TYPE        Bool
#define HAL_APB_SSI_LFIFFUL             HAL_APB_SSI_LFIFFUL_MASK
#define HAL_APB_SSI_LFIFFUL_READABLE    1
#define HAL_APB_SSI_LFIFFUL_WRITABLE    1
#define HAL_APB_SSI_LFIFFUL_SIGNED      0
#define HAL_APB_SSI_LFIFFUL_ADR         0xCF001410

#define HAL_APB_SSI_LFIFEMP_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LFIFEMP_LSB         4
#define HAL_APB_SSI_LFIFEMP_MSB         4
#define HAL_APB_SSI_LFIFEMP_MASK        0x00000010
#define HAL_APB_SSI_LFIFEMP_TYPE        Bool
#define HAL_APB_SSI_LFIFEMP             HAL_APB_SSI_LFIFEMP_MASK
#define HAL_APB_SSI_LFIFEMP_READABLE    1
#define HAL_APB_SSI_LFIFEMP_WRITABLE    1
#define HAL_APB_SSI_LFIFEMP_SIGNED      0
#define HAL_APB_SSI_LFIFEMP_ADR         0xCF001410

#define HAL_APB_SSI_LRDVALD_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LRDVALD_LSB         3
#define HAL_APB_SSI_LRDVALD_MSB         3
#define HAL_APB_SSI_LRDVALD_MASK        0x00000008
#define HAL_APB_SSI_LRDVALD_TYPE        Bool
#define HAL_APB_SSI_LRDVALD             HAL_APB_SSI_LRDVALD_MASK
#define HAL_APB_SSI_LRDVALD_READABLE    1
#define HAL_APB_SSI_LRDVALD_WRITABLE    1
#define HAL_APB_SSI_LRDVALD_SIGNED      0
#define HAL_APB_SSI_LRDVALD_ADR         0xCF001410

#define HAL_APB_SSI_LFIFERR_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LFIFERR_LSB         2
#define HAL_APB_SSI_LFIFERR_MSB         2
#define HAL_APB_SSI_LFIFERR_MASK        0x00000004
#define HAL_APB_SSI_LFIFERR_TYPE        Bool
#define HAL_APB_SSI_LFIFERR             HAL_APB_SSI_LFIFERR_MASK
#define HAL_APB_SSI_LFIFERR_READABLE    1
#define HAL_APB_SSI_LFIFERR_WRITABLE    1
#define HAL_APB_SSI_LFIFERR_SIGNED      0
#define HAL_APB_SSI_LFIFERR_ADR         0xCF001410

#define HAL_APB_SSI_LRDERR_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LRDERR_LSB         1
#define HAL_APB_SSI_LRDERR_MSB         1
#define HAL_APB_SSI_LRDERR_MASK        0x00000002
#define HAL_APB_SSI_LRDERR_TYPE        Bool
#define HAL_APB_SSI_LRDERR             HAL_APB_SSI_LRDERR_MASK
#define HAL_APB_SSI_LRDERR_READABLE    1
#define HAL_APB_SSI_LRDERR_WRITABLE    1
#define HAL_APB_SSI_LRDERR_SIGNED      0
#define HAL_APB_SSI_LRDERR_ADR         0xCF001410

#define HAL_APB_SSI_LCMDERR_REGISTER    (HAL_APB_SSIREG_MAP->LCDINT)
#define HAL_APB_SSI_LCMDERR_LSB         0
#define HAL_APB_SSI_LCMDERR_MSB         0
#define HAL_APB_SSI_LCMDERR_MASK        0x00000001
#define HAL_APB_SSI_LCMDERR_TYPE        Bool
#define HAL_APB_SSI_LCMDERR             HAL_APB_SSI_LCMDERR_MASK
#define HAL_APB_SSI_LCMDERR_READABLE    1
#define HAL_APB_SSI_LCMDERR_WRITABLE    1
#define HAL_APB_SSI_LCMDERR_SIGNED      0
#define HAL_APB_SSI_LCMDERR_ADR         0xCF001410

// Register LCDINTEN
#define HAL_APB_SSI_LFIFHLFEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LFIFHLFEN_LSB         6
#define HAL_APB_SSI_LFIFHLFEN_MSB         6
#define HAL_APB_SSI_LFIFHLFEN_MASK        0x00000040
#define HAL_APB_SSI_LFIFHLFEN_TYPE        Bool
#define HAL_APB_SSI_LFIFHLFEN             HAL_APB_SSI_LFIFHLFEN_MASK
#define HAL_APB_SSI_LFIFHLFEN_READABLE    1
#define HAL_APB_SSI_LFIFHLFEN_WRITABLE    1
#define HAL_APB_SSI_LFIFHLFEN_SIGNED      0
#define HAL_APB_SSI_LFIFHLFEN_ADR         0xCF001414

#define HAL_APB_SSI_LFIFFULEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LFIFFULEN_LSB         5
#define HAL_APB_SSI_LFIFFULEN_MSB         5
#define HAL_APB_SSI_LFIFFULEN_MASK        0x00000020
#define HAL_APB_SSI_LFIFFULEN_TYPE        Bool
#define HAL_APB_SSI_LFIFFULEN             HAL_APB_SSI_LFIFFULEN_MASK
#define HAL_APB_SSI_LFIFFULEN_READABLE    1
#define HAL_APB_SSI_LFIFFULEN_WRITABLE    1
#define HAL_APB_SSI_LFIFFULEN_SIGNED      0
#define HAL_APB_SSI_LFIFFULEN_ADR         0xCF001414

#define HAL_APB_SSI_LFIFEMPEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LFIFEMPEN_LSB         4
#define HAL_APB_SSI_LFIFEMPEN_MSB         4
#define HAL_APB_SSI_LFIFEMPEN_MASK        0x00000010
#define HAL_APB_SSI_LFIFEMPEN_TYPE        Bool
#define HAL_APB_SSI_LFIFEMPEN             HAL_APB_SSI_LFIFEMPEN_MASK
#define HAL_APB_SSI_LFIFEMPEN_READABLE    1
#define HAL_APB_SSI_LFIFEMPEN_WRITABLE    1
#define HAL_APB_SSI_LFIFEMPEN_SIGNED      0
#define HAL_APB_SSI_LFIFEMPEN_ADR         0xCF001414

#define HAL_APB_SSI_LRDVALDEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LRDVALDEN_LSB         3
#define HAL_APB_SSI_LRDVALDEN_MSB         3
#define HAL_APB_SSI_LRDVALDEN_MASK        0x00000008
#define HAL_APB_SSI_LRDVALDEN_TYPE        Bool
#define HAL_APB_SSI_LRDVALDEN             HAL_APB_SSI_LRDVALDEN_MASK
#define HAL_APB_SSI_LRDVALDEN_READABLE    1
#define HAL_APB_SSI_LRDVALDEN_WRITABLE    1
#define HAL_APB_SSI_LRDVALDEN_SIGNED      0
#define HAL_APB_SSI_LRDVALDEN_ADR         0xCF001414

#define HAL_APB_SSI_LFIFERREN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LFIFERREN_LSB         2
#define HAL_APB_SSI_LFIFERREN_MSB         2
#define HAL_APB_SSI_LFIFERREN_MASK        0x00000004
#define HAL_APB_SSI_LFIFERREN_TYPE        Bool
#define HAL_APB_SSI_LFIFERREN             HAL_APB_SSI_LFIFERREN_MASK
#define HAL_APB_SSI_LFIFERREN_READABLE    1
#define HAL_APB_SSI_LFIFERREN_WRITABLE    1
#define HAL_APB_SSI_LFIFERREN_SIGNED      0
#define HAL_APB_SSI_LFIFERREN_ADR         0xCF001414

#define HAL_APB_SSI_LRDERREN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LRDERREN_LSB         1
#define HAL_APB_SSI_LRDERREN_MSB         1
#define HAL_APB_SSI_LRDERREN_MASK        0x00000002
#define HAL_APB_SSI_LRDERREN_TYPE        Bool
#define HAL_APB_SSI_LRDERREN             HAL_APB_SSI_LRDERREN_MASK
#define HAL_APB_SSI_LRDERREN_READABLE    1
#define HAL_APB_SSI_LRDERREN_WRITABLE    1
#define HAL_APB_SSI_LRDERREN_SIGNED      0
#define HAL_APB_SSI_LRDERREN_ADR         0xCF001414

#define HAL_APB_SSI_LCMDERREN_REGISTER    (HAL_APB_SSIREG_MAP->LCDINTEN)
#define HAL_APB_SSI_LCMDERREN_LSB         0
#define HAL_APB_SSI_LCMDERREN_MSB         0
#define HAL_APB_SSI_LCMDERREN_MASK        0x00000001
#define HAL_APB_SSI_LCMDERREN_TYPE        Bool
#define HAL_APB_SSI_LCMDERREN             HAL_APB_SSI_LCMDERREN_MASK
#define HAL_APB_SSI_LCMDERREN_READABLE    1
#define HAL_APB_SSI_LCMDERREN_WRITABLE    1
#define HAL_APB_SSI_LCMDERREN_SIGNED      0
#define HAL_APB_SSI_LCMDERREN_ADR         0xCF001414

// Register LCDCFG1
#define HAL_APB_SSI_LMANEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG1)
#define HAL_APB_SSI_LMANEN_LSB         4
#define HAL_APB_SSI_LMANEN_MSB         4
#define HAL_APB_SSI_LMANEN_MASK        0x00000010
#define HAL_APB_SSI_LMANEN_TYPE        Bool
#define HAL_APB_SSI_LMANEN             HAL_APB_SSI_LMANEN_MASK
#define HAL_APB_SSI_LMANEN_READABLE    1
#define HAL_APB_SSI_LMANEN_WRITABLE    1
#define HAL_APB_SSI_LMANEN_SIGNED      0
#define HAL_APB_SSI_LMANEN_ADR         0xCF001418

#define HAL_APB_SSI_LMODEPOL_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG1)
#define HAL_APB_SSI_LMODEPOL_LSB         3
#define HAL_APB_SSI_LMODEPOL_MSB         3
#define HAL_APB_SSI_LMODEPOL_MASK        0x00000008
#define HAL_APB_SSI_LMODEPOL_TYPE        Bool
#define HAL_APB_SSI_LMODEPOL             HAL_APB_SSI_LMODEPOL_MASK
#define HAL_APB_SSI_LMODEPOL_READABLE    1
#define HAL_APB_SSI_LMODEPOL_WRITABLE    1
#define HAL_APB_SSI_LMODEPOL_SIGNED      0
#define HAL_APB_SSI_LMODEPOL_ADR         0xCF001418

#define HAL_APB_SSI_LMODELOC_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG1)
#define HAL_APB_SSI_LMODELOC_LSB         2
#define HAL_APB_SSI_LMODELOC_MSB         2
#define HAL_APB_SSI_LMODELOC_MASK        0x00000004
#define HAL_APB_SSI_LMODELOC_TYPE        Bool
#define HAL_APB_SSI_LMODELOC             HAL_APB_SSI_LMODELOC_MASK
#define HAL_APB_SSI_LMODELOC_READABLE    1
#define HAL_APB_SSI_LMODELOC_WRITABLE    1
#define HAL_APB_SSI_LMODELOC_SIGNED      0
#define HAL_APB_SSI_LMODELOC_ADR         0xCF001418

#define HAL_APB_SSI_LDATA1ST_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG1)
#define HAL_APB_SSI_LDATA1ST_LSB         1
#define HAL_APB_SSI_LDATA1ST_MSB         1
#define HAL_APB_SSI_LDATA1ST_MASK        0x00000002
#define HAL_APB_SSI_LDATA1ST_TYPE        Bool
#define HAL_APB_SSI_LDATA1ST             HAL_APB_SSI_LDATA1ST_MASK
#define HAL_APB_SSI_LDATA1ST_READABLE    1
#define HAL_APB_SSI_LDATA1ST_WRITABLE    1
#define HAL_APB_SSI_LDATA1ST_SIGNED      0
#define HAL_APB_SSI_LDATA1ST_ADR         0xCF001418

// Register LCDCFG2

#if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_LDATAIDEN_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG2)
#define HAL_APB_SSI_LDATAIDEN_LSB         3
#define HAL_APB_SSI_LDATAIDEN_MSB         3
#define HAL_APB_SSI_LDATAIDEN_MASK        0x00000008
#define HAL_APB_SSI_LDATAIDEN_TYPE        Bool
#define HAL_APB_SSI_LDATAIDEN             HAL_APB_SSI_LDATAIDEN_MASK
#define HAL_APB_SSI_LDATAIDEN_READABLE    1
#define HAL_APB_SSI_LDATAIDEN_WRITABLE    1
#define HAL_APB_SSI_LDATAIDEN_SIGNED      0
#define HAL_APB_SSI_LDATAIDEN_ADR         0xCF00141C

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_APB_SSI_LDCLKDLY_REGISTER    (HAL_APB_SSIREG_MAP->LCDCFG2)
#define HAL_APB_SSI_LDCLKDLY_LSB         0
#define HAL_APB_SSI_LDCLKDLY_MSB         2
#define HAL_APB_SSI_LDCLKDLY_MASK        0x00000007
#define HAL_APB_SSI_LDCLKDLY_TYPE        UByte
#define HAL_APB_SSI_LDCLKDLY             HAL_APB_SSI_LDCLKDLY_MASK
#define HAL_APB_SSI_LDCLKDLY_READABLE    1
#define HAL_APB_SSI_LDCLKDLY_WRITABLE    1
#define HAL_APB_SSI_LDCLKDLY_SIGNED      0
#define HAL_APB_SSI_LDCLKDLY_ADR         0xCF00141C

// Register SVCFG
#define HAL_APB_SSI_SVFORCE_REGISTER    (HAL_APB_SSIREG_MAP->SVCFG)
#define HAL_APB_SSI_SVFORCE_LSB         1
#define HAL_APB_SSI_SVFORCE_MSB         1
#define HAL_APB_SSI_SVFORCE_MASK        0x00000002
#define HAL_APB_SSI_SVFORCE_TYPE        Bool
#define HAL_APB_SSI_SVFORCE             HAL_APB_SSI_SVFORCE_MASK
#define HAL_APB_SSI_SVFORCE_READABLE    1
#define HAL_APB_SSI_SVFORCE_WRITABLE    1
#define HAL_APB_SSI_SVFORCE_SIGNED      0
#define HAL_APB_SSI_SVFORCE_ADR         0xCF001800

#define HAL_APB_SSI_SVSTOP_REGISTER    (HAL_APB_SSIREG_MAP->SVCFG)
#define HAL_APB_SSI_SVSTOP_LSB         0
#define HAL_APB_SSI_SVSTOP_MSB         0
#define HAL_APB_SSI_SVSTOP_MASK        0x00000001
#define HAL_APB_SSI_SVSTOP_TYPE        Bool
#define HAL_APB_SSI_SVSTOP             HAL_APB_SSI_SVSTOP_MASK
#define HAL_APB_SSI_SVSTOP_READABLE    1
#define HAL_APB_SSI_SVSTOP_WRITABLE    1
#define HAL_APB_SSI_SVSTOP_SIGNED      0
#define HAL_APB_SSI_SVSTOP_ADR         0xCF001800

// Register SSISPARE
#endif /* __REG_SSI_H__ */

