/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_cpycmp.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the SOC_CPYCMP core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_CPYCMP_H__
#define __REG_CPYCMP_H__

// Core register map
#define HAL_CPYCMP_VERSION 7.142
#define HAL_CPYCMP_BaseAddress 0x10000E00
#define HAL_CPYCMPREG_MAP ((struct halCPYCMPReg_Map*) (void *) HAL_CPYCMP_BaseAddress)
__packed struct halCPYCMPReg_Map
{
	HAL_Reg8  ReservedBlk0[208];              //00000000
	HAL_Reg8  CPYCTL;                         //000000D0
	HAL_Reg8  ReservedBlk1[1];                //000000D1
	HAL_Reg16 CPYSRCL;                        //000000D2
	HAL_Reg16 CPYTGTL;                        //000000D4
	HAL_Reg16 CPYSOFL;                        //000000D6
	HAL_Reg16 CPYTOFL;                        //000000D8
	HAL_Reg16 CPYPCNTL;                       //000000DA
	HAL_Reg32 CPYWCNTL;                       //000000DC
	HAL_Reg8  CPYINT;                         //000000E0
	HAL_Reg8  CPYINTEN;                       //000000E1
	HAL_Reg8  ReservedBlk2[2];                //000000E2
	HAL_Reg32 DCPYSADL;                       //000000E4
	HAL_Reg32 DCPYTADL;                       //000000E8
	HAL_Reg16 CPYSPGL;                        //000000EC
	HAL_Reg16 CPYEPGL;                        //000000EE
	HAL_Reg16 CPYPATL;                        //000000F0
};
// Register CPYCTL
#define HAL_CPYCMP_CPYSTRT_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_CPYSTRT_LSB         7
#define HAL_CPYCMP_CPYSTRT_MSB         7
#define HAL_CPYCMP_CPYSTRT_MASK        0x00000080
#define HAL_CPYCMP_CPYSTRT_TYPE        Bool
#define HAL_CPYCMP_CPYSTRT             HAL_CPYCMP_CPYSTRT_MASK
#define HAL_CPYCMP_CPYSTRT_READABLE    1
#define HAL_CPYCMP_CPYSTRT_WRITABLE    1
#define HAL_CPYCMP_CPYSTRT_SIGNED      0
#define HAL_CPYCMP_CPYSTRT_ADR         0x10000ED0

#define HAL_CPYCMP_CMPSTRT_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_CMPSTRT_LSB         6
#define HAL_CPYCMP_CMPSTRT_MSB         6
#define HAL_CPYCMP_CMPSTRT_MASK        0x00000040
#define HAL_CPYCMP_CMPSTRT_TYPE        Bool
#define HAL_CPYCMP_CMPSTRT             HAL_CPYCMP_CMPSTRT_MASK
#define HAL_CPYCMP_CMPSTRT_READABLE    1
#define HAL_CPYCMP_CMPSTRT_WRITABLE    1
#define HAL_CPYCMP_CMPSTRT_SIGNED      0
#define HAL_CPYCMP_CMPSTRT_ADR         0x10000ED0

#define HAL_CPYCMP_PFILSTRT_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_PFILSTRT_LSB         5
#define HAL_CPYCMP_PFILSTRT_MSB         5
#define HAL_CPYCMP_PFILSTRT_MASK        0x00000020
#define HAL_CPYCMP_PFILSTRT_TYPE        Bool
#define HAL_CPYCMP_PFILSTRT             HAL_CPYCMP_PFILSTRT_MASK
#define HAL_CPYCMP_PFILSTRT_READABLE    1
#define HAL_CPYCMP_PFILSTRT_WRITABLE    1
#define HAL_CPYCMP_PFILSTRT_SIGNED      0
#define HAL_CPYCMP_PFILSTRT_ADR         0x10000ED0

#define HAL_CPYCMP_DCPYSTRT_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_DCPYSTRT_LSB         4
#define HAL_CPYCMP_DCPYSTRT_MSB         4
#define HAL_CPYCMP_DCPYSTRT_MASK        0x00000010
#define HAL_CPYCMP_DCPYSTRT_TYPE        Bool
#define HAL_CPYCMP_DCPYSTRT             HAL_CPYCMP_DCPYSTRT_MASK
#define HAL_CPYCMP_DCPYSTRT_READABLE    1
#define HAL_CPYCMP_DCPYSTRT_WRITABLE    1
#define HAL_CPYCMP_DCPYSTRT_SIGNED      0
#define HAL_CPYCMP_DCPYSTRT_ADR         0x10000ED0

#define HAL_CPYCMP_TFLAG_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_TFLAG_LSB         2
#define HAL_CPYCMP_TFLAG_MSB         2
#define HAL_CPYCMP_TFLAG_MASK        0x00000004
#define HAL_CPYCMP_TFLAG_TYPE        halCPYCMP_TGT_t
#define HAL_CPYCMP_TFLAG             HAL_CPYCMP_TFLAG_MASK
#define HAL_CPYCMP_TFLAG_READABLE    1
#define HAL_CPYCMP_TFLAG_WRITABLE    1
#define HAL_CPYCMP_TFLAG_SIGNED      0
#define HAL_CPYCMP_TFLAG_ADR         0x10000ED0

#define HAL_CPYCMP_SFLAG_REGISTER    (HAL_CPYCMPREG_MAP->CPYCTL)
#define HAL_CPYCMP_SFLAG_LSB         1
#define HAL_CPYCMP_SFLAG_MSB         1
#define HAL_CPYCMP_SFLAG_MASK        0x00000002
#define HAL_CPYCMP_SFLAG_TYPE        halCPYCMP_SRC_t
#define HAL_CPYCMP_SFLAG             HAL_CPYCMP_SFLAG_MASK
#define HAL_CPYCMP_SFLAG_READABLE    1
#define HAL_CPYCMP_SFLAG_WRITABLE    1
#define HAL_CPYCMP_SFLAG_SIGNED      0
#define HAL_CPYCMP_SFLAG_ADR         0x10000ED0

// Registers CPYSRCL/CPYSRCH
#define HAL_CPYCMP_CPYSRC_REGISTER    (HAL_CPYCMPREG_MAP->CPYSRCL)
#define HAL_CPYCMP_CPYSRC_LSB         0
#define HAL_CPYCMP_CPYSRC_MSB         12
#define HAL_CPYCMP_CPYSRC_MASK        0x00001FFF
#define HAL_CPYCMP_CPYSRC_TYPE        UInt16
#define HAL_CPYCMP_CPYSRC             HAL_CPYCMP_CPYSRC_MASK
#define HAL_CPYCMP_CPYSRC_READABLE    1
#define HAL_CPYCMP_CPYSRC_WRITABLE    1
#define HAL_CPYCMP_CPYSRC_SIGNED      0
#define HAL_CPYCMP_CPYSRC_ADR         0x10000ED2

// Registers CPYTGTL/CPYTGTH
#define HAL_CPYCMP_CPYTGT_REGISTER    (HAL_CPYCMPREG_MAP->CPYTGTL)
#define HAL_CPYCMP_CPYTGT_LSB         0
#define HAL_CPYCMP_CPYTGT_MSB         12
#define HAL_CPYCMP_CPYTGT_MASK        0x00001FFF
#define HAL_CPYCMP_CPYTGT_TYPE        UInt16
#define HAL_CPYCMP_CPYTGT             HAL_CPYCMP_CPYTGT_MASK
#define HAL_CPYCMP_CPYTGT_READABLE    1
#define HAL_CPYCMP_CPYTGT_WRITABLE    1
#define HAL_CPYCMP_CPYTGT_SIGNED      0
#define HAL_CPYCMP_CPYTGT_ADR         0x10000ED4

// Registers CPYSOFL/CPYSOFH
#define HAL_CPYCMP_CPYSOF_REGISTER    (HAL_CPYCMPREG_MAP->CPYSOFL)
#define HAL_CPYCMP_CPYSOF_LSB         0
#define HAL_CPYCMP_CPYSOF_MSB         15
#define HAL_CPYCMP_CPYSOF_MASK        0x0000FFFF
#define HAL_CPYCMP_CPYSOF_TYPE        UInt16
#define HAL_CPYCMP_CPYSOF             HAL_CPYCMP_CPYSOF_MASK
#define HAL_CPYCMP_CPYSOF_READABLE    1
#define HAL_CPYCMP_CPYSOF_WRITABLE    1
#define HAL_CPYCMP_CPYSOF_SIGNED      0
#define HAL_CPYCMP_CPYSOF_ADR         0x10000ED6

// Registers CPYTOFL/CPYTOFH
#define HAL_CPYCMP_CPYTOF_REGISTER    (HAL_CPYCMPREG_MAP->CPYTOFL)
#define HAL_CPYCMP_CPYTOF_LSB         0
#define HAL_CPYCMP_CPYTOF_MSB         15
#define HAL_CPYCMP_CPYTOF_MASK        0x0000FFFF
#define HAL_CPYCMP_CPYTOF_TYPE        UInt16
#define HAL_CPYCMP_CPYTOF             HAL_CPYCMP_CPYTOF_MASK
#define HAL_CPYCMP_CPYTOF_READABLE    1
#define HAL_CPYCMP_CPYTOF_WRITABLE    1
#define HAL_CPYCMP_CPYTOF_SIGNED      0
#define HAL_CPYCMP_CPYTOF_ADR         0x10000ED8

// Registers CPYPCNTL/CPYPCNTH
#define HAL_CPYCMP_CPYPCNT_REGISTER    (HAL_CPYCMPREG_MAP->CPYPCNTL)
#define HAL_CPYCMP_CPYPCNT_LSB         0
#define HAL_CPYCMP_CPYPCNT_MSB         12
#define HAL_CPYCMP_CPYPCNT_MASK        0x00001FFF
#define HAL_CPYCMP_CPYPCNT_TYPE        UInt16
#define HAL_CPYCMP_CPYPCNT             HAL_CPYCMP_CPYPCNT_MASK
#define HAL_CPYCMP_CPYPCNT_READABLE    1
#define HAL_CPYCMP_CPYPCNT_WRITABLE    1
#define HAL_CPYCMP_CPYPCNT_SIGNED      0
#define HAL_CPYCMP_CPYPCNT_ADR         0x10000EDA

// Registers CPYWCNTL/CPYWCNTH/CPYWCNTU
#define HAL_CPYCMP_CPYWCNT_REGISTER    (HAL_CPYCMPREG_MAP->CPYWCNTL)
#define HAL_CPYCMP_CPYWCNT_LSB         0
#define HAL_CPYCMP_CPYWCNT_MSB         16
#define HAL_CPYCMP_CPYWCNT_MASK        0x0001FFFF
#define HAL_CPYCMP_CPYWCNT_TYPE        UInt32
#define HAL_CPYCMP_CPYWCNT             HAL_CPYCMP_CPYWCNT_MASK
#define HAL_CPYCMP_CPYWCNT_READABLE    1
#define HAL_CPYCMP_CPYWCNT_WRITABLE    1
#define HAL_CPYCMP_CPYWCNT_SIGNED      0
#define HAL_CPYCMP_CPYWCNT_ADR         0x10000EDC

// Register CPYINT
#define HAL_CPYCMP_CPYDONE_REGISTER    (HAL_CPYCMPREG_MAP->CPYINT)
#define HAL_CPYCMP_CPYDONE_LSB         7
#define HAL_CPYCMP_CPYDONE_MSB         7
#define HAL_CPYCMP_CPYDONE_MASK        0x00000080
#define HAL_CPYCMP_CPYDONE_TYPE        Bool
#define HAL_CPYCMP_CPYDONE             HAL_CPYCMP_CPYDONE_MASK
#define HAL_CPYCMP_CPYDONE_READABLE    1
#define HAL_CPYCMP_CPYDONE_WRITABLE    1
#define HAL_CPYCMP_CPYDONE_SIGNED      0
#define HAL_CPYCMP_CPYDONE_ADR         0x10000EE0

#define HAL_CPYCMP_CMPDONE_REGISTER    (HAL_CPYCMPREG_MAP->CPYINT)
#define HAL_CPYCMP_CMPDONE_LSB         6
#define HAL_CPYCMP_CMPDONE_MSB         6
#define HAL_CPYCMP_CMPDONE_MASK        0x00000040
#define HAL_CPYCMP_CMPDONE_TYPE        Bool
#define HAL_CPYCMP_CMPDONE             HAL_CPYCMP_CMPDONE_MASK
#define HAL_CPYCMP_CMPDONE_READABLE    1
#define HAL_CPYCMP_CMPDONE_WRITABLE    1
#define HAL_CPYCMP_CMPDONE_SIGNED      0
#define HAL_CPYCMP_CMPDONE_ADR         0x10000EE0

#define HAL_CPYCMP_PFILDONE_REGISTER    (HAL_CPYCMPREG_MAP->CPYINT)
#define HAL_CPYCMP_PFILDONE_LSB         5
#define HAL_CPYCMP_PFILDONE_MSB         5
#define HAL_CPYCMP_PFILDONE_MASK        0x00000020
#define HAL_CPYCMP_PFILDONE_TYPE        Bool
#define HAL_CPYCMP_PFILDONE             HAL_CPYCMP_PFILDONE_MASK
#define HAL_CPYCMP_PFILDONE_READABLE    1
#define HAL_CPYCMP_PFILDONE_WRITABLE    1
#define HAL_CPYCMP_PFILDONE_SIGNED      0
#define HAL_CPYCMP_PFILDONE_ADR         0x10000EE0

#define HAL_CPYCMP_DCPYDONE_REGISTER    (HAL_CPYCMPREG_MAP->CPYINT)
#define HAL_CPYCMP_DCPYDONE_LSB         4
#define HAL_CPYCMP_DCPYDONE_MSB         4
#define HAL_CPYCMP_DCPYDONE_MASK        0x00000010
#define HAL_CPYCMP_DCPYDONE_TYPE        Bool
#define HAL_CPYCMP_DCPYDONE             HAL_CPYCMP_DCPYDONE_MASK
#define HAL_CPYCMP_DCPYDONE_READABLE    1
#define HAL_CPYCMP_DCPYDONE_WRITABLE    1
#define HAL_CPYCMP_DCPYDONE_SIGNED      0
#define HAL_CPYCMP_DCPYDONE_ADR         0x10000EE0

#define HAL_CPYCMP_CMPDIFF_REGISTER    (HAL_CPYCMPREG_MAP->CPYINT)
#define HAL_CPYCMP_CMPDIFF_LSB         0
#define HAL_CPYCMP_CMPDIFF_MSB         0
#define HAL_CPYCMP_CMPDIFF_MASK        0x00000001
#define HAL_CPYCMP_CMPDIFF_TYPE        Bool
#define HAL_CPYCMP_CMPDIFF             HAL_CPYCMP_CMPDIFF_MASK
#define HAL_CPYCMP_CMPDIFF_READABLE    1
#define HAL_CPYCMP_CMPDIFF_WRITABLE    1
#define HAL_CPYCMP_CMPDIFF_SIGNED      0
#define HAL_CPYCMP_CMPDIFF_ADR         0x10000EE0

// Register CPYINTEN
#define HAL_CPYCMP_CPYIEN_REGISTER    (HAL_CPYCMPREG_MAP->CPYINTEN)
#define HAL_CPYCMP_CPYIEN_LSB         7
#define HAL_CPYCMP_CPYIEN_MSB         7
#define HAL_CPYCMP_CPYIEN_MASK        0x00000080
#define HAL_CPYCMP_CPYIEN_TYPE        Bool
#define HAL_CPYCMP_CPYIEN             HAL_CPYCMP_CPYIEN_MASK
#define HAL_CPYCMP_CPYIEN_READABLE    1
#define HAL_CPYCMP_CPYIEN_WRITABLE    1
#define HAL_CPYCMP_CPYIEN_SIGNED      0
#define HAL_CPYCMP_CPYIEN_ADR         0x10000EE1

#define HAL_CPYCMP_CMPIEN_REGISTER    (HAL_CPYCMPREG_MAP->CPYINTEN)
#define HAL_CPYCMP_CMPIEN_LSB         6
#define HAL_CPYCMP_CMPIEN_MSB         6
#define HAL_CPYCMP_CMPIEN_MASK        0x00000040
#define HAL_CPYCMP_CMPIEN_TYPE        Bool
#define HAL_CPYCMP_CMPIEN             HAL_CPYCMP_CMPIEN_MASK
#define HAL_CPYCMP_CMPIEN_READABLE    1
#define HAL_CPYCMP_CMPIEN_WRITABLE    1
#define HAL_CPYCMP_CMPIEN_SIGNED      0
#define HAL_CPYCMP_CMPIEN_ADR         0x10000EE1

#define HAL_CPYCMP_PFILIEN_REGISTER    (HAL_CPYCMPREG_MAP->CPYINTEN)
#define HAL_CPYCMP_PFILIEN_LSB         5
#define HAL_CPYCMP_PFILIEN_MSB         5
#define HAL_CPYCMP_PFILIEN_MASK        0x00000020
#define HAL_CPYCMP_PFILIEN_TYPE        Bool
#define HAL_CPYCMP_PFILIEN             HAL_CPYCMP_PFILIEN_MASK
#define HAL_CPYCMP_PFILIEN_READABLE    1
#define HAL_CPYCMP_PFILIEN_WRITABLE    1
#define HAL_CPYCMP_PFILIEN_SIGNED      0
#define HAL_CPYCMP_PFILIEN_ADR         0x10000EE1

#define HAL_CPYCMP_DCPYIEN_REGISTER    (HAL_CPYCMPREG_MAP->CPYINTEN)
#define HAL_CPYCMP_DCPYIEN_LSB         4
#define HAL_CPYCMP_DCPYIEN_MSB         4
#define HAL_CPYCMP_DCPYIEN_MASK        0x00000010
#define HAL_CPYCMP_DCPYIEN_TYPE        Bool
#define HAL_CPYCMP_DCPYIEN             HAL_CPYCMP_DCPYIEN_MASK
#define HAL_CPYCMP_DCPYIEN_READABLE    1
#define HAL_CPYCMP_DCPYIEN_WRITABLE    1
#define HAL_CPYCMP_DCPYIEN_SIGNED      0
#define HAL_CPYCMP_DCPYIEN_ADR         0x10000EE1

#define HAL_CPYCMP_DIFFIEN_REGISTER    (HAL_CPYCMPREG_MAP->CPYINTEN)
#define HAL_CPYCMP_DIFFIEN_LSB         0
#define HAL_CPYCMP_DIFFIEN_MSB         0
#define HAL_CPYCMP_DIFFIEN_MASK        0x00000001
#define HAL_CPYCMP_DIFFIEN_TYPE        Bool
#define HAL_CPYCMP_DIFFIEN             HAL_CPYCMP_DIFFIEN_MASK
#define HAL_CPYCMP_DIFFIEN_READABLE    1
#define HAL_CPYCMP_DIFFIEN_WRITABLE    1
#define HAL_CPYCMP_DIFFIEN_SIGNED      0
#define HAL_CPYCMP_DIFFIEN_ADR         0x10000EE1

// Registers DCPYSADL/DCPYSADH/DCPYSADU
#define HAL_CPYCMP_DCPYSAD_REGISTER    (HAL_CPYCMPREG_MAP->DCPYSADL)
#define HAL_CPYCMP_DCPYSAD_LSB         0
#define HAL_CPYCMP_DCPYSAD_MSB         23
#define HAL_CPYCMP_DCPYSAD_MASK        0x00FFFFFF
#define HAL_CPYCMP_DCPYSAD_TYPE        UInt32
#define HAL_CPYCMP_DCPYSAD             HAL_CPYCMP_DCPYSAD_MASK
#define HAL_CPYCMP_DCPYSAD_READABLE    1
#define HAL_CPYCMP_DCPYSAD_WRITABLE    1
#define HAL_CPYCMP_DCPYSAD_SIGNED      0
#define HAL_CPYCMP_DCPYSAD_ADR         0x10000EE4

// Registers DCPYTADL/DCPYTADH/DCPYTADU
#define HAL_CPYCMP_DCPYTAD_REGISTER    (HAL_CPYCMPREG_MAP->DCPYTADL)
#define HAL_CPYCMP_DCPYTAD_LSB         0
#define HAL_CPYCMP_DCPYTAD_MSB         23
#define HAL_CPYCMP_DCPYTAD_MASK        0x00FFFFFF
#define HAL_CPYCMP_DCPYTAD_TYPE        UInt32
#define HAL_CPYCMP_DCPYTAD             HAL_CPYCMP_DCPYTAD_MASK
#define HAL_CPYCMP_DCPYTAD_READABLE    1
#define HAL_CPYCMP_DCPYTAD_WRITABLE    1
#define HAL_CPYCMP_DCPYTAD_SIGNED      0
#define HAL_CPYCMP_DCPYTAD_ADR         0x10000EE8

// Registers CPYSPGL/CPYSPGH
#define HAL_CPYCMP_CPYSPG_REGISTER    (HAL_CPYCMPREG_MAP->CPYSPGL)
#define HAL_CPYCMP_CPYSPG_LSB         0
#define HAL_CPYCMP_CPYSPG_MSB         12
#define HAL_CPYCMP_CPYSPG_MASK        0x00001FFF
#define HAL_CPYCMP_CPYSPG_TYPE        UInt16
#define HAL_CPYCMP_CPYSPG             HAL_CPYCMP_CPYSPG_MASK
#define HAL_CPYCMP_CPYSPG_READABLE    1
#define HAL_CPYCMP_CPYSPG_WRITABLE    1
#define HAL_CPYCMP_CPYSPG_SIGNED      0
#define HAL_CPYCMP_CPYSPG_ADR         0x10000EEC

// Registers CPYEPGL/CPYEPGH
#define HAL_CPYCMP_CPYEPG_REGISTER    (HAL_CPYCMPREG_MAP->CPYEPGL)
#define HAL_CPYCMP_CPYEPG_LSB         0
#define HAL_CPYCMP_CPYEPG_MSB         12
#define HAL_CPYCMP_CPYEPG_MASK        0x00001FFF
#define HAL_CPYCMP_CPYEPG_TYPE        UInt16
#define HAL_CPYCMP_CPYEPG             HAL_CPYCMP_CPYEPG_MASK
#define HAL_CPYCMP_CPYEPG_READABLE    1
#define HAL_CPYCMP_CPYEPG_WRITABLE    1
#define HAL_CPYCMP_CPYEPG_SIGNED      0
#define HAL_CPYCMP_CPYEPG_ADR         0x10000EEE

// Registers CPYPATL/CPYPATH
#define HAL_CPYCMP_CPYPAT_REGISTER    (HAL_CPYCMPREG_MAP->CPYPATL)
#define HAL_CPYCMP_CPYPAT_LSB         0
#define HAL_CPYCMP_CPYPAT_MSB         15
#define HAL_CPYCMP_CPYPAT_MASK        0x0000FFFF
#define HAL_CPYCMP_CPYPAT_TYPE        UInt16
#define HAL_CPYCMP_CPYPAT             HAL_CPYCMP_CPYPAT_MASK
#define HAL_CPYCMP_CPYPAT_READABLE    1
#define HAL_CPYCMP_CPYPAT_WRITABLE    1
#define HAL_CPYCMP_CPYPAT_SIGNED      0
#define HAL_CPYCMP_CPYPAT_ADR         0x10000EF0

// Enumerations
typedef enum
{
	halCPYCMP_TGT_NoWrap   = 0,    // Target in Buffering Data Area, Linear, no page wrap
	halCPYCMP_TGT_PageWrap = 1     // Target in User Data Area, Page will wrap within the User Data Area
} halCPYCMP_TGT_t;

typedef enum
{
	halCPYCMP_SRC_NoWrap   = 0,    // Source in Buffering Data Area, Linear, no page wrap
	halCPYCMP_SRC_PageWrap = 1     // Source in User Data Area, Page will wrap within the User Data Area
} halCPYCMP_SRC_t;

#endif /* __REG_CPYCMP_H__ */

