/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_periph.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the SOC_PERIPH core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_PERIPH_H__
#define __REG_PERIPH_H__

// Core register map
#define HAL_PERIPH_VERSION 7.142
#define HAL_PERIPH_BaseAddress 0x10000500
#define HAL_PERIPHREG_MAP ((struct halPERIPHReg_Map*) (void *) HAL_PERIPH_BaseAddress)
__packed struct halPERIPHReg_Map
{
	HAL_Reg8  ReservedBlk0[128];              //00000000
	HAL_Reg8  T0CNTRL;                        //00000080
	HAL_Reg8  T0CLK;                          //00000081
	HAL_Reg8  T0CMCTRL;                       //00000082
	HAL_Reg8  T0STATUS;                       //00000083
	HAL_Reg16 T0CMPL;                         //00000084
	HAL_Reg16 T0VALL;                         //00000086
	HAL_Reg8  T1CNTRL;                        //00000088
	HAL_Reg8  T1CLK;                          //00000089
	HAL_Reg8  T1CMCTRL;                       //0000008A
	HAL_Reg8  T1STATUS;                       //0000008B
	HAL_Reg16 T1CMPL;                         //0000008C
	HAL_Reg16 T1VALL;                         //0000008E
	HAL_Reg8  T2CNTRL;                        //00000090
	HAL_Reg8  T2CLK;                          //00000091
	HAL_Reg8  T2CMCTRL;                       //00000092
	HAL_Reg8  T2STATUS;                       //00000093
	HAL_Reg16 T2CMPL;                         //00000094
	HAL_Reg16 T2VALL;                         //00000096
	HAL_Reg8  T3CNTRL;                        //00000098
	HAL_Reg8  T3CLK;                          //00000099
	HAL_Reg8  T3CMCTRL;                       //0000009A
	HAL_Reg8  T3STATUS;                       //0000009B
	HAL_Reg16 T3CMPL;                         //0000009C
	HAL_Reg16 T3VALL;                         //0000009E
	HAL_Reg8  T4CNTRL;                        //000000A0
	HAL_Reg8  T4CLK;                          //000000A1
	HAL_Reg8  T4CMCTRL;                       //000000A2
	HAL_Reg8  T4STATUS;                       //000000A3
	HAL_Reg16 T4CMPL;                         //000000A4
	HAL_Reg16 T4VALL;                         //000000A6
	HAL_Reg8  T5CNTRL;                        //000000A8
	HAL_Reg8  T5CLK;                          //000000A9
	HAL_Reg8  T5CMCTRL;                       //000000AA
	HAL_Reg8  T5STATUS;                       //000000AB
	HAL_Reg16 T5CMPL;                         //000000AC
	HAL_Reg16 T5VALL;                         //000000AE
	HAL_Reg8  T6CNTRL;                        //000000B0
	HAL_Reg8  T6CLK;                          //000000B1
	HAL_Reg8  T6CMCTRL;                       //000000B2
	HAL_Reg8  T6STATUS;                       //000000B3
	HAL_Reg16 T6CMPL;                         //000000B4
	HAL_Reg16 T6VALL;                         //000000B6
	HAL_Reg8  T7CNTRL;                        //000000B8
	HAL_Reg8  T7CLK;                          //000000B9
	HAL_Reg8  T7CMCTRL;                       //000000BA
	HAL_Reg8  T7STATUS;                       //000000BB
	HAL_Reg16 T7CMPL;                         //000000BC
	HAL_Reg16 T7VALL;                         //000000BE
	HAL_Reg8  PADATA;                         //000000C0
	HAL_Reg8  PACTRL;                         //000000C1
	HAL_Reg8  PBDATA;                         //000000C2
	HAL_Reg8  PBCTRL;                         //000000C3
	HAL_Reg8  PCDATA;                         //000000C4
	HAL_Reg8  PCCTRL;                         //000000C5
	HAL_Reg8  ReservedBlk1[10];               //000000C6
	HAL_Reg16 ADC0L;                          //000000D0
	HAL_Reg16 ADC1L;                          //000000D2
	HAL_Reg16 ADC2L;                          //000000D4
	HAL_Reg16 ADC3L;                          //000000D6
	HAL_Reg16 ADC4L;                          //000000D8
	HAL_Reg16 ADC5L;                          //000000DA
	HAL_Reg16 ADC6L;                          //000000DC
	HAL_Reg16 ADC7L;                          //000000DE
	HAL_Reg16 ADC8L;                          //000000E0
	HAL_Reg16 ADC9L;                          //000000E2
	HAL_Reg16 ADC10L;                         //000000E4
	HAL_Reg16 ADC11L;                         //000000E6
	HAL_Reg16 ADC12L;                         //000000E8
	HAL_Reg16 ADC13L;                         //000000EA
	HAL_Reg16 ADC14L;                         //000000EC
	HAL_Reg16 ADC15L;                         //000000EE
	HAL_Reg8  ADCSTATL;                       //000000F0
	HAL_Reg8  ADCSTATH;                       //000000F1
	HAL_Reg8  ReservedBlk2[2];                //000000F2
	HAL_Reg8  ADCCTL;                         //000000F4
};
// Register T0CNTRL
#define HAL_PERIPH_T0STRT_REGISTER    (HAL_PERIPHREG_MAP->T0CNTRL)
#define HAL_PERIPH_T0STRT_LSB         7
#define HAL_PERIPH_T0STRT_MSB         7
#define HAL_PERIPH_T0STRT_MASK        0x00000080
#define HAL_PERIPH_T0STRT_TYPE        Bool
#define HAL_PERIPH_T0STRT             HAL_PERIPH_T0STRT_MASK
#define HAL_PERIPH_T0STRT_READABLE    1
#define HAL_PERIPH_T0STRT_WRITABLE    1
#define HAL_PERIPH_T0STRT_SIGNED      0
#define HAL_PERIPH_T0STRT_ADR         0x10000580

#define HAL_PERIPH_T0BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T0CNTRL)
#define HAL_PERIPH_T0BRKEN_LSB         5
#define HAL_PERIPH_T0BRKEN_MSB         5
#define HAL_PERIPH_T0BRKEN_MASK        0x00000020
#define HAL_PERIPH_T0BRKEN_TYPE        Bool
#define HAL_PERIPH_T0BRKEN             HAL_PERIPH_T0BRKEN_MASK
#define HAL_PERIPH_T0BRKEN_READABLE    1
#define HAL_PERIPH_T0BRKEN_WRITABLE    1
#define HAL_PERIPH_T0BRKEN_SIGNED      0
#define HAL_PERIPH_T0BRKEN_ADR         0x10000580

#define HAL_PERIPH_T0ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T0CNTRL)
#define HAL_PERIPH_T0ASTOP_LSB         4
#define HAL_PERIPH_T0ASTOP_MSB         4
#define HAL_PERIPH_T0ASTOP_MASK        0x00000010
#define HAL_PERIPH_T0ASTOP_TYPE        Bool
#define HAL_PERIPH_T0ASTOP             HAL_PERIPH_T0ASTOP_MASK
#define HAL_PERIPH_T0ASTOP_READABLE    1
#define HAL_PERIPH_T0ASTOP_WRITABLE    1
#define HAL_PERIPH_T0ASTOP_SIGNED      0
#define HAL_PERIPH_T0ASTOP_ADR         0x10000580

#define HAL_PERIPH_T0INTEN_REGISTER    (HAL_PERIPHREG_MAP->T0CNTRL)
#define HAL_PERIPH_T0INTEN_LSB         2
#define HAL_PERIPH_T0INTEN_MSB         3
#define HAL_PERIPH_T0INTEN_MASK        0x0000000C
#define HAL_PERIPH_T0INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T0INTEN             HAL_PERIPH_T0INTEN_MASK
#define HAL_PERIPH_T0INTEN_READABLE    1
#define HAL_PERIPH_T0INTEN_WRITABLE    1
#define HAL_PERIPH_T0INTEN_SIGNED      0
#define HAL_PERIPH_T0INTEN_ADR         0x10000580

#define HAL_PERIPH_T0MOD_REGISTER    (HAL_PERIPHREG_MAP->T0CNTRL)
#define HAL_PERIPH_T0MOD_LSB         0
#define HAL_PERIPH_T0MOD_MSB         1
#define HAL_PERIPH_T0MOD_MASK        0x00000003
#define HAL_PERIPH_T0MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T0MOD             HAL_PERIPH_T0MOD_MASK
#define HAL_PERIPH_T0MOD_READABLE    1
#define HAL_PERIPH_T0MOD_WRITABLE    1
#define HAL_PERIPH_T0MOD_SIGNED      0
#define HAL_PERIPH_T0MOD_ADR         0x10000580

// Register T0CLK
#define HAL_PERIPH_T0CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T0CLK)
#define HAL_PERIPH_T0CKDIV_LSB         0
#define HAL_PERIPH_T0CKDIV_MSB         2
#define HAL_PERIPH_T0CKDIV_MASK        0x00000007
#define HAL_PERIPH_T0CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T0CKDIV             HAL_PERIPH_T0CKDIV_MASK
#define HAL_PERIPH_T0CKDIV_READABLE    1
#define HAL_PERIPH_T0CKDIV_WRITABLE    1
#define HAL_PERIPH_T0CKDIV_SIGNED      0
#define HAL_PERIPH_T0CKDIV_ADR         0x10000581

// Register T0CMCTRL
#define HAL_PERIPH_T0MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T0CMCTRL)
#define HAL_PERIPH_T0MSREDG_LSB         4
#define HAL_PERIPH_T0MSREDG_MSB         4
#define HAL_PERIPH_T0MSREDG_MASK        0x00000010
#define HAL_PERIPH_T0MSREDG_TYPE        Bool
#define HAL_PERIPH_T0MSREDG             HAL_PERIPH_T0MSREDG_MASK
#define HAL_PERIPH_T0MSREDG_READABLE    1
#define HAL_PERIPH_T0MSREDG_WRITABLE    1
#define HAL_PERIPH_T0MSREDG_SIGNED      0
#define HAL_PERIPH_T0MSREDG_ADR         0x10000582

#define HAL_PERIPH_T0CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T0CMCTRL)
#define HAL_PERIPH_T0CMPOL_LSB         3
#define HAL_PERIPH_T0CMPOL_MSB         3
#define HAL_PERIPH_T0CMPOL_MASK        0x00000008
#define HAL_PERIPH_T0CMPOL_TYPE        Bool
#define HAL_PERIPH_T0CMPOL             HAL_PERIPH_T0CMPOL_MASK
#define HAL_PERIPH_T0CMPOL_READABLE    1
#define HAL_PERIPH_T0CMPOL_WRITABLE    1
#define HAL_PERIPH_T0CMPOL_SIGNED      0
#define HAL_PERIPH_T0CMPOL_ADR         0x10000582

#define HAL_PERIPH_T0CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T0CMCTRL)
#define HAL_PERIPH_T0CMSEL_LSB         0
#define HAL_PERIPH_T0CMSEL_MSB         1
#define HAL_PERIPH_T0CMSEL_MASK        0x00000003
#define HAL_PERIPH_T0CMSEL_TYPE        halPERIPH_T0CMInput_t
#define HAL_PERIPH_T0CMSEL             HAL_PERIPH_T0CMSEL_MASK
#define HAL_PERIPH_T0CMSEL_READABLE    1
#define HAL_PERIPH_T0CMSEL_WRITABLE    1
#define HAL_PERIPH_T0CMSEL_SIGNED      0
#define HAL_PERIPH_T0CMSEL_ADR         0x10000582

// Register T0STATUS
#define HAL_PERIPH_T0OVFL_REGISTER    (HAL_PERIPHREG_MAP->T0STATUS)
#define HAL_PERIPH_T0OVFL_LSB         2
#define HAL_PERIPH_T0OVFL_MSB         2
#define HAL_PERIPH_T0OVFL_MASK        0x00000004
#define HAL_PERIPH_T0OVFL_TYPE        Bool
#define HAL_PERIPH_T0OVFL             HAL_PERIPH_T0OVFL_MASK
#define HAL_PERIPH_T0OVFL_READABLE    1
#define HAL_PERIPH_T0OVFL_WRITABLE    0
#define HAL_PERIPH_T0OVFL_SIGNED      0
#define HAL_PERIPH_T0OVFL_ADR         0x10000583

#define HAL_PERIPH_T0BUSY_REGISTER    (HAL_PERIPHREG_MAP->T0STATUS)
#define HAL_PERIPH_T0BUSY_LSB         1
#define HAL_PERIPH_T0BUSY_MSB         1
#define HAL_PERIPH_T0BUSY_MASK        0x00000002
#define HAL_PERIPH_T0BUSY_TYPE        Bool
#define HAL_PERIPH_T0BUSY             HAL_PERIPH_T0BUSY_MASK
#define HAL_PERIPH_T0BUSY_READABLE    1
#define HAL_PERIPH_T0BUSY_WRITABLE    0
#define HAL_PERIPH_T0BUSY_SIGNED      0
#define HAL_PERIPH_T0BUSY_ADR         0x10000583

#define HAL_PERIPH_T0INTF_REGISTER    (HAL_PERIPHREG_MAP->T0STATUS)
#define HAL_PERIPH_T0INTF_LSB         0
#define HAL_PERIPH_T0INTF_MSB         0
#define HAL_PERIPH_T0INTF_MASK        0x00000001
#define HAL_PERIPH_T0INTF_TYPE        Bool
#define HAL_PERIPH_T0INTF             HAL_PERIPH_T0INTF_MASK
#define HAL_PERIPH_T0INTF_READABLE    1
#define HAL_PERIPH_T0INTF_WRITABLE    1
#define HAL_PERIPH_T0INTF_SIGNED      0
#define HAL_PERIPH_T0INTF_ADR         0x10000583

// Registers T0CMPL/T0CMPH
#define HAL_PERIPH_T0CMP_REGISTER    (HAL_PERIPHREG_MAP->T0CMPL)
#define HAL_PERIPH_T0CMP_LSB         0
#define HAL_PERIPH_T0CMP_MSB         15
#define HAL_PERIPH_T0CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T0CMP_TYPE        UInt16
#define HAL_PERIPH_T0CMP             HAL_PERIPH_T0CMP_MASK
#define HAL_PERIPH_T0CMP_READABLE    1
#define HAL_PERIPH_T0CMP_WRITABLE    1
#define HAL_PERIPH_T0CMP_SIGNED      0
#define HAL_PERIPH_T0CMP_ADR         0x10000584

// Registers T0VALL/T0VALH
#define HAL_PERIPH_T0VAL_REGISTER    (HAL_PERIPHREG_MAP->T0VALL)
#define HAL_PERIPH_T0VAL_LSB         0
#define HAL_PERIPH_T0VAL_MSB         15
#define HAL_PERIPH_T0VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T0VAL_TYPE        UInt16
#define HAL_PERIPH_T0VAL             HAL_PERIPH_T0VAL_MASK
#define HAL_PERIPH_T0VAL_READABLE    1
#define HAL_PERIPH_T0VAL_WRITABLE    0
#define HAL_PERIPH_T0VAL_SIGNED      0
#define HAL_PERIPH_T0VAL_ADR         0x10000586

// Register T1CNTRL
#define HAL_PERIPH_T1STRT_REGISTER    (HAL_PERIPHREG_MAP->T1CNTRL)
#define HAL_PERIPH_T1STRT_LSB         7
#define HAL_PERIPH_T1STRT_MSB         7
#define HAL_PERIPH_T1STRT_MASK        0x00000080
#define HAL_PERIPH_T1STRT_TYPE        Bool
#define HAL_PERIPH_T1STRT             HAL_PERIPH_T1STRT_MASK
#define HAL_PERIPH_T1STRT_READABLE    1
#define HAL_PERIPH_T1STRT_WRITABLE    1
#define HAL_PERIPH_T1STRT_SIGNED      0
#define HAL_PERIPH_T1STRT_ADR         0x10000588

#define HAL_PERIPH_T1BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T1CNTRL)
#define HAL_PERIPH_T1BRKEN_LSB         5
#define HAL_PERIPH_T1BRKEN_MSB         5
#define HAL_PERIPH_T1BRKEN_MASK        0x00000020
#define HAL_PERIPH_T1BRKEN_TYPE        Bool
#define HAL_PERIPH_T1BRKEN             HAL_PERIPH_T1BRKEN_MASK
#define HAL_PERIPH_T1BRKEN_READABLE    1
#define HAL_PERIPH_T1BRKEN_WRITABLE    1
#define HAL_PERIPH_T1BRKEN_SIGNED      0
#define HAL_PERIPH_T1BRKEN_ADR         0x10000588

#define HAL_PERIPH_T1ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T1CNTRL)
#define HAL_PERIPH_T1ASTOP_LSB         4
#define HAL_PERIPH_T1ASTOP_MSB         4
#define HAL_PERIPH_T1ASTOP_MASK        0x00000010
#define HAL_PERIPH_T1ASTOP_TYPE        Bool
#define HAL_PERIPH_T1ASTOP             HAL_PERIPH_T1ASTOP_MASK
#define HAL_PERIPH_T1ASTOP_READABLE    1
#define HAL_PERIPH_T1ASTOP_WRITABLE    1
#define HAL_PERIPH_T1ASTOP_SIGNED      0
#define HAL_PERIPH_T1ASTOP_ADR         0x10000588

#define HAL_PERIPH_T1INTEN_REGISTER    (HAL_PERIPHREG_MAP->T1CNTRL)
#define HAL_PERIPH_T1INTEN_LSB         2
#define HAL_PERIPH_T1INTEN_MSB         3
#define HAL_PERIPH_T1INTEN_MASK        0x0000000C
#define HAL_PERIPH_T1INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T1INTEN             HAL_PERIPH_T1INTEN_MASK
#define HAL_PERIPH_T1INTEN_READABLE    1
#define HAL_PERIPH_T1INTEN_WRITABLE    1
#define HAL_PERIPH_T1INTEN_SIGNED      0
#define HAL_PERIPH_T1INTEN_ADR         0x10000588

#define HAL_PERIPH_T1MOD_REGISTER    (HAL_PERIPHREG_MAP->T1CNTRL)
#define HAL_PERIPH_T1MOD_LSB         0
#define HAL_PERIPH_T1MOD_MSB         1
#define HAL_PERIPH_T1MOD_MASK        0x00000003
#define HAL_PERIPH_T1MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T1MOD             HAL_PERIPH_T1MOD_MASK
#define HAL_PERIPH_T1MOD_READABLE    1
#define HAL_PERIPH_T1MOD_WRITABLE    1
#define HAL_PERIPH_T1MOD_SIGNED      0
#define HAL_PERIPH_T1MOD_ADR         0x10000588

// Register T1CLK
#define HAL_PERIPH_T1CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T1CLK)
#define HAL_PERIPH_T1CKDIV_LSB         0
#define HAL_PERIPH_T1CKDIV_MSB         2
#define HAL_PERIPH_T1CKDIV_MASK        0x00000007
#define HAL_PERIPH_T1CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T1CKDIV             HAL_PERIPH_T1CKDIV_MASK
#define HAL_PERIPH_T1CKDIV_READABLE    1
#define HAL_PERIPH_T1CKDIV_WRITABLE    1
#define HAL_PERIPH_T1CKDIV_SIGNED      0
#define HAL_PERIPH_T1CKDIV_ADR         0x10000589

// Register T1CMCTRL
#define HAL_PERIPH_T1MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T1CMCTRL)
#define HAL_PERIPH_T1MSREDG_LSB         4
#define HAL_PERIPH_T1MSREDG_MSB         4
#define HAL_PERIPH_T1MSREDG_MASK        0x00000010
#define HAL_PERIPH_T1MSREDG_TYPE        Bool
#define HAL_PERIPH_T1MSREDG             HAL_PERIPH_T1MSREDG_MASK
#define HAL_PERIPH_T1MSREDG_READABLE    1
#define HAL_PERIPH_T1MSREDG_WRITABLE    1
#define HAL_PERIPH_T1MSREDG_SIGNED      0
#define HAL_PERIPH_T1MSREDG_ADR         0x1000058A

#define HAL_PERIPH_T1CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T1CMCTRL)
#define HAL_PERIPH_T1CMPOL_LSB         3
#define HAL_PERIPH_T1CMPOL_MSB         3
#define HAL_PERIPH_T1CMPOL_MASK        0x00000008
#define HAL_PERIPH_T1CMPOL_TYPE        Bool
#define HAL_PERIPH_T1CMPOL             HAL_PERIPH_T1CMPOL_MASK
#define HAL_PERIPH_T1CMPOL_READABLE    1
#define HAL_PERIPH_T1CMPOL_WRITABLE    1
#define HAL_PERIPH_T1CMPOL_SIGNED      0
#define HAL_PERIPH_T1CMPOL_ADR         0x1000058A

#define HAL_PERIPH_T1CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T1CMCTRL)
#define HAL_PERIPH_T1CMSEL_LSB         0
#define HAL_PERIPH_T1CMSEL_MSB         1
#define HAL_PERIPH_T1CMSEL_MASK        0x00000003
#define HAL_PERIPH_T1CMSEL_TYPE        halPERIPH_T1CMInput_t
#define HAL_PERIPH_T1CMSEL             HAL_PERIPH_T1CMSEL_MASK
#define HAL_PERIPH_T1CMSEL_READABLE    1
#define HAL_PERIPH_T1CMSEL_WRITABLE    1
#define HAL_PERIPH_T1CMSEL_SIGNED      0
#define HAL_PERIPH_T1CMSEL_ADR         0x1000058A

// Register T1STATUS
#define HAL_PERIPH_T1OVFL_REGISTER    (HAL_PERIPHREG_MAP->T1STATUS)
#define HAL_PERIPH_T1OVFL_LSB         2
#define HAL_PERIPH_T1OVFL_MSB         2
#define HAL_PERIPH_T1OVFL_MASK        0x00000004
#define HAL_PERIPH_T1OVFL_TYPE        Bool
#define HAL_PERIPH_T1OVFL             HAL_PERIPH_T1OVFL_MASK
#define HAL_PERIPH_T1OVFL_READABLE    1
#define HAL_PERIPH_T1OVFL_WRITABLE    0
#define HAL_PERIPH_T1OVFL_SIGNED      0
#define HAL_PERIPH_T1OVFL_ADR         0x1000058B

#define HAL_PERIPH_T1BUSY_REGISTER    (HAL_PERIPHREG_MAP->T1STATUS)
#define HAL_PERIPH_T1BUSY_LSB         1
#define HAL_PERIPH_T1BUSY_MSB         1
#define HAL_PERIPH_T1BUSY_MASK        0x00000002
#define HAL_PERIPH_T1BUSY_TYPE        Bool
#define HAL_PERIPH_T1BUSY             HAL_PERIPH_T1BUSY_MASK
#define HAL_PERIPH_T1BUSY_READABLE    1
#define HAL_PERIPH_T1BUSY_WRITABLE    0
#define HAL_PERIPH_T1BUSY_SIGNED      0
#define HAL_PERIPH_T1BUSY_ADR         0x1000058B

#define HAL_PERIPH_T1INTF_REGISTER    (HAL_PERIPHREG_MAP->T1STATUS)
#define HAL_PERIPH_T1INTF_LSB         0
#define HAL_PERIPH_T1INTF_MSB         0
#define HAL_PERIPH_T1INTF_MASK        0x00000001
#define HAL_PERIPH_T1INTF_TYPE        Bool
#define HAL_PERIPH_T1INTF             HAL_PERIPH_T1INTF_MASK
#define HAL_PERIPH_T1INTF_READABLE    1
#define HAL_PERIPH_T1INTF_WRITABLE    1
#define HAL_PERIPH_T1INTF_SIGNED      0
#define HAL_PERIPH_T1INTF_ADR         0x1000058B

// Registers T1CMPL/T1CMPH
#define HAL_PERIPH_T1CMP_REGISTER    (HAL_PERIPHREG_MAP->T1CMPL)
#define HAL_PERIPH_T1CMP_LSB         0
#define HAL_PERIPH_T1CMP_MSB         15
#define HAL_PERIPH_T1CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T1CMP_TYPE        UInt16
#define HAL_PERIPH_T1CMP             HAL_PERIPH_T1CMP_MASK
#define HAL_PERIPH_T1CMP_READABLE    1
#define HAL_PERIPH_T1CMP_WRITABLE    1
#define HAL_PERIPH_T1CMP_SIGNED      0
#define HAL_PERIPH_T1CMP_ADR         0x1000058C

// Registers T1VALL/T1VALH
#define HAL_PERIPH_T1VAL_REGISTER    (HAL_PERIPHREG_MAP->T1VALL)
#define HAL_PERIPH_T1VAL_LSB         0
#define HAL_PERIPH_T1VAL_MSB         15
#define HAL_PERIPH_T1VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T1VAL_TYPE        UInt16
#define HAL_PERIPH_T1VAL             HAL_PERIPH_T1VAL_MASK
#define HAL_PERIPH_T1VAL_READABLE    1
#define HAL_PERIPH_T1VAL_WRITABLE    0
#define HAL_PERIPH_T1VAL_SIGNED      0
#define HAL_PERIPH_T1VAL_ADR         0x1000058E

// Register T2CNTRL
#define HAL_PERIPH_T2STRT_REGISTER    (HAL_PERIPHREG_MAP->T2CNTRL)
#define HAL_PERIPH_T2STRT_LSB         7
#define HAL_PERIPH_T2STRT_MSB         7
#define HAL_PERIPH_T2STRT_MASK        0x00000080
#define HAL_PERIPH_T2STRT_TYPE        Bool
#define HAL_PERIPH_T2STRT             HAL_PERIPH_T2STRT_MASK
#define HAL_PERIPH_T2STRT_READABLE    1
#define HAL_PERIPH_T2STRT_WRITABLE    1
#define HAL_PERIPH_T2STRT_SIGNED      0
#define HAL_PERIPH_T2STRT_ADR         0x10000590

#define HAL_PERIPH_T2BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T2CNTRL)
#define HAL_PERIPH_T2BRKEN_LSB         5
#define HAL_PERIPH_T2BRKEN_MSB         5
#define HAL_PERIPH_T2BRKEN_MASK        0x00000020
#define HAL_PERIPH_T2BRKEN_TYPE        Bool
#define HAL_PERIPH_T2BRKEN             HAL_PERIPH_T2BRKEN_MASK
#define HAL_PERIPH_T2BRKEN_READABLE    1
#define HAL_PERIPH_T2BRKEN_WRITABLE    1
#define HAL_PERIPH_T2BRKEN_SIGNED      0
#define HAL_PERIPH_T2BRKEN_ADR         0x10000590

#define HAL_PERIPH_T2ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T2CNTRL)
#define HAL_PERIPH_T2ASTOP_LSB         4
#define HAL_PERIPH_T2ASTOP_MSB         4
#define HAL_PERIPH_T2ASTOP_MASK        0x00000010
#define HAL_PERIPH_T2ASTOP_TYPE        Bool
#define HAL_PERIPH_T2ASTOP             HAL_PERIPH_T2ASTOP_MASK
#define HAL_PERIPH_T2ASTOP_READABLE    1
#define HAL_PERIPH_T2ASTOP_WRITABLE    1
#define HAL_PERIPH_T2ASTOP_SIGNED      0
#define HAL_PERIPH_T2ASTOP_ADR         0x10000590

#define HAL_PERIPH_T2INTEN_REGISTER    (HAL_PERIPHREG_MAP->T2CNTRL)
#define HAL_PERIPH_T2INTEN_LSB         2
#define HAL_PERIPH_T2INTEN_MSB         3
#define HAL_PERIPH_T2INTEN_MASK        0x0000000C
#define HAL_PERIPH_T2INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T2INTEN             HAL_PERIPH_T2INTEN_MASK
#define HAL_PERIPH_T2INTEN_READABLE    1
#define HAL_PERIPH_T2INTEN_WRITABLE    1
#define HAL_PERIPH_T2INTEN_SIGNED      0
#define HAL_PERIPH_T2INTEN_ADR         0x10000590

#define HAL_PERIPH_T2MOD_REGISTER    (HAL_PERIPHREG_MAP->T2CNTRL)
#define HAL_PERIPH_T2MOD_LSB         0
#define HAL_PERIPH_T2MOD_MSB         1
#define HAL_PERIPH_T2MOD_MASK        0x00000003
#define HAL_PERIPH_T2MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T2MOD             HAL_PERIPH_T2MOD_MASK
#define HAL_PERIPH_T2MOD_READABLE    1
#define HAL_PERIPH_T2MOD_WRITABLE    1
#define HAL_PERIPH_T2MOD_SIGNED      0
#define HAL_PERIPH_T2MOD_ADR         0x10000590

// Register T2CLK
#define HAL_PERIPH_T2CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T2CLK)
#define HAL_PERIPH_T2CKDIV_LSB         0
#define HAL_PERIPH_T2CKDIV_MSB         2
#define HAL_PERIPH_T2CKDIV_MASK        0x00000007
#define HAL_PERIPH_T2CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T2CKDIV             HAL_PERIPH_T2CKDIV_MASK
#define HAL_PERIPH_T2CKDIV_READABLE    1
#define HAL_PERIPH_T2CKDIV_WRITABLE    1
#define HAL_PERIPH_T2CKDIV_SIGNED      0
#define HAL_PERIPH_T2CKDIV_ADR         0x10000591

// Register T2CMCTRL
#define HAL_PERIPH_T2MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T2CMCTRL)
#define HAL_PERIPH_T2MSREDG_LSB         4
#define HAL_PERIPH_T2MSREDG_MSB         4
#define HAL_PERIPH_T2MSREDG_MASK        0x00000010
#define HAL_PERIPH_T2MSREDG_TYPE        Bool
#define HAL_PERIPH_T2MSREDG             HAL_PERIPH_T2MSREDG_MASK
#define HAL_PERIPH_T2MSREDG_READABLE    1
#define HAL_PERIPH_T2MSREDG_WRITABLE    1
#define HAL_PERIPH_T2MSREDG_SIGNED      0
#define HAL_PERIPH_T2MSREDG_ADR         0x10000592

#define HAL_PERIPH_T2CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T2CMCTRL)
#define HAL_PERIPH_T2CMPOL_LSB         3
#define HAL_PERIPH_T2CMPOL_MSB         3
#define HAL_PERIPH_T2CMPOL_MASK        0x00000008
#define HAL_PERIPH_T2CMPOL_TYPE        Bool
#define HAL_PERIPH_T2CMPOL             HAL_PERIPH_T2CMPOL_MASK
#define HAL_PERIPH_T2CMPOL_READABLE    1
#define HAL_PERIPH_T2CMPOL_WRITABLE    1
#define HAL_PERIPH_T2CMPOL_SIGNED      0
#define HAL_PERIPH_T2CMPOL_ADR         0x10000592

#define HAL_PERIPH_T2CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T2CMCTRL)
#define HAL_PERIPH_T2CMSEL_LSB         0
#define HAL_PERIPH_T2CMSEL_MSB         1
#define HAL_PERIPH_T2CMSEL_MASK        0x00000003
#define HAL_PERIPH_T2CMSEL_TYPE        halPERIPH_T2CMInput_t
#define HAL_PERIPH_T2CMSEL             HAL_PERIPH_T2CMSEL_MASK
#define HAL_PERIPH_T2CMSEL_READABLE    1
#define HAL_PERIPH_T2CMSEL_WRITABLE    1
#define HAL_PERIPH_T2CMSEL_SIGNED      0
#define HAL_PERIPH_T2CMSEL_ADR         0x10000592

// Register T2STATUS
#define HAL_PERIPH_T2OVFL_REGISTER    (HAL_PERIPHREG_MAP->T2STATUS)
#define HAL_PERIPH_T2OVFL_LSB         2
#define HAL_PERIPH_T2OVFL_MSB         2
#define HAL_PERIPH_T2OVFL_MASK        0x00000004
#define HAL_PERIPH_T2OVFL_TYPE        Bool
#define HAL_PERIPH_T2OVFL             HAL_PERIPH_T2OVFL_MASK
#define HAL_PERIPH_T2OVFL_READABLE    1
#define HAL_PERIPH_T2OVFL_WRITABLE    0
#define HAL_PERIPH_T2OVFL_SIGNED      0
#define HAL_PERIPH_T2OVFL_ADR         0x10000593

#define HAL_PERIPH_T2BUSY_REGISTER    (HAL_PERIPHREG_MAP->T2STATUS)
#define HAL_PERIPH_T2BUSY_LSB         1
#define HAL_PERIPH_T2BUSY_MSB         1
#define HAL_PERIPH_T2BUSY_MASK        0x00000002
#define HAL_PERIPH_T2BUSY_TYPE        Bool
#define HAL_PERIPH_T2BUSY             HAL_PERIPH_T2BUSY_MASK
#define HAL_PERIPH_T2BUSY_READABLE    1
#define HAL_PERIPH_T2BUSY_WRITABLE    0
#define HAL_PERIPH_T2BUSY_SIGNED      0
#define HAL_PERIPH_T2BUSY_ADR         0x10000593

#define HAL_PERIPH_T2INTF_REGISTER    (HAL_PERIPHREG_MAP->T2STATUS)
#define HAL_PERIPH_T2INTF_LSB         0
#define HAL_PERIPH_T2INTF_MSB         0
#define HAL_PERIPH_T2INTF_MASK        0x00000001
#define HAL_PERIPH_T2INTF_TYPE        Bool
#define HAL_PERIPH_T2INTF             HAL_PERIPH_T2INTF_MASK
#define HAL_PERIPH_T2INTF_READABLE    1
#define HAL_PERIPH_T2INTF_WRITABLE    1
#define HAL_PERIPH_T2INTF_SIGNED      0
#define HAL_PERIPH_T2INTF_ADR         0x10000593

// Registers T2CMPL/T2CMPH
#define HAL_PERIPH_T2CMP_REGISTER    (HAL_PERIPHREG_MAP->T2CMPL)
#define HAL_PERIPH_T2CMP_LSB         0
#define HAL_PERIPH_T2CMP_MSB         15
#define HAL_PERIPH_T2CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T2CMP_TYPE        UInt16
#define HAL_PERIPH_T2CMP             HAL_PERIPH_T2CMP_MASK
#define HAL_PERIPH_T2CMP_READABLE    1
#define HAL_PERIPH_T2CMP_WRITABLE    1
#define HAL_PERIPH_T2CMP_SIGNED      0
#define HAL_PERIPH_T2CMP_ADR         0x10000594

// Registers T2VALL/T2VALH
#define HAL_PERIPH_T2VAL_REGISTER    (HAL_PERIPHREG_MAP->T2VALL)
#define HAL_PERIPH_T2VAL_LSB         0
#define HAL_PERIPH_T2VAL_MSB         15
#define HAL_PERIPH_T2VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T2VAL_TYPE        UInt16
#define HAL_PERIPH_T2VAL             HAL_PERIPH_T2VAL_MASK
#define HAL_PERIPH_T2VAL_READABLE    1
#define HAL_PERIPH_T2VAL_WRITABLE    0
#define HAL_PERIPH_T2VAL_SIGNED      0
#define HAL_PERIPH_T2VAL_ADR         0x10000596

// Register T3CNTRL
#define HAL_PERIPH_T3STRT_REGISTER    (HAL_PERIPHREG_MAP->T3CNTRL)
#define HAL_PERIPH_T3STRT_LSB         7
#define HAL_PERIPH_T3STRT_MSB         7
#define HAL_PERIPH_T3STRT_MASK        0x00000080
#define HAL_PERIPH_T3STRT_TYPE        Bool
#define HAL_PERIPH_T3STRT             HAL_PERIPH_T3STRT_MASK
#define HAL_PERIPH_T3STRT_READABLE    1
#define HAL_PERIPH_T3STRT_WRITABLE    1
#define HAL_PERIPH_T3STRT_SIGNED      0
#define HAL_PERIPH_T3STRT_ADR         0x10000598

#define HAL_PERIPH_T3BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T3CNTRL)
#define HAL_PERIPH_T3BRKEN_LSB         5
#define HAL_PERIPH_T3BRKEN_MSB         5
#define HAL_PERIPH_T3BRKEN_MASK        0x00000020
#define HAL_PERIPH_T3BRKEN_TYPE        Bool
#define HAL_PERIPH_T3BRKEN             HAL_PERIPH_T3BRKEN_MASK
#define HAL_PERIPH_T3BRKEN_READABLE    1
#define HAL_PERIPH_T3BRKEN_WRITABLE    1
#define HAL_PERIPH_T3BRKEN_SIGNED      0
#define HAL_PERIPH_T3BRKEN_ADR         0x10000598

#define HAL_PERIPH_T3ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T3CNTRL)
#define HAL_PERIPH_T3ASTOP_LSB         4
#define HAL_PERIPH_T3ASTOP_MSB         4
#define HAL_PERIPH_T3ASTOP_MASK        0x00000010
#define HAL_PERIPH_T3ASTOP_TYPE        Bool
#define HAL_PERIPH_T3ASTOP             HAL_PERIPH_T3ASTOP_MASK
#define HAL_PERIPH_T3ASTOP_READABLE    1
#define HAL_PERIPH_T3ASTOP_WRITABLE    1
#define HAL_PERIPH_T3ASTOP_SIGNED      0
#define HAL_PERIPH_T3ASTOP_ADR         0x10000598

#define HAL_PERIPH_T3INTEN_REGISTER    (HAL_PERIPHREG_MAP->T3CNTRL)
#define HAL_PERIPH_T3INTEN_LSB         2
#define HAL_PERIPH_T3INTEN_MSB         3
#define HAL_PERIPH_T3INTEN_MASK        0x0000000C
#define HAL_PERIPH_T3INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T3INTEN             HAL_PERIPH_T3INTEN_MASK
#define HAL_PERIPH_T3INTEN_READABLE    1
#define HAL_PERIPH_T3INTEN_WRITABLE    1
#define HAL_PERIPH_T3INTEN_SIGNED      0
#define HAL_PERIPH_T3INTEN_ADR         0x10000598

#define HAL_PERIPH_T3MOD_REGISTER    (HAL_PERIPHREG_MAP->T3CNTRL)
#define HAL_PERIPH_T3MOD_LSB         0
#define HAL_PERIPH_T3MOD_MSB         1
#define HAL_PERIPH_T3MOD_MASK        0x00000003
#define HAL_PERIPH_T3MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T3MOD             HAL_PERIPH_T3MOD_MASK
#define HAL_PERIPH_T3MOD_READABLE    1
#define HAL_PERIPH_T3MOD_WRITABLE    1
#define HAL_PERIPH_T3MOD_SIGNED      0
#define HAL_PERIPH_T3MOD_ADR         0x10000598

// Register T3CLK
#define HAL_PERIPH_T3CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T3CLK)
#define HAL_PERIPH_T3CKDIV_LSB         0
#define HAL_PERIPH_T3CKDIV_MSB         2
#define HAL_PERIPH_T3CKDIV_MASK        0x00000007
#define HAL_PERIPH_T3CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T3CKDIV             HAL_PERIPH_T3CKDIV_MASK
#define HAL_PERIPH_T3CKDIV_READABLE    1
#define HAL_PERIPH_T3CKDIV_WRITABLE    1
#define HAL_PERIPH_T3CKDIV_SIGNED      0
#define HAL_PERIPH_T3CKDIV_ADR         0x10000599

// Register T3CMCTRL
#define HAL_PERIPH_T3MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T3CMCTRL)
#define HAL_PERIPH_T3MSREDG_LSB         4
#define HAL_PERIPH_T3MSREDG_MSB         4
#define HAL_PERIPH_T3MSREDG_MASK        0x00000010
#define HAL_PERIPH_T3MSREDG_TYPE        Bool
#define HAL_PERIPH_T3MSREDG             HAL_PERIPH_T3MSREDG_MASK
#define HAL_PERIPH_T3MSREDG_READABLE    1
#define HAL_PERIPH_T3MSREDG_WRITABLE    1
#define HAL_PERIPH_T3MSREDG_SIGNED      0
#define HAL_PERIPH_T3MSREDG_ADR         0x1000059A

#define HAL_PERIPH_T3CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T3CMCTRL)
#define HAL_PERIPH_T3CMPOL_LSB         3
#define HAL_PERIPH_T3CMPOL_MSB         3
#define HAL_PERIPH_T3CMPOL_MASK        0x00000008
#define HAL_PERIPH_T3CMPOL_TYPE        Bool
#define HAL_PERIPH_T3CMPOL             HAL_PERIPH_T3CMPOL_MASK
#define HAL_PERIPH_T3CMPOL_READABLE    1
#define HAL_PERIPH_T3CMPOL_WRITABLE    1
#define HAL_PERIPH_T3CMPOL_SIGNED      0
#define HAL_PERIPH_T3CMPOL_ADR         0x1000059A

#define HAL_PERIPH_T3CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T3CMCTRL)
#define HAL_PERIPH_T3CMSEL_LSB         0
#define HAL_PERIPH_T3CMSEL_MSB         1
#define HAL_PERIPH_T3CMSEL_MASK        0x00000003
#define HAL_PERIPH_T3CMSEL_TYPE        halPERIPH_T3CMInput_t
#define HAL_PERIPH_T3CMSEL             HAL_PERIPH_T3CMSEL_MASK
#define HAL_PERIPH_T3CMSEL_READABLE    1
#define HAL_PERIPH_T3CMSEL_WRITABLE    1
#define HAL_PERIPH_T3CMSEL_SIGNED      0
#define HAL_PERIPH_T3CMSEL_ADR         0x1000059A

// Register T3STATUS
#define HAL_PERIPH_T3OVFL_REGISTER    (HAL_PERIPHREG_MAP->T3STATUS)
#define HAL_PERIPH_T3OVFL_LSB         2
#define HAL_PERIPH_T3OVFL_MSB         2
#define HAL_PERIPH_T3OVFL_MASK        0x00000004
#define HAL_PERIPH_T3OVFL_TYPE        Bool
#define HAL_PERIPH_T3OVFL             HAL_PERIPH_T3OVFL_MASK
#define HAL_PERIPH_T3OVFL_READABLE    1
#define HAL_PERIPH_T3OVFL_WRITABLE    0
#define HAL_PERIPH_T3OVFL_SIGNED      0
#define HAL_PERIPH_T3OVFL_ADR         0x1000059B

#define HAL_PERIPH_T3BUSY_REGISTER    (HAL_PERIPHREG_MAP->T3STATUS)
#define HAL_PERIPH_T3BUSY_LSB         1
#define HAL_PERIPH_T3BUSY_MSB         1
#define HAL_PERIPH_T3BUSY_MASK        0x00000002
#define HAL_PERIPH_T3BUSY_TYPE        Bool
#define HAL_PERIPH_T3BUSY             HAL_PERIPH_T3BUSY_MASK
#define HAL_PERIPH_T3BUSY_READABLE    1
#define HAL_PERIPH_T3BUSY_WRITABLE    0
#define HAL_PERIPH_T3BUSY_SIGNED      0
#define HAL_PERIPH_T3BUSY_ADR         0x1000059B

#define HAL_PERIPH_T3INTF_REGISTER    (HAL_PERIPHREG_MAP->T3STATUS)
#define HAL_PERIPH_T3INTF_LSB         0
#define HAL_PERIPH_T3INTF_MSB         0
#define HAL_PERIPH_T3INTF_MASK        0x00000001
#define HAL_PERIPH_T3INTF_TYPE        Bool
#define HAL_PERIPH_T3INTF             HAL_PERIPH_T3INTF_MASK
#define HAL_PERIPH_T3INTF_READABLE    1
#define HAL_PERIPH_T3INTF_WRITABLE    1
#define HAL_PERIPH_T3INTF_SIGNED      0
#define HAL_PERIPH_T3INTF_ADR         0x1000059B

// Registers T3CMPL/T3CMPH
#define HAL_PERIPH_T3CMP_REGISTER    (HAL_PERIPHREG_MAP->T3CMPL)
#define HAL_PERIPH_T3CMP_LSB         0
#define HAL_PERIPH_T3CMP_MSB         15
#define HAL_PERIPH_T3CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T3CMP_TYPE        UInt16
#define HAL_PERIPH_T3CMP             HAL_PERIPH_T3CMP_MASK
#define HAL_PERIPH_T3CMP_READABLE    1
#define HAL_PERIPH_T3CMP_WRITABLE    1
#define HAL_PERIPH_T3CMP_SIGNED      0
#define HAL_PERIPH_T3CMP_ADR         0x1000059C

// Registers T3VALL/T3VALH
#define HAL_PERIPH_T3VAL_REGISTER    (HAL_PERIPHREG_MAP->T3VALL)
#define HAL_PERIPH_T3VAL_LSB         0
#define HAL_PERIPH_T3VAL_MSB         15
#define HAL_PERIPH_T3VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T3VAL_TYPE        UInt16
#define HAL_PERIPH_T3VAL             HAL_PERIPH_T3VAL_MASK
#define HAL_PERIPH_T3VAL_READABLE    1
#define HAL_PERIPH_T3VAL_WRITABLE    0
#define HAL_PERIPH_T3VAL_SIGNED      0
#define HAL_PERIPH_T3VAL_ADR         0x1000059E

// Register T4CNTRL
#define HAL_PERIPH_T4STRT_REGISTER    (HAL_PERIPHREG_MAP->T4CNTRL)
#define HAL_PERIPH_T4STRT_LSB         7
#define HAL_PERIPH_T4STRT_MSB         7
#define HAL_PERIPH_T4STRT_MASK        0x00000080
#define HAL_PERIPH_T4STRT_TYPE        Bool
#define HAL_PERIPH_T4STRT             HAL_PERIPH_T4STRT_MASK
#define HAL_PERIPH_T4STRT_READABLE    1
#define HAL_PERIPH_T4STRT_WRITABLE    1
#define HAL_PERIPH_T4STRT_SIGNED      0
#define HAL_PERIPH_T4STRT_ADR         0x100005A0

#define HAL_PERIPH_T4BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T4CNTRL)
#define HAL_PERIPH_T4BRKEN_LSB         5
#define HAL_PERIPH_T4BRKEN_MSB         5
#define HAL_PERIPH_T4BRKEN_MASK        0x00000020
#define HAL_PERIPH_T4BRKEN_TYPE        Bool
#define HAL_PERIPH_T4BRKEN             HAL_PERIPH_T4BRKEN_MASK
#define HAL_PERIPH_T4BRKEN_READABLE    1
#define HAL_PERIPH_T4BRKEN_WRITABLE    1
#define HAL_PERIPH_T4BRKEN_SIGNED      0
#define HAL_PERIPH_T4BRKEN_ADR         0x100005A0

#define HAL_PERIPH_T4ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T4CNTRL)
#define HAL_PERIPH_T4ASTOP_LSB         4
#define HAL_PERIPH_T4ASTOP_MSB         4
#define HAL_PERIPH_T4ASTOP_MASK        0x00000010
#define HAL_PERIPH_T4ASTOP_TYPE        Bool
#define HAL_PERIPH_T4ASTOP             HAL_PERIPH_T4ASTOP_MASK
#define HAL_PERIPH_T4ASTOP_READABLE    1
#define HAL_PERIPH_T4ASTOP_WRITABLE    1
#define HAL_PERIPH_T4ASTOP_SIGNED      0
#define HAL_PERIPH_T4ASTOP_ADR         0x100005A0

#define HAL_PERIPH_T4INTEN_REGISTER    (HAL_PERIPHREG_MAP->T4CNTRL)
#define HAL_PERIPH_T4INTEN_LSB         2
#define HAL_PERIPH_T4INTEN_MSB         3
#define HAL_PERIPH_T4INTEN_MASK        0x0000000C
#define HAL_PERIPH_T4INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T4INTEN             HAL_PERIPH_T4INTEN_MASK
#define HAL_PERIPH_T4INTEN_READABLE    1
#define HAL_PERIPH_T4INTEN_WRITABLE    1
#define HAL_PERIPH_T4INTEN_SIGNED      0
#define HAL_PERIPH_T4INTEN_ADR         0x100005A0

#define HAL_PERIPH_T4MOD_REGISTER    (HAL_PERIPHREG_MAP->T4CNTRL)
#define HAL_PERIPH_T4MOD_LSB         0
#define HAL_PERIPH_T4MOD_MSB         1
#define HAL_PERIPH_T4MOD_MASK        0x00000003
#define HAL_PERIPH_T4MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T4MOD             HAL_PERIPH_T4MOD_MASK
#define HAL_PERIPH_T4MOD_READABLE    1
#define HAL_PERIPH_T4MOD_WRITABLE    1
#define HAL_PERIPH_T4MOD_SIGNED      0
#define HAL_PERIPH_T4MOD_ADR         0x100005A0

// Register T4CLK
#define HAL_PERIPH_T4CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T4CLK)
#define HAL_PERIPH_T4CKDIV_LSB         0
#define HAL_PERIPH_T4CKDIV_MSB         2
#define HAL_PERIPH_T4CKDIV_MASK        0x00000007
#define HAL_PERIPH_T4CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T4CKDIV             HAL_PERIPH_T4CKDIV_MASK
#define HAL_PERIPH_T4CKDIV_READABLE    1
#define HAL_PERIPH_T4CKDIV_WRITABLE    1
#define HAL_PERIPH_T4CKDIV_SIGNED      0
#define HAL_PERIPH_T4CKDIV_ADR         0x100005A1

// Register T4CMCTRL
#define HAL_PERIPH_T4MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T4CMCTRL)
#define HAL_PERIPH_T4MSREDG_LSB         4
#define HAL_PERIPH_T4MSREDG_MSB         4
#define HAL_PERIPH_T4MSREDG_MASK        0x00000010
#define HAL_PERIPH_T4MSREDG_TYPE        Bool
#define HAL_PERIPH_T4MSREDG             HAL_PERIPH_T4MSREDG_MASK
#define HAL_PERIPH_T4MSREDG_READABLE    1
#define HAL_PERIPH_T4MSREDG_WRITABLE    1
#define HAL_PERIPH_T4MSREDG_SIGNED      0
#define HAL_PERIPH_T4MSREDG_ADR         0x100005A2

#define HAL_PERIPH_T4CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T4CMCTRL)
#define HAL_PERIPH_T4CMPOL_LSB         3
#define HAL_PERIPH_T4CMPOL_MSB         3
#define HAL_PERIPH_T4CMPOL_MASK        0x00000008
#define HAL_PERIPH_T4CMPOL_TYPE        Bool
#define HAL_PERIPH_T4CMPOL             HAL_PERIPH_T4CMPOL_MASK
#define HAL_PERIPH_T4CMPOL_READABLE    1
#define HAL_PERIPH_T4CMPOL_WRITABLE    1
#define HAL_PERIPH_T4CMPOL_SIGNED      0
#define HAL_PERIPH_T4CMPOL_ADR         0x100005A2

#define HAL_PERIPH_T4CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T4CMCTRL)
#define HAL_PERIPH_T4CMSEL_LSB         0
#define HAL_PERIPH_T4CMSEL_MSB         1
#define HAL_PERIPH_T4CMSEL_MASK        0x00000003
#define HAL_PERIPH_T4CMSEL_TYPE        halPERIPH_T4CMInput_t
#define HAL_PERIPH_T4CMSEL             HAL_PERIPH_T4CMSEL_MASK
#define HAL_PERIPH_T4CMSEL_READABLE    1
#define HAL_PERIPH_T4CMSEL_WRITABLE    1
#define HAL_PERIPH_T4CMSEL_SIGNED      0
#define HAL_PERIPH_T4CMSEL_ADR         0x100005A2

// Register T4STATUS
#define HAL_PERIPH_T4OVFL_REGISTER    (HAL_PERIPHREG_MAP->T4STATUS)
#define HAL_PERIPH_T4OVFL_LSB         2
#define HAL_PERIPH_T4OVFL_MSB         2
#define HAL_PERIPH_T4OVFL_MASK        0x00000004
#define HAL_PERIPH_T4OVFL_TYPE        Bool
#define HAL_PERIPH_T4OVFL             HAL_PERIPH_T4OVFL_MASK
#define HAL_PERIPH_T4OVFL_READABLE    1
#define HAL_PERIPH_T4OVFL_WRITABLE    0
#define HAL_PERIPH_T4OVFL_SIGNED      0
#define HAL_PERIPH_T4OVFL_ADR         0x100005A3

#define HAL_PERIPH_T4BUSY_REGISTER    (HAL_PERIPHREG_MAP->T4STATUS)
#define HAL_PERIPH_T4BUSY_LSB         1
#define HAL_PERIPH_T4BUSY_MSB         1
#define HAL_PERIPH_T4BUSY_MASK        0x00000002
#define HAL_PERIPH_T4BUSY_TYPE        Bool
#define HAL_PERIPH_T4BUSY             HAL_PERIPH_T4BUSY_MASK
#define HAL_PERIPH_T4BUSY_READABLE    1
#define HAL_PERIPH_T4BUSY_WRITABLE    0
#define HAL_PERIPH_T4BUSY_SIGNED      0
#define HAL_PERIPH_T4BUSY_ADR         0x100005A3

#define HAL_PERIPH_T4INTF_REGISTER    (HAL_PERIPHREG_MAP->T4STATUS)
#define HAL_PERIPH_T4INTF_LSB         0
#define HAL_PERIPH_T4INTF_MSB         0
#define HAL_PERIPH_T4INTF_MASK        0x00000001
#define HAL_PERIPH_T4INTF_TYPE        Bool
#define HAL_PERIPH_T4INTF             HAL_PERIPH_T4INTF_MASK
#define HAL_PERIPH_T4INTF_READABLE    1
#define HAL_PERIPH_T4INTF_WRITABLE    1
#define HAL_PERIPH_T4INTF_SIGNED      0
#define HAL_PERIPH_T4INTF_ADR         0x100005A3

// Registers T4CMPL/T4CMPH
#define HAL_PERIPH_T4CMP_REGISTER    (HAL_PERIPHREG_MAP->T4CMPL)
#define HAL_PERIPH_T4CMP_LSB         0
#define HAL_PERIPH_T4CMP_MSB         15
#define HAL_PERIPH_T4CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T4CMP_TYPE        UInt16
#define HAL_PERIPH_T4CMP             HAL_PERIPH_T4CMP_MASK
#define HAL_PERIPH_T4CMP_READABLE    1
#define HAL_PERIPH_T4CMP_WRITABLE    1
#define HAL_PERIPH_T4CMP_SIGNED      0
#define HAL_PERIPH_T4CMP_ADR         0x100005A4

// Registers T4VALL/T4VALH
#define HAL_PERIPH_T4VAL_REGISTER    (HAL_PERIPHREG_MAP->T4VALL)
#define HAL_PERIPH_T4VAL_LSB         0
#define HAL_PERIPH_T4VAL_MSB         15
#define HAL_PERIPH_T4VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T4VAL_TYPE        UInt16
#define HAL_PERIPH_T4VAL             HAL_PERIPH_T4VAL_MASK
#define HAL_PERIPH_T4VAL_READABLE    1
#define HAL_PERIPH_T4VAL_WRITABLE    0
#define HAL_PERIPH_T4VAL_SIGNED      0
#define HAL_PERIPH_T4VAL_ADR         0x100005A6

// Register T5CNTRL
#define HAL_PERIPH_T5STRT_REGISTER    (HAL_PERIPHREG_MAP->T5CNTRL)
#define HAL_PERIPH_T5STRT_LSB         7
#define HAL_PERIPH_T5STRT_MSB         7
#define HAL_PERIPH_T5STRT_MASK        0x00000080
#define HAL_PERIPH_T5STRT_TYPE        Bool
#define HAL_PERIPH_T5STRT             HAL_PERIPH_T5STRT_MASK
#define HAL_PERIPH_T5STRT_READABLE    1
#define HAL_PERIPH_T5STRT_WRITABLE    1
#define HAL_PERIPH_T5STRT_SIGNED      0
#define HAL_PERIPH_T5STRT_ADR         0x100005A8

#define HAL_PERIPH_T5BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T5CNTRL)
#define HAL_PERIPH_T5BRKEN_LSB         5
#define HAL_PERIPH_T5BRKEN_MSB         5
#define HAL_PERIPH_T5BRKEN_MASK        0x00000020
#define HAL_PERIPH_T5BRKEN_TYPE        Bool
#define HAL_PERIPH_T5BRKEN             HAL_PERIPH_T5BRKEN_MASK
#define HAL_PERIPH_T5BRKEN_READABLE    1
#define HAL_PERIPH_T5BRKEN_WRITABLE    1
#define HAL_PERIPH_T5BRKEN_SIGNED      0
#define HAL_PERIPH_T5BRKEN_ADR         0x100005A8

#define HAL_PERIPH_T5ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T5CNTRL)
#define HAL_PERIPH_T5ASTOP_LSB         4
#define HAL_PERIPH_T5ASTOP_MSB         4
#define HAL_PERIPH_T5ASTOP_MASK        0x00000010
#define HAL_PERIPH_T5ASTOP_TYPE        Bool
#define HAL_PERIPH_T5ASTOP             HAL_PERIPH_T5ASTOP_MASK
#define HAL_PERIPH_T5ASTOP_READABLE    1
#define HAL_PERIPH_T5ASTOP_WRITABLE    1
#define HAL_PERIPH_T5ASTOP_SIGNED      0
#define HAL_PERIPH_T5ASTOP_ADR         0x100005A8

#define HAL_PERIPH_T5INTEN_REGISTER    (HAL_PERIPHREG_MAP->T5CNTRL)
#define HAL_PERIPH_T5INTEN_LSB         2
#define HAL_PERIPH_T5INTEN_MSB         3
#define HAL_PERIPH_T5INTEN_MASK        0x0000000C
#define HAL_PERIPH_T5INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T5INTEN             HAL_PERIPH_T5INTEN_MASK
#define HAL_PERIPH_T5INTEN_READABLE    1
#define HAL_PERIPH_T5INTEN_WRITABLE    1
#define HAL_PERIPH_T5INTEN_SIGNED      0
#define HAL_PERIPH_T5INTEN_ADR         0x100005A8

#define HAL_PERIPH_T5MOD_REGISTER    (HAL_PERIPHREG_MAP->T5CNTRL)
#define HAL_PERIPH_T5MOD_LSB         0
#define HAL_PERIPH_T5MOD_MSB         1
#define HAL_PERIPH_T5MOD_MASK        0x00000003
#define HAL_PERIPH_T5MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T5MOD             HAL_PERIPH_T5MOD_MASK
#define HAL_PERIPH_T5MOD_READABLE    1
#define HAL_PERIPH_T5MOD_WRITABLE    1
#define HAL_PERIPH_T5MOD_SIGNED      0
#define HAL_PERIPH_T5MOD_ADR         0x100005A8

// Register T5CLK
#define HAL_PERIPH_T5CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T5CLK)
#define HAL_PERIPH_T5CKDIV_LSB         0
#define HAL_PERIPH_T5CKDIV_MSB         2
#define HAL_PERIPH_T5CKDIV_MASK        0x00000007
#define HAL_PERIPH_T5CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T5CKDIV             HAL_PERIPH_T5CKDIV_MASK
#define HAL_PERIPH_T5CKDIV_READABLE    1
#define HAL_PERIPH_T5CKDIV_WRITABLE    1
#define HAL_PERIPH_T5CKDIV_SIGNED      0
#define HAL_PERIPH_T5CKDIV_ADR         0x100005A9

// Register T5CMCTRL
#define HAL_PERIPH_T5MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T5CMCTRL)
#define HAL_PERIPH_T5MSREDG_LSB         4
#define HAL_PERIPH_T5MSREDG_MSB         4
#define HAL_PERIPH_T5MSREDG_MASK        0x00000010
#define HAL_PERIPH_T5MSREDG_TYPE        Bool
#define HAL_PERIPH_T5MSREDG             HAL_PERIPH_T5MSREDG_MASK
#define HAL_PERIPH_T5MSREDG_READABLE    1
#define HAL_PERIPH_T5MSREDG_WRITABLE    1
#define HAL_PERIPH_T5MSREDG_SIGNED      0
#define HAL_PERIPH_T5MSREDG_ADR         0x100005AA

#define HAL_PERIPH_T5CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T5CMCTRL)
#define HAL_PERIPH_T5CMPOL_LSB         3
#define HAL_PERIPH_T5CMPOL_MSB         3
#define HAL_PERIPH_T5CMPOL_MASK        0x00000008
#define HAL_PERIPH_T5CMPOL_TYPE        Bool
#define HAL_PERIPH_T5CMPOL             HAL_PERIPH_T5CMPOL_MASK
#define HAL_PERIPH_T5CMPOL_READABLE    1
#define HAL_PERIPH_T5CMPOL_WRITABLE    1
#define HAL_PERIPH_T5CMPOL_SIGNED      0
#define HAL_PERIPH_T5CMPOL_ADR         0x100005AA

#define HAL_PERIPH_T5CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T5CMCTRL)
#define HAL_PERIPH_T5CMSEL_LSB         0
#define HAL_PERIPH_T5CMSEL_MSB         1
#define HAL_PERIPH_T5CMSEL_MASK        0x00000003
#define HAL_PERIPH_T5CMSEL_TYPE        halPERIPH_T5CMInput_t
#define HAL_PERIPH_T5CMSEL             HAL_PERIPH_T5CMSEL_MASK
#define HAL_PERIPH_T5CMSEL_READABLE    1
#define HAL_PERIPH_T5CMSEL_WRITABLE    1
#define HAL_PERIPH_T5CMSEL_SIGNED      0
#define HAL_PERIPH_T5CMSEL_ADR         0x100005AA

// Register T5STATUS
#define HAL_PERIPH_T5OVFL_REGISTER    (HAL_PERIPHREG_MAP->T5STATUS)
#define HAL_PERIPH_T5OVFL_LSB         2
#define HAL_PERIPH_T5OVFL_MSB         2
#define HAL_PERIPH_T5OVFL_MASK        0x00000004
#define HAL_PERIPH_T5OVFL_TYPE        Bool
#define HAL_PERIPH_T5OVFL             HAL_PERIPH_T5OVFL_MASK
#define HAL_PERIPH_T5OVFL_READABLE    1
#define HAL_PERIPH_T5OVFL_WRITABLE    0
#define HAL_PERIPH_T5OVFL_SIGNED      0
#define HAL_PERIPH_T5OVFL_ADR         0x100005AB

#define HAL_PERIPH_T5BUSY_REGISTER    (HAL_PERIPHREG_MAP->T5STATUS)
#define HAL_PERIPH_T5BUSY_LSB         1
#define HAL_PERIPH_T5BUSY_MSB         1
#define HAL_PERIPH_T5BUSY_MASK        0x00000002
#define HAL_PERIPH_T5BUSY_TYPE        Bool
#define HAL_PERIPH_T5BUSY             HAL_PERIPH_T5BUSY_MASK
#define HAL_PERIPH_T5BUSY_READABLE    1
#define HAL_PERIPH_T5BUSY_WRITABLE    0
#define HAL_PERIPH_T5BUSY_SIGNED      0
#define HAL_PERIPH_T5BUSY_ADR         0x100005AB

#define HAL_PERIPH_T5INTF_REGISTER    (HAL_PERIPHREG_MAP->T5STATUS)
#define HAL_PERIPH_T5INTF_LSB         0
#define HAL_PERIPH_T5INTF_MSB         0
#define HAL_PERIPH_T5INTF_MASK        0x00000001
#define HAL_PERIPH_T5INTF_TYPE        Bool
#define HAL_PERIPH_T5INTF             HAL_PERIPH_T5INTF_MASK
#define HAL_PERIPH_T5INTF_READABLE    1
#define HAL_PERIPH_T5INTF_WRITABLE    1
#define HAL_PERIPH_T5INTF_SIGNED      0
#define HAL_PERIPH_T5INTF_ADR         0x100005AB

// Registers T5CMPL/T5CMPH
#define HAL_PERIPH_T5CMP_REGISTER    (HAL_PERIPHREG_MAP->T5CMPL)
#define HAL_PERIPH_T5CMP_LSB         0
#define HAL_PERIPH_T5CMP_MSB         15
#define HAL_PERIPH_T5CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T5CMP_TYPE        UInt16
#define HAL_PERIPH_T5CMP             HAL_PERIPH_T5CMP_MASK
#define HAL_PERIPH_T5CMP_READABLE    1
#define HAL_PERIPH_T5CMP_WRITABLE    1
#define HAL_PERIPH_T5CMP_SIGNED      0
#define HAL_PERIPH_T5CMP_ADR         0x100005AC

// Registers T5VALL/T5VALH
#define HAL_PERIPH_T5VAL_REGISTER    (HAL_PERIPHREG_MAP->T5VALL)
#define HAL_PERIPH_T5VAL_LSB         0
#define HAL_PERIPH_T5VAL_MSB         15
#define HAL_PERIPH_T5VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T5VAL_TYPE        UInt16
#define HAL_PERIPH_T5VAL             HAL_PERIPH_T5VAL_MASK
#define HAL_PERIPH_T5VAL_READABLE    1
#define HAL_PERIPH_T5VAL_WRITABLE    0
#define HAL_PERIPH_T5VAL_SIGNED      0
#define HAL_PERIPH_T5VAL_ADR         0x100005AE

// Register T6CNTRL
#define HAL_PERIPH_T6STRT_REGISTER    (HAL_PERIPHREG_MAP->T6CNTRL)
#define HAL_PERIPH_T6STRT_LSB         7
#define HAL_PERIPH_T6STRT_MSB         7
#define HAL_PERIPH_T6STRT_MASK        0x00000080
#define HAL_PERIPH_T6STRT_TYPE        Bool
#define HAL_PERIPH_T6STRT             HAL_PERIPH_T6STRT_MASK
#define HAL_PERIPH_T6STRT_READABLE    1
#define HAL_PERIPH_T6STRT_WRITABLE    1
#define HAL_PERIPH_T6STRT_SIGNED      0
#define HAL_PERIPH_T6STRT_ADR         0x100005B0

#define HAL_PERIPH_T6BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T6CNTRL)
#define HAL_PERIPH_T6BRKEN_LSB         5
#define HAL_PERIPH_T6BRKEN_MSB         5
#define HAL_PERIPH_T6BRKEN_MASK        0x00000020
#define HAL_PERIPH_T6BRKEN_TYPE        Bool
#define HAL_PERIPH_T6BRKEN             HAL_PERIPH_T6BRKEN_MASK
#define HAL_PERIPH_T6BRKEN_READABLE    1
#define HAL_PERIPH_T6BRKEN_WRITABLE    1
#define HAL_PERIPH_T6BRKEN_SIGNED      0
#define HAL_PERIPH_T6BRKEN_ADR         0x100005B0

#define HAL_PERIPH_T6ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T6CNTRL)
#define HAL_PERIPH_T6ASTOP_LSB         4
#define HAL_PERIPH_T6ASTOP_MSB         4
#define HAL_PERIPH_T6ASTOP_MASK        0x00000010
#define HAL_PERIPH_T6ASTOP_TYPE        Bool
#define HAL_PERIPH_T6ASTOP             HAL_PERIPH_T6ASTOP_MASK
#define HAL_PERIPH_T6ASTOP_READABLE    1
#define HAL_PERIPH_T6ASTOP_WRITABLE    1
#define HAL_PERIPH_T6ASTOP_SIGNED      0
#define HAL_PERIPH_T6ASTOP_ADR         0x100005B0

#define HAL_PERIPH_T6INTEN_REGISTER    (HAL_PERIPHREG_MAP->T6CNTRL)
#define HAL_PERIPH_T6INTEN_LSB         2
#define HAL_PERIPH_T6INTEN_MSB         3
#define HAL_PERIPH_T6INTEN_MASK        0x0000000C
#define HAL_PERIPH_T6INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T6INTEN             HAL_PERIPH_T6INTEN_MASK
#define HAL_PERIPH_T6INTEN_READABLE    1
#define HAL_PERIPH_T6INTEN_WRITABLE    1
#define HAL_PERIPH_T6INTEN_SIGNED      0
#define HAL_PERIPH_T6INTEN_ADR         0x100005B0

#define HAL_PERIPH_T6MOD_REGISTER    (HAL_PERIPHREG_MAP->T6CNTRL)
#define HAL_PERIPH_T6MOD_LSB         0
#define HAL_PERIPH_T6MOD_MSB         1
#define HAL_PERIPH_T6MOD_MASK        0x00000003
#define HAL_PERIPH_T6MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T6MOD             HAL_PERIPH_T6MOD_MASK
#define HAL_PERIPH_T6MOD_READABLE    1
#define HAL_PERIPH_T6MOD_WRITABLE    1
#define HAL_PERIPH_T6MOD_SIGNED      0
#define HAL_PERIPH_T6MOD_ADR         0x100005B0

// Register T6CLK
#define HAL_PERIPH_T6CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T6CLK)
#define HAL_PERIPH_T6CKDIV_LSB         0
#define HAL_PERIPH_T6CKDIV_MSB         2
#define HAL_PERIPH_T6CKDIV_MASK        0x00000007
#define HAL_PERIPH_T6CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T6CKDIV             HAL_PERIPH_T6CKDIV_MASK
#define HAL_PERIPH_T6CKDIV_READABLE    1
#define HAL_PERIPH_T6CKDIV_WRITABLE    1
#define HAL_PERIPH_T6CKDIV_SIGNED      0
#define HAL_PERIPH_T6CKDIV_ADR         0x100005B1

// Register T6CMCTRL
#define HAL_PERIPH_T6MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T6CMCTRL)
#define HAL_PERIPH_T6MSREDG_LSB         4
#define HAL_PERIPH_T6MSREDG_MSB         4
#define HAL_PERIPH_T6MSREDG_MASK        0x00000010
#define HAL_PERIPH_T6MSREDG_TYPE        Bool
#define HAL_PERIPH_T6MSREDG             HAL_PERIPH_T6MSREDG_MASK
#define HAL_PERIPH_T6MSREDG_READABLE    1
#define HAL_PERIPH_T6MSREDG_WRITABLE    1
#define HAL_PERIPH_T6MSREDG_SIGNED      0
#define HAL_PERIPH_T6MSREDG_ADR         0x100005B2

#define HAL_PERIPH_T6CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T6CMCTRL)
#define HAL_PERIPH_T6CMPOL_LSB         3
#define HAL_PERIPH_T6CMPOL_MSB         3
#define HAL_PERIPH_T6CMPOL_MASK        0x00000008
#define HAL_PERIPH_T6CMPOL_TYPE        Bool
#define HAL_PERIPH_T6CMPOL             HAL_PERIPH_T6CMPOL_MASK
#define HAL_PERIPH_T6CMPOL_READABLE    1
#define HAL_PERIPH_T6CMPOL_WRITABLE    1
#define HAL_PERIPH_T6CMPOL_SIGNED      0
#define HAL_PERIPH_T6CMPOL_ADR         0x100005B2

#define HAL_PERIPH_T6CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T6CMCTRL)
#define HAL_PERIPH_T6CMSEL_LSB         0
#define HAL_PERIPH_T6CMSEL_MSB         1
#define HAL_PERIPH_T6CMSEL_MASK        0x00000003
#define HAL_PERIPH_T6CMSEL_TYPE        UByte
#define HAL_PERIPH_T6CMSEL             HAL_PERIPH_T6CMSEL_MASK
#define HAL_PERIPH_T6CMSEL_READABLE    1
#define HAL_PERIPH_T6CMSEL_WRITABLE    1
#define HAL_PERIPH_T6CMSEL_SIGNED      0
#define HAL_PERIPH_T6CMSEL_ADR         0x100005B2

// Register T6STATUS
#define HAL_PERIPH_T6OVFL_REGISTER    (HAL_PERIPHREG_MAP->T6STATUS)
#define HAL_PERIPH_T6OVFL_LSB         2
#define HAL_PERIPH_T6OVFL_MSB         2
#define HAL_PERIPH_T6OVFL_MASK        0x00000004
#define HAL_PERIPH_T6OVFL_TYPE        Bool
#define HAL_PERIPH_T6OVFL             HAL_PERIPH_T6OVFL_MASK
#define HAL_PERIPH_T6OVFL_READABLE    1
#define HAL_PERIPH_T6OVFL_WRITABLE    0
#define HAL_PERIPH_T6OVFL_SIGNED      0
#define HAL_PERIPH_T6OVFL_ADR         0x100005B3

#define HAL_PERIPH_T6BUSY_REGISTER    (HAL_PERIPHREG_MAP->T6STATUS)
#define HAL_PERIPH_T6BUSY_LSB         1
#define HAL_PERIPH_T6BUSY_MSB         1
#define HAL_PERIPH_T6BUSY_MASK        0x00000002
#define HAL_PERIPH_T6BUSY_TYPE        Bool
#define HAL_PERIPH_T6BUSY             HAL_PERIPH_T6BUSY_MASK
#define HAL_PERIPH_T6BUSY_READABLE    1
#define HAL_PERIPH_T6BUSY_WRITABLE    0
#define HAL_PERIPH_T6BUSY_SIGNED      0
#define HAL_PERIPH_T6BUSY_ADR         0x100005B3

#define HAL_PERIPH_T6INTF_REGISTER    (HAL_PERIPHREG_MAP->T6STATUS)
#define HAL_PERIPH_T6INTF_LSB         0
#define HAL_PERIPH_T6INTF_MSB         0
#define HAL_PERIPH_T6INTF_MASK        0x00000001
#define HAL_PERIPH_T6INTF_TYPE        Bool
#define HAL_PERIPH_T6INTF             HAL_PERIPH_T6INTF_MASK
#define HAL_PERIPH_T6INTF_READABLE    1
#define HAL_PERIPH_T6INTF_WRITABLE    1
#define HAL_PERIPH_T6INTF_SIGNED      0
#define HAL_PERIPH_T6INTF_ADR         0x100005B3

// Registers T6CMPL/T6CMPH
#define HAL_PERIPH_T6CMP_REGISTER    (HAL_PERIPHREG_MAP->T6CMPL)
#define HAL_PERIPH_T6CMP_LSB         0
#define HAL_PERIPH_T6CMP_MSB         15
#define HAL_PERIPH_T6CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T6CMP_TYPE        UInt16
#define HAL_PERIPH_T6CMP             HAL_PERIPH_T6CMP_MASK
#define HAL_PERIPH_T6CMP_READABLE    1
#define HAL_PERIPH_T6CMP_WRITABLE    1
#define HAL_PERIPH_T6CMP_SIGNED      0
#define HAL_PERIPH_T6CMP_ADR         0x100005B4

// Registers T6VALL/T6VALH
#define HAL_PERIPH_T6VAL_REGISTER    (HAL_PERIPHREG_MAP->T6VALL)
#define HAL_PERIPH_T6VAL_LSB         0
#define HAL_PERIPH_T6VAL_MSB         15
#define HAL_PERIPH_T6VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T6VAL_TYPE        UInt16
#define HAL_PERIPH_T6VAL             HAL_PERIPH_T6VAL_MASK
#define HAL_PERIPH_T6VAL_READABLE    1
#define HAL_PERIPH_T6VAL_WRITABLE    0
#define HAL_PERIPH_T6VAL_SIGNED      0
#define HAL_PERIPH_T6VAL_ADR         0x100005B6

// Register T7CNTRL
#define HAL_PERIPH_T7STRT_REGISTER    (HAL_PERIPHREG_MAP->T7CNTRL)
#define HAL_PERIPH_T7STRT_LSB         7
#define HAL_PERIPH_T7STRT_MSB         7
#define HAL_PERIPH_T7STRT_MASK        0x00000080
#define HAL_PERIPH_T7STRT_TYPE        Bool
#define HAL_PERIPH_T7STRT             HAL_PERIPH_T7STRT_MASK
#define HAL_PERIPH_T7STRT_READABLE    1
#define HAL_PERIPH_T7STRT_WRITABLE    1
#define HAL_PERIPH_T7STRT_SIGNED      0
#define HAL_PERIPH_T7STRT_ADR         0x100005B8

#define HAL_PERIPH_T7BRKEN_REGISTER    (HAL_PERIPHREG_MAP->T7CNTRL)
#define HAL_PERIPH_T7BRKEN_LSB         5
#define HAL_PERIPH_T7BRKEN_MSB         5
#define HAL_PERIPH_T7BRKEN_MASK        0x00000020
#define HAL_PERIPH_T7BRKEN_TYPE        Bool
#define HAL_PERIPH_T7BRKEN             HAL_PERIPH_T7BRKEN_MASK
#define HAL_PERIPH_T7BRKEN_READABLE    1
#define HAL_PERIPH_T7BRKEN_WRITABLE    1
#define HAL_PERIPH_T7BRKEN_SIGNED      0
#define HAL_PERIPH_T7BRKEN_ADR         0x100005B8

#define HAL_PERIPH_T7ASTOP_REGISTER    (HAL_PERIPHREG_MAP->T7CNTRL)
#define HAL_PERIPH_T7ASTOP_LSB         4
#define HAL_PERIPH_T7ASTOP_MSB         4
#define HAL_PERIPH_T7ASTOP_MASK        0x00000010
#define HAL_PERIPH_T7ASTOP_TYPE        Bool
#define HAL_PERIPH_T7ASTOP             HAL_PERIPH_T7ASTOP_MASK
#define HAL_PERIPH_T7ASTOP_READABLE    1
#define HAL_PERIPH_T7ASTOP_WRITABLE    1
#define HAL_PERIPH_T7ASTOP_SIGNED      0
#define HAL_PERIPH_T7ASTOP_ADR         0x100005B8

#define HAL_PERIPH_T7INTEN_REGISTER    (HAL_PERIPHREG_MAP->T7CNTRL)
#define HAL_PERIPH_T7INTEN_LSB         2
#define HAL_PERIPH_T7INTEN_MSB         3
#define HAL_PERIPH_T7INTEN_MASK        0x0000000C
#define HAL_PERIPH_T7INTEN_TYPE        halPERIPH_EnTInt_t
#define HAL_PERIPH_T7INTEN             HAL_PERIPH_T7INTEN_MASK
#define HAL_PERIPH_T7INTEN_READABLE    1
#define HAL_PERIPH_T7INTEN_WRITABLE    1
#define HAL_PERIPH_T7INTEN_SIGNED      0
#define HAL_PERIPH_T7INTEN_ADR         0x100005B8

#define HAL_PERIPH_T7MOD_REGISTER    (HAL_PERIPHREG_MAP->T7CNTRL)
#define HAL_PERIPH_T7MOD_LSB         0
#define HAL_PERIPH_T7MOD_MSB         1
#define HAL_PERIPH_T7MOD_MASK        0x00000003
#define HAL_PERIPH_T7MOD_TYPE        halPERIPH_TMode_t
#define HAL_PERIPH_T7MOD             HAL_PERIPH_T7MOD_MASK
#define HAL_PERIPH_T7MOD_READABLE    1
#define HAL_PERIPH_T7MOD_WRITABLE    1
#define HAL_PERIPH_T7MOD_SIGNED      0
#define HAL_PERIPH_T7MOD_ADR         0x100005B8

// Register T7CLK
#define HAL_PERIPH_T7CKDIV_REGISTER    (HAL_PERIPHREG_MAP->T7CLK)
#define HAL_PERIPH_T7CKDIV_LSB         0
#define HAL_PERIPH_T7CKDIV_MSB         2
#define HAL_PERIPH_T7CKDIV_MASK        0x00000007
#define HAL_PERIPH_T7CKDIV_TYPE        halPERIPH_TClkDiv_t
#define HAL_PERIPH_T7CKDIV             HAL_PERIPH_T7CKDIV_MASK
#define HAL_PERIPH_T7CKDIV_READABLE    1
#define HAL_PERIPH_T7CKDIV_WRITABLE    1
#define HAL_PERIPH_T7CKDIV_SIGNED      0
#define HAL_PERIPH_T7CKDIV_ADR         0x100005B9

// Register T7CMCTRL
#define HAL_PERIPH_T7MSREDG_REGISTER    (HAL_PERIPHREG_MAP->T7CMCTRL)
#define HAL_PERIPH_T7MSREDG_LSB         4
#define HAL_PERIPH_T7MSREDG_MSB         4
#define HAL_PERIPH_T7MSREDG_MASK        0x00000010
#define HAL_PERIPH_T7MSREDG_TYPE        Bool
#define HAL_PERIPH_T7MSREDG             HAL_PERIPH_T7MSREDG_MASK
#define HAL_PERIPH_T7MSREDG_READABLE    1
#define HAL_PERIPH_T7MSREDG_WRITABLE    1
#define HAL_PERIPH_T7MSREDG_SIGNED      0
#define HAL_PERIPH_T7MSREDG_ADR         0x100005BA

#define HAL_PERIPH_T7CMPOL_REGISTER    (HAL_PERIPHREG_MAP->T7CMCTRL)
#define HAL_PERIPH_T7CMPOL_LSB         3
#define HAL_PERIPH_T7CMPOL_MSB         3
#define HAL_PERIPH_T7CMPOL_MASK        0x00000008
#define HAL_PERIPH_T7CMPOL_TYPE        Bool
#define HAL_PERIPH_T7CMPOL             HAL_PERIPH_T7CMPOL_MASK
#define HAL_PERIPH_T7CMPOL_READABLE    1
#define HAL_PERIPH_T7CMPOL_WRITABLE    1
#define HAL_PERIPH_T7CMPOL_SIGNED      0
#define HAL_PERIPH_T7CMPOL_ADR         0x100005BA

#define HAL_PERIPH_T7CMSEL_REGISTER    (HAL_PERIPHREG_MAP->T7CMCTRL)
#define HAL_PERIPH_T7CMSEL_LSB         0
#define HAL_PERIPH_T7CMSEL_MSB         1
#define HAL_PERIPH_T7CMSEL_MASK        0x00000003
#define HAL_PERIPH_T7CMSEL_TYPE        UByte
#define HAL_PERIPH_T7CMSEL             HAL_PERIPH_T7CMSEL_MASK
#define HAL_PERIPH_T7CMSEL_READABLE    1
#define HAL_PERIPH_T7CMSEL_WRITABLE    1
#define HAL_PERIPH_T7CMSEL_SIGNED      0
#define HAL_PERIPH_T7CMSEL_ADR         0x100005BA

// Register T7STATUS
#define HAL_PERIPH_T7OVFL_REGISTER    (HAL_PERIPHREG_MAP->T7STATUS)
#define HAL_PERIPH_T7OVFL_LSB         2
#define HAL_PERIPH_T7OVFL_MSB         2
#define HAL_PERIPH_T7OVFL_MASK        0x00000004
#define HAL_PERIPH_T7OVFL_TYPE        Bool
#define HAL_PERIPH_T7OVFL             HAL_PERIPH_T7OVFL_MASK
#define HAL_PERIPH_T7OVFL_READABLE    1
#define HAL_PERIPH_T7OVFL_WRITABLE    0
#define HAL_PERIPH_T7OVFL_SIGNED      0
#define HAL_PERIPH_T7OVFL_ADR         0x100005BB

#define HAL_PERIPH_T7BUSY_REGISTER    (HAL_PERIPHREG_MAP->T7STATUS)
#define HAL_PERIPH_T7BUSY_LSB         1
#define HAL_PERIPH_T7BUSY_MSB         1
#define HAL_PERIPH_T7BUSY_MASK        0x00000002
#define HAL_PERIPH_T7BUSY_TYPE        Bool
#define HAL_PERIPH_T7BUSY             HAL_PERIPH_T7BUSY_MASK
#define HAL_PERIPH_T7BUSY_READABLE    1
#define HAL_PERIPH_T7BUSY_WRITABLE    0
#define HAL_PERIPH_T7BUSY_SIGNED      0
#define HAL_PERIPH_T7BUSY_ADR         0x100005BB

#define HAL_PERIPH_T7INTF_REGISTER    (HAL_PERIPHREG_MAP->T7STATUS)
#define HAL_PERIPH_T7INTF_LSB         0
#define HAL_PERIPH_T7INTF_MSB         0
#define HAL_PERIPH_T7INTF_MASK        0x00000001
#define HAL_PERIPH_T7INTF_TYPE        Bool
#define HAL_PERIPH_T7INTF             HAL_PERIPH_T7INTF_MASK
#define HAL_PERIPH_T7INTF_READABLE    1
#define HAL_PERIPH_T7INTF_WRITABLE    1
#define HAL_PERIPH_T7INTF_SIGNED      0
#define HAL_PERIPH_T7INTF_ADR         0x100005BB

// Registers T7CMPL/T7CMPH
#define HAL_PERIPH_T7CMP_REGISTER    (HAL_PERIPHREG_MAP->T7CMPL)
#define HAL_PERIPH_T7CMP_LSB         0
#define HAL_PERIPH_T7CMP_MSB         15
#define HAL_PERIPH_T7CMP_MASK        0x0000FFFF
#define HAL_PERIPH_T7CMP_TYPE        UInt16
#define HAL_PERIPH_T7CMP             HAL_PERIPH_T7CMP_MASK
#define HAL_PERIPH_T7CMP_READABLE    1
#define HAL_PERIPH_T7CMP_WRITABLE    1
#define HAL_PERIPH_T7CMP_SIGNED      0
#define HAL_PERIPH_T7CMP_ADR         0x100005BC

// Registers T7VALL/T7VALH
#define HAL_PERIPH_T7VAL_REGISTER    (HAL_PERIPHREG_MAP->T7VALL)
#define HAL_PERIPH_T7VAL_LSB         0
#define HAL_PERIPH_T7VAL_MSB         15
#define HAL_PERIPH_T7VAL_MASK        0x0000FFFF
#define HAL_PERIPH_T7VAL_TYPE        UInt16
#define HAL_PERIPH_T7VAL             HAL_PERIPH_T7VAL_MASK
#define HAL_PERIPH_T7VAL_READABLE    1
#define HAL_PERIPH_T7VAL_WRITABLE    0
#define HAL_PERIPH_T7VAL_SIGNED      0
#define HAL_PERIPH_T7VAL_ADR         0x100005BE

// Register PADATA
#define HAL_PERIPH_PA7DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA7DATA_LSB         7
#define HAL_PERIPH_PA7DATA_MSB         7
#define HAL_PERIPH_PA7DATA_MASK        0x00000080
#define HAL_PERIPH_PA7DATA_TYPE        Bool
#define HAL_PERIPH_PA7DATA             HAL_PERIPH_PA7DATA_MASK
#define HAL_PERIPH_PA7DATA_READABLE    1
#define HAL_PERIPH_PA7DATA_WRITABLE    1
#define HAL_PERIPH_PA7DATA_SIGNED      0
#define HAL_PERIPH_PA7DATA_ADR         0x100005C0

#define HAL_PERIPH_PA6DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA6DATA_LSB         6
#define HAL_PERIPH_PA6DATA_MSB         6
#define HAL_PERIPH_PA6DATA_MASK        0x00000040
#define HAL_PERIPH_PA6DATA_TYPE        Bool
#define HAL_PERIPH_PA6DATA             HAL_PERIPH_PA6DATA_MASK
#define HAL_PERIPH_PA6DATA_READABLE    1
#define HAL_PERIPH_PA6DATA_WRITABLE    1
#define HAL_PERIPH_PA6DATA_SIGNED      0
#define HAL_PERIPH_PA6DATA_ADR         0x100005C0

#define HAL_PERIPH_PA5DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA5DATA_LSB         5
#define HAL_PERIPH_PA5DATA_MSB         5
#define HAL_PERIPH_PA5DATA_MASK        0x00000020
#define HAL_PERIPH_PA5DATA_TYPE        Bool
#define HAL_PERIPH_PA5DATA             HAL_PERIPH_PA5DATA_MASK
#define HAL_PERIPH_PA5DATA_READABLE    1
#define HAL_PERIPH_PA5DATA_WRITABLE    1
#define HAL_PERIPH_PA5DATA_SIGNED      0
#define HAL_PERIPH_PA5DATA_ADR         0x100005C0

#define HAL_PERIPH_PA4DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA4DATA_LSB         4
#define HAL_PERIPH_PA4DATA_MSB         4
#define HAL_PERIPH_PA4DATA_MASK        0x00000010
#define HAL_PERIPH_PA4DATA_TYPE        Bool
#define HAL_PERIPH_PA4DATA             HAL_PERIPH_PA4DATA_MASK
#define HAL_PERIPH_PA4DATA_READABLE    1
#define HAL_PERIPH_PA4DATA_WRITABLE    1
#define HAL_PERIPH_PA4DATA_SIGNED      0
#define HAL_PERIPH_PA4DATA_ADR         0x100005C0

#define HAL_PERIPH_PA3DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA3DATA_LSB         3
#define HAL_PERIPH_PA3DATA_MSB         3
#define HAL_PERIPH_PA3DATA_MASK        0x00000008
#define HAL_PERIPH_PA3DATA_TYPE        Bool
#define HAL_PERIPH_PA3DATA             HAL_PERIPH_PA3DATA_MASK
#define HAL_PERIPH_PA3DATA_READABLE    1
#define HAL_PERIPH_PA3DATA_WRITABLE    1
#define HAL_PERIPH_PA3DATA_SIGNED      0
#define HAL_PERIPH_PA3DATA_ADR         0x100005C0

#define HAL_PERIPH_PA2DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA2DATA_LSB         2
#define HAL_PERIPH_PA2DATA_MSB         2
#define HAL_PERIPH_PA2DATA_MASK        0x00000004
#define HAL_PERIPH_PA2DATA_TYPE        Bool
#define HAL_PERIPH_PA2DATA             HAL_PERIPH_PA2DATA_MASK
#define HAL_PERIPH_PA2DATA_READABLE    1
#define HAL_PERIPH_PA2DATA_WRITABLE    1
#define HAL_PERIPH_PA2DATA_SIGNED      0
#define HAL_PERIPH_PA2DATA_ADR         0x100005C0

#define HAL_PERIPH_PA1DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA1DATA_LSB         1
#define HAL_PERIPH_PA1DATA_MSB         1
#define HAL_PERIPH_PA1DATA_MASK        0x00000002
#define HAL_PERIPH_PA1DATA_TYPE        Bool
#define HAL_PERIPH_PA1DATA             HAL_PERIPH_PA1DATA_MASK
#define HAL_PERIPH_PA1DATA_READABLE    1
#define HAL_PERIPH_PA1DATA_WRITABLE    1
#define HAL_PERIPH_PA1DATA_SIGNED      0
#define HAL_PERIPH_PA1DATA_ADR         0x100005C0

#define HAL_PERIPH_PA0DATA_REGISTER    (HAL_PERIPHREG_MAP->PADATA)
#define HAL_PERIPH_PA0DATA_LSB         0
#define HAL_PERIPH_PA0DATA_MSB         0
#define HAL_PERIPH_PA0DATA_MASK        0x00000001
#define HAL_PERIPH_PA0DATA_TYPE        Bool
#define HAL_PERIPH_PA0DATA             HAL_PERIPH_PA0DATA_MASK
#define HAL_PERIPH_PA0DATA_READABLE    1
#define HAL_PERIPH_PA0DATA_WRITABLE    1
#define HAL_PERIPH_PA0DATA_SIGNED      0
#define HAL_PERIPH_PA0DATA_ADR         0x100005C0

// Register PACTRL
#define HAL_PERIPH_PA7DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA7DIR_LSB         7
#define HAL_PERIPH_PA7DIR_MSB         7
#define HAL_PERIPH_PA7DIR_MASK        0x00000080
#define HAL_PERIPH_PA7DIR_TYPE        Bool
#define HAL_PERIPH_PA7DIR             HAL_PERIPH_PA7DIR_MASK
#define HAL_PERIPH_PA7DIR_READABLE    1
#define HAL_PERIPH_PA7DIR_WRITABLE    1
#define HAL_PERIPH_PA7DIR_SIGNED      0
#define HAL_PERIPH_PA7DIR_ADR         0x100005C1

#define HAL_PERIPH_PA6DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA6DIR_LSB         6
#define HAL_PERIPH_PA6DIR_MSB         6
#define HAL_PERIPH_PA6DIR_MASK        0x00000040
#define HAL_PERIPH_PA6DIR_TYPE        Bool
#define HAL_PERIPH_PA6DIR             HAL_PERIPH_PA6DIR_MASK
#define HAL_PERIPH_PA6DIR_READABLE    1
#define HAL_PERIPH_PA6DIR_WRITABLE    1
#define HAL_PERIPH_PA6DIR_SIGNED      0
#define HAL_PERIPH_PA6DIR_ADR         0x100005C1

#define HAL_PERIPH_PA5DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA5DIR_LSB         5
#define HAL_PERIPH_PA5DIR_MSB         5
#define HAL_PERIPH_PA5DIR_MASK        0x00000020
#define HAL_PERIPH_PA5DIR_TYPE        Bool
#define HAL_PERIPH_PA5DIR             HAL_PERIPH_PA5DIR_MASK
#define HAL_PERIPH_PA5DIR_READABLE    1
#define HAL_PERIPH_PA5DIR_WRITABLE    1
#define HAL_PERIPH_PA5DIR_SIGNED      0
#define HAL_PERIPH_PA5DIR_ADR         0x100005C1

#define HAL_PERIPH_PA4DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA4DIR_LSB         4
#define HAL_PERIPH_PA4DIR_MSB         4
#define HAL_PERIPH_PA4DIR_MASK        0x00000010
#define HAL_PERIPH_PA4DIR_TYPE        Bool
#define HAL_PERIPH_PA4DIR             HAL_PERIPH_PA4DIR_MASK
#define HAL_PERIPH_PA4DIR_READABLE    1
#define HAL_PERIPH_PA4DIR_WRITABLE    1
#define HAL_PERIPH_PA4DIR_SIGNED      0
#define HAL_PERIPH_PA4DIR_ADR         0x100005C1

#define HAL_PERIPH_PA3DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA3DIR_LSB         3
#define HAL_PERIPH_PA3DIR_MSB         3
#define HAL_PERIPH_PA3DIR_MASK        0x00000008
#define HAL_PERIPH_PA3DIR_TYPE        Bool
#define HAL_PERIPH_PA3DIR             HAL_PERIPH_PA3DIR_MASK
#define HAL_PERIPH_PA3DIR_READABLE    1
#define HAL_PERIPH_PA3DIR_WRITABLE    1
#define HAL_PERIPH_PA3DIR_SIGNED      0
#define HAL_PERIPH_PA3DIR_ADR         0x100005C1

#define HAL_PERIPH_PA2DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA2DIR_LSB         2
#define HAL_PERIPH_PA2DIR_MSB         2
#define HAL_PERIPH_PA2DIR_MASK        0x00000004
#define HAL_PERIPH_PA2DIR_TYPE        Bool
#define HAL_PERIPH_PA2DIR             HAL_PERIPH_PA2DIR_MASK
#define HAL_PERIPH_PA2DIR_READABLE    1
#define HAL_PERIPH_PA2DIR_WRITABLE    1
#define HAL_PERIPH_PA2DIR_SIGNED      0
#define HAL_PERIPH_PA2DIR_ADR         0x100005C1

#define HAL_PERIPH_PA1DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA1DIR_LSB         1
#define HAL_PERIPH_PA1DIR_MSB         1
#define HAL_PERIPH_PA1DIR_MASK        0x00000002
#define HAL_PERIPH_PA1DIR_TYPE        Bool
#define HAL_PERIPH_PA1DIR             HAL_PERIPH_PA1DIR_MASK
#define HAL_PERIPH_PA1DIR_READABLE    1
#define HAL_PERIPH_PA1DIR_WRITABLE    1
#define HAL_PERIPH_PA1DIR_SIGNED      0
#define HAL_PERIPH_PA1DIR_ADR         0x100005C1

#define HAL_PERIPH_PA0DIR_REGISTER    (HAL_PERIPHREG_MAP->PACTRL)
#define HAL_PERIPH_PA0DIR_LSB         0
#define HAL_PERIPH_PA0DIR_MSB         0
#define HAL_PERIPH_PA0DIR_MASK        0x00000001
#define HAL_PERIPH_PA0DIR_TYPE        Bool
#define HAL_PERIPH_PA0DIR             HAL_PERIPH_PA0DIR_MASK
#define HAL_PERIPH_PA0DIR_READABLE    1
#define HAL_PERIPH_PA0DIR_WRITABLE    1
#define HAL_PERIPH_PA0DIR_SIGNED      0
#define HAL_PERIPH_PA0DIR_ADR         0x100005C1

// Register PBDATA
#define HAL_PERIPH_PB7DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB7DATA_LSB         7
#define HAL_PERIPH_PB7DATA_MSB         7
#define HAL_PERIPH_PB7DATA_MASK        0x00000080
#define HAL_PERIPH_PB7DATA_TYPE        Bool
#define HAL_PERIPH_PB7DATA             HAL_PERIPH_PB7DATA_MASK
#define HAL_PERIPH_PB7DATA_READABLE    1
#define HAL_PERIPH_PB7DATA_WRITABLE    1
#define HAL_PERIPH_PB7DATA_SIGNED      0
#define HAL_PERIPH_PB7DATA_ADR         0x100005C2

#define HAL_PERIPH_PB6DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB6DATA_LSB         6
#define HAL_PERIPH_PB6DATA_MSB         6
#define HAL_PERIPH_PB6DATA_MASK        0x00000040
#define HAL_PERIPH_PB6DATA_TYPE        Bool
#define HAL_PERIPH_PB6DATA             HAL_PERIPH_PB6DATA_MASK
#define HAL_PERIPH_PB6DATA_READABLE    1
#define HAL_PERIPH_PB6DATA_WRITABLE    1
#define HAL_PERIPH_PB6DATA_SIGNED      0
#define HAL_PERIPH_PB6DATA_ADR         0x100005C2

#define HAL_PERIPH_PB5DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB5DATA_LSB         5
#define HAL_PERIPH_PB5DATA_MSB         5
#define HAL_PERIPH_PB5DATA_MASK        0x00000020
#define HAL_PERIPH_PB5DATA_TYPE        Bool
#define HAL_PERIPH_PB5DATA             HAL_PERIPH_PB5DATA_MASK
#define HAL_PERIPH_PB5DATA_READABLE    1
#define HAL_PERIPH_PB5DATA_WRITABLE    1
#define HAL_PERIPH_PB5DATA_SIGNED      0
#define HAL_PERIPH_PB5DATA_ADR         0x100005C2

#define HAL_PERIPH_PB4DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB4DATA_LSB         4
#define HAL_PERIPH_PB4DATA_MSB         4
#define HAL_PERIPH_PB4DATA_MASK        0x00000010
#define HAL_PERIPH_PB4DATA_TYPE        Bool
#define HAL_PERIPH_PB4DATA             HAL_PERIPH_PB4DATA_MASK
#define HAL_PERIPH_PB4DATA_READABLE    1
#define HAL_PERIPH_PB4DATA_WRITABLE    1
#define HAL_PERIPH_PB4DATA_SIGNED      0
#define HAL_PERIPH_PB4DATA_ADR         0x100005C2

#define HAL_PERIPH_PB3DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB3DATA_LSB         3
#define HAL_PERIPH_PB3DATA_MSB         3
#define HAL_PERIPH_PB3DATA_MASK        0x00000008
#define HAL_PERIPH_PB3DATA_TYPE        Bool
#define HAL_PERIPH_PB3DATA             HAL_PERIPH_PB3DATA_MASK
#define HAL_PERIPH_PB3DATA_READABLE    1
#define HAL_PERIPH_PB3DATA_WRITABLE    1
#define HAL_PERIPH_PB3DATA_SIGNED      0
#define HAL_PERIPH_PB3DATA_ADR         0x100005C2

#define HAL_PERIPH_PB2DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB2DATA_LSB         2
#define HAL_PERIPH_PB2DATA_MSB         2
#define HAL_PERIPH_PB2DATA_MASK        0x00000004
#define HAL_PERIPH_PB2DATA_TYPE        Bool
#define HAL_PERIPH_PB2DATA             HAL_PERIPH_PB2DATA_MASK
#define HAL_PERIPH_PB2DATA_READABLE    1
#define HAL_PERIPH_PB2DATA_WRITABLE    1
#define HAL_PERIPH_PB2DATA_SIGNED      0
#define HAL_PERIPH_PB2DATA_ADR         0x100005C2

#define HAL_PERIPH_PB1DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB1DATA_LSB         1
#define HAL_PERIPH_PB1DATA_MSB         1
#define HAL_PERIPH_PB1DATA_MASK        0x00000002
#define HAL_PERIPH_PB1DATA_TYPE        Bool
#define HAL_PERIPH_PB1DATA             HAL_PERIPH_PB1DATA_MASK
#define HAL_PERIPH_PB1DATA_READABLE    1
#define HAL_PERIPH_PB1DATA_WRITABLE    1
#define HAL_PERIPH_PB1DATA_SIGNED      0
#define HAL_PERIPH_PB1DATA_ADR         0x100005C2

#define HAL_PERIPH_PB0DATA_REGISTER    (HAL_PERIPHREG_MAP->PBDATA)
#define HAL_PERIPH_PB0DATA_LSB         0
#define HAL_PERIPH_PB0DATA_MSB         0
#define HAL_PERIPH_PB0DATA_MASK        0x00000001
#define HAL_PERIPH_PB0DATA_TYPE        Bool
#define HAL_PERIPH_PB0DATA             HAL_PERIPH_PB0DATA_MASK
#define HAL_PERIPH_PB0DATA_READABLE    1
#define HAL_PERIPH_PB0DATA_WRITABLE    1
#define HAL_PERIPH_PB0DATA_SIGNED      0
#define HAL_PERIPH_PB0DATA_ADR         0x100005C2

// Register PBCTRL
#define HAL_PERIPH_PB7DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB7DIR_LSB         7
#define HAL_PERIPH_PB7DIR_MSB         7
#define HAL_PERIPH_PB7DIR_MASK        0x00000080
#define HAL_PERIPH_PB7DIR_TYPE        Bool
#define HAL_PERIPH_PB7DIR             HAL_PERIPH_PB7DIR_MASK
#define HAL_PERIPH_PB7DIR_READABLE    1
#define HAL_PERIPH_PB7DIR_WRITABLE    1
#define HAL_PERIPH_PB7DIR_SIGNED      0
#define HAL_PERIPH_PB7DIR_ADR         0x100005C3

#define HAL_PERIPH_PB6DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB6DIR_LSB         6
#define HAL_PERIPH_PB6DIR_MSB         6
#define HAL_PERIPH_PB6DIR_MASK        0x00000040
#define HAL_PERIPH_PB6DIR_TYPE        Bool
#define HAL_PERIPH_PB6DIR             HAL_PERIPH_PB6DIR_MASK
#define HAL_PERIPH_PB6DIR_READABLE    1
#define HAL_PERIPH_PB6DIR_WRITABLE    1
#define HAL_PERIPH_PB6DIR_SIGNED      0
#define HAL_PERIPH_PB6DIR_ADR         0x100005C3

#define HAL_PERIPH_PB5DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB5DIR_LSB         5
#define HAL_PERIPH_PB5DIR_MSB         5
#define HAL_PERIPH_PB5DIR_MASK        0x00000020
#define HAL_PERIPH_PB5DIR_TYPE        Bool
#define HAL_PERIPH_PB5DIR             HAL_PERIPH_PB5DIR_MASK
#define HAL_PERIPH_PB5DIR_READABLE    1
#define HAL_PERIPH_PB5DIR_WRITABLE    1
#define HAL_PERIPH_PB5DIR_SIGNED      0
#define HAL_PERIPH_PB5DIR_ADR         0x100005C3

#define HAL_PERIPH_PB4DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB4DIR_LSB         4
#define HAL_PERIPH_PB4DIR_MSB         4
#define HAL_PERIPH_PB4DIR_MASK        0x00000010
#define HAL_PERIPH_PB4DIR_TYPE        Bool
#define HAL_PERIPH_PB4DIR             HAL_PERIPH_PB4DIR_MASK
#define HAL_PERIPH_PB4DIR_READABLE    1
#define HAL_PERIPH_PB4DIR_WRITABLE    1
#define HAL_PERIPH_PB4DIR_SIGNED      0
#define HAL_PERIPH_PB4DIR_ADR         0x100005C3

#define HAL_PERIPH_PB3DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB3DIR_LSB         3
#define HAL_PERIPH_PB3DIR_MSB         3
#define HAL_PERIPH_PB3DIR_MASK        0x00000008
#define HAL_PERIPH_PB3DIR_TYPE        Bool
#define HAL_PERIPH_PB3DIR             HAL_PERIPH_PB3DIR_MASK
#define HAL_PERIPH_PB3DIR_READABLE    1
#define HAL_PERIPH_PB3DIR_WRITABLE    1
#define HAL_PERIPH_PB3DIR_SIGNED      0
#define HAL_PERIPH_PB3DIR_ADR         0x100005C3

#define HAL_PERIPH_PB2DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB2DIR_LSB         2
#define HAL_PERIPH_PB2DIR_MSB         2
#define HAL_PERIPH_PB2DIR_MASK        0x00000004
#define HAL_PERIPH_PB2DIR_TYPE        Bool
#define HAL_PERIPH_PB2DIR             HAL_PERIPH_PB2DIR_MASK
#define HAL_PERIPH_PB2DIR_READABLE    1
#define HAL_PERIPH_PB2DIR_WRITABLE    1
#define HAL_PERIPH_PB2DIR_SIGNED      0
#define HAL_PERIPH_PB2DIR_ADR         0x100005C3

#define HAL_PERIPH_PB1DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB1DIR_LSB         1
#define HAL_PERIPH_PB1DIR_MSB         1
#define HAL_PERIPH_PB1DIR_MASK        0x00000002
#define HAL_PERIPH_PB1DIR_TYPE        Bool
#define HAL_PERIPH_PB1DIR             HAL_PERIPH_PB1DIR_MASK
#define HAL_PERIPH_PB1DIR_READABLE    1
#define HAL_PERIPH_PB1DIR_WRITABLE    1
#define HAL_PERIPH_PB1DIR_SIGNED      0
#define HAL_PERIPH_PB1DIR_ADR         0x100005C3

#define HAL_PERIPH_PB0DIR_REGISTER    (HAL_PERIPHREG_MAP->PBCTRL)
#define HAL_PERIPH_PB0DIR_LSB         0
#define HAL_PERIPH_PB0DIR_MSB         0
#define HAL_PERIPH_PB0DIR_MASK        0x00000001
#define HAL_PERIPH_PB0DIR_TYPE        Bool
#define HAL_PERIPH_PB0DIR             HAL_PERIPH_PB0DIR_MASK
#define HAL_PERIPH_PB0DIR_READABLE    1
#define HAL_PERIPH_PB0DIR_WRITABLE    1
#define HAL_PERIPH_PB0DIR_SIGNED      0
#define HAL_PERIPH_PB0DIR_ADR         0x100005C3

// Register PCDATA
#define HAL_PERIPH_PC3DATA_REGISTER    (HAL_PERIPHREG_MAP->PCDATA)
#define HAL_PERIPH_PC3DATA_LSB         3
#define HAL_PERIPH_PC3DATA_MSB         3
#define HAL_PERIPH_PC3DATA_MASK        0x00000008
#define HAL_PERIPH_PC3DATA_TYPE        Bool
#define HAL_PERIPH_PC3DATA             HAL_PERIPH_PC3DATA_MASK
#define HAL_PERIPH_PC3DATA_READABLE    1
#define HAL_PERIPH_PC3DATA_WRITABLE    1
#define HAL_PERIPH_PC3DATA_SIGNED      0
#define HAL_PERIPH_PC3DATA_ADR         0x100005C4

#define HAL_PERIPH_PC2DATA_REGISTER    (HAL_PERIPHREG_MAP->PCDATA)
#define HAL_PERIPH_PC2DATA_LSB         2
#define HAL_PERIPH_PC2DATA_MSB         2
#define HAL_PERIPH_PC2DATA_MASK        0x00000004
#define HAL_PERIPH_PC2DATA_TYPE        Bool
#define HAL_PERIPH_PC2DATA             HAL_PERIPH_PC2DATA_MASK
#define HAL_PERIPH_PC2DATA_READABLE    1
#define HAL_PERIPH_PC2DATA_WRITABLE    1
#define HAL_PERIPH_PC2DATA_SIGNED      0
#define HAL_PERIPH_PC2DATA_ADR         0x100005C4

#define HAL_PERIPH_PC1DATA_REGISTER    (HAL_PERIPHREG_MAP->PCDATA)
#define HAL_PERIPH_PC1DATA_LSB         1
#define HAL_PERIPH_PC1DATA_MSB         1
#define HAL_PERIPH_PC1DATA_MASK        0x00000002
#define HAL_PERIPH_PC1DATA_TYPE        Bool
#define HAL_PERIPH_PC1DATA             HAL_PERIPH_PC1DATA_MASK
#define HAL_PERIPH_PC1DATA_READABLE    1
#define HAL_PERIPH_PC1DATA_WRITABLE    1
#define HAL_PERIPH_PC1DATA_SIGNED      0
#define HAL_PERIPH_PC1DATA_ADR         0x100005C4

#define HAL_PERIPH_PC0DATA_REGISTER    (HAL_PERIPHREG_MAP->PCDATA)
#define HAL_PERIPH_PC0DATA_LSB         0
#define HAL_PERIPH_PC0DATA_MSB         0
#define HAL_PERIPH_PC0DATA_MASK        0x00000001
#define HAL_PERIPH_PC0DATA_TYPE        Bool
#define HAL_PERIPH_PC0DATA             HAL_PERIPH_PC0DATA_MASK
#define HAL_PERIPH_PC0DATA_READABLE    1
#define HAL_PERIPH_PC0DATA_WRITABLE    1
#define HAL_PERIPH_PC0DATA_SIGNED      0
#define HAL_PERIPH_PC0DATA_ADR         0x100005C4

// Register PCCTRL
#define HAL_PERIPH_PC3DIR_REGISTER    (HAL_PERIPHREG_MAP->PCCTRL)
#define HAL_PERIPH_PC3DIR_LSB         3
#define HAL_PERIPH_PC3DIR_MSB         3
#define HAL_PERIPH_PC3DIR_MASK        0x00000008
#define HAL_PERIPH_PC3DIR_TYPE        Bool
#define HAL_PERIPH_PC3DIR             HAL_PERIPH_PC3DIR_MASK
#define HAL_PERIPH_PC3DIR_READABLE    1
#define HAL_PERIPH_PC3DIR_WRITABLE    1
#define HAL_PERIPH_PC3DIR_SIGNED      0
#define HAL_PERIPH_PC3DIR_ADR         0x100005C5

#define HAL_PERIPH_PC2DIR_REGISTER    (HAL_PERIPHREG_MAP->PCCTRL)
#define HAL_PERIPH_PC2DIR_LSB         2
#define HAL_PERIPH_PC2DIR_MSB         2
#define HAL_PERIPH_PC2DIR_MASK        0x00000004
#define HAL_PERIPH_PC2DIR_TYPE        Bool
#define HAL_PERIPH_PC2DIR             HAL_PERIPH_PC2DIR_MASK
#define HAL_PERIPH_PC2DIR_READABLE    1
#define HAL_PERIPH_PC2DIR_WRITABLE    1
#define HAL_PERIPH_PC2DIR_SIGNED      0
#define HAL_PERIPH_PC2DIR_ADR         0x100005C5

#define HAL_PERIPH_PC1DIR_REGISTER    (HAL_PERIPHREG_MAP->PCCTRL)
#define HAL_PERIPH_PC1DIR_LSB         1
#define HAL_PERIPH_PC1DIR_MSB         1
#define HAL_PERIPH_PC1DIR_MASK        0x00000002
#define HAL_PERIPH_PC1DIR_TYPE        Bool
#define HAL_PERIPH_PC1DIR             HAL_PERIPH_PC1DIR_MASK
#define HAL_PERIPH_PC1DIR_READABLE    1
#define HAL_PERIPH_PC1DIR_WRITABLE    1
#define HAL_PERIPH_PC1DIR_SIGNED      0
#define HAL_PERIPH_PC1DIR_ADR         0x100005C5

#define HAL_PERIPH_PC0DIR_REGISTER    (HAL_PERIPHREG_MAP->PCCTRL)
#define HAL_PERIPH_PC0DIR_LSB         0
#define HAL_PERIPH_PC0DIR_MSB         0
#define HAL_PERIPH_PC0DIR_MASK        0x00000001
#define HAL_PERIPH_PC0DIR_TYPE        Bool
#define HAL_PERIPH_PC0DIR             HAL_PERIPH_PC0DIR_MASK
#define HAL_PERIPH_PC0DIR_READABLE    1
#define HAL_PERIPH_PC0DIR_WRITABLE    1
#define HAL_PERIPH_PC0DIR_SIGNED      0
#define HAL_PERIPH_PC0DIR_ADR         0x100005C5

// Registers ADC0L/ADC0H
#define HAL_PERIPH_ADC0_REGISTER    (HAL_PERIPHREG_MAP->ADC0L)
#define HAL_PERIPH_ADC0_LSB         0
#define HAL_PERIPH_ADC0_MSB         9
#define HAL_PERIPH_ADC0_MASK        0x000003FF
#define HAL_PERIPH_ADC0_TYPE        UInt16
#define HAL_PERIPH_ADC0             HAL_PERIPH_ADC0_MASK
#define HAL_PERIPH_ADC0_READABLE    1
#define HAL_PERIPH_ADC0_WRITABLE    0
#define HAL_PERIPH_ADC0_SIGNED      0
#define HAL_PERIPH_ADC0_ADR         0x100005D0

// Registers ADC1L/ADC1H
#define HAL_PERIPH_ADC1_REGISTER    (HAL_PERIPHREG_MAP->ADC1L)
#define HAL_PERIPH_ADC1_LSB         0
#define HAL_PERIPH_ADC1_MSB         9
#define HAL_PERIPH_ADC1_MASK        0x000003FF
#define HAL_PERIPH_ADC1_TYPE        UInt16
#define HAL_PERIPH_ADC1             HAL_PERIPH_ADC1_MASK
#define HAL_PERIPH_ADC1_READABLE    1
#define HAL_PERIPH_ADC1_WRITABLE    0
#define HAL_PERIPH_ADC1_SIGNED      0
#define HAL_PERIPH_ADC1_ADR         0x100005D2

// Registers ADC2L/ADC2H
#define HAL_PERIPH_ADC2_REGISTER    (HAL_PERIPHREG_MAP->ADC2L)
#define HAL_PERIPH_ADC2_LSB         0
#define HAL_PERIPH_ADC2_MSB         9
#define HAL_PERIPH_ADC2_MASK        0x000003FF
#define HAL_PERIPH_ADC2_TYPE        UInt16
#define HAL_PERIPH_ADC2             HAL_PERIPH_ADC2_MASK
#define HAL_PERIPH_ADC2_READABLE    1
#define HAL_PERIPH_ADC2_WRITABLE    0
#define HAL_PERIPH_ADC2_SIGNED      0
#define HAL_PERIPH_ADC2_ADR         0x100005D4

// Registers ADC3L/ADC3H
#define HAL_PERIPH_ADC3_REGISTER    (HAL_PERIPHREG_MAP->ADC3L)
#define HAL_PERIPH_ADC3_LSB         0
#define HAL_PERIPH_ADC3_MSB         9
#define HAL_PERIPH_ADC3_MASK        0x000003FF
#define HAL_PERIPH_ADC3_TYPE        UInt16
#define HAL_PERIPH_ADC3             HAL_PERIPH_ADC3_MASK
#define HAL_PERIPH_ADC3_READABLE    1
#define HAL_PERIPH_ADC3_WRITABLE    0
#define HAL_PERIPH_ADC3_SIGNED      0
#define HAL_PERIPH_ADC3_ADR         0x100005D6

// Registers ADC4L/ADC4H
#define HAL_PERIPH_ADC4_REGISTER    (HAL_PERIPHREG_MAP->ADC4L)
#define HAL_PERIPH_ADC4_LSB         0
#define HAL_PERIPH_ADC4_MSB         9
#define HAL_PERIPH_ADC4_MASK        0x000003FF
#define HAL_PERIPH_ADC4_TYPE        UInt16
#define HAL_PERIPH_ADC4             HAL_PERIPH_ADC4_MASK
#define HAL_PERIPH_ADC4_READABLE    1
#define HAL_PERIPH_ADC4_WRITABLE    0
#define HAL_PERIPH_ADC4_SIGNED      0
#define HAL_PERIPH_ADC4_ADR         0x100005D8

// Registers ADC5L/ADC5H
#define HAL_PERIPH_ADC5_REGISTER    (HAL_PERIPHREG_MAP->ADC5L)
#define HAL_PERIPH_ADC5_LSB         0
#define HAL_PERIPH_ADC5_MSB         9
#define HAL_PERIPH_ADC5_MASK        0x000003FF
#define HAL_PERIPH_ADC5_TYPE        UInt16
#define HAL_PERIPH_ADC5             HAL_PERIPH_ADC5_MASK
#define HAL_PERIPH_ADC5_READABLE    1
#define HAL_PERIPH_ADC5_WRITABLE    0
#define HAL_PERIPH_ADC5_SIGNED      0
#define HAL_PERIPH_ADC5_ADR         0x100005DA

// Registers ADC6L/ADC6H
#define HAL_PERIPH_ADC6_REGISTER    (HAL_PERIPHREG_MAP->ADC6L)
#define HAL_PERIPH_ADC6_LSB         0
#define HAL_PERIPH_ADC6_MSB         9
#define HAL_PERIPH_ADC6_MASK        0x000003FF
#define HAL_PERIPH_ADC6_TYPE        UInt16
#define HAL_PERIPH_ADC6             HAL_PERIPH_ADC6_MASK
#define HAL_PERIPH_ADC6_READABLE    1
#define HAL_PERIPH_ADC6_WRITABLE    0
#define HAL_PERIPH_ADC6_SIGNED      0
#define HAL_PERIPH_ADC6_ADR         0x100005DC

// Registers ADC7L/ADC7H
#define HAL_PERIPH_ADC7_REGISTER    (HAL_PERIPHREG_MAP->ADC7L)
#define HAL_PERIPH_ADC7_LSB         0
#define HAL_PERIPH_ADC7_MSB         9
#define HAL_PERIPH_ADC7_MASK        0x000003FF
#define HAL_PERIPH_ADC7_TYPE        UInt16
#define HAL_PERIPH_ADC7             HAL_PERIPH_ADC7_MASK
#define HAL_PERIPH_ADC7_READABLE    1
#define HAL_PERIPH_ADC7_WRITABLE    0
#define HAL_PERIPH_ADC7_SIGNED      0
#define HAL_PERIPH_ADC7_ADR         0x100005DE

// Registers ADC8L/ADC8H
#define HAL_PERIPH_ADC8_REGISTER    (HAL_PERIPHREG_MAP->ADC8L)
#define HAL_PERIPH_ADC8_LSB         0
#define HAL_PERIPH_ADC8_MSB         9
#define HAL_PERIPH_ADC8_MASK        0x000003FF
#define HAL_PERIPH_ADC8_TYPE        UInt16
#define HAL_PERIPH_ADC8             HAL_PERIPH_ADC8_MASK
#define HAL_PERIPH_ADC8_READABLE    1
#define HAL_PERIPH_ADC8_WRITABLE    0
#define HAL_PERIPH_ADC8_SIGNED      0
#define HAL_PERIPH_ADC8_ADR         0x100005E0

// Registers ADC9L/ADC9H
#define HAL_PERIPH_ADC9_REGISTER    (HAL_PERIPHREG_MAP->ADC9L)
#define HAL_PERIPH_ADC9_LSB         0
#define HAL_PERIPH_ADC9_MSB         9
#define HAL_PERIPH_ADC9_MASK        0x000003FF
#define HAL_PERIPH_ADC9_TYPE        UInt16
#define HAL_PERIPH_ADC9             HAL_PERIPH_ADC9_MASK
#define HAL_PERIPH_ADC9_READABLE    1
#define HAL_PERIPH_ADC9_WRITABLE    0
#define HAL_PERIPH_ADC9_SIGNED      0
#define HAL_PERIPH_ADC9_ADR         0x100005E2

// Registers ADC10L/ADC10H
#define HAL_PERIPH_ADC10_REGISTER    (HAL_PERIPHREG_MAP->ADC10L)
#define HAL_PERIPH_ADC10_LSB         0
#define HAL_PERIPH_ADC10_MSB         9
#define HAL_PERIPH_ADC10_MASK        0x000003FF
#define HAL_PERIPH_ADC10_TYPE        UInt16
#define HAL_PERIPH_ADC10             HAL_PERIPH_ADC10_MASK
#define HAL_PERIPH_ADC10_READABLE    1
#define HAL_PERIPH_ADC10_WRITABLE    0
#define HAL_PERIPH_ADC10_SIGNED      0
#define HAL_PERIPH_ADC10_ADR         0x100005E4

// Registers ADC11L/ADC11H
#define HAL_PERIPH_ADC11_REGISTER    (HAL_PERIPHREG_MAP->ADC11L)
#define HAL_PERIPH_ADC11_LSB         0
#define HAL_PERIPH_ADC11_MSB         9
#define HAL_PERIPH_ADC11_MASK        0x000003FF
#define HAL_PERIPH_ADC11_TYPE        UInt16
#define HAL_PERIPH_ADC11             HAL_PERIPH_ADC11_MASK
#define HAL_PERIPH_ADC11_READABLE    1
#define HAL_PERIPH_ADC11_WRITABLE    0
#define HAL_PERIPH_ADC11_SIGNED      0
#define HAL_PERIPH_ADC11_ADR         0x100005E6

// Registers ADC12L/ADC12H
#define HAL_PERIPH_ADC12_REGISTER    (HAL_PERIPHREG_MAP->ADC12L)
#define HAL_PERIPH_ADC12_LSB         0
#define HAL_PERIPH_ADC12_MSB         9
#define HAL_PERIPH_ADC12_MASK        0x000003FF
#define HAL_PERIPH_ADC12_TYPE        UInt16
#define HAL_PERIPH_ADC12             HAL_PERIPH_ADC12_MASK
#define HAL_PERIPH_ADC12_READABLE    1
#define HAL_PERIPH_ADC12_WRITABLE    0
#define HAL_PERIPH_ADC12_SIGNED      0
#define HAL_PERIPH_ADC12_ADR         0x100005E8

// Registers ADC13L/ADC13H
#define HAL_PERIPH_ADC13_REGISTER    (HAL_PERIPHREG_MAP->ADC13L)
#define HAL_PERIPH_ADC13_LSB         0
#define HAL_PERIPH_ADC13_MSB         9
#define HAL_PERIPH_ADC13_MASK        0x000003FF
#define HAL_PERIPH_ADC13_TYPE        UInt16
#define HAL_PERIPH_ADC13             HAL_PERIPH_ADC13_MASK
#define HAL_PERIPH_ADC13_READABLE    1
#define HAL_PERIPH_ADC13_WRITABLE    0
#define HAL_PERIPH_ADC13_SIGNED      0
#define HAL_PERIPH_ADC13_ADR         0x100005EA

// Registers ADC14L/ADC14H
#define HAL_PERIPH_ADC14_REGISTER    (HAL_PERIPHREG_MAP->ADC14L)
#define HAL_PERIPH_ADC14_LSB         0
#define HAL_PERIPH_ADC14_MSB         9
#define HAL_PERIPH_ADC14_MASK        0x000003FF
#define HAL_PERIPH_ADC14_TYPE        UInt16
#define HAL_PERIPH_ADC14             HAL_PERIPH_ADC14_MASK
#define HAL_PERIPH_ADC14_READABLE    1
#define HAL_PERIPH_ADC14_WRITABLE    0
#define HAL_PERIPH_ADC14_SIGNED      0
#define HAL_PERIPH_ADC14_ADR         0x100005EC

// Registers ADC15L/ADC15H
#define HAL_PERIPH_ADC15_REGISTER    (HAL_PERIPHREG_MAP->ADC15L)
#define HAL_PERIPH_ADC15_LSB         0
#define HAL_PERIPH_ADC15_MSB         9
#define HAL_PERIPH_ADC15_MASK        0x000003FF
#define HAL_PERIPH_ADC15_TYPE        UInt16
#define HAL_PERIPH_ADC15             HAL_PERIPH_ADC15_MASK
#define HAL_PERIPH_ADC15_READABLE    1
#define HAL_PERIPH_ADC15_WRITABLE    0
#define HAL_PERIPH_ADC15_SIGNED      0
#define HAL_PERIPH_ADC15_ADR         0x100005EE

// Register ADCSTATL
#define HAL_PERIPH_ADC7DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC7DNE_LSB         7
#define HAL_PERIPH_ADC7DNE_MSB         7
#define HAL_PERIPH_ADC7DNE_MASK        0x00000080
#define HAL_PERIPH_ADC7DNE_TYPE        Bool
#define HAL_PERIPH_ADC7DNE             HAL_PERIPH_ADC7DNE_MASK
#define HAL_PERIPH_ADC7DNE_READABLE    1
#define HAL_PERIPH_ADC7DNE_WRITABLE    1
#define HAL_PERIPH_ADC7DNE_SIGNED      0
#define HAL_PERIPH_ADC7DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC6DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC6DNE_LSB         6
#define HAL_PERIPH_ADC6DNE_MSB         6
#define HAL_PERIPH_ADC6DNE_MASK        0x00000040
#define HAL_PERIPH_ADC6DNE_TYPE        Bool
#define HAL_PERIPH_ADC6DNE             HAL_PERIPH_ADC6DNE_MASK
#define HAL_PERIPH_ADC6DNE_READABLE    1
#define HAL_PERIPH_ADC6DNE_WRITABLE    1
#define HAL_PERIPH_ADC6DNE_SIGNED      0
#define HAL_PERIPH_ADC6DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC5DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC5DNE_LSB         5
#define HAL_PERIPH_ADC5DNE_MSB         5
#define HAL_PERIPH_ADC5DNE_MASK        0x00000020
#define HAL_PERIPH_ADC5DNE_TYPE        Bool
#define HAL_PERIPH_ADC5DNE             HAL_PERIPH_ADC5DNE_MASK
#define HAL_PERIPH_ADC5DNE_READABLE    1
#define HAL_PERIPH_ADC5DNE_WRITABLE    1
#define HAL_PERIPH_ADC5DNE_SIGNED      0
#define HAL_PERIPH_ADC5DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC4DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC4DNE_LSB         4
#define HAL_PERIPH_ADC4DNE_MSB         4
#define HAL_PERIPH_ADC4DNE_MASK        0x00000010
#define HAL_PERIPH_ADC4DNE_TYPE        Bool
#define HAL_PERIPH_ADC4DNE             HAL_PERIPH_ADC4DNE_MASK
#define HAL_PERIPH_ADC4DNE_READABLE    1
#define HAL_PERIPH_ADC4DNE_WRITABLE    1
#define HAL_PERIPH_ADC4DNE_SIGNED      0
#define HAL_PERIPH_ADC4DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC3DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC3DNE_LSB         3
#define HAL_PERIPH_ADC3DNE_MSB         3
#define HAL_PERIPH_ADC3DNE_MASK        0x00000008
#define HAL_PERIPH_ADC3DNE_TYPE        Bool
#define HAL_PERIPH_ADC3DNE             HAL_PERIPH_ADC3DNE_MASK
#define HAL_PERIPH_ADC3DNE_READABLE    1
#define HAL_PERIPH_ADC3DNE_WRITABLE    1
#define HAL_PERIPH_ADC3DNE_SIGNED      0
#define HAL_PERIPH_ADC3DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC2DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC2DNE_LSB         2
#define HAL_PERIPH_ADC2DNE_MSB         2
#define HAL_PERIPH_ADC2DNE_MASK        0x00000004
#define HAL_PERIPH_ADC2DNE_TYPE        Bool
#define HAL_PERIPH_ADC2DNE             HAL_PERIPH_ADC2DNE_MASK
#define HAL_PERIPH_ADC2DNE_READABLE    1
#define HAL_PERIPH_ADC2DNE_WRITABLE    1
#define HAL_PERIPH_ADC2DNE_SIGNED      0
#define HAL_PERIPH_ADC2DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC1DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC1DNE_LSB         1
#define HAL_PERIPH_ADC1DNE_MSB         1
#define HAL_PERIPH_ADC1DNE_MASK        0x00000002
#define HAL_PERIPH_ADC1DNE_TYPE        Bool
#define HAL_PERIPH_ADC1DNE             HAL_PERIPH_ADC1DNE_MASK
#define HAL_PERIPH_ADC1DNE_READABLE    1
#define HAL_PERIPH_ADC1DNE_WRITABLE    1
#define HAL_PERIPH_ADC1DNE_SIGNED      0
#define HAL_PERIPH_ADC1DNE_ADR         0x100005F0

#define HAL_PERIPH_ADC0DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATL)
#define HAL_PERIPH_ADC0DNE_LSB         0
#define HAL_PERIPH_ADC0DNE_MSB         0
#define HAL_PERIPH_ADC0DNE_MASK        0x00000001
#define HAL_PERIPH_ADC0DNE_TYPE        Bool
#define HAL_PERIPH_ADC0DNE             HAL_PERIPH_ADC0DNE_MASK
#define HAL_PERIPH_ADC0DNE_READABLE    1
#define HAL_PERIPH_ADC0DNE_WRITABLE    1
#define HAL_PERIPH_ADC0DNE_SIGNED      0
#define HAL_PERIPH_ADC0DNE_ADR         0x100005F0

// Register ADCSTATH
#define HAL_PERIPH_ADC15DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC15DNE_LSB         7
#define HAL_PERIPH_ADC15DNE_MSB         7
#define HAL_PERIPH_ADC15DNE_MASK        0x00000080
#define HAL_PERIPH_ADC15DNE_TYPE        Bool
#define HAL_PERIPH_ADC15DNE             HAL_PERIPH_ADC15DNE_MASK
#define HAL_PERIPH_ADC15DNE_READABLE    1
#define HAL_PERIPH_ADC15DNE_WRITABLE    1
#define HAL_PERIPH_ADC15DNE_SIGNED      0
#define HAL_PERIPH_ADC15DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC14DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC14DNE_LSB         6
#define HAL_PERIPH_ADC14DNE_MSB         6
#define HAL_PERIPH_ADC14DNE_MASK        0x00000040
#define HAL_PERIPH_ADC14DNE_TYPE        Bool
#define HAL_PERIPH_ADC14DNE             HAL_PERIPH_ADC14DNE_MASK
#define HAL_PERIPH_ADC14DNE_READABLE    1
#define HAL_PERIPH_ADC14DNE_WRITABLE    1
#define HAL_PERIPH_ADC14DNE_SIGNED      0
#define HAL_PERIPH_ADC14DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC13DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC13DNE_LSB         5
#define HAL_PERIPH_ADC13DNE_MSB         5
#define HAL_PERIPH_ADC13DNE_MASK        0x00000020
#define HAL_PERIPH_ADC13DNE_TYPE        Bool
#define HAL_PERIPH_ADC13DNE             HAL_PERIPH_ADC13DNE_MASK
#define HAL_PERIPH_ADC13DNE_READABLE    1
#define HAL_PERIPH_ADC13DNE_WRITABLE    1
#define HAL_PERIPH_ADC13DNE_SIGNED      0
#define HAL_PERIPH_ADC13DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC12DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC12DNE_LSB         4
#define HAL_PERIPH_ADC12DNE_MSB         4
#define HAL_PERIPH_ADC12DNE_MASK        0x00000010
#define HAL_PERIPH_ADC12DNE_TYPE        Bool
#define HAL_PERIPH_ADC12DNE             HAL_PERIPH_ADC12DNE_MASK
#define HAL_PERIPH_ADC12DNE_READABLE    1
#define HAL_PERIPH_ADC12DNE_WRITABLE    1
#define HAL_PERIPH_ADC12DNE_SIGNED      0
#define HAL_PERIPH_ADC12DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC11DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC11DNE_LSB         3
#define HAL_PERIPH_ADC11DNE_MSB         3
#define HAL_PERIPH_ADC11DNE_MASK        0x00000008
#define HAL_PERIPH_ADC11DNE_TYPE        Bool
#define HAL_PERIPH_ADC11DNE             HAL_PERIPH_ADC11DNE_MASK
#define HAL_PERIPH_ADC11DNE_READABLE    1
#define HAL_PERIPH_ADC11DNE_WRITABLE    1
#define HAL_PERIPH_ADC11DNE_SIGNED      0
#define HAL_PERIPH_ADC11DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC10DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC10DNE_LSB         2
#define HAL_PERIPH_ADC10DNE_MSB         2
#define HAL_PERIPH_ADC10DNE_MASK        0x00000004
#define HAL_PERIPH_ADC10DNE_TYPE        Bool
#define HAL_PERIPH_ADC10DNE             HAL_PERIPH_ADC10DNE_MASK
#define HAL_PERIPH_ADC10DNE_READABLE    1
#define HAL_PERIPH_ADC10DNE_WRITABLE    1
#define HAL_PERIPH_ADC10DNE_SIGNED      0
#define HAL_PERIPH_ADC10DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC9DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC9DNE_LSB         1
#define HAL_PERIPH_ADC9DNE_MSB         1
#define HAL_PERIPH_ADC9DNE_MASK        0x00000002
#define HAL_PERIPH_ADC9DNE_TYPE        Bool
#define HAL_PERIPH_ADC9DNE             HAL_PERIPH_ADC9DNE_MASK
#define HAL_PERIPH_ADC9DNE_READABLE    1
#define HAL_PERIPH_ADC9DNE_WRITABLE    1
#define HAL_PERIPH_ADC9DNE_SIGNED      0
#define HAL_PERIPH_ADC9DNE_ADR         0x100005F1

#define HAL_PERIPH_ADC8DNE_REGISTER    (HAL_PERIPHREG_MAP->ADCSTATH)
#define HAL_PERIPH_ADC8DNE_LSB         0
#define HAL_PERIPH_ADC8DNE_MSB         0
#define HAL_PERIPH_ADC8DNE_MASK        0x00000001
#define HAL_PERIPH_ADC8DNE_TYPE        Bool
#define HAL_PERIPH_ADC8DNE             HAL_PERIPH_ADC8DNE_MASK
#define HAL_PERIPH_ADC8DNE_READABLE    1
#define HAL_PERIPH_ADC8DNE_WRITABLE    1
#define HAL_PERIPH_ADC8DNE_SIGNED      0
#define HAL_PERIPH_ADC8DNE_ADR         0x100005F1

// Register ADCCTL
#define HAL_PERIPH_ADCGAIN_REGISTER    (HAL_PERIPHREG_MAP->ADCCTL)
#define HAL_PERIPH_ADCGAIN_LSB         0
#define HAL_PERIPH_ADCGAIN_MSB         0
#define HAL_PERIPH_ADCGAIN_MASK        0x00000001
#define HAL_PERIPH_ADCGAIN_TYPE        Bool
#define HAL_PERIPH_ADCGAIN             HAL_PERIPH_ADCGAIN_MASK
#define HAL_PERIPH_ADCGAIN_READABLE    1
#define HAL_PERIPH_ADCGAIN_WRITABLE    1
#define HAL_PERIPH_ADCGAIN_SIGNED      0
#define HAL_PERIPH_ADCGAIN_ADR         0x100005F4

// Enumerations
typedef enum
{
	halPERIPH_TINT_Off   = 0,    // Timer Interrupt Off
	halPERIPH_TINT_Int   = 1,    // Timer Interrupt generated when Timer done
	halPERIPH_TINT_Reset = 2     // Timer Reset generated when Timer done
} halPERIPH_EnTInt_t;

typedef enum
{
	halPERIPH_TMOD_Off     = 0,    // Timer Off
	halPERIPH_TMOD_Measure = 1,    // Timer Measure Mode
	halPERIPH_TMOD_Counter = 2,    // Timer Counter Mode
	halPERIPH_TMOD_Timer   = 3     // Timer Timer Mode
} halPERIPH_TMode_t;

typedef enum
{
	halPERIPH_TClk_XINDiv1    = 0,    // XIN (No Divide)
	halPERIPH_TClk_XINDiv4    = 1,    // XIN / 4
	halPERIPH_TClk_XINDiv16   = 2,    // XIN / 16
	halPERIPH_TClk_XINDiv64   = 3,    // XIN / 64
	halPERIPH_TClk_XINDiv256  = 4,    // XIN / 256
	halPERIPH_TClk_XINDiv1024 = 5     // XIN / 1024
} halPERIPH_TClkDiv_t;

typedef enum
{
	halPERIPH_T0CM_IN0_PA0  = 0,    // PA0 (IN0)
	halPERIPH_T0CM_IN1_PA6  = 1,    // PA6 (IN1)
	halPERIPH_T0CM_IN2_ESFS = 2     // ESFS (IN2)
} halPERIPH_T0CMInput_t;

typedef enum
{
	halPERIPH_T1CM_IN0_PA1 = 0,    // PA1 (IN0)
	halPERIPH_T1CM_IN1_PA7 = 1,    // PA7 (IN1)
	halPERIPH_T1CM_IN2_PC3 = 2     // PC3 (IN2)
} halPERIPH_T1CMInput_t;

typedef enum
{
	halPERIPH_T2CM_IN0_PA2 = 0,    // PA2 (IN0)
	halPERIPH_T2CM_IN1_PB4 = 1,    // PB4 (IN1)
	halPERIPH_T2CM_IN2_FG  = 2     // FG (IN2)
} halPERIPH_T2CMInput_t;

typedef enum
{
	halPERIPH_T3CM_IN0_PA3 = 0,    // PA3 (IN0)
	halPERIPH_T3CM_IN1_PB5 = 1,    // PB5 (IN1)
	halPERIPH_T3CM_IN2_PB0 = 2     // PB0 (IN2)
} halPERIPH_T3CMInput_t;

typedef enum
{
	halPERIPH_T4CM_IN0_PA4 = 0,    // PA4 (IN0)
	halPERIPH_T4CM_IN1_PB6 = 1,    // PB6 (IN1)
	halPERIPH_T4CM_IN2_PB1 = 2     // PB1 (IN2)
} halPERIPH_T4CMInput_t;

typedef enum
{
	halPERIPH_T5CM_IN0_PA5  = 0,    // PA5 (IN0)
	halPERIPH_T5CM_IN1_PB7  = 1,    // PB7 (IN1)
	halPERIPH_T5CM_IN2_OENC = 2     // OENC (IN2)
} halPERIPH_T5CMInput_t;

#endif /* __REG_PERIPH_H__ */

