/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_arm2sc.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the SOC_AHB_ARM2SC core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_ARM2SC_H__
#define __REG_ARM2SC_H__

// Core register map
#define HAL_AHB_ARM2SC_VERSION 7.142
#define HAL_AHB_ARM2SC_BaseAddress 0xCD000000
#define HAL_AHB_ARM2SCREG_MAP ((struct halAHB_ARM2SCReg_Map*) (void *) HAL_AHB_ARM2SC_BaseAddress)
__packed struct halAHB_ARM2SCReg_Map
{
	HAL_Reg32 PVCIWD;                         //00000000
	HAL_Reg32 AHBSLVWD;                       //00000004
};
// Register PVCIWD
#define HAL_AHB_ARM2SC_PWDERRAD_REGISTER    (HAL_AHB_ARM2SCREG_MAP->PVCIWD)
#define HAL_AHB_ARM2SC_PWDERRAD_LSB         2
#define HAL_AHB_ARM2SC_PWDERRAD_MSB         17
#define HAL_AHB_ARM2SC_PWDERRAD_MASK        0x0003FFFC
#define HAL_AHB_ARM2SC_PWDERRAD_TYPE        UInt16
#define HAL_AHB_ARM2SC_PWDERRAD             HAL_AHB_ARM2SC_PWDERRAD_MASK
#define HAL_AHB_ARM2SC_PWDERRAD_READABLE    1
#define HAL_AHB_ARM2SC_PWDERRAD_WRITABLE    0
#define HAL_AHB_ARM2SC_PWDERRAD_SIGNED      0
#define HAL_AHB_ARM2SC_PWDERRAD_ADR         0xCD000000

#define HAL_AHB_ARM2SC_PWDINT_REGISTER    (HAL_AHB_ARM2SCREG_MAP->PVCIWD)
#define HAL_AHB_ARM2SC_PWDINT_LSB         1
#define HAL_AHB_ARM2SC_PWDINT_MSB         1
#define HAL_AHB_ARM2SC_PWDINT_MASK        0x00000002
#define HAL_AHB_ARM2SC_PWDINT_TYPE        Bool
#define HAL_AHB_ARM2SC_PWDINT             HAL_AHB_ARM2SC_PWDINT_MASK
#define HAL_AHB_ARM2SC_PWDINT_READABLE    1
#define HAL_AHB_ARM2SC_PWDINT_WRITABLE    1
#define HAL_AHB_ARM2SC_PWDINT_SIGNED      0
#define HAL_AHB_ARM2SC_PWDINT_ADR         0xCD000000

#define HAL_AHB_ARM2SC_PWDEN_REGISTER    (HAL_AHB_ARM2SCREG_MAP->PVCIWD)
#define HAL_AHB_ARM2SC_PWDEN_LSB         0
#define HAL_AHB_ARM2SC_PWDEN_MSB         0
#define HAL_AHB_ARM2SC_PWDEN_MASK        0x00000001
#define HAL_AHB_ARM2SC_PWDEN_TYPE        Bool
#define HAL_AHB_ARM2SC_PWDEN             HAL_AHB_ARM2SC_PWDEN_MASK
#define HAL_AHB_ARM2SC_PWDEN_READABLE    1
#define HAL_AHB_ARM2SC_PWDEN_WRITABLE    1
#define HAL_AHB_ARM2SC_PWDEN_SIGNED      0
#define HAL_AHB_ARM2SC_PWDEN_ADR         0xCD000000

// Register AHBSLVWD
#define HAL_AHB_ARM2SC_ASWDERRAD_REGISTER    (HAL_AHB_ARM2SCREG_MAP->AHBSLVWD)
#define HAL_AHB_ARM2SC_ASWDERRAD_LSB         2
#define HAL_AHB_ARM2SC_ASWDERRAD_MSB         17
#define HAL_AHB_ARM2SC_ASWDERRAD_MASK        0x0003FFFC
#define HAL_AHB_ARM2SC_ASWDERRAD_TYPE        UInt16
#define HAL_AHB_ARM2SC_ASWDERRAD             HAL_AHB_ARM2SC_ASWDERRAD_MASK
#define HAL_AHB_ARM2SC_ASWDERRAD_READABLE    1
#define HAL_AHB_ARM2SC_ASWDERRAD_WRITABLE    0
#define HAL_AHB_ARM2SC_ASWDERRAD_SIGNED      0
#define HAL_AHB_ARM2SC_ASWDERRAD_ADR         0xCD000004

#define HAL_AHB_ARM2SC_ASWDINT_REGISTER    (HAL_AHB_ARM2SCREG_MAP->AHBSLVWD)
#define HAL_AHB_ARM2SC_ASWDINT_LSB         1
#define HAL_AHB_ARM2SC_ASWDINT_MSB         1
#define HAL_AHB_ARM2SC_ASWDINT_MASK        0x00000002
#define HAL_AHB_ARM2SC_ASWDINT_TYPE        Bool
#define HAL_AHB_ARM2SC_ASWDINT             HAL_AHB_ARM2SC_ASWDINT_MASK
#define HAL_AHB_ARM2SC_ASWDINT_READABLE    1
#define HAL_AHB_ARM2SC_ASWDINT_WRITABLE    1
#define HAL_AHB_ARM2SC_ASWDINT_SIGNED      0
#define HAL_AHB_ARM2SC_ASWDINT_ADR         0xCD000004

#define HAL_AHB_ARM2SC_ASWDEN_REGISTER    (HAL_AHB_ARM2SCREG_MAP->AHBSLVWD)
#define HAL_AHB_ARM2SC_ASWDEN_LSB         0
#define HAL_AHB_ARM2SC_ASWDEN_MSB         0
#define HAL_AHB_ARM2SC_ASWDEN_MASK        0x00000001
#define HAL_AHB_ARM2SC_ASWDEN_TYPE        Bool
#define HAL_AHB_ARM2SC_ASWDEN             HAL_AHB_ARM2SC_ASWDEN_MASK
#define HAL_AHB_ARM2SC_ASWDEN_READABLE    1
#define HAL_AHB_ARM2SC_ASWDEN_WRITABLE    1
#define HAL_AHB_ARM2SC_ASWDEN_SIGNED      0
#define HAL_AHB_ARM2SC_ASWDEN_ADR         0xCD000004

#endif /* __REG_ARM2SC_H__ */

