/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_demod.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the DMOD core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_DEMOD_H__
#define __REG_DEMOD_H__

// Core register map
#define HAL_DMOD_VERSION 1.32
#define HAL_DMOD_BaseAddress 0xB0004000
#define HAL_DMODREG_MAP ((struct halDMODReg_Map*) (void *) HAL_DMOD_BaseAddress)
__packed struct halDMODReg_Map
{
	HAL_Reg32 BDDMODCFG;                      //00000000
	HAL_Reg32 BDDMDCFG2;                      //00000004
	HAL_Reg32 BDDMODSTA;                      //00000008
	HAL_Reg32 HDDMODCFG;                      //0000000C
	HAL_Reg32 HDDMODSTA;                      //00000010
	HAL_Reg32 ReservedBlk0[3];                //00000014
	HAL_Reg32 CDVDMDCFG;                      //00000020
	HAL_Reg32 ReservedBlk1[1];                //00000024
	HAL_Reg32 CDVDMDSTA;                      //00000028
	HAL_Reg32 ReservedBlk2[5];                //0000002C
	HAL_Reg32 DMODINTS;                       //00000040
	HAL_Reg32 DMODINTE;                       //00000044
	HAL_Reg32 DMODINT;                        //00000048
	HAL_Reg32 BDPICDCFG;                      //0000004C
	HAL_Reg32 BDPICDMDS;                      //00000050
	HAL_Reg32 ReservedBlk3[3];                //00000054
	HAL_Reg32 DMDERACNT;                      //00000060
	HAL_Reg32 ReservedBlk4[3];                //00000064
	HAL_Reg32 MMCFG;                          //00000070
	HAL_Reg32 MMOFSCFG;                       //00000074
	HAL_Reg32 MMDATA;                         //00000078
	HAL_Reg32 ReservedBlk5[33];               //0000007C
	HAL_Reg32 DMODDBG;                        //00000100
	HAL_Reg32 DMDSPARE;                       //00000104
};
// Register BDDMODCFG
#define HAL_DMOD_BDDISTSY_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDDISTSY_LSB         22
#define HAL_DMOD_BDDISTSY_MSB         25
#define HAL_DMOD_BDDISTSY_MASK        0x03C00000
#define HAL_DMOD_BDDISTSY_TYPE        UByte
#define HAL_DMOD_BDDISTSY             HAL_DMOD_BDDISTSY_MASK
#define HAL_DMOD_BDDISTSY_READABLE    1
#define HAL_DMOD_BDDISTSY_WRITABLE    1
#define HAL_DMOD_BDDISTSY_SIGNED      0
#define HAL_DMOD_BDDISTSY_ADR         0xB0004000

#define HAL_DMOD_BDSYCOLMX_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDSYCOLMX_LSB         18
#define HAL_DMOD_BDSYCOLMX_MSB         21
#define HAL_DMOD_BDSYCOLMX_MASK        0x003C0000
#define HAL_DMOD_BDSYCOLMX_TYPE        UByte
#define HAL_DMOD_BDSYCOLMX             HAL_DMOD_BDSYCOLMX_MASK
#define HAL_DMOD_BDSYCOLMX_READABLE    1
#define HAL_DMOD_BDSYCOLMX_WRITABLE    1
#define HAL_DMOD_BDSYCOLMX_SIGNED      0
#define HAL_DMOD_BDSYCOLMX_ADR         0xB0004000

#define HAL_DMOD_BDSYCOLTH_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDSYCOLTH_LSB         14
#define HAL_DMOD_BDSYCOLTH_MSB         17
#define HAL_DMOD_BDSYCOLTH_MASK        0x0003C000
#define HAL_DMOD_BDSYCOLTH_TYPE        UByte
#define HAL_DMOD_BDSYCOLTH             HAL_DMOD_BDSYCOLTH_MASK
#define HAL_DMOD_BDSYCOLTH_READABLE    1
#define HAL_DMOD_BDSYCOLTH_WRITABLE    1
#define HAL_DMOD_BDSYCOLTH_SIGNED      0
#define HAL_DMOD_BDSYCOLTH_ADR         0xB0004000

#define HAL_DMOD_BDSYUNTHR_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDSYUNTHR_LSB         8
#define HAL_DMOD_BDSYUNTHR_MSB         13
#define HAL_DMOD_BDSYUNTHR_MASK        0x00003F00
#define HAL_DMOD_BDSYUNTHR_TYPE        UByte
#define HAL_DMOD_BDSYUNTHR             HAL_DMOD_BDSYUNTHR_MASK
#define HAL_DMOD_BDSYUNTHR_READABLE    1
#define HAL_DMOD_BDSYUNTHR_WRITABLE    1
#define HAL_DMOD_BDSYUNTHR_SIGNED      0
#define HAL_DMOD_BDSYUNTHR_ADR         0xB0004000

#define HAL_DMOD_BDSYGATCL_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDSYGATCL_LSB         2
#define HAL_DMOD_BDSYGATCL_MSB         2
#define HAL_DMOD_BDSYGATCL_MASK        0x00000004
#define HAL_DMOD_BDSYGATCL_TYPE        Bool
#define HAL_DMOD_BDSYGATCL             HAL_DMOD_BDSYGATCL_MASK
#define HAL_DMOD_BDSYGATCL_READABLE    1
#define HAL_DMOD_BDSYGATCL_WRITABLE    1
#define HAL_DMOD_BDSYGATCL_SIGNED      0
#define HAL_DMOD_BDSYGATCL_ADR         0xB0004000

#define HAL_DMOD_BDROBSYLK_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDROBSYLK_LSB         1
#define HAL_DMOD_BDROBSYLK_MSB         1
#define HAL_DMOD_BDROBSYLK_MASK        0x00000002
#define HAL_DMOD_BDROBSYLK_TYPE        Bool
#define HAL_DMOD_BDROBSYLK             HAL_DMOD_BDROBSYLK_MASK
#define HAL_DMOD_BDROBSYLK_READABLE    1
#define HAL_DMOD_BDROBSYLK_WRITABLE    1
#define HAL_DMOD_BDROBSYLK_SIGNED      0
#define HAL_DMOD_BDROBSYLK_ADR         0xB0004000

#define HAL_DMOD_BDDMODRUN_REGISTER    (HAL_DMODREG_MAP->BDDMODCFG)
#define HAL_DMOD_BDDMODRUN_LSB         0
#define HAL_DMOD_BDDMODRUN_MSB         0
#define HAL_DMOD_BDDMODRUN_MASK        0x00000001
#define HAL_DMOD_BDDMODRUN_TYPE        Bool
#define HAL_DMOD_BDDMODRUN             HAL_DMOD_BDDMODRUN_MASK
#define HAL_DMOD_BDDMODRUN_READABLE    1
#define HAL_DMOD_BDDMODRUN_WRITABLE    1
#define HAL_DMOD_BDDMODRUN_SIGNED      0
#define HAL_DMOD_BDDMODRUN_ADR         0xB0004000

// Register BDDMDCFG2
#define HAL_DMOD_RELINKCUT_REGISTER    (HAL_DMODREG_MAP->BDDMDCFG2)
#define HAL_DMOD_RELINKCUT_LSB         1
#define HAL_DMOD_RELINKCUT_MSB         1
#define HAL_DMOD_RELINKCUT_MASK        0x00000002
#define HAL_DMOD_RELINKCUT_TYPE        halDMOD_RELinkingCut_t
#define HAL_DMOD_RELINKCUT             HAL_DMOD_RELINKCUT_MASK
#define HAL_DMOD_RELINKCUT_READABLE    1
#define HAL_DMOD_RELINKCUT_WRITABLE    1
#define HAL_DMOD_RELINKCUT_SIGNED      0
#define HAL_DMOD_RELINKCUT_ADR         0xB0004004

#define HAL_DMOD_DISDMDFRC_REGISTER    (HAL_DMODREG_MAP->BDDMDCFG2)
#define HAL_DMOD_DISDMDFRC_LSB         0
#define HAL_DMOD_DISDMDFRC_MSB         0
#define HAL_DMOD_DISDMDFRC_MASK        0x00000001
#define HAL_DMOD_DISDMDFRC_TYPE        Bool
#define HAL_DMOD_DISDMDFRC             HAL_DMOD_DISDMDFRC_MASK
#define HAL_DMOD_DISDMDFRC_READABLE    1
#define HAL_DMOD_DISDMDFRC_WRITABLE    1
#define HAL_DMOD_DISDMDFRC_SIGNED      0
#define HAL_DMOD_DISDMDFRC_ADR         0xB0004004

// Register BDDMODSTA
#define HAL_DMOD_BDSYCOLLK_REGISTER    (HAL_DMODREG_MAP->BDDMODSTA)
#define HAL_DMOD_BDSYCOLLK_LSB         1
#define HAL_DMOD_BDSYCOLLK_MSB         1
#define HAL_DMOD_BDSYCOLLK_MASK        0x00000002
#define HAL_DMOD_BDSYCOLLK_TYPE        Bool
#define HAL_DMOD_BDSYCOLLK             HAL_DMOD_BDSYCOLLK_MASK
#define HAL_DMOD_BDSYCOLLK_READABLE    1
#define HAL_DMOD_BDSYCOLLK_WRITABLE    0
#define HAL_DMOD_BDSYCOLLK_SIGNED      0
#define HAL_DMOD_BDSYCOLLK_ADR         0xB0004008

#define HAL_DMOD_BDSYPOSLK_REGISTER    (HAL_DMODREG_MAP->BDDMODSTA)
#define HAL_DMOD_BDSYPOSLK_LSB         0
#define HAL_DMOD_BDSYPOSLK_MSB         0
#define HAL_DMOD_BDSYPOSLK_MASK        0x00000001
#define HAL_DMOD_BDSYPOSLK_TYPE        Bool
#define HAL_DMOD_BDSYPOSLK             HAL_DMOD_BDSYPOSLK_MASK
#define HAL_DMOD_BDSYPOSLK_READABLE    1
#define HAL_DMOD_BDSYPOSLK_WRITABLE    0
#define HAL_DMOD_BDSYPOSLK_SIGNED      0
#define HAL_DMOD_BDSYPOSLK_ADR         0xB0004008

// Register HDDMODCFG
#define HAL_DMOD_HDDISTSY_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDDISTSY_LSB         22
#define HAL_DMOD_HDDISTSY_MSB         25
#define HAL_DMOD_HDDISTSY_MASK        0x03C00000
#define HAL_DMOD_HDDISTSY_TYPE        UByte
#define HAL_DMOD_HDDISTSY             HAL_DMOD_HDDISTSY_MASK
#define HAL_DMOD_HDDISTSY_READABLE    1
#define HAL_DMOD_HDDISTSY_WRITABLE    1
#define HAL_DMOD_HDDISTSY_SIGNED      0
#define HAL_DMOD_HDDISTSY_ADR         0xB000400C

#define HAL_DMOD_HDSYCOLMX_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDSYCOLMX_LSB         18
#define HAL_DMOD_HDSYCOLMX_MSB         21
#define HAL_DMOD_HDSYCOLMX_MASK        0x003C0000
#define HAL_DMOD_HDSYCOLMX_TYPE        UByte
#define HAL_DMOD_HDSYCOLMX             HAL_DMOD_HDSYCOLMX_MASK
#define HAL_DMOD_HDSYCOLMX_READABLE    1
#define HAL_DMOD_HDSYCOLMX_WRITABLE    1
#define HAL_DMOD_HDSYCOLMX_SIGNED      0
#define HAL_DMOD_HDSYCOLMX_ADR         0xB000400C

#define HAL_DMOD_HDSYCOLTH_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDSYCOLTH_LSB         14
#define HAL_DMOD_HDSYCOLTH_MSB         17
#define HAL_DMOD_HDSYCOLTH_MASK        0x0003C000
#define HAL_DMOD_HDSYCOLTH_TYPE        UByte
#define HAL_DMOD_HDSYCOLTH             HAL_DMOD_HDSYCOLTH_MASK
#define HAL_DMOD_HDSYCOLTH_READABLE    1
#define HAL_DMOD_HDSYCOLTH_WRITABLE    1
#define HAL_DMOD_HDSYCOLTH_SIGNED      0
#define HAL_DMOD_HDSYCOLTH_ADR         0xB000400C

#define HAL_DMOD_HDSYUNTHR_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDSYUNTHR_LSB         8
#define HAL_DMOD_HDSYUNTHR_MSB         13
#define HAL_DMOD_HDSYUNTHR_MASK        0x00003F00
#define HAL_DMOD_HDSYUNTHR_TYPE        UByte
#define HAL_DMOD_HDSYUNTHR             HAL_DMOD_HDSYUNTHR_MASK
#define HAL_DMOD_HDSYUNTHR_READABLE    1
#define HAL_DMOD_HDSYUNTHR_WRITABLE    1
#define HAL_DMOD_HDSYUNTHR_SIGNED      0
#define HAL_DMOD_HDSYUNTHR_ADR         0xB000400C

#define HAL_DMOD_HDSYGATEC_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDSYGATEC_LSB         3
#define HAL_DMOD_HDSYGATEC_MSB         3
#define HAL_DMOD_HDSYGATEC_MASK        0x00000008
#define HAL_DMOD_HDSYGATEC_TYPE        Bool
#define HAL_DMOD_HDSYGATEC             HAL_DMOD_HDSYGATEC_MASK
#define HAL_DMOD_HDSYGATEC_READABLE    1
#define HAL_DMOD_HDSYGATEC_WRITABLE    1
#define HAL_DMOD_HDSYGATEC_SIGNED      0
#define HAL_DMOD_HDSYGATEC_ADR         0xB000400C

#define HAL_DMOD_HDLASTSEC_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDLASTSEC_LSB         2
#define HAL_DMOD_HDLASTSEC_MSB         2
#define HAL_DMOD_HDLASTSEC_MASK        0x00000004
#define HAL_DMOD_HDLASTSEC_TYPE        Bool
#define HAL_DMOD_HDLASTSEC             HAL_DMOD_HDLASTSEC_MASK
#define HAL_DMOD_HDLASTSEC_READABLE    1
#define HAL_DMOD_HDLASTSEC_WRITABLE    1
#define HAL_DMOD_HDLASTSEC_SIGNED      0
#define HAL_DMOD_HDLASTSEC_ADR         0xB000400C

#define HAL_DMOD_HDROBSYLK_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDROBSYLK_LSB         1
#define HAL_DMOD_HDROBSYLK_MSB         1
#define HAL_DMOD_HDROBSYLK_MASK        0x00000002
#define HAL_DMOD_HDROBSYLK_TYPE        Bool
#define HAL_DMOD_HDROBSYLK             HAL_DMOD_HDROBSYLK_MASK
#define HAL_DMOD_HDROBSYLK_READABLE    1
#define HAL_DMOD_HDROBSYLK_WRITABLE    1
#define HAL_DMOD_HDROBSYLK_SIGNED      0
#define HAL_DMOD_HDROBSYLK_ADR         0xB000400C

#define HAL_DMOD_HDFRCROM_REGISTER    (HAL_DMODREG_MAP->HDDMODCFG)
#define HAL_DMOD_HDFRCROM_LSB         0
#define HAL_DMOD_HDFRCROM_MSB         0
#define HAL_DMOD_HDFRCROM_MASK        0x00000001
#define HAL_DMOD_HDFRCROM_TYPE        Bool
#define HAL_DMOD_HDFRCROM             HAL_DMOD_HDFRCROM_MASK
#define HAL_DMOD_HDFRCROM_READABLE    1
#define HAL_DMOD_HDFRCROM_WRITABLE    1
#define HAL_DMOD_HDFRCROM_SIGNED      0
#define HAL_DMOD_HDFRCROM_ADR         0xB000400C

// Register HDDMODSTA
#define HAL_DMOD_DMDFRMNO_REGISTER    (HAL_DMODREG_MAP->HDDMODSTA)
#define HAL_DMOD_DMDFRMNO_LSB         3
#define HAL_DMOD_DMDFRMNO_MSB         7
#define HAL_DMOD_DMDFRMNO_MASK        0x000000F8
#define HAL_DMOD_DMDFRMNO_TYPE        UByte
#define HAL_DMOD_DMDFRMNO             HAL_DMOD_DMDFRMNO_MASK
#define HAL_DMOD_DMDFRMNO_READABLE    1
#define HAL_DMOD_DMDFRMNO_WRITABLE    0
#define HAL_DMOD_DMDFRMNO_SIGNED      0
#define HAL_DMOD_DMDFRMNO_ADR         0xB0004010

#define HAL_DMOD_DMDFRMNOC_REGISTER    (HAL_DMODREG_MAP->HDDMODSTA)
#define HAL_DMOD_DMDFRMNOC_LSB         2
#define HAL_DMOD_DMDFRMNOC_MSB         2
#define HAL_DMOD_DMDFRMNOC_MASK        0x00000004
#define HAL_DMOD_DMDFRMNOC_TYPE        Bool
#define HAL_DMOD_DMDFRMNOC             HAL_DMOD_DMDFRMNOC_MASK
#define HAL_DMOD_DMDFRMNOC_READABLE    1
#define HAL_DMOD_DMDFRMNOC_WRITABLE    0
#define HAL_DMOD_DMDFRMNOC_SIGNED      0
#define HAL_DMOD_DMDFRMNOC_ADR         0xB0004010

#define HAL_DMOD_HDSYCOLLK_REGISTER    (HAL_DMODREG_MAP->HDDMODSTA)
#define HAL_DMOD_HDSYCOLLK_LSB         1
#define HAL_DMOD_HDSYCOLLK_MSB         1
#define HAL_DMOD_HDSYCOLLK_MASK        0x00000002
#define HAL_DMOD_HDSYCOLLK_TYPE        Bool
#define HAL_DMOD_HDSYCOLLK             HAL_DMOD_HDSYCOLLK_MASK
#define HAL_DMOD_HDSYCOLLK_READABLE    1
#define HAL_DMOD_HDSYCOLLK_WRITABLE    0
#define HAL_DMOD_HDSYCOLLK_SIGNED      0
#define HAL_DMOD_HDSYCOLLK_ADR         0xB0004010

#define HAL_DMOD_HDSYPOSLK_REGISTER    (HAL_DMODREG_MAP->HDDMODSTA)
#define HAL_DMOD_HDSYPOSLK_LSB         0
#define HAL_DMOD_HDSYPOSLK_MSB         0
#define HAL_DMOD_HDSYPOSLK_MASK        0x00000001
#define HAL_DMOD_HDSYPOSLK_TYPE        Bool
#define HAL_DMOD_HDSYPOSLK             HAL_DMOD_HDSYPOSLK_MASK
#define HAL_DMOD_HDSYPOSLK_READABLE    1
#define HAL_DMOD_HDSYPOSLK_WRITABLE    0
#define HAL_DMOD_HDSYPOSLK_SIGNED      0
#define HAL_DMOD_HDSYPOSLK_ADR         0xB0004010

// Register CDVDMDCFG
#define HAL_DMOD_AMSYCFDTH_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_AMSYCFDTH_LSB         9
#define HAL_DMOD_AMSYCFDTH_MSB         11
#define HAL_DMOD_AMSYCFDTH_MASK        0x00000E00
#define HAL_DMOD_AMSYCFDTH_TYPE        UByte
#define HAL_DMOD_AMSYCFDTH             HAL_DMOD_AMSYCFDTH_MASK
#define HAL_DMOD_AMSYCFDTH_READABLE    1
#define HAL_DMOD_AMSYCFDTH_WRITABLE    1
#define HAL_DMOD_AMSYCFDTH_SIGNED      0
#define HAL_DMOD_AMSYCFDTH_ADR         0xB0004020

#define HAL_DMOD_DMDHDRONL_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_DMDHDRONL_LSB         8
#define HAL_DMOD_DMDHDRONL_MSB         8
#define HAL_DMOD_DMDHDRONL_MASK        0x00000100
#define HAL_DMOD_DMDHDRONL_TYPE        Bool
#define HAL_DMOD_DMDHDRONL             HAL_DMOD_DMDHDRONL_MASK
#define HAL_DMOD_DMDHDRONL_READABLE    1
#define HAL_DMOD_DMDHDRONL_WRITABLE    1
#define HAL_DMOD_DMDHDRONL_SIGNED      0
#define HAL_DMOD_DMDHDRONL_ADR         0xB0004020

#define HAL_DMOD_CDVCOLKSP_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVCOLKSP_LSB         6
#define HAL_DMOD_CDVCOLKSP_MSB         7
#define HAL_DMOD_CDVCOLKSP_MASK        0x000000C0
#define HAL_DMOD_CDVCOLKSP_TYPE        halDMOD_CDDVDConfOutLockSpeed_t
#define HAL_DMOD_CDVCOLKSP             HAL_DMOD_CDVCOLKSP_MASK
#define HAL_DMOD_CDVCOLKSP_READABLE    1
#define HAL_DMOD_CDVCOLKSP_WRITABLE    1
#define HAL_DMOD_CDVCOLKSP_SIGNED      0
#define HAL_DMOD_CDVCOLKSP_ADR         0xB0004020

#define HAL_DMOD_CDVCOLTOG_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVCOLTOG_LSB         5
#define HAL_DMOD_CDVCOLTOG_MSB         5
#define HAL_DMOD_CDVCOLTOG_MASK        0x00000020
#define HAL_DMOD_CDVCOLTOG_TYPE        Bool
#define HAL_DMOD_CDVCOLTOG             HAL_DMOD_CDVCOLTOG_MASK
#define HAL_DMOD_CDVCOLTOG_READABLE    1
#define HAL_DMOD_CDVCOLTOG_WRITABLE    1
#define HAL_DMOD_CDVCOLTOG_SIGNED      0
#define HAL_DMOD_CDVCOLTOG_ADR         0xB0004020

#define HAL_DMOD_CDVSYGAC_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVSYGAC_LSB         4
#define HAL_DMOD_CDVSYGAC_MSB         4
#define HAL_DMOD_CDVSYGAC_MASK        0x00000010
#define HAL_DMOD_CDVSYGAC_TYPE        Bool
#define HAL_DMOD_CDVSYGAC             HAL_DMOD_CDVSYGAC_MASK
#define HAL_DMOD_CDVSYGAC_READABLE    1
#define HAL_DMOD_CDVSYGAC_WRITABLE    1
#define HAL_DMOD_CDVSYGAC_SIGNED      0
#define HAL_DMOD_CDVSYGAC_ADR         0xB0004020

#define HAL_DMOD_CDVROBCNT_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVROBCNT_LSB         3
#define HAL_DMOD_CDVROBCNT_MSB         3
#define HAL_DMOD_CDVROBCNT_MASK        0x00000008
#define HAL_DMOD_CDVROBCNT_TYPE        Bool
#define HAL_DMOD_CDVROBCNT             HAL_DMOD_CDVROBCNT_MASK
#define HAL_DMOD_CDVROBCNT_READABLE    1
#define HAL_DMOD_CDVROBCNT_WRITABLE    1
#define HAL_DMOD_CDVROBCNT_SIGNED      0
#define HAL_DMOD_CDVROBCNT_ADR         0xB0004020

#define HAL_DMOD_CDVFRCOLK_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVFRCOLK_LSB         2
#define HAL_DMOD_CDVFRCOLK_MSB         2
#define HAL_DMOD_CDVFRCOLK_MASK        0x00000004
#define HAL_DMOD_CDVFRCOLK_TYPE        Bool
#define HAL_DMOD_CDVFRCOLK             HAL_DMOD_CDVFRCOLK_MASK
#define HAL_DMOD_CDVFRCOLK_READABLE    1
#define HAL_DMOD_CDVFRCOLK_WRITABLE    1
#define HAL_DMOD_CDVFRCOLK_SIGNED      0
#define HAL_DMOD_CDVFRCOLK_ADR         0xB0004020

#define HAL_DMOD_CDVROBLKD_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVROBLKD_LSB         1
#define HAL_DMOD_CDVROBLKD_MSB         1
#define HAL_DMOD_CDVROBLKD_MASK        0x00000002
#define HAL_DMOD_CDVROBLKD_TYPE        Bool
#define HAL_DMOD_CDVROBLKD             HAL_DMOD_CDVROBLKD_MASK
#define HAL_DMOD_CDVROBLKD_READABLE    1
#define HAL_DMOD_CDVROBLKD_WRITABLE    1
#define HAL_DMOD_CDVROBLKD_SIGNED      0
#define HAL_DMOD_CDVROBLKD_ADR         0xB0004020

#define HAL_DMOD_CDVLK16_REGISTER    (HAL_DMODREG_MAP->CDVDMDCFG)
#define HAL_DMOD_CDVLK16_LSB         0
#define HAL_DMOD_CDVLK16_MSB         0
#define HAL_DMOD_CDVLK16_MASK        0x00000001
#define HAL_DMOD_CDVLK16_TYPE        Bool
#define HAL_DMOD_CDVLK16             HAL_DMOD_CDVLK16_MASK
#define HAL_DMOD_CDVLK16_READABLE    1
#define HAL_DMOD_CDVLK16_WRITABLE    1
#define HAL_DMOD_CDVLK16_SIGNED      0
#define HAL_DMOD_CDVLK16_ADR         0xB0004020

// Register CDVDMDSTA
#define HAL_DMOD_CDVAMSYCF_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVAMSYCF_LSB         16
#define HAL_DMOD_CDVAMSYCF_MSB         18
#define HAL_DMOD_CDVAMSYCF_MASK        0x00070000
#define HAL_DMOD_CDVAMSYCF_TYPE        UByte
#define HAL_DMOD_CDVAMSYCF             HAL_DMOD_CDVAMSYCF_MASK
#define HAL_DMOD_CDVAMSYCF_READABLE    1
#define HAL_DMOD_CDVAMSYCF_WRITABLE    0
#define HAL_DMOD_CDVAMSYCF_SIGNED      0
#define HAL_DMOD_CDVAMSYCF_ADR         0xB0004028

#define HAL_DMOD_CDVFRMCFD_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVFRMCFD_LSB         12
#define HAL_DMOD_CDVFRMCFD_MSB         15
#define HAL_DMOD_CDVFRMCFD_MASK        0x0000F000
#define HAL_DMOD_CDVFRMCFD_TYPE        UByte
#define HAL_DMOD_CDVFRMCFD             HAL_DMOD_CDVFRMCFD_MASK
#define HAL_DMOD_CDVFRMCFD_READABLE    1
#define HAL_DMOD_CDVFRMCFD_WRITABLE    0
#define HAL_DMOD_CDVFRMCFD_SIGNED      0
#define HAL_DMOD_CDVFRMCFD_ADR         0xB0004028

#define HAL_DMOD_CDVSYCOLC_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVSYCOLC_LSB         8
#define HAL_DMOD_CDVSYCOLC_MSB         11
#define HAL_DMOD_CDVSYCOLC_MASK        0x00000F00
#define HAL_DMOD_CDVSYCOLC_TYPE        UByte
#define HAL_DMOD_CDVSYCOLC             HAL_DMOD_CDVSYCOLC_MASK
#define HAL_DMOD_CDVSYCOLC_READABLE    1
#define HAL_DMOD_CDVSYCOLC_WRITABLE    0
#define HAL_DMOD_CDVSYCOLC_SIGNED      0
#define HAL_DMOD_CDVSYCOLC_ADR         0xB0004028

#define HAL_DMOD_CDVAMSYLK_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVAMSYLK_LSB         3
#define HAL_DMOD_CDVAMSYLK_MSB         3
#define HAL_DMOD_CDVAMSYLK_MASK        0x00000008
#define HAL_DMOD_CDVAMSYLK_TYPE        Bool
#define HAL_DMOD_CDVAMSYLK             HAL_DMOD_CDVAMSYLK_MASK
#define HAL_DMOD_CDVAMSYLK_READABLE    1
#define HAL_DMOD_CDVAMSYLK_WRITABLE    0
#define HAL_DMOD_CDVAMSYLK_SIGNED      0
#define HAL_DMOD_CDVAMSYLK_ADR         0xB0004028

#define HAL_DMOD_CDVSYLK_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVSYLK_LSB         2
#define HAL_DMOD_CDVSYLK_MSB         2
#define HAL_DMOD_CDVSYLK_MASK        0x00000004
#define HAL_DMOD_CDVSYLK_TYPE        Bool
#define HAL_DMOD_CDVSYLK             HAL_DMOD_CDVSYLK_MASK
#define HAL_DMOD_CDVSYLK_READABLE    1
#define HAL_DMOD_CDVSYLK_WRITABLE    0
#define HAL_DMOD_CDVSYLK_SIGNED      0
#define HAL_DMOD_CDVSYLK_ADR         0xB0004028

#define HAL_DMOD_CDVLK_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVLK_LSB         1
#define HAL_DMOD_CDVLK_MSB         1
#define HAL_DMOD_CDVLK_MASK        0x00000002
#define HAL_DMOD_CDVLK_TYPE        Bool
#define HAL_DMOD_CDVLK             HAL_DMOD_CDVLK_MASK
#define HAL_DMOD_CDVLK_READABLE    1
#define HAL_DMOD_CDVLK_WRITABLE    0
#define HAL_DMOD_CDVLK_SIGNED      0
#define HAL_DMOD_CDVLK_ADR         0xB0004028

#define HAL_DMOD_CDVFLK_REGISTER    (HAL_DMODREG_MAP->CDVDMDSTA)
#define HAL_DMOD_CDVFLK_LSB         0
#define HAL_DMOD_CDVFLK_MSB         0
#define HAL_DMOD_CDVFLK_MASK        0x00000001
#define HAL_DMOD_CDVFLK_TYPE        Bool
#define HAL_DMOD_CDVFLK             HAL_DMOD_CDVFLK_MASK
#define HAL_DMOD_CDVFLK_READABLE    1
#define HAL_DMOD_CDVFLK_WRITABLE    0
#define HAL_DMOD_CDVFLK_SIGNED      0
#define HAL_DMOD_CDVFLK_ADR         0xB0004028

// Register DMODINTS
#define HAL_DMOD_MMCAPS_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_MMCAPS_LSB         5
#define HAL_DMOD_MMCAPS_MSB         5
#define HAL_DMOD_MMCAPS_MASK        0x00000020
#define HAL_DMOD_MMCAPS_TYPE        Bool
#define HAL_DMOD_MMCAPS             HAL_DMOD_MMCAPS_MASK
#define HAL_DMOD_MMCAPS_READABLE    1
#define HAL_DMOD_MMCAPS_WRITABLE    1
#define HAL_DMOD_MMCAPS_SIGNED      0
#define HAL_DMOD_MMCAPS_ADR         0xB0004040

#define HAL_DMOD_PICCOLRES_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_PICCOLRES_LSB         4
#define HAL_DMOD_PICCOLRES_MSB         4
#define HAL_DMOD_PICCOLRES_MASK        0x00000010
#define HAL_DMOD_PICCOLRES_TYPE        Bool
#define HAL_DMOD_PICCOLRES             HAL_DMOD_PICCOLRES_MASK
#define HAL_DMOD_PICCOLRES_READABLE    1
#define HAL_DMOD_PICCOLRES_WRITABLE    1
#define HAL_DMOD_PICCOLRES_SIGNED      0
#define HAL_DMOD_PICCOLRES_ADR         0xB0004040

#define HAL_DMOD_DMDCOLOLS_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_DMDCOLOLS_LSB         3
#define HAL_DMOD_DMDCOLOLS_MSB         3
#define HAL_DMOD_DMDCOLOLS_MASK        0x00000008
#define HAL_DMOD_DMDCOLOLS_TYPE        Bool
#define HAL_DMOD_DMDCOLOLS             HAL_DMOD_DMDCOLOLS_MASK
#define HAL_DMOD_DMDCOLOLS_READABLE    1
#define HAL_DMOD_DMDCOLOLS_WRITABLE    1
#define HAL_DMOD_DMDCOLOLS_SIGNED      0
#define HAL_DMOD_DMDCOLOLS_ADR         0xB0004040

#define HAL_DMOD_DMDCOLILS_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_DMDCOLILS_LSB         2
#define HAL_DMOD_DMDCOLILS_MSB         2
#define HAL_DMOD_DMDCOLILS_MASK        0x00000004
#define HAL_DMOD_DMDCOLILS_TYPE        Bool
#define HAL_DMOD_DMDCOLILS             HAL_DMOD_DMDCOLILS_MASK
#define HAL_DMOD_DMDCOLILS_READABLE    1
#define HAL_DMOD_DMDCOLILS_WRITABLE    1
#define HAL_DMOD_DMDCOLILS_SIGNED      0
#define HAL_DMOD_DMDCOLILS_ADR         0xB0004040

#define HAL_DMOD_DMODOLKS_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_DMODOLKS_LSB         1
#define HAL_DMOD_DMODOLKS_MSB         1
#define HAL_DMOD_DMODOLKS_MASK        0x00000002
#define HAL_DMOD_DMODOLKS_TYPE        Bool
#define HAL_DMOD_DMODOLKS             HAL_DMOD_DMODOLKS_MASK
#define HAL_DMOD_DMODOLKS_READABLE    1
#define HAL_DMOD_DMODOLKS_WRITABLE    1
#define HAL_DMOD_DMODOLKS_SIGNED      0
#define HAL_DMOD_DMODOLKS_ADR         0xB0004040

#define HAL_DMOD_DMODILKS_REGISTER    (HAL_DMODREG_MAP->DMODINTS)
#define HAL_DMOD_DMODILKS_LSB         0
#define HAL_DMOD_DMODILKS_MSB         0
#define HAL_DMOD_DMODILKS_MASK        0x00000001
#define HAL_DMOD_DMODILKS_TYPE        Bool
#define HAL_DMOD_DMODILKS             HAL_DMOD_DMODILKS_MASK
#define HAL_DMOD_DMODILKS_READABLE    1
#define HAL_DMOD_DMODILKS_WRITABLE    1
#define HAL_DMOD_DMODILKS_SIGNED      0
#define HAL_DMOD_DMODILKS_ADR         0xB0004040

// Register DMODINTE
#define HAL_DMOD_MMCAPE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_MMCAPE_LSB         5
#define HAL_DMOD_MMCAPE_MSB         5
#define HAL_DMOD_MMCAPE_MASK        0x00000020
#define HAL_DMOD_MMCAPE_TYPE        Bool
#define HAL_DMOD_MMCAPE             HAL_DMOD_MMCAPE_MASK
#define HAL_DMOD_MMCAPE_READABLE    1
#define HAL_DMOD_MMCAPE_WRITABLE    1
#define HAL_DMOD_MMCAPE_SIGNED      0
#define HAL_DMOD_MMCAPE_ADR         0xB0004044

#define HAL_DMOD_PICCOLREE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_PICCOLREE_LSB         4
#define HAL_DMOD_PICCOLREE_MSB         4
#define HAL_DMOD_PICCOLREE_MASK        0x00000010
#define HAL_DMOD_PICCOLREE_TYPE        Bool
#define HAL_DMOD_PICCOLREE             HAL_DMOD_PICCOLREE_MASK
#define HAL_DMOD_PICCOLREE_READABLE    1
#define HAL_DMOD_PICCOLREE_WRITABLE    1
#define HAL_DMOD_PICCOLREE_SIGNED      0
#define HAL_DMOD_PICCOLREE_ADR         0xB0004044

#define HAL_DMOD_DMDCOLOLE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_DMDCOLOLE_LSB         3
#define HAL_DMOD_DMDCOLOLE_MSB         3
#define HAL_DMOD_DMDCOLOLE_MASK        0x00000008
#define HAL_DMOD_DMDCOLOLE_TYPE        Bool
#define HAL_DMOD_DMDCOLOLE             HAL_DMOD_DMDCOLOLE_MASK
#define HAL_DMOD_DMDCOLOLE_READABLE    1
#define HAL_DMOD_DMDCOLOLE_WRITABLE    1
#define HAL_DMOD_DMDCOLOLE_SIGNED      0
#define HAL_DMOD_DMDCOLOLE_ADR         0xB0004044

#define HAL_DMOD_DMDCOLILE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_DMDCOLILE_LSB         2
#define HAL_DMOD_DMDCOLILE_MSB         2
#define HAL_DMOD_DMDCOLILE_MASK        0x00000004
#define HAL_DMOD_DMDCOLILE_TYPE        Bool
#define HAL_DMOD_DMDCOLILE             HAL_DMOD_DMDCOLILE_MASK
#define HAL_DMOD_DMDCOLILE_READABLE    1
#define HAL_DMOD_DMDCOLILE_WRITABLE    1
#define HAL_DMOD_DMDCOLILE_SIGNED      0
#define HAL_DMOD_DMDCOLILE_ADR         0xB0004044

#define HAL_DMOD_DMODOLKE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_DMODOLKE_LSB         1
#define HAL_DMOD_DMODOLKE_MSB         1
#define HAL_DMOD_DMODOLKE_MASK        0x00000002
#define HAL_DMOD_DMODOLKE_TYPE        Bool
#define HAL_DMOD_DMODOLKE             HAL_DMOD_DMODOLKE_MASK
#define HAL_DMOD_DMODOLKE_READABLE    1
#define HAL_DMOD_DMODOLKE_WRITABLE    1
#define HAL_DMOD_DMODOLKE_SIGNED      0
#define HAL_DMOD_DMODOLKE_ADR         0xB0004044

#define HAL_DMOD_DMODILKE_REGISTER    (HAL_DMODREG_MAP->DMODINTE)
#define HAL_DMOD_DMODILKE_LSB         0
#define HAL_DMOD_DMODILKE_MSB         0
#define HAL_DMOD_DMODILKE_MASK        0x00000001
#define HAL_DMOD_DMODILKE_TYPE        Bool
#define HAL_DMOD_DMODILKE             HAL_DMOD_DMODILKE_MASK
#define HAL_DMOD_DMODILKE_READABLE    1
#define HAL_DMOD_DMODILKE_WRITABLE    1
#define HAL_DMOD_DMODILKE_SIGNED      0
#define HAL_DMOD_DMODILKE_ADR         0xB0004044

// Register DMODINT
#define HAL_DMOD_MMCAPI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_MMCAPI_LSB         5
#define HAL_DMOD_MMCAPI_MSB         5
#define HAL_DMOD_MMCAPI_MASK        0x00000020
#define HAL_DMOD_MMCAPI_TYPE        Bool
#define HAL_DMOD_MMCAPI             HAL_DMOD_MMCAPI_MASK
#define HAL_DMOD_MMCAPI_READABLE    1
#define HAL_DMOD_MMCAPI_WRITABLE    0
#define HAL_DMOD_MMCAPI_SIGNED      0
#define HAL_DMOD_MMCAPI_ADR         0xB0004048

#define HAL_DMOD_PICCOLREI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_PICCOLREI_LSB         4
#define HAL_DMOD_PICCOLREI_MSB         4
#define HAL_DMOD_PICCOLREI_MASK        0x00000010
#define HAL_DMOD_PICCOLREI_TYPE        Bool
#define HAL_DMOD_PICCOLREI             HAL_DMOD_PICCOLREI_MASK
#define HAL_DMOD_PICCOLREI_READABLE    1
#define HAL_DMOD_PICCOLREI_WRITABLE    0
#define HAL_DMOD_PICCOLREI_SIGNED      0
#define HAL_DMOD_PICCOLREI_ADR         0xB0004048

#define HAL_DMOD_DMDCOLOLI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_DMDCOLOLI_LSB         3
#define HAL_DMOD_DMDCOLOLI_MSB         3
#define HAL_DMOD_DMDCOLOLI_MASK        0x00000008
#define HAL_DMOD_DMDCOLOLI_TYPE        Bool
#define HAL_DMOD_DMDCOLOLI             HAL_DMOD_DMDCOLOLI_MASK
#define HAL_DMOD_DMDCOLOLI_READABLE    1
#define HAL_DMOD_DMDCOLOLI_WRITABLE    0
#define HAL_DMOD_DMDCOLOLI_SIGNED      0
#define HAL_DMOD_DMDCOLOLI_ADR         0xB0004048

#define HAL_DMOD_DMDCOLILI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_DMDCOLILI_LSB         2
#define HAL_DMOD_DMDCOLILI_MSB         2
#define HAL_DMOD_DMDCOLILI_MASK        0x00000004
#define HAL_DMOD_DMDCOLILI_TYPE        Bool
#define HAL_DMOD_DMDCOLILI             HAL_DMOD_DMDCOLILI_MASK
#define HAL_DMOD_DMDCOLILI_READABLE    1
#define HAL_DMOD_DMDCOLILI_WRITABLE    0
#define HAL_DMOD_DMDCOLILI_SIGNED      0
#define HAL_DMOD_DMDCOLILI_ADR         0xB0004048

#define HAL_DMOD_DMODOLKI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_DMODOLKI_LSB         1
#define HAL_DMOD_DMODOLKI_MSB         1
#define HAL_DMOD_DMODOLKI_MASK        0x00000002
#define HAL_DMOD_DMODOLKI_TYPE        Bool
#define HAL_DMOD_DMODOLKI             HAL_DMOD_DMODOLKI_MASK
#define HAL_DMOD_DMODOLKI_READABLE    1
#define HAL_DMOD_DMODOLKI_WRITABLE    0
#define HAL_DMOD_DMODOLKI_SIGNED      0
#define HAL_DMOD_DMODOLKI_ADR         0xB0004048

#define HAL_DMOD_DMODILKI_REGISTER    (HAL_DMODREG_MAP->DMODINT)
#define HAL_DMOD_DMODILKI_LSB         0
#define HAL_DMOD_DMODILKI_MSB         0
#define HAL_DMOD_DMODILKI_MASK        0x00000001
#define HAL_DMOD_DMODILKI_TYPE        Bool
#define HAL_DMOD_DMODILKI             HAL_DMOD_DMODILKI_MASK
#define HAL_DMOD_DMODILKI_READABLE    1
#define HAL_DMOD_DMODILKI_WRITABLE    0
#define HAL_DMOD_DMODILKI_SIGNED      0
#define HAL_DMOD_DMODILKI_ADR         0xB0004048

// Register BDPICDCFG
#define HAL_DMOD_BDPICBUG_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICBUG_LSB         24
#define HAL_DMOD_BDPICBUG_MSB         24
#define HAL_DMOD_BDPICBUG_MASK        0x01000000
#define HAL_DMOD_BDPICBUG_TYPE        Bool
#define HAL_DMOD_BDPICBUG             HAL_DMOD_BDPICBUG_MASK
#define HAL_DMOD_BDPICBUG_READABLE    1
#define HAL_DMOD_BDPICBUG_WRITABLE    1
#define HAL_DMOD_BDPICBUG_SIGNED      0
#define HAL_DMOD_BDPICBUG_ADR         0xB000404C

#define HAL_DMOD_BDPICSYWI_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICSYWI_LSB         20
#define HAL_DMOD_BDPICSYWI_MSB         23
#define HAL_DMOD_BDPICSYWI_MASK        0x00F00000
#define HAL_DMOD_BDPICSYWI_TYPE        UByte
#define HAL_DMOD_BDPICSYWI             HAL_DMOD_BDPICSYWI_MASK
#define HAL_DMOD_BDPICSYWI_READABLE    1
#define HAL_DMOD_BDPICSYWI_WRITABLE    1
#define HAL_DMOD_BDPICSYWI_SIGNED      0
#define HAL_DMOD_BDPICSYWI_ADR         0xB000404C

#define HAL_DMOD_BDPICSYCW_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICSYCW_LSB         16
#define HAL_DMOD_BDPICSYCW_MSB         19
#define HAL_DMOD_BDPICSYCW_MASK        0x000F0000
#define HAL_DMOD_BDPICSYCW_TYPE        UByte
#define HAL_DMOD_BDPICSYCW             HAL_DMOD_BDPICSYCW_MASK
#define HAL_DMOD_BDPICSYCW_READABLE    1
#define HAL_DMOD_BDPICSYCW_WRITABLE    1
#define HAL_DMOD_BDPICSYCW_SIGNED      0
#define HAL_DMOD_BDPICSYCW_ADR         0xB000404C

#define HAL_DMOD_BDPICSYCM_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICSYCM_LSB         12
#define HAL_DMOD_BDPICSYCM_MSB         15
#define HAL_DMOD_BDPICSYCM_MASK        0x0000F000
#define HAL_DMOD_BDPICSYCM_TYPE        UByte
#define HAL_DMOD_BDPICSYCM             HAL_DMOD_BDPICSYCM_MASK
#define HAL_DMOD_BDPICSYCM_READABLE    1
#define HAL_DMOD_BDPICSYCM_WRITABLE    1
#define HAL_DMOD_BDPICSYCM_SIGNED      0
#define HAL_DMOD_BDPICSYCM_ADR         0xB000404C

#define HAL_DMOD_BDPICSCT_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICSCT_LSB         8
#define HAL_DMOD_BDPICSCT_MSB         11
#define HAL_DMOD_BDPICSCT_MASK        0x00000F00
#define HAL_DMOD_BDPICSCT_TYPE        UByte
#define HAL_DMOD_BDPICSCT             HAL_DMOD_BDPICSCT_MASK
#define HAL_DMOD_BDPICSCT_READABLE    1
#define HAL_DMOD_BDPICSCT_WRITABLE    1
#define HAL_DMOD_BDPICSCT_SIGNED      0
#define HAL_DMOD_BDPICSCT_ADR         0xB000404C

#define HAL_DMOD_BDPICRSYL_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICRSYL_LSB         4
#define HAL_DMOD_BDPICRSYL_MSB         4
#define HAL_DMOD_BDPICRSYL_MASK        0x00000010
#define HAL_DMOD_BDPICRSYL_TYPE        Bool
#define HAL_DMOD_BDPICRSYL             HAL_DMOD_BDPICRSYL_MASK
#define HAL_DMOD_BDPICRSYL_READABLE    1
#define HAL_DMOD_BDPICRSYL_WRITABLE    1
#define HAL_DMOD_BDPICRSYL_SIGNED      0
#define HAL_DMOD_BDPICRSYL_ADR         0xB000404C

#define HAL_DMOD_BDPICSYLT_REGISTER    (HAL_DMODREG_MAP->BDPICDCFG)
#define HAL_DMOD_BDPICSYLT_LSB         0
#define HAL_DMOD_BDPICSYLT_MSB         3
#define HAL_DMOD_BDPICSYLT_MASK        0x0000000F
#define HAL_DMOD_BDPICSYLT_TYPE        UByte
#define HAL_DMOD_BDPICSYLT             HAL_DMOD_BDPICSYLT_MASK
#define HAL_DMOD_BDPICSYLT_READABLE    1
#define HAL_DMOD_BDPICSYLT_WRITABLE    1
#define HAL_DMOD_BDPICSYLT_SIGNED      0
#define HAL_DMOD_BDPICSYLT_ADR         0xB000404C

// Register BDPICDMDS
#define HAL_DMOD_BDPICCOLK_REGISTER    (HAL_DMODREG_MAP->BDPICDMDS)
#define HAL_DMOD_BDPICCOLK_LSB         1
#define HAL_DMOD_BDPICCOLK_MSB         1
#define HAL_DMOD_BDPICCOLK_MASK        0x00000002
#define HAL_DMOD_BDPICCOLK_TYPE        Bool
#define HAL_DMOD_BDPICCOLK             HAL_DMOD_BDPICCOLK_MASK
#define HAL_DMOD_BDPICCOLK_READABLE    1
#define HAL_DMOD_BDPICCOLK_WRITABLE    0
#define HAL_DMOD_BDPICCOLK_SIGNED      0
#define HAL_DMOD_BDPICCOLK_ADR         0xB0004050

#define HAL_DMOD_BDPICSYLK_REGISTER    (HAL_DMODREG_MAP->BDPICDMDS)
#define HAL_DMOD_BDPICSYLK_LSB         0
#define HAL_DMOD_BDPICSYLK_MSB         0
#define HAL_DMOD_BDPICSYLK_MASK        0x00000001
#define HAL_DMOD_BDPICSYLK_TYPE        Bool
#define HAL_DMOD_BDPICSYLK             HAL_DMOD_BDPICSYLK_MASK
#define HAL_DMOD_BDPICSYLK_READABLE    1
#define HAL_DMOD_BDPICSYLK_WRITABLE    0
#define HAL_DMOD_BDPICSYLK_SIGNED      0
#define HAL_DMOD_BDPICSYLK_ADR         0xB0004050

// Register DMDERACNT
#define HAL_DMOD_DMDERACNT_REGISTER    (HAL_DMODREG_MAP->DMDERACNT)
#define HAL_DMOD_DMDERACNT_LSB         0
#define HAL_DMOD_DMDERACNT_MSB         15
#define HAL_DMOD_DMDERACNT_MASK        0x0000FFFF
#define HAL_DMOD_DMDERACNT_TYPE        UInt16
#define HAL_DMOD_DMDERACNT             HAL_DMOD_DMDERACNT_MASK
#define HAL_DMOD_DMDERACNT_READABLE    1
#define HAL_DMOD_DMDERACNT_WRITABLE    0
#define HAL_DMOD_DMDERACNT_SIGNED      0
#define HAL_DMOD_DMDERACNT_ADR         0xB0004060

// Register MMCFG
#define HAL_DMOD_MMCAPEN_REGISTER    (HAL_DMODREG_MAP->MMCFG)
#define HAL_DMOD_MMCAPEN_LSB         0
#define HAL_DMOD_MMCAPEN_MSB         0
#define HAL_DMOD_MMCAPEN_MASK        0x00000001
#define HAL_DMOD_MMCAPEN_TYPE        Bool
#define HAL_DMOD_MMCAPEN             HAL_DMOD_MMCAPEN_MASK
#define HAL_DMOD_MMCAPEN_READABLE    1
#define HAL_DMOD_MMCAPEN_WRITABLE    1
#define HAL_DMOD_MMCAPEN_SIGNED      0
#define HAL_DMOD_MMCAPEN_ADR         0xB0004070

// Register MMOFSCFG
#define HAL_DMOD_MMOFFSET_REGISTER    (HAL_DMODREG_MAP->MMOFSCFG)
#define HAL_DMOD_MMOFFSET_LSB         0
#define HAL_DMOD_MMOFFSET_MSB         11
#define HAL_DMOD_MMOFFSET_MASK        0x00000FFF
#define HAL_DMOD_MMOFFSET_TYPE        UInt16
#define HAL_DMOD_MMOFFSET             HAL_DMOD_MMOFFSET_MASK
#define HAL_DMOD_MMOFFSET_READABLE    1
#define HAL_DMOD_MMOFFSET_WRITABLE    1
#define HAL_DMOD_MMOFFSET_SIGNED      0
#define HAL_DMOD_MMOFFSET_ADR         0xB0004074

// Register MMDATA
#define HAL_DMOD_MMWORD_REGISTER    (HAL_DMODREG_MAP->MMDATA)
#define HAL_DMOD_MMWORD_LSB         0
#define HAL_DMOD_MMWORD_MSB         31
#define HAL_DMOD_MMWORD_MASK        0xFFFFFFFF
#define HAL_DMOD_MMWORD_TYPE        UInt32
#define HAL_DMOD_MMWORD             HAL_DMOD_MMWORD_MASK
#define HAL_DMOD_MMWORD_READABLE    1
#define HAL_DMOD_MMWORD_WRITABLE    0
#define HAL_DMOD_MMWORD_SIGNED      0
#define HAL_DMOD_MMWORD_ADR         0xB0004078

// Register DMODDBG

#if (CHIP_REV <= 0xB3)

#define HAL_DMOD_DMDDBGSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGSEL_LSB         0
#define HAL_DMOD_DMDDBGSEL_MSB         5
#define HAL_DMOD_DMDDBGSEL_MASK        0x0000003F
#define HAL_DMOD_DMDDBGSEL_TYPE        halDMOD_DemodSignalSel_t
#define HAL_DMOD_DMDDBGSEL             HAL_DMOD_DMDDBGSEL_MASK
#define HAL_DMOD_DMDDBGSEL_READABLE    1
#define HAL_DMOD_DMDDBGSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGSEL_SIGNED      0
#define HAL_DMOD_DMDDBGSEL_ADR         0xB0004100

#endif // #if (CHIP_REV <= 0xB3)

#if (CHIP_REV >= 0xC0)

#define HAL_DMOD_DMDDBGFSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGFSEL_LSB         16
#define HAL_DMOD_DMDDBGFSEL_MSB         19
#define HAL_DMOD_DMDDBGFSEL_MASK        0x000F0000
#define HAL_DMOD_DMDDBGFSEL_TYPE        halDMOD_DemodSignalFSel_t
#define HAL_DMOD_DMDDBGFSEL             HAL_DMOD_DMDDBGFSEL_MASK
#define HAL_DMOD_DMDDBGFSEL_READABLE    1
#define HAL_DMOD_DMDDBGFSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGFSEL_SIGNED      0
#define HAL_DMOD_DMDDBGFSEL_ADR         0xB0004100

#define HAL_DMOD_DMDDBGHSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGHSEL_LSB         12
#define HAL_DMOD_DMDDBGHSEL_MSB         15
#define HAL_DMOD_DMDDBGHSEL_MASK        0x0000F000
#define HAL_DMOD_DMDDBGHSEL_TYPE        halDMOD_DemodSignalHSel_t
#define HAL_DMOD_DMDDBGHSEL             HAL_DMOD_DMDDBGHSEL_MASK
#define HAL_DMOD_DMDDBGHSEL_READABLE    1
#define HAL_DMOD_DMDDBGHSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGHSEL_SIGNED      0
#define HAL_DMOD_DMDDBGHSEL_ADR         0xB0004100

#define HAL_DMOD_DMDDBGMSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGMSEL_LSB         8
#define HAL_DMOD_DMDDBGMSEL_MSB         11
#define HAL_DMOD_DMDDBGMSEL_MASK        0x00000F00
#define HAL_DMOD_DMDDBGMSEL_TYPE        halDMOD_DemodSignalMSel_t
#define HAL_DMOD_DMDDBGMSEL             HAL_DMOD_DMDDBGMSEL_MASK
#define HAL_DMOD_DMDDBGMSEL_READABLE    1
#define HAL_DMOD_DMDDBGMSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGMSEL_SIGNED      0
#define HAL_DMOD_DMDDBGMSEL_ADR         0xB0004100

#define HAL_DMOD_DMDDBGLSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGLSEL_LSB         4
#define HAL_DMOD_DMDDBGLSEL_MSB         7
#define HAL_DMOD_DMDDBGLSEL_MASK        0x000000F0
#define HAL_DMOD_DMDDBGLSEL_TYPE        halDMOD_DemodSignalLSel_t
#define HAL_DMOD_DMDDBGLSEL             HAL_DMOD_DMDDBGLSEL_MASK
#define HAL_DMOD_DMDDBGLSEL_READABLE    1
#define HAL_DMOD_DMDDBGLSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGLSEL_SIGNED      0
#define HAL_DMOD_DMDDBGLSEL_ADR         0xB0004100

#define HAL_DMOD_DMDDBGSEL_REGISTER    (HAL_DMODREG_MAP->DMODDBG)
#define HAL_DMOD_DMDDBGSEL_LSB         0
#define HAL_DMOD_DMDDBGSEL_MSB         3
#define HAL_DMOD_DMDDBGSEL_MASK        0x0000000F
#define HAL_DMOD_DMDDBGSEL_TYPE        halDMOD_DemodSignalSel_t
#define HAL_DMOD_DMDDBGSEL             HAL_DMOD_DMDDBGSEL_MASK
#define HAL_DMOD_DMDDBGSEL_READABLE    1
#define HAL_DMOD_DMDDBGSEL_WRITABLE    1
#define HAL_DMOD_DMDDBGSEL_SIGNED      0
#define HAL_DMOD_DMDDBGSEL_ADR         0xB0004100

#endif // #if (CHIP_REV >= 0xC0)

// Register DMDSPARE

#if (CHIP_REV == 0xC0)

#define HAL_DMOD_DMDSPARE_REGISTER    (HAL_DMODREG_MAP->DMDSPARE)
#define HAL_DMOD_DMDSPARE_LSB         0
#define HAL_DMOD_DMDSPARE_MSB         7
#define HAL_DMOD_DMDSPARE_MASK        0x000000FF
#define HAL_DMOD_DMDSPARE_TYPE        UByte
#define HAL_DMOD_DMDSPARE             HAL_DMOD_DMDSPARE_MASK
#define HAL_DMOD_DMDSPARE_READABLE    1
#define HAL_DMOD_DMDSPARE_WRITABLE    1
#define HAL_DMOD_DMDSPARE_SIGNED      0
#define HAL_DMOD_DMDSPARE_ADR         0xB0004104

#endif // #if (CHIP_REV == 0xC0)

#if (CHIP_REV >= 0xC1)

#define HAL_DMOD_DMDSPARE_REGISTER    (HAL_DMODREG_MAP->DMDSPARE)
#define HAL_DMOD_DMDSPARE_LSB         2
#define HAL_DMOD_DMDSPARE_MSB         7
#define HAL_DMOD_DMDSPARE_MASK        0x000000FC
#define HAL_DMOD_DMDSPARE_TYPE        UByte
#define HAL_DMOD_DMDSPARE             HAL_DMOD_DMDSPARE_MASK
#define HAL_DMOD_DMDSPARE_READABLE    1
#define HAL_DMOD_DMDSPARE_WRITABLE    1
#define HAL_DMOD_DMDSPARE_SIGNED      0
#define HAL_DMOD_DMDSPARE_ADR         0xB0004104

#define HAL_DMOD_FSLIBDIS_REGISTER    (HAL_DMODREG_MAP->DMDSPARE)
#define HAL_DMOD_FSLIBDIS_LSB         1
#define HAL_DMOD_FSLIBDIS_MSB         1
#define HAL_DMOD_FSLIBDIS_MASK        0x00000002
#define HAL_DMOD_FSLIBDIS_TYPE        Bool
#define HAL_DMOD_FSLIBDIS             HAL_DMOD_FSLIBDIS_MASK
#define HAL_DMOD_FSLIBDIS_READABLE    1
#define HAL_DMOD_FSLIBDIS_WRITABLE    1
#define HAL_DMOD_FSLIBDIS_SIGNED      0
#define HAL_DMOD_FSLIBDIS_ADR         0xB0004104

#define HAL_DMOD_FSLIBENRAM_REGISTER    (HAL_DMODREG_MAP->DMDSPARE)
#define HAL_DMOD_FSLIBENRAM_LSB         0
#define HAL_DMOD_FSLIBENRAM_MSB         0
#define HAL_DMOD_FSLIBENRAM_MASK        0x00000001
#define HAL_DMOD_FSLIBENRAM_TYPE        Bool
#define HAL_DMOD_FSLIBENRAM             HAL_DMOD_FSLIBENRAM_MASK
#define HAL_DMOD_FSLIBENRAM_READABLE    1
#define HAL_DMOD_FSLIBENRAM_WRITABLE    1
#define HAL_DMOD_FSLIBENRAM_SIGNED      0
#define HAL_DMOD_FSLIBENRAM_ADR         0xB0004104

#endif // #if (CHIP_REV >= 0xC1)

// Enumerations
typedef enum
{
	halDMOD_RELinkingCutByCtrlBlock = 0,    // The linking area is cut out of the datastream based on the wobble signal (Normal RE operation)
	halDMOD_RELinkingCutByDemod     = 1     // The linking area is cut out of the datastream by the demodulator, based on decoder signals (For test purposes)
} halDMOD_RELinkingCut_t;

#if (CHIP_REV <= 0xB3)

typedef enum
{
    halDMOD_SlowConfOutLock     = 0,    // Slow out of lock decrement, confidence -1 on every mismatch.
    halDMOD_FastConfOutLock     = 1,    // Fast out of lock decrement, confidence -2 on every mismatch.
    halDMOD_FasterConfOutLock   = 2     // Faster out of lock decrement, confidence -4 on every mismatch.
} halDMOD_CDDVDConfOutLockSpeed_t;

typedef enum
{
	halDMOD_BDMode        = 0,
	halDMOD_PICMode       = 1,
	halDMOD_HDDVDMode     = 2,
	halDMOD_CDDVDMode     = 3,
	halDMOD_InterfaceMode = 4 
} halDMOD_DemodSignalSel_t;

#endif // #if (CHIP_REV <= 0xB3)

#if (CHIP_REV >= 0xC0)

typedef enum
{
	halDMOD_SlowConfOutLock   = 0,    // Slow out of lock decrement, confidence -1 on every mismatch.
	halDMOD_FasterConfOutLock = 1,    // Faster out of lock decrement, confidence -2 on every mismatch.
	halDMOD_FastConfOutLock   = 2     // Fast out of lock decrement, confidence -4 on every mismatch.
} halDMOD_CDDVDConfOutLockSpeed_t;

typedef enum
{
	halDMOD_FOURTH_BUS = 0     // Select the fourth bus to different operation signals.
} halDMOD_DemodSignalFSel_t;

typedef enum
{
	halDMOD_THIRD_BUS = 0     // Select the third bus to different operation signals.
} halDMOD_DemodSignalHSel_t;

typedef enum
{
	halDMOD_SECOND_BUS = 0     // Select the second bus to different operation signals.
} halDMOD_DemodSignalMSel_t;

typedef enum
{
	halDMOD_FIRST_BUS = 0     // Select the first bus to different operation signals.
} halDMOD_DemodSignalLSel_t;

typedef enum
{
	halDMOD_DISABLE       = 0,
	halDMOD_BDMode        = 1,
	halDMOD_PICMode       = 2,
	halDMOD_HDDVDMode     = 3,
	halDMOD_CDDVDMode     = 4,
	halDMOD_InterfaceMode = 5,
	halDMOD_InputMode     = 6 
} halDMOD_DemodSignalSel_t;

#endif // #if (CHIP_REV >= 0xC0)

#endif /* __REG_DEMOD_H__ */

