/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_opc.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the OPC core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_OPC_H__
#define __REG_OPC_H__

// Core register map
#define HAL_OPC_VERSION 7.29
#define HAL_OPC_BaseAddress 0x10000C00
#define HAL_OPCREG_MAP ((struct halOPCReg_Map*) (void *) HAL_OPC_BaseAddress)

#if (CHIP_REV <= 0xB3)

__packed struct halOPCReg_Map
{
	HAL_Reg8  OPCMODE;                        //00000000
	HAL_Reg8  ReservedBlk0[2];                //00000001
	HAL_Reg8  OPCCONF;                        //00000003
	HAL_Reg8  OPCINT;                         //00000004
	HAL_Reg8  OPCINTEN;                       //00000005
	HAL_Reg8  OPCSTART;                       //00000006
	HAL_Reg8  OPCSIZE;                        //00000007
	HAL_Reg8  OPCDEC;                         //00000008
	HAL_Reg8  OPCAVG;                         //00000009
	HAL_Reg8  ADCSEL0;                        //0000000A
	HAL_Reg8  ADCSEL1;                        //0000000B
	HAL_Reg16 SAMPFREQL;                      //0000000C
	HAL_Reg8  OPCTRAMT;                       //0000000E
	HAL_Reg8  OPCTRCNT;                       //0000000F
	HAL_Reg8  OPCTCCNT;                       //00000010
	HAL_Reg8  OPCTDCNT;                       //00000011
	HAL_Reg8  OPCSPARE;                       //00000012
};

#endif // #if (CHIP_REV <= 0xB3)

#if (CHIP_REV >= 0xC0)

__packed struct halOPCReg_Map
{
	HAL_Reg8  OPCMODE;                        //00000000
	HAL_Reg8  ReservedBlk0[1];                //00000001
	HAL_Reg8  OPCCONF;                        //00000002
	HAL_Reg8  OPCCONF2;                       //00000003
	HAL_Reg8  OPCINT;                         //00000004
	HAL_Reg8  OPCINTEN;                       //00000005
	HAL_Reg8  OPCSTART;                       //00000006
	HAL_Reg8  OPCSIZE;                        //00000007
	HAL_Reg8  OPCDEC;                         //00000008
	HAL_Reg8  OPCAVG;                         //00000009
	HAL_Reg8  ADCSEL0;                        //0000000A
	HAL_Reg8  ADCSEL1;                        //0000000B
	HAL_Reg16 SAMPFREQL;                      //0000000C
	HAL_Reg8  OPCTRAMT;                       //0000000E
	HAL_Reg8  OPCTRCNT;                       //0000000F
	HAL_Reg8  OPCTCCNT;                       //00000010
	HAL_Reg8  OPCTDCNT;                       //00000011
	HAL_Reg16 SAMPDELYL;                      //00000012
	HAL_Reg8  ReservedBlk1[11];               //00000014
	HAL_Reg8  AFENUMSET;                      //0000001F
	HAL_Reg8  AFEADDR0;                       //00000020
	HAL_Reg8  AFEADDR1;                       //00000021
	HAL_Reg8  AFEADDR2;                       //00000022
	HAL_Reg8  AFEADDR3;                       //00000023
	HAL_Reg8  AFEADDR4;                       //00000024
	HAL_Reg8  AFEADDR5;                       //00000025
	HAL_Reg8  AFEADDR6;                       //00000026
	HAL_Reg8  AFEADDR7;                       //00000027
	HAL_Reg8  AFEADDR8;                       //00000028
	HAL_Reg8  AFEADDR9;                       //00000029
	HAL_Reg8  AFEADDRA;                       //0000002A
	HAL_Reg8  AFEADDRB;                       //0000002B
	HAL_Reg8  AFEADDRC;                       //0000002C
	HAL_Reg8  AFEADDRD;                       //0000002D
	HAL_Reg8  AFEADDRE;                       //0000002E
	HAL_Reg8  AFEADDRF;                       //0000002F
	HAL_Reg8  AFEDATA0;                       //00000030
	HAL_Reg8  AFEDATA1;                       //00000031
	HAL_Reg8  AFEDATA2;                       //00000032
	HAL_Reg8  AFEDATA3;                       //00000033
	HAL_Reg8  AFEDATA4;                       //00000034
	HAL_Reg8  AFEDATA5;                       //00000035
	HAL_Reg8  AFEDATA6;                       //00000036
	HAL_Reg8  AFEDATA7;                       //00000037
	HAL_Reg8  AFEDATA8;                       //00000038
	HAL_Reg8  AFEDATA9;                       //00000039
	HAL_Reg8  AFEDATAA;                       //0000003A
	HAL_Reg8  AFEDATAB;                       //0000003B
	HAL_Reg8  AFEDATAC;                       //0000003C
	HAL_Reg8  AFEDATAD;                       //0000003D
	HAL_Reg8  AFEDATAE;                       //0000003E
	HAL_Reg8  AFEDATAF;                       //0000003F
};

#endif // #if (CHIP_REV >= 0xC0)

// Register OPCMODE
#define HAL_OPC_WSTRT_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_WSTRT_LSB         7
#define HAL_OPC_WSTRT_MSB         7
#define HAL_OPC_WSTRT_MASK        0x00000080
#define HAL_OPC_WSTRT_TYPE        Bool
#define HAL_OPC_WSTRT             HAL_OPC_WSTRT_MASK
#define HAL_OPC_WSTRT_READABLE    1
#define HAL_OPC_WSTRT_WRITABLE    1
#define HAL_OPC_WSTRT_SIGNED      0
#define HAL_OPC_WSTRT_ADR         0x10000C00

#define HAL_OPC_RSTRT_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_RSTRT_LSB         6
#define HAL_OPC_RSTRT_MSB         6
#define HAL_OPC_RSTRT_MASK        0x00000040
#define HAL_OPC_RSTRT_TYPE        Bool
#define HAL_OPC_RSTRT             HAL_OPC_RSTRT_MASK
#define HAL_OPC_RSTRT_READABLE    1
#define HAL_OPC_RSTRT_WRITABLE    1
#define HAL_OPC_RSTRT_SIGNED      0
#define HAL_OPC_RSTRT_ADR         0x10000C00

#define HAL_OPC_WBLSTM_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_WBLSTM_LSB         5
#define HAL_OPC_WBLSTM_MSB         5
#define HAL_OPC_WBLSTM_MASK        0x00000020
#define HAL_OPC_WBLSTM_TYPE        Bool
#define HAL_OPC_WBLSTM             HAL_OPC_WBLSTM_MASK
#define HAL_OPC_WBLSTM_READABLE    1
#define HAL_OPC_WBLSTM_WRITABLE    1
#define HAL_OPC_WBLSTM_SIGNED      0
#define HAL_OPC_WBLSTM_ADR         0x10000C00

#if (CHIP_REV >= 0xC0)

#define HAL_OPC_OPCWGDNEN_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_OPCWGDNEN_LSB         2
#define HAL_OPC_OPCWGDNEN_MSB         2
#define HAL_OPC_OPCWGDNEN_MASK        0x00000004
#define HAL_OPC_OPCWGDNEN_TYPE        Bool
#define HAL_OPC_OPCWGDNEN             HAL_OPC_OPCWGDNEN_MASK
#define HAL_OPC_OPCWGDNEN_READABLE    1
#define HAL_OPC_OPCWGDNEN_WRITABLE    1
#define HAL_OPC_OPCWGDNEN_SIGNED      0
#define HAL_OPC_OPCWGDNEN_ADR         0x10000C00

#define HAL_OPC_OPCWGUPEN_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_OPCWGUPEN_LSB         1
#define HAL_OPC_OPCWGUPEN_MSB         1
#define HAL_OPC_OPCWGUPEN_MASK        0x00000002
#define HAL_OPC_OPCWGUPEN_TYPE        Bool
#define HAL_OPC_OPCWGUPEN             HAL_OPC_OPCWGUPEN_MASK
#define HAL_OPC_OPCWGUPEN_READABLE    1
#define HAL_OPC_OPCWGUPEN_WRITABLE    1
#define HAL_OPC_OPCWGUPEN_SIGNED      0
#define HAL_OPC_OPCWGUPEN_ADR         0x10000C00

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_OPC_OPCTEST_REGISTER    (HAL_OPCREG_MAP->OPCMODE)
#define HAL_OPC_OPCTEST_LSB         0
#define HAL_OPC_OPCTEST_MSB         0
#define HAL_OPC_OPCTEST_MASK        0x00000001
#define HAL_OPC_OPCTEST_TYPE        Bool
#define HAL_OPC_OPCTEST             HAL_OPC_OPCTEST_MASK
#define HAL_OPC_OPCTEST_READABLE    1
#define HAL_OPC_OPCTEST_WRITABLE    1
#define HAL_OPC_OPCTEST_SIGNED      0
#define HAL_OPC_OPCTEST_ADR         0x10000C00

// Register OPCCONF

#if (CHIP_REV <= 0xB3)

#define HAL_OPC_OPCDSRC_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCDSRC_LSB         7
#define HAL_OPC_OPCDSRC_MSB         7
#define HAL_OPC_OPCDSRC_MASK        0x00000080
#define HAL_OPC_OPCDSRC_TYPE        halOPC_OPCDSRC_t
#define HAL_OPC_OPCDSRC             HAL_OPC_OPCDSRC_MASK
#define HAL_OPC_OPCDSRC_READABLE    1
#define HAL_OPC_OPCDSRC_WRITABLE    1
#define HAL_OPC_OPCDSRC_SIGNED      0
#define HAL_OPC_OPCDSRC_ADR         0x10000C03

#define HAL_OPC_OPCCIRC_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCCIRC_LSB         6
#define HAL_OPC_OPCCIRC_MSB         6
#define HAL_OPC_OPCCIRC_MASK        0x00000040
#define HAL_OPC_OPCCIRC_TYPE        Bool
#define HAL_OPC_OPCCIRC             HAL_OPC_OPCCIRC_MASK
#define HAL_OPC_OPCCIRC_READABLE    1
#define HAL_OPC_OPCCIRC_WRITABLE    1
#define HAL_OPC_OPCCIRC_SIGNED      0
#define HAL_OPC_OPCCIRC_ADR         0x10000C03

#define HAL_OPC_OPCGATE_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCGATE_LSB         5
#define HAL_OPC_OPCGATE_MSB         5
#define HAL_OPC_OPCGATE_MASK        0x00000020
#define HAL_OPC_OPCGATE_TYPE        halOPC_OPCGate_t
#define HAL_OPC_OPCGATE             HAL_OPC_OPCGATE_MASK
#define HAL_OPC_OPCGATE_READABLE    1
#define HAL_OPC_OPCGATE_WRITABLE    1
#define HAL_OPC_OPCGATE_SIGNED      0
#define HAL_OPC_OPCGATE_ADR         0x10000C03

#define HAL_OPC_OPCMIO_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCMIO_LSB         4
#define HAL_OPC_OPCMIO_MSB         4
#define HAL_OPC_OPCMIO_MASK        0x00000010
#define HAL_OPC_OPCMIO_TYPE        halOPC_OPCMIO_t
#define HAL_OPC_OPCMIO             HAL_OPC_OPCMIO_MASK
#define HAL_OPC_OPCMIO_READABLE    1
#define HAL_OPC_OPCMIO_WRITABLE    1
#define HAL_OPC_OPCMIO_SIGNED      0
#define HAL_OPC_OPCMIO_ADR         0x10000C03

#define HAL_OPC_SAMPNUM_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_SAMPNUM_LSB         0
#define HAL_OPC_SAMPNUM_MSB         3
#define HAL_OPC_SAMPNUM_MASK        0x0000000F
#define HAL_OPC_SAMPNUM_TYPE        halOPC_AOPCSampNum_t
#define HAL_OPC_SAMPNUM             HAL_OPC_SAMPNUM_MASK
#define HAL_OPC_SAMPNUM_READABLE    1
#define HAL_OPC_SAMPNUM_WRITABLE    1
#define HAL_OPC_SAMPNUM_SIGNED      0
#define HAL_OPC_SAMPNUM_ADR         0x10000C03

#endif // #if (CHIP_REV <= 0xB3)

#if (CHIP_REV >= 0xC0)

#define HAL_OPC_OPCDSRC_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCDSRC_LSB         7
#define HAL_OPC_OPCDSRC_MSB         7
#define HAL_OPC_OPCDSRC_MASK        0x00000080
#define HAL_OPC_OPCDSRC_TYPE        halOPC_OPCDSRC_t
#define HAL_OPC_OPCDSRC             HAL_OPC_OPCDSRC_MASK
#define HAL_OPC_OPCDSRC_READABLE    1
#define HAL_OPC_OPCDSRC_WRITABLE    1
#define HAL_OPC_OPCDSRC_SIGNED      0
#define HAL_OPC_OPCDSRC_ADR         0x10000C02

#define HAL_OPC_OPCCIRC_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCCIRC_LSB         6
#define HAL_OPC_OPCCIRC_MSB         6
#define HAL_OPC_OPCCIRC_MASK        0x00000040
#define HAL_OPC_OPCCIRC_TYPE        Bool
#define HAL_OPC_OPCCIRC             HAL_OPC_OPCCIRC_MASK
#define HAL_OPC_OPCCIRC_READABLE    1
#define HAL_OPC_OPCCIRC_WRITABLE    1
#define HAL_OPC_OPCCIRC_SIGNED      0
#define HAL_OPC_OPCCIRC_ADR         0x10000C02

#define HAL_OPC_OPCGATE_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCGATE_LSB         5
#define HAL_OPC_OPCGATE_MSB         5
#define HAL_OPC_OPCGATE_MASK        0x00000020
#define HAL_OPC_OPCGATE_TYPE        halOPC_OPCGate_t
#define HAL_OPC_OPCGATE             HAL_OPC_OPCGATE_MASK
#define HAL_OPC_OPCGATE_READABLE    1
#define HAL_OPC_OPCGATE_WRITABLE    1
#define HAL_OPC_OPCGATE_SIGNED      0
#define HAL_OPC_OPCGATE_ADR         0x10000C02

#define HAL_OPC_OPCMIO_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_OPCMIO_LSB         4
#define HAL_OPC_OPCMIO_MSB         4
#define HAL_OPC_OPCMIO_MASK        0x00000010
#define HAL_OPC_OPCMIO_TYPE        halOPC_OPCMIO_t
#define HAL_OPC_OPCMIO             HAL_OPC_OPCMIO_MASK
#define HAL_OPC_OPCMIO_READABLE    1
#define HAL_OPC_OPCMIO_WRITABLE    1
#define HAL_OPC_OPCMIO_SIGNED      0
#define HAL_OPC_OPCMIO_ADR         0x10000C02

#define HAL_OPC_SAMPNUM_REGISTER    (HAL_OPCREG_MAP->OPCCONF)
#define HAL_OPC_SAMPNUM_LSB         0
#define HAL_OPC_SAMPNUM_MSB         3
#define HAL_OPC_SAMPNUM_MASK        0x0000000F
#define HAL_OPC_SAMPNUM_TYPE        halOPC_AOPCSampNum_t
#define HAL_OPC_SAMPNUM             HAL_OPC_SAMPNUM_MASK
#define HAL_OPC_SAMPNUM_READABLE    1
#define HAL_OPC_SAMPNUM_WRITABLE    1
#define HAL_OPC_SAMPNUM_SIGNED      0
#define HAL_OPC_SAMPNUM_ADR         0x10000C02

// Register OPCCONF2
#define HAL_OPC_OPCDBGSEL_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_OPCDBGSEL_LSB         5
#define HAL_OPC_OPCDBGSEL_MSB         5
#define HAL_OPC_OPCDBGSEL_MASK        0x00000020
#define HAL_OPC_OPCDBGSEL_TYPE        Bool
#define HAL_OPC_OPCDBGSEL             HAL_OPC_OPCDBGSEL_MASK
#define HAL_OPC_OPCDBGSEL_READABLE    1
#define HAL_OPC_OPCDBGSEL_WRITABLE    1
#define HAL_OPC_OPCDBGSEL_SIGNED      0
#define HAL_OPC_OPCDBGSEL_ADR         0x10000C03

#define HAL_OPC_OPCDBGEN_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_OPCDBGEN_LSB         4
#define HAL_OPC_OPCDBGEN_MSB         4
#define HAL_OPC_OPCDBGEN_MASK        0x00000010
#define HAL_OPC_OPCDBGEN_TYPE        Bool
#define HAL_OPC_OPCDBGEN             HAL_OPC_OPCDBGEN_MASK
#define HAL_OPC_OPCDBGEN_READABLE    1
#define HAL_OPC_OPCDBGEN_WRITABLE    1
#define HAL_OPC_OPCDBGEN_SIGNED      0
#define HAL_OPC_OPCDBGEN_ADR         0x10000C03

#define HAL_OPC_FORCESTOP_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_FORCESTOP_LSB         3
#define HAL_OPC_FORCESTOP_MSB         3
#define HAL_OPC_FORCESTOP_MASK        0x00000008
#define HAL_OPC_FORCESTOP_TYPE        Bool
#define HAL_OPC_FORCESTOP             HAL_OPC_FORCESTOP_MASK
#define HAL_OPC_FORCESTOP_READABLE    1
#define HAL_OPC_FORCESTOP_WRITABLE    1
#define HAL_OPC_FORCESTOP_SIGNED      0
#define HAL_OPC_FORCESTOP_ADR         0x10000C03

#define HAL_OPC_INFTRAMT_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_INFTRAMT_LSB         2
#define HAL_OPC_INFTRAMT_MSB         2
#define HAL_OPC_INFTRAMT_MASK        0x00000004
#define HAL_OPC_INFTRAMT_TYPE        Bool
#define HAL_OPC_INFTRAMT             HAL_OPC_INFTRAMT_MASK
#define HAL_OPC_INFTRAMT_READABLE    1
#define HAL_OPC_INFTRAMT_WRITABLE    1
#define HAL_OPC_INFTRAMT_SIGNED      0
#define HAL_OPC_INFTRAMT_ADR         0x10000C03

#define HAL_OPC_OPCDELYEN_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_OPCDELYEN_LSB         1
#define HAL_OPC_OPCDELYEN_MSB         1
#define HAL_OPC_OPCDELYEN_MASK        0x00000002
#define HAL_OPC_OPCDELYEN_TYPE        Bool
#define HAL_OPC_OPCDELYEN             HAL_OPC_OPCDELYEN_MASK
#define HAL_OPC_OPCDELYEN_READABLE    1
#define HAL_OPC_OPCDELYEN_WRITABLE    1
#define HAL_OPC_OPCDELYEN_SIGNED      0
#define HAL_OPC_OPCDELYEN_ADR         0x10000C03

#define HAL_OPC_OPCTCTOTR_REGISTER    (HAL_OPCREG_MAP->OPCCONF2)
#define HAL_OPC_OPCTCTOTR_LSB         0
#define HAL_OPC_OPCTCTOTR_MSB         0
#define HAL_OPC_OPCTCTOTR_MASK        0x00000001
#define HAL_OPC_OPCTCTOTR_TYPE        Bool
#define HAL_OPC_OPCTCTOTR             HAL_OPC_OPCTCTOTR_MASK
#define HAL_OPC_OPCTCTOTR_READABLE    1
#define HAL_OPC_OPCTCTOTR_WRITABLE    1
#define HAL_OPC_OPCTCTOTR_SIGNED      0
#define HAL_OPC_OPCTCTOTR_ADR         0x10000C03

#endif // #if (CHIP_REV >= 0xC0)

// Register OPCINT
#define HAL_OPC_OPCRATE_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_OPCRATE_LSB         5
#define HAL_OPC_OPCRATE_MSB         5
#define HAL_OPC_OPCRATE_MASK        0x00000020
#define HAL_OPC_OPCRATE_TYPE        Bool
#define HAL_OPC_OPCRATE             HAL_OPC_OPCRATE_MASK
#define HAL_OPC_OPCRATE_READABLE    1
#define HAL_OPC_OPCRATE_WRITABLE    1
#define HAL_OPC_OPCRATE_SIGNED      0
#define HAL_OPC_OPCRATE_ADR         0x10000C04

#define HAL_OPC_SMPOVL_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_SMPOVL_LSB         4
#define HAL_OPC_SMPOVL_MSB         4
#define HAL_OPC_SMPOVL_MASK        0x00000010
#define HAL_OPC_SMPOVL_TYPE        Bool
#define HAL_OPC_SMPOVL             HAL_OPC_SMPOVL_MASK
#define HAL_OPC_SMPOVL_READABLE    1
#define HAL_OPC_SMPOVL_WRITABLE    1
#define HAL_OPC_SMPOVL_SIGNED      0
#define HAL_OPC_SMPOVL_ADR         0x10000C04

#define HAL_OPC_OPCTR_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_OPCTR_LSB         3
#define HAL_OPC_OPCTR_MSB         3
#define HAL_OPC_OPCTR_MASK        0x00000008
#define HAL_OPC_OPCTR_TYPE        Bool
#define HAL_OPC_OPCTR             HAL_OPC_OPCTR_MASK
#define HAL_OPC_OPCTR_READABLE    1
#define HAL_OPC_OPCTR_WRITABLE    1
#define HAL_OPC_OPCTR_SIGNED      0
#define HAL_OPC_OPCTR_ADR         0x10000C04

#define HAL_OPC_OPCTC_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_OPCTC_LSB         2
#define HAL_OPC_OPCTC_MSB         2
#define HAL_OPC_OPCTC_MASK        0x00000004
#define HAL_OPC_OPCTC_TYPE        Bool
#define HAL_OPC_OPCTC             HAL_OPC_OPCTC_MASK
#define HAL_OPC_OPCTC_READABLE    1
#define HAL_OPC_OPCTC_WRITABLE    1
#define HAL_OPC_OPCTC_SIGNED      0
#define HAL_OPC_OPCTC_ADR         0x10000C04

#define HAL_OPC_OPCTD_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_OPCTD_LSB         1
#define HAL_OPC_OPCTD_MSB         1
#define HAL_OPC_OPCTD_MASK        0x00000002
#define HAL_OPC_OPCTD_TYPE        Bool
#define HAL_OPC_OPCTD             HAL_OPC_OPCTD_MASK
#define HAL_OPC_OPCTD_READABLE    1
#define HAL_OPC_OPCTD_WRITABLE    1
#define HAL_OPC_OPCTD_SIGNED      0
#define HAL_OPC_OPCTD_ADR         0x10000C04

#define HAL_OPC_OPCSTP_REGISTER    (HAL_OPCREG_MAP->OPCINT)
#define HAL_OPC_OPCSTP_LSB         0
#define HAL_OPC_OPCSTP_MSB         0
#define HAL_OPC_OPCSTP_MASK        0x00000001
#define HAL_OPC_OPCSTP_TYPE        Bool
#define HAL_OPC_OPCSTP             HAL_OPC_OPCSTP_MASK
#define HAL_OPC_OPCSTP_READABLE    1
#define HAL_OPC_OPCSTP_WRITABLE    1
#define HAL_OPC_OPCSTP_SIGNED      0
#define HAL_OPC_OPCSTP_ADR         0x10000C04

// Register OPCINTEN
#define HAL_OPC_OPCRATEN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_OPCRATEN_LSB         5
#define HAL_OPC_OPCRATEN_MSB         5
#define HAL_OPC_OPCRATEN_MASK        0x00000020
#define HAL_OPC_OPCRATEN_TYPE        Bool
#define HAL_OPC_OPCRATEN             HAL_OPC_OPCRATEN_MASK
#define HAL_OPC_OPCRATEN_READABLE    1
#define HAL_OPC_OPCRATEN_WRITABLE    1
#define HAL_OPC_OPCRATEN_SIGNED      0
#define HAL_OPC_OPCRATEN_ADR         0x10000C05

#define HAL_OPC_SMPOVLEN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_SMPOVLEN_LSB         4
#define HAL_OPC_SMPOVLEN_MSB         4
#define HAL_OPC_SMPOVLEN_MASK        0x00000010
#define HAL_OPC_SMPOVLEN_TYPE        Bool
#define HAL_OPC_SMPOVLEN             HAL_OPC_SMPOVLEN_MASK
#define HAL_OPC_SMPOVLEN_READABLE    1
#define HAL_OPC_SMPOVLEN_WRITABLE    1
#define HAL_OPC_SMPOVLEN_SIGNED      0
#define HAL_OPC_SMPOVLEN_ADR         0x10000C05

#define HAL_OPC_OPCTREN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_OPCTREN_LSB         3
#define HAL_OPC_OPCTREN_MSB         3
#define HAL_OPC_OPCTREN_MASK        0x00000008
#define HAL_OPC_OPCTREN_TYPE        Bool
#define HAL_OPC_OPCTREN             HAL_OPC_OPCTREN_MASK
#define HAL_OPC_OPCTREN_READABLE    1
#define HAL_OPC_OPCTREN_WRITABLE    1
#define HAL_OPC_OPCTREN_SIGNED      0
#define HAL_OPC_OPCTREN_ADR         0x10000C05

#define HAL_OPC_OPCTCEN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_OPCTCEN_LSB         2
#define HAL_OPC_OPCTCEN_MSB         2
#define HAL_OPC_OPCTCEN_MASK        0x00000004
#define HAL_OPC_OPCTCEN_TYPE        Bool
#define HAL_OPC_OPCTCEN             HAL_OPC_OPCTCEN_MASK
#define HAL_OPC_OPCTCEN_READABLE    1
#define HAL_OPC_OPCTCEN_WRITABLE    1
#define HAL_OPC_OPCTCEN_SIGNED      0
#define HAL_OPC_OPCTCEN_ADR         0x10000C05

#define HAL_OPC_OPCTDEN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_OPCTDEN_LSB         1
#define HAL_OPC_OPCTDEN_MSB         1
#define HAL_OPC_OPCTDEN_MASK        0x00000002
#define HAL_OPC_OPCTDEN_TYPE        Bool
#define HAL_OPC_OPCTDEN             HAL_OPC_OPCTDEN_MASK
#define HAL_OPC_OPCTDEN_READABLE    1
#define HAL_OPC_OPCTDEN_WRITABLE    1
#define HAL_OPC_OPCTDEN_SIGNED      0
#define HAL_OPC_OPCTDEN_ADR         0x10000C05

#define HAL_OPC_OPCSTPEN_REGISTER    (HAL_OPCREG_MAP->OPCINTEN)
#define HAL_OPC_OPCSTPEN_LSB         0
#define HAL_OPC_OPCSTPEN_MSB         0
#define HAL_OPC_OPCSTPEN_MASK        0x00000001
#define HAL_OPC_OPCSTPEN_TYPE        Bool
#define HAL_OPC_OPCSTPEN             HAL_OPC_OPCSTPEN_MASK
#define HAL_OPC_OPCSTPEN_READABLE    1
#define HAL_OPC_OPCSTPEN_WRITABLE    1
#define HAL_OPC_OPCSTPEN_SIGNED      0
#define HAL_OPC_OPCSTPEN_ADR         0x10000C05

// Register OPCSTART
#define HAL_OPC_OPCSTART_REGISTER    (HAL_OPCREG_MAP->OPCSTART)
#define HAL_OPC_OPCSTART_LSB         0
#define HAL_OPC_OPCSTART_MSB         7
#define HAL_OPC_OPCSTART_MASK        0x000000FF
#define HAL_OPC_OPCSTART_TYPE        UByte
#define HAL_OPC_OPCSTART             HAL_OPC_OPCSTART_MASK
#define HAL_OPC_OPCSTART_READABLE    1
#define HAL_OPC_OPCSTART_WRITABLE    1
#define HAL_OPC_OPCSTART_SIGNED      0
#define HAL_OPC_OPCSTART_ADR         0x10000C06

// Register OPCSIZE
#define HAL_OPC_OPCSIZE_REGISTER    (HAL_OPCREG_MAP->OPCSIZE)
#define HAL_OPC_OPCSIZE_LSB         0
#define HAL_OPC_OPCSIZE_MSB         7
#define HAL_OPC_OPCSIZE_MASK        0x000000FF
#define HAL_OPC_OPCSIZE_TYPE        UByte
#define HAL_OPC_OPCSIZE             HAL_OPC_OPCSIZE_MASK
#define HAL_OPC_OPCSIZE_READABLE    1
#define HAL_OPC_OPCSIZE_WRITABLE    1
#define HAL_OPC_OPCSIZE_SIGNED      0
#define HAL_OPC_OPCSIZE_ADR         0x10000C07

// Register OPCDEC
#define HAL_OPC_OPCDEC_REGISTER    (HAL_OPCREG_MAP->OPCDEC)
#define HAL_OPC_OPCDEC_LSB         0
#define HAL_OPC_OPCDEC_MSB         7
#define HAL_OPC_OPCDEC_MASK        0x000000FF
#define HAL_OPC_OPCDEC_TYPE        UByte
#define HAL_OPC_OPCDEC             HAL_OPC_OPCDEC_MASK
#define HAL_OPC_OPCDEC_READABLE    1
#define HAL_OPC_OPCDEC_WRITABLE    1
#define HAL_OPC_OPCDEC_SIGNED      0
#define HAL_OPC_OPCDEC_ADR         0x10000C08

// Register OPCAVG
#define HAL_OPC_OPCAVG_REGISTER    (HAL_OPCREG_MAP->OPCAVG)
#define HAL_OPC_OPCAVG_LSB         0
#define HAL_OPC_OPCAVG_MSB         2
#define HAL_OPC_OPCAVG_MASK        0x00000007
#define HAL_OPC_OPCAVG_TYPE        halOPC_AOPCAvgSamp_t
#define HAL_OPC_OPCAVG             HAL_OPC_OPCAVG_MASK
#define HAL_OPC_OPCAVG_READABLE    1
#define HAL_OPC_OPCAVG_WRITABLE    1
#define HAL_OPC_OPCAVG_SIGNED      0
#define HAL_OPC_OPCAVG_ADR         0x10000C09

// Register ADCSEL0
#define HAL_OPC_ADCSLOT1_REGISTER    (HAL_OPCREG_MAP->ADCSEL0)
#define HAL_OPC_ADCSLOT1_LSB         4
#define HAL_OPC_ADCSLOT1_MSB         7
#define HAL_OPC_ADCSLOT1_MASK        0x000000F0
#define HAL_OPC_ADCSLOT1_TYPE        halOPC_AOPCADCSampS1_t
#define HAL_OPC_ADCSLOT1             HAL_OPC_ADCSLOT1_MASK
#define HAL_OPC_ADCSLOT1_READABLE    1
#define HAL_OPC_ADCSLOT1_WRITABLE    1
#define HAL_OPC_ADCSLOT1_SIGNED      0
#define HAL_OPC_ADCSLOT1_ADR         0x10000C0A

#define HAL_OPC_ADCSLOT0_REGISTER    (HAL_OPCREG_MAP->ADCSEL0)
#define HAL_OPC_ADCSLOT0_LSB         0
#define HAL_OPC_ADCSLOT0_MSB         3
#define HAL_OPC_ADCSLOT0_MASK        0x0000000F
#define HAL_OPC_ADCSLOT0_TYPE        halOPC_AOPCADCSampS0_t
#define HAL_OPC_ADCSLOT0             HAL_OPC_ADCSLOT0_MASK
#define HAL_OPC_ADCSLOT0_READABLE    1
#define HAL_OPC_ADCSLOT0_WRITABLE    1
#define HAL_OPC_ADCSLOT0_SIGNED      0
#define HAL_OPC_ADCSLOT0_ADR         0x10000C0A

// Register ADCSEL1
#define HAL_OPC_ADCSLOT2_REGISTER    (HAL_OPCREG_MAP->ADCSEL1)
#define HAL_OPC_ADCSLOT2_LSB         0
#define HAL_OPC_ADCSLOT2_MSB         3
#define HAL_OPC_ADCSLOT2_MASK        0x0000000F
#define HAL_OPC_ADCSLOT2_TYPE        halOPC_AOPCADCSampS2_t
#define HAL_OPC_ADCSLOT2             HAL_OPC_ADCSLOT2_MASK
#define HAL_OPC_ADCSLOT2_READABLE    1
#define HAL_OPC_ADCSLOT2_WRITABLE    1
#define HAL_OPC_ADCSLOT2_SIGNED      0
#define HAL_OPC_ADCSLOT2_ADR         0x10000C0B

// Registers SAMPFREQL/SAMPFREQH
#define HAL_OPC_SAMPFREQ_REGISTER    (HAL_OPCREG_MAP->SAMPFREQL)
#define HAL_OPC_SAMPFREQ_LSB         0
#define HAL_OPC_SAMPFREQ_MSB         15
#define HAL_OPC_SAMPFREQ_MASK        0x0000FFFF
#define HAL_OPC_SAMPFREQ_TYPE        UInt16
#define HAL_OPC_SAMPFREQ             HAL_OPC_SAMPFREQ_MASK
#define HAL_OPC_SAMPFREQ_READABLE    1
#define HAL_OPC_SAMPFREQ_WRITABLE    1
#define HAL_OPC_SAMPFREQ_SIGNED      0
#define HAL_OPC_SAMPFREQ_ADR         0x10000C0C

// Register OPCTRAMT
#define HAL_OPC_OPCTRAMT_REGISTER    (HAL_OPCREG_MAP->OPCTRAMT)
#define HAL_OPC_OPCTRAMT_LSB         0
#define HAL_OPC_OPCTRAMT_MSB         5
#define HAL_OPC_OPCTRAMT_MASK        0x0000003F
#define HAL_OPC_OPCTRAMT_TYPE        UByte
#define HAL_OPC_OPCTRAMT             HAL_OPC_OPCTRAMT_MASK
#define HAL_OPC_OPCTRAMT_READABLE    1
#define HAL_OPC_OPCTRAMT_WRITABLE    1
#define HAL_OPC_OPCTRAMT_SIGNED      0
#define HAL_OPC_OPCTRAMT_ADR         0x10000C0E

// Register OPCTRCNT
#define HAL_OPC_OPCTRCNT_REGISTER    (HAL_OPCREG_MAP->OPCTRCNT)
#define HAL_OPC_OPCTRCNT_LSB         0
#define HAL_OPC_OPCTRCNT_MSB         7
#define HAL_OPC_OPCTRCNT_MASK        0x000000FF
#define HAL_OPC_OPCTRCNT_TYPE        UByte
#define HAL_OPC_OPCTRCNT             HAL_OPC_OPCTRCNT_MASK
#define HAL_OPC_OPCTRCNT_READABLE    1
#define HAL_OPC_OPCTRCNT_WRITABLE    1
#define HAL_OPC_OPCTRCNT_SIGNED      0
#define HAL_OPC_OPCTRCNT_ADR         0x10000C0F

// Register OPCTCCNT
#define HAL_OPC_OPCTCCNT_REGISTER    (HAL_OPCREG_MAP->OPCTCCNT)
#define HAL_OPC_OPCTCCNT_LSB         0
#define HAL_OPC_OPCTCCNT_MSB         7
#define HAL_OPC_OPCTCCNT_MASK        0x000000FF
#define HAL_OPC_OPCTCCNT_TYPE        UByte
#define HAL_OPC_OPCTCCNT             HAL_OPC_OPCTCCNT_MASK
#define HAL_OPC_OPCTCCNT_READABLE    1
#define HAL_OPC_OPCTCCNT_WRITABLE    1
#define HAL_OPC_OPCTCCNT_SIGNED      0
#define HAL_OPC_OPCTCCNT_ADR         0x10000C10

// Register OPCTDCNT
#define HAL_OPC_OPCTDCNT_REGISTER    (HAL_OPCREG_MAP->OPCTDCNT)
#define HAL_OPC_OPCTDCNT_LSB         0
#define HAL_OPC_OPCTDCNT_MSB         7
#define HAL_OPC_OPCTDCNT_MASK        0x000000FF
#define HAL_OPC_OPCTDCNT_TYPE        UByte
#define HAL_OPC_OPCTDCNT             HAL_OPC_OPCTDCNT_MASK
#define HAL_OPC_OPCTDCNT_READABLE    1
#define HAL_OPC_OPCTDCNT_WRITABLE    1
#define HAL_OPC_OPCTDCNT_SIGNED      0
#define HAL_OPC_OPCTDCNT_ADR         0x10000C11

// Register OPCSPARE

#if (CHIP_REV <= 0xB2)

#define HAL_OPC_BDSRAMDEN_REGISTER    (HAL_OPCREG_MAP->OPCSPARE)
#define HAL_OPC_BDSRAMDEN_LSB         0
#define HAL_OPC_BDSRAMDEN_MSB         0
#define HAL_OPC_BDSRAMDEN_MASK        0x00000001
#define HAL_OPC_BDSRAMDEN_TYPE        Bool
#define HAL_OPC_BDSRAMDEN             HAL_OPC_BDSRAMDEN_MASK
#define HAL_OPC_BDSRAMDEN_READABLE    1
#define HAL_OPC_BDSRAMDEN_WRITABLE    1
#define HAL_OPC_BDSRAMDEN_SIGNED      0
#define HAL_OPC_BDSRAMDEN_ADR         0x10000C12

#endif // #if (CHIP_REV <= 0xB2)

#if (CHIP_REV <= 0xB3)

#define HAL_OPC_BDSRAMDIS_REGISTER    (HAL_OPCREG_MAP->OPCSPARE)
#define HAL_OPC_BDSRAMDIS_LSB         0
#define HAL_OPC_BDSRAMDIS_MSB         0
#define HAL_OPC_BDSRAMDIS_MASK        0x00000001
#define HAL_OPC_BDSRAMDIS_TYPE        Bool
#define HAL_OPC_BDSRAMDIS             HAL_OPC_BDSRAMDIS_MASK
#define HAL_OPC_BDSRAMDIS_READABLE    1
#define HAL_OPC_BDSRAMDIS_WRITABLE    1
#define HAL_OPC_BDSRAMDIS_SIGNED      0
#define HAL_OPC_BDSRAMDIS_ADR         0x10000C12

#endif // #if (CHIP_REV <= 0xB3)

#if (CHIP_REV >= 0xC0)

// Registers SAMPDELYL/SAMPDELYH
#define HAL_OPC_SAMPDELY_REGISTER    (HAL_OPCREG_MAP->SAMPDELYL)
#define HAL_OPC_SAMPDELY_LSB         0
#define HAL_OPC_SAMPDELY_MSB         15
#define HAL_OPC_SAMPDELY_MASK        0x0000FFFF
#define HAL_OPC_SAMPDELY_TYPE        UInt16
#define HAL_OPC_SAMPDELY             HAL_OPC_SAMPDELY_MASK
#define HAL_OPC_SAMPDELY_READABLE    1
#define HAL_OPC_SAMPDELY_WRITABLE    1
#define HAL_OPC_SAMPDELY_SIGNED      0
#define HAL_OPC_SAMPDELY_ADR         0x10000C12

// Register AFENUMSET
#define HAL_OPC_AFENUMSET_REGISTER    (HAL_OPCREG_MAP->AFENUMSET)
#define HAL_OPC_AFENUMSET_LSB         0
#define HAL_OPC_AFENUMSET_MSB         4
#define HAL_OPC_AFENUMSET_MASK        0x0000001F
#define HAL_OPC_AFENUMSET_TYPE        UByte
#define HAL_OPC_AFENUMSET             HAL_OPC_AFENUMSET_MASK
#define HAL_OPC_AFENUMSET_READABLE    1
#define HAL_OPC_AFENUMSET_WRITABLE    1
#define HAL_OPC_AFENUMSET_SIGNED      0
#define HAL_OPC_AFENUMSET_ADR         0x10000C1F

// Register AFEADDR0
#define HAL_OPC_AFEADDR0_REGISTER    (HAL_OPCREG_MAP->AFEADDR0)
#define HAL_OPC_AFEADDR0_LSB         0
#define HAL_OPC_AFEADDR0_MSB         7
#define HAL_OPC_AFEADDR0_MASK        0x000000FF
#define HAL_OPC_AFEADDR0_TYPE        UByte
#define HAL_OPC_AFEADDR0             HAL_OPC_AFEADDR0_MASK
#define HAL_OPC_AFEADDR0_READABLE    1
#define HAL_OPC_AFEADDR0_WRITABLE    1
#define HAL_OPC_AFEADDR0_SIGNED      0
#define HAL_OPC_AFEADDR0_ADR         0x10000C20

// Register AFEADDR1
#define HAL_OPC_AFEADDR1_REGISTER    (HAL_OPCREG_MAP->AFEADDR1)
#define HAL_OPC_AFEADDR1_LSB         0
#define HAL_OPC_AFEADDR1_MSB         7
#define HAL_OPC_AFEADDR1_MASK        0x000000FF
#define HAL_OPC_AFEADDR1_TYPE        UByte
#define HAL_OPC_AFEADDR1             HAL_OPC_AFEADDR1_MASK
#define HAL_OPC_AFEADDR1_READABLE    1
#define HAL_OPC_AFEADDR1_WRITABLE    1
#define HAL_OPC_AFEADDR1_SIGNED      0
#define HAL_OPC_AFEADDR1_ADR         0x10000C21

// Register AFEADDR2
#define HAL_OPC_AFEADDR2_REGISTER    (HAL_OPCREG_MAP->AFEADDR2)
#define HAL_OPC_AFEADDR2_LSB         0
#define HAL_OPC_AFEADDR2_MSB         7
#define HAL_OPC_AFEADDR2_MASK        0x000000FF
#define HAL_OPC_AFEADDR2_TYPE        UByte
#define HAL_OPC_AFEADDR2             HAL_OPC_AFEADDR2_MASK
#define HAL_OPC_AFEADDR2_READABLE    1
#define HAL_OPC_AFEADDR2_WRITABLE    1
#define HAL_OPC_AFEADDR2_SIGNED      0
#define HAL_OPC_AFEADDR2_ADR         0x10000C22

// Register AFEADDR3
#define HAL_OPC_AFEADDR3_REGISTER    (HAL_OPCREG_MAP->AFEADDR3)
#define HAL_OPC_AFEADDR3_LSB         0
#define HAL_OPC_AFEADDR3_MSB         7
#define HAL_OPC_AFEADDR3_MASK        0x000000FF
#define HAL_OPC_AFEADDR3_TYPE        UByte
#define HAL_OPC_AFEADDR3             HAL_OPC_AFEADDR3_MASK
#define HAL_OPC_AFEADDR3_READABLE    1
#define HAL_OPC_AFEADDR3_WRITABLE    1
#define HAL_OPC_AFEADDR3_SIGNED      0
#define HAL_OPC_AFEADDR3_ADR         0x10000C23

// Register AFEADDR4
#define HAL_OPC_AFEADDR4_REGISTER    (HAL_OPCREG_MAP->AFEADDR4)
#define HAL_OPC_AFEADDR4_LSB         0
#define HAL_OPC_AFEADDR4_MSB         7
#define HAL_OPC_AFEADDR4_MASK        0x000000FF
#define HAL_OPC_AFEADDR4_TYPE        UByte
#define HAL_OPC_AFEADDR4             HAL_OPC_AFEADDR4_MASK
#define HAL_OPC_AFEADDR4_READABLE    1
#define HAL_OPC_AFEADDR4_WRITABLE    1
#define HAL_OPC_AFEADDR4_SIGNED      0
#define HAL_OPC_AFEADDR4_ADR         0x10000C24

// Register AFEADDR5
#define HAL_OPC_AFEADDR5_REGISTER    (HAL_OPCREG_MAP->AFEADDR5)
#define HAL_OPC_AFEADDR5_LSB         0
#define HAL_OPC_AFEADDR5_MSB         7
#define HAL_OPC_AFEADDR5_MASK        0x000000FF
#define HAL_OPC_AFEADDR5_TYPE        UByte
#define HAL_OPC_AFEADDR5             HAL_OPC_AFEADDR5_MASK
#define HAL_OPC_AFEADDR5_READABLE    1
#define HAL_OPC_AFEADDR5_WRITABLE    1
#define HAL_OPC_AFEADDR5_SIGNED      0
#define HAL_OPC_AFEADDR5_ADR         0x10000C25

// Register AFEADDR6
#define HAL_OPC_AFEADDR6_REGISTER    (HAL_OPCREG_MAP->AFEADDR6)
#define HAL_OPC_AFEADDR6_LSB         0
#define HAL_OPC_AFEADDR6_MSB         7
#define HAL_OPC_AFEADDR6_MASK        0x000000FF
#define HAL_OPC_AFEADDR6_TYPE        UByte
#define HAL_OPC_AFEADDR6             HAL_OPC_AFEADDR6_MASK
#define HAL_OPC_AFEADDR6_READABLE    1
#define HAL_OPC_AFEADDR6_WRITABLE    1
#define HAL_OPC_AFEADDR6_SIGNED      0
#define HAL_OPC_AFEADDR6_ADR         0x10000C26

// Register AFEADDR7
#define HAL_OPC_AFEADDR7_REGISTER    (HAL_OPCREG_MAP->AFEADDR7)
#define HAL_OPC_AFEADDR7_LSB         0
#define HAL_OPC_AFEADDR7_MSB         7
#define HAL_OPC_AFEADDR7_MASK        0x000000FF
#define HAL_OPC_AFEADDR7_TYPE        UByte
#define HAL_OPC_AFEADDR7             HAL_OPC_AFEADDR7_MASK
#define HAL_OPC_AFEADDR7_READABLE    1
#define HAL_OPC_AFEADDR7_WRITABLE    1
#define HAL_OPC_AFEADDR7_SIGNED      0
#define HAL_OPC_AFEADDR7_ADR         0x10000C27

// Register AFEADDR8
#define HAL_OPC_AFEADDR8_REGISTER    (HAL_OPCREG_MAP->AFEADDR8)
#define HAL_OPC_AFEADDR8_LSB         0
#define HAL_OPC_AFEADDR8_MSB         7
#define HAL_OPC_AFEADDR8_MASK        0x000000FF
#define HAL_OPC_AFEADDR8_TYPE        UByte
#define HAL_OPC_AFEADDR8             HAL_OPC_AFEADDR8_MASK
#define HAL_OPC_AFEADDR8_READABLE    1
#define HAL_OPC_AFEADDR8_WRITABLE    1
#define HAL_OPC_AFEADDR8_SIGNED      0
#define HAL_OPC_AFEADDR8_ADR         0x10000C28

// Register AFEADDR9
#define HAL_OPC_AFEADDR9_REGISTER    (HAL_OPCREG_MAP->AFEADDR9)
#define HAL_OPC_AFEADDR9_LSB         0
#define HAL_OPC_AFEADDR9_MSB         7
#define HAL_OPC_AFEADDR9_MASK        0x000000FF
#define HAL_OPC_AFEADDR9_TYPE        UByte
#define HAL_OPC_AFEADDR9             HAL_OPC_AFEADDR9_MASK
#define HAL_OPC_AFEADDR9_READABLE    1
#define HAL_OPC_AFEADDR9_WRITABLE    1
#define HAL_OPC_AFEADDR9_SIGNED      0
#define HAL_OPC_AFEADDR9_ADR         0x10000C29

// Register AFEADDRA
#define HAL_OPC_AFEADDRA_REGISTER    (HAL_OPCREG_MAP->AFEADDRA)
#define HAL_OPC_AFEADDRA_LSB         0
#define HAL_OPC_AFEADDRA_MSB         7
#define HAL_OPC_AFEADDRA_MASK        0x000000FF
#define HAL_OPC_AFEADDRA_TYPE        UByte
#define HAL_OPC_AFEADDRA             HAL_OPC_AFEADDRA_MASK
#define HAL_OPC_AFEADDRA_READABLE    1
#define HAL_OPC_AFEADDRA_WRITABLE    1
#define HAL_OPC_AFEADDRA_SIGNED      0
#define HAL_OPC_AFEADDRA_ADR         0x10000C2A

// Register AFEADDRB
#define HAL_OPC_AFEADDRB_REGISTER    (HAL_OPCREG_MAP->AFEADDRB)
#define HAL_OPC_AFEADDRB_LSB         0
#define HAL_OPC_AFEADDRB_MSB         7
#define HAL_OPC_AFEADDRB_MASK        0x000000FF
#define HAL_OPC_AFEADDRB_TYPE        UByte
#define HAL_OPC_AFEADDRB             HAL_OPC_AFEADDRB_MASK
#define HAL_OPC_AFEADDRB_READABLE    1
#define HAL_OPC_AFEADDRB_WRITABLE    1
#define HAL_OPC_AFEADDRB_SIGNED      0
#define HAL_OPC_AFEADDRB_ADR         0x10000C2B

// Register AFEADDRC
#define HAL_OPC_AFEADDRC_REGISTER    (HAL_OPCREG_MAP->AFEADDRC)
#define HAL_OPC_AFEADDRC_LSB         0
#define HAL_OPC_AFEADDRC_MSB         7
#define HAL_OPC_AFEADDRC_MASK        0x000000FF
#define HAL_OPC_AFEADDRC_TYPE        UByte
#define HAL_OPC_AFEADDRC             HAL_OPC_AFEADDRC_MASK
#define HAL_OPC_AFEADDRC_READABLE    1
#define HAL_OPC_AFEADDRC_WRITABLE    1
#define HAL_OPC_AFEADDRC_SIGNED      0
#define HAL_OPC_AFEADDRC_ADR         0x10000C2C

// Register AFEADDRD
#define HAL_OPC_AFEADDRD_REGISTER    (HAL_OPCREG_MAP->AFEADDRD)
#define HAL_OPC_AFEADDRD_LSB         0
#define HAL_OPC_AFEADDRD_MSB         7
#define HAL_OPC_AFEADDRD_MASK        0x000000FF
#define HAL_OPC_AFEADDRD_TYPE        UByte
#define HAL_OPC_AFEADDRD             HAL_OPC_AFEADDRD_MASK
#define HAL_OPC_AFEADDRD_READABLE    1
#define HAL_OPC_AFEADDRD_WRITABLE    1
#define HAL_OPC_AFEADDRD_SIGNED      0
#define HAL_OPC_AFEADDRD_ADR         0x10000C2D

// Register AFEADDRE
#define HAL_OPC_AFEADDRE_REGISTER    (HAL_OPCREG_MAP->AFEADDRE)
#define HAL_OPC_AFEADDRE_LSB         0
#define HAL_OPC_AFEADDRE_MSB         7
#define HAL_OPC_AFEADDRE_MASK        0x000000FF
#define HAL_OPC_AFEADDRE_TYPE        UByte
#define HAL_OPC_AFEADDRE             HAL_OPC_AFEADDRE_MASK
#define HAL_OPC_AFEADDRE_READABLE    1
#define HAL_OPC_AFEADDRE_WRITABLE    1
#define HAL_OPC_AFEADDRE_SIGNED      0
#define HAL_OPC_AFEADDRE_ADR         0x10000C2E

// Register AFEADDRF
#define HAL_OPC_AFEADDRF_REGISTER    (HAL_OPCREG_MAP->AFEADDRF)
#define HAL_OPC_AFEADDRF_LSB         0
#define HAL_OPC_AFEADDRF_MSB         7
#define HAL_OPC_AFEADDRF_MASK        0x000000FF
#define HAL_OPC_AFEADDRF_TYPE        UByte
#define HAL_OPC_AFEADDRF             HAL_OPC_AFEADDRF_MASK
#define HAL_OPC_AFEADDRF_READABLE    1
#define HAL_OPC_AFEADDRF_WRITABLE    1
#define HAL_OPC_AFEADDRF_SIGNED      0
#define HAL_OPC_AFEADDRF_ADR         0x10000C2F

// Register AFEDATA0
#define HAL_OPC_AFEDATA0_REGISTER    (HAL_OPCREG_MAP->AFEDATA0)
#define HAL_OPC_AFEDATA0_LSB         0
#define HAL_OPC_AFEDATA0_MSB         7
#define HAL_OPC_AFEDATA0_MASK        0x000000FF
#define HAL_OPC_AFEDATA0_TYPE        UByte
#define HAL_OPC_AFEDATA0             HAL_OPC_AFEDATA0_MASK
#define HAL_OPC_AFEDATA0_READABLE    1
#define HAL_OPC_AFEDATA0_WRITABLE    1
#define HAL_OPC_AFEDATA0_SIGNED      0
#define HAL_OPC_AFEDATA0_ADR         0x10000C30

// Register AFEDATA1
#define HAL_OPC_AFEDATA1_REGISTER    (HAL_OPCREG_MAP->AFEDATA1)
#define HAL_OPC_AFEDATA1_LSB         0
#define HAL_OPC_AFEDATA1_MSB         7
#define HAL_OPC_AFEDATA1_MASK        0x000000FF
#define HAL_OPC_AFEDATA1_TYPE        UByte
#define HAL_OPC_AFEDATA1             HAL_OPC_AFEDATA1_MASK
#define HAL_OPC_AFEDATA1_READABLE    1
#define HAL_OPC_AFEDATA1_WRITABLE    1
#define HAL_OPC_AFEDATA1_SIGNED      0
#define HAL_OPC_AFEDATA1_ADR         0x10000C31

// Register AFEDATA2
#define HAL_OPC_AFEDATA2_REGISTER    (HAL_OPCREG_MAP->AFEDATA2)
#define HAL_OPC_AFEDATA2_LSB         0
#define HAL_OPC_AFEDATA2_MSB         7
#define HAL_OPC_AFEDATA2_MASK        0x000000FF
#define HAL_OPC_AFEDATA2_TYPE        UByte
#define HAL_OPC_AFEDATA2             HAL_OPC_AFEDATA2_MASK
#define HAL_OPC_AFEDATA2_READABLE    1
#define HAL_OPC_AFEDATA2_WRITABLE    1
#define HAL_OPC_AFEDATA2_SIGNED      0
#define HAL_OPC_AFEDATA2_ADR         0x10000C32

// Register AFEDATA3
#define HAL_OPC_AFEDATA3_REGISTER    (HAL_OPCREG_MAP->AFEDATA3)
#define HAL_OPC_AFEDATA3_LSB         0
#define HAL_OPC_AFEDATA3_MSB         7
#define HAL_OPC_AFEDATA3_MASK        0x000000FF
#define HAL_OPC_AFEDATA3_TYPE        UByte
#define HAL_OPC_AFEDATA3             HAL_OPC_AFEDATA3_MASK
#define HAL_OPC_AFEDATA3_READABLE    1
#define HAL_OPC_AFEDATA3_WRITABLE    1
#define HAL_OPC_AFEDATA3_SIGNED      0
#define HAL_OPC_AFEDATA3_ADR         0x10000C33

// Register AFEDATA4
#define HAL_OPC_AFEDATA4_REGISTER    (HAL_OPCREG_MAP->AFEDATA4)
#define HAL_OPC_AFEDATA4_LSB         0
#define HAL_OPC_AFEDATA4_MSB         7
#define HAL_OPC_AFEDATA4_MASK        0x000000FF
#define HAL_OPC_AFEDATA4_TYPE        UByte
#define HAL_OPC_AFEDATA4             HAL_OPC_AFEDATA4_MASK
#define HAL_OPC_AFEDATA4_READABLE    1
#define HAL_OPC_AFEDATA4_WRITABLE    1
#define HAL_OPC_AFEDATA4_SIGNED      0
#define HAL_OPC_AFEDATA4_ADR         0x10000C34

// Register AFEDATA5
#define HAL_OPC_AFEDATA5_REGISTER    (HAL_OPCREG_MAP->AFEDATA5)
#define HAL_OPC_AFEDATA5_LSB         0
#define HAL_OPC_AFEDATA5_MSB         7
#define HAL_OPC_AFEDATA5_MASK        0x000000FF
#define HAL_OPC_AFEDATA5_TYPE        UByte
#define HAL_OPC_AFEDATA5             HAL_OPC_AFEDATA5_MASK
#define HAL_OPC_AFEDATA5_READABLE    1
#define HAL_OPC_AFEDATA5_WRITABLE    1
#define HAL_OPC_AFEDATA5_SIGNED      0
#define HAL_OPC_AFEDATA5_ADR         0x10000C35

// Register AFEDATA6
#define HAL_OPC_AFEDATA6_REGISTER    (HAL_OPCREG_MAP->AFEDATA6)
#define HAL_OPC_AFEDATA6_LSB         0
#define HAL_OPC_AFEDATA6_MSB         7
#define HAL_OPC_AFEDATA6_MASK        0x000000FF
#define HAL_OPC_AFEDATA6_TYPE        UByte
#define HAL_OPC_AFEDATA6             HAL_OPC_AFEDATA6_MASK
#define HAL_OPC_AFEDATA6_READABLE    1
#define HAL_OPC_AFEDATA6_WRITABLE    1
#define HAL_OPC_AFEDATA6_SIGNED      0
#define HAL_OPC_AFEDATA6_ADR         0x10000C36

// Register AFEDATA7
#define HAL_OPC_AFEDATA7_REGISTER    (HAL_OPCREG_MAP->AFEDATA7)
#define HAL_OPC_AFEDATA7_LSB         0
#define HAL_OPC_AFEDATA7_MSB         7
#define HAL_OPC_AFEDATA7_MASK        0x000000FF
#define HAL_OPC_AFEDATA7_TYPE        UByte
#define HAL_OPC_AFEDATA7             HAL_OPC_AFEDATA7_MASK
#define HAL_OPC_AFEDATA7_READABLE    1
#define HAL_OPC_AFEDATA7_WRITABLE    1
#define HAL_OPC_AFEDATA7_SIGNED      0
#define HAL_OPC_AFEDATA7_ADR         0x10000C37

// Register AFEDATA8
#define HAL_OPC_AFEDATA8_REGISTER    (HAL_OPCREG_MAP->AFEDATA8)
#define HAL_OPC_AFEDATA8_LSB         0
#define HAL_OPC_AFEDATA8_MSB         7
#define HAL_OPC_AFEDATA8_MASK        0x000000FF
#define HAL_OPC_AFEDATA8_TYPE        UByte
#define HAL_OPC_AFEDATA8             HAL_OPC_AFEDATA8_MASK
#define HAL_OPC_AFEDATA8_READABLE    1
#define HAL_OPC_AFEDATA8_WRITABLE    1
#define HAL_OPC_AFEDATA8_SIGNED      0
#define HAL_OPC_AFEDATA8_ADR         0x10000C38

// Register AFEDATA9
#define HAL_OPC_AFEDATA9_REGISTER    (HAL_OPCREG_MAP->AFEDATA9)
#define HAL_OPC_AFEDATA9_LSB         0
#define HAL_OPC_AFEDATA9_MSB         7
#define HAL_OPC_AFEDATA9_MASK        0x000000FF
#define HAL_OPC_AFEDATA9_TYPE        UByte
#define HAL_OPC_AFEDATA9             HAL_OPC_AFEDATA9_MASK
#define HAL_OPC_AFEDATA9_READABLE    1
#define HAL_OPC_AFEDATA9_WRITABLE    1
#define HAL_OPC_AFEDATA9_SIGNED      0
#define HAL_OPC_AFEDATA9_ADR         0x10000C39

// Register AFEDATAA
#define HAL_OPC_AFEDATAA_REGISTER    (HAL_OPCREG_MAP->AFEDATAA)
#define HAL_OPC_AFEDATAA_LSB         0
#define HAL_OPC_AFEDATAA_MSB         7
#define HAL_OPC_AFEDATAA_MASK        0x000000FF
#define HAL_OPC_AFEDATAA_TYPE        UByte
#define HAL_OPC_AFEDATAA             HAL_OPC_AFEDATAA_MASK
#define HAL_OPC_AFEDATAA_READABLE    1
#define HAL_OPC_AFEDATAA_WRITABLE    1
#define HAL_OPC_AFEDATAA_SIGNED      0
#define HAL_OPC_AFEDATAA_ADR         0x10000C3A

// Register AFEDATAB
#define HAL_OPC_AFEDATAB_REGISTER    (HAL_OPCREG_MAP->AFEDATAB)
#define HAL_OPC_AFEDATAB_LSB         0
#define HAL_OPC_AFEDATAB_MSB         7
#define HAL_OPC_AFEDATAB_MASK        0x000000FF
#define HAL_OPC_AFEDATAB_TYPE        UByte
#define HAL_OPC_AFEDATAB             HAL_OPC_AFEDATAB_MASK
#define HAL_OPC_AFEDATAB_READABLE    1
#define HAL_OPC_AFEDATAB_WRITABLE    1
#define HAL_OPC_AFEDATAB_SIGNED      0
#define HAL_OPC_AFEDATAB_ADR         0x10000C3B

// Register AFEDATAC
#define HAL_OPC_AFEDATAC_REGISTER    (HAL_OPCREG_MAP->AFEDATAC)
#define HAL_OPC_AFEDATAC_LSB         0
#define HAL_OPC_AFEDATAC_MSB         7
#define HAL_OPC_AFEDATAC_MASK        0x000000FF
#define HAL_OPC_AFEDATAC_TYPE        UByte
#define HAL_OPC_AFEDATAC             HAL_OPC_AFEDATAC_MASK
#define HAL_OPC_AFEDATAC_READABLE    1
#define HAL_OPC_AFEDATAC_WRITABLE    1
#define HAL_OPC_AFEDATAC_SIGNED      0
#define HAL_OPC_AFEDATAC_ADR         0x10000C3C

// Register AFEDATAD
#define HAL_OPC_AFEDATAD_REGISTER    (HAL_OPCREG_MAP->AFEDATAD)
#define HAL_OPC_AFEDATAD_LSB         0
#define HAL_OPC_AFEDATAD_MSB         7
#define HAL_OPC_AFEDATAD_MASK        0x000000FF
#define HAL_OPC_AFEDATAD_TYPE        UByte
#define HAL_OPC_AFEDATAD             HAL_OPC_AFEDATAD_MASK
#define HAL_OPC_AFEDATAD_READABLE    1
#define HAL_OPC_AFEDATAD_WRITABLE    1
#define HAL_OPC_AFEDATAD_SIGNED      0
#define HAL_OPC_AFEDATAD_ADR         0x10000C3D

// Register AFEDATAE
#define HAL_OPC_AFEDATAE_REGISTER    (HAL_OPCREG_MAP->AFEDATAE)
#define HAL_OPC_AFEDATAE_LSB         0
#define HAL_OPC_AFEDATAE_MSB         7
#define HAL_OPC_AFEDATAE_MASK        0x000000FF
#define HAL_OPC_AFEDATAE_TYPE        UByte
#define HAL_OPC_AFEDATAE             HAL_OPC_AFEDATAE_MASK
#define HAL_OPC_AFEDATAE_READABLE    1
#define HAL_OPC_AFEDATAE_WRITABLE    1
#define HAL_OPC_AFEDATAE_SIGNED      0
#define HAL_OPC_AFEDATAE_ADR         0x10000C3E

// Register AFEDATAF
#define HAL_OPC_AFEDATAF_REGISTER    (HAL_OPCREG_MAP->AFEDATAF)
#define HAL_OPC_AFEDATAF_LSB         0
#define HAL_OPC_AFEDATAF_MSB         7
#define HAL_OPC_AFEDATAF_MASK        0x000000FF
#define HAL_OPC_AFEDATAF_TYPE        UByte
#define HAL_OPC_AFEDATAF             HAL_OPC_AFEDATAF_MASK
#define HAL_OPC_AFEDATAF_READABLE    1
#define HAL_OPC_AFEDATAF_WRITABLE    1
#define HAL_OPC_AFEDATAF_SIGNED      0
#define HAL_OPC_AFEDATAF_ADR         0x10000C3F

#endif // #if (CHIP_REV >= 0xC0)

// Enumerations
typedef enum
{
	halOPC_OPCDSRC_DFE = 0,    // OPC Data Source from the DFE
	halOPC_OPCDSRC_ADC = 1     // OPC Data Source from the ADC
} halOPC_OPCDSRC_t;

typedef enum
{
	halOPC_OPCGate_NoLimit = 0,    // No limit on the number of samples taken
	halOPC_OPCGate_SAMPNUM = 1     // Number of samples taken is determined by SAMPNUM(3-0)
} halOPC_OPCGate_t;

typedef enum
{
	halOPC_OPCMIO0_opc_td         = 0,    // For WSTRT  = 1
	halOPC_OPCMIO0_opc_samp       = 0,    // For WSTRT  = 0
	halOPC_OPCMIO0_opc_start      = 1,    // For WBLSTM = 1
	halOPC_OPCMIO1_opc_tc         = 0,    // For WSTRT  = 1
	halOPC_OPCMIO1_opc_td         = 0,    // For WSTRT  = 0
	halOPC_OPCMIO1_opc_samp       = 1,    // For WBLSTM = 1
	halOPC_OPCMIO1_opc_adcld      = 1,    // For WBLSTM = 0
	halOPC_OPCMIO2_opc_tr         = 0,    // For WSTRT  = 1
	halOPC_OPCMIO2_opc_tc         = 0,    // For WSTRT  = 0
	halOPC_OPCMIO2_opc_stop       = 1,    // For WBLSTM = 1
	halOPC_OPCMIO2_sramwr         = 1,    // For WBLSTM = 0
	halOPC_OPCMIO3_wbl_opc_pulse1 = 0,    // For WSTRT  = 1
	halOPC_OPCMIO3_wbl_opc_pulse0 = 0,    // For WSTRT  = 0
	halOPC_OPCMIO3_srv_stm_d_opc  = 1,    // For WBLSTM = 1
	halOPC_OPCMIO3_opc_samp       = 1     // For WBLSTM = 0
} halOPC_OPCMIO_t;

typedef enum
{
	halOPC_AOPCSampNum_1    = 0,    // Auto OPC Number of Samples Per Channel Per Segment = 1    (When OPCGATE = 1)
	halOPC_AOPCSampNum_2    = 1,    // Auto OPC Number of Samples Per Channel Per Segment = 2    (When OPCGATE = 1)
	halOPC_AOPCSampNum_4    = 2,    // Auto OPC Number of Samples Per Channel Per Segment = 4    (When OPCGATE = 1)
	halOPC_AOPCSampNum_8    = 3,    // Auto OPC Number of Samples Per Channel Per Segment = 8    (When OPCGATE = 1)
	halOPC_AOPCSampNum_16   = 4,    // Auto OPC Number of Samples Per Channel Per Segment = 16   (When OPCGATE = 1)
	halOPC_AOPCSampNum_32   = 5,    // Auto OPC Number of Samples Per Channel Per Segment = 32   (When OPCGATE = 1)
	halOPC_AOPCSampNum_64   = 6,    // Auto OPC Number of Samples Per Channel Per Segment = 64   (When OPCGATE = 1)
	halOPC_AOPCSampNum_128  = 7,    // Auto OPC Number of Samples Per Channel Per Segment = 128  (When OPCGATE = 1)
	halOPC_AOPCSampNum_256  = 8,    // Auto OPC Number of Samples Per Channel Per Segment = 256  (When OPCGATE = 1)
	halOPC_AOPCSampNum_512  = 9,    // Auto OPC Number of Samples Per Channel Per Segment = 512  (When OPCGATE = 1)
	halOPC_AOPCSampNum_1024 = 10     // Auto OPC Number of Samples Per Channel Per Segment = 1024 (When OPCGATE = 1)
} halOPC_AOPCSampNum_t;

typedef enum
{
	halOPC_AOPCAvg_1Samp   = 0,    // Auto OPC Averaging Ratio 1 :   1 Samples
	halOPC_AOPCAvg_2Samp   = 1,    // Auto OPC Averaging Ratio 1 :   2 Samples
	halOPC_AOPCAvg_4Samp   = 2,    // Auto OPC Averaging Ratio 1 :   4 Samples
	halOPC_AOPCAvg_8Samp   = 3,    // Auto OPC Averaging Ratio 1 :   8 Samples
	halOPC_AOPCAvg_16Samp  = 4,    // Auto OPC Averaging Ratio 1 :  16 Samples
	halOPC_AOPCAvg_32Samp  = 5,    // Auto OPC Averaging Ratio 1 :  32 Samples
	halOPC_AOPCAvg_64Samp  = 6,    // Auto OPC Averaging Ratio 1 :  64 Samples
	halOPC_AOPCAvg_128Samp = 7     // Auto OPC Averaging Ratio 1 : 128 Samples
} halOPC_AOPCAvgSamp_t;

typedef enum
{
	halOPC_AOPCADCSampS1_GPADC1   = 0,    // Auto OPC Channel 1 Sample Signal = GPADC1
	halOPC_AOPCADCSampS1_CE       = 1,    // Auto OPC Channel 1 Sample Signal = CE
	halOPC_AOPCADCSampS1_BS       = 2,    // Auto OPC Channel 1 Sample Signal = BS
	halOPC_AOPCADCSampS1_RP       = 3,    // Auto OPC Channel 1 Sample Signal = RP
	halOPC_AOPCADCSampS1_GPADC2   = 4,    // Auto OPC Channel 1 Sample Signal = GPADC2
	halOPC_AOPCADCSampS1_TE5      = 5,    // Auto OPC Channel 1 Sample Signal = TE5
	halOPC_AOPCADCSampS1_FE6      = 6,    // Auto OPC Channel 1 Sample Signal = FE6
	halOPC_AOPCADCSampS1_MUXTOAD1 = 7,    // Auto OPC Channel 1 Sample Signal = MUXTOAD1
	halOPC_AOPCADCSampS1_VRPOW    = 8,    // Auto OPC Channel 1 Sample Signal = VRPOW
	halOPC_AOPCADCSampS1_VWPOW    = 9,    // Auto OPC Channel 1 Sample Signal = VWPOW
	halOPC_AOPCADCSampS1_PHSO     = 10,    // Auto OPC Channel 1 Sample Signal = PHSO
	halOPC_AOPCADCSampS1_BHSO     = 11,    // Auto OPC Channel 1 Sample Signal = BHSO
	halOPC_AOPCADCSampS1_MUXTOAD3 = 12,    // Auto OPC Channel 1 Sample Signal = MUXTOAD3
	halOPC_AOPCADCSampS1_TE13     = 13,    // Auto OPC Channel 1 Sample Signal = TE13
	halOPC_AOPCADCSampS1_FE14     = 14,    // Auto OPC Channel 1 Sample Signal = FE14
	halOPC_AOPCADCSampS1_MUXTOAD2 = 15     // Auto OPC Channel 1 Sample Signal = MUXTOAD2
} halOPC_AOPCADCSampS1_t;

typedef enum
{
	halOPC_AOPCADCSampS0_GPADC1   = 0,    // Auto OPC Channel 0 Sample Signal = GPADC1
	halOPC_AOPCADCSampS0_CE       = 1,    // Auto OPC Channel 0 Sample Signal = CE
	halOPC_AOPCADCSampS0_BS       = 2,    // Auto OPC Channel 0 Sample Signal = BS
	halOPC_AOPCADCSampS0_RP       = 3,    // Auto OPC Channel 0 Sample Signal = RP
	halOPC_AOPCADCSampS0_GPADC2   = 4,    // Auto OPC Channel 0 Sample Signal = GPADC2
	halOPC_AOPCADCSampS0_TE5      = 5,    // Auto OPC Channel 0 Sample Signal = TE5
	halOPC_AOPCADCSampS0_FE6      = 6,    // Auto OPC Channel 0 Sample Signal = FE6
	halOPC_AOPCADCSampS0_MUXTOAD1 = 7,    // Auto OPC Channel 0 Sample Signal = MUXTOAD1
	halOPC_AOPCADCSampS0_VRPOW    = 8,    // Auto OPC Channel 0 Sample Signal = VRPOW
	halOPC_AOPCADCSampS0_VWPOW    = 9,    // Auto OPC Channel 0 Sample Signal = VWPOW
	halOPC_AOPCADCSampS0_PHSO     = 10,    // Auto OPC Channel 0 Sample Signal = PHSO
	halOPC_AOPCADCSampS0_BHSO     = 11,    // Auto OPC Channel 0 Sample Signal = BHSO
	halOPC_AOPCADCSampS0_MUXTOAD3 = 12,    // Auto OPC Channel 0 Sample Signal = MUXTOAD3
	halOPC_AOPCADCSampS0_TE13     = 13,    // Auto OPC Channel 0 Sample Signal = TE13
	halOPC_AOPCADCSampS0_FE14     = 14,    // Auto OPC Channel 0 Sample Signal = FE14
	halOPC_AOPCADCSampS0_MUXTOAD2 = 15     // Auto OPC Channel 0 Sample Signal = MUXTOAD2
} halOPC_AOPCADCSampS0_t;

typedef enum
{
	halOPC_AOPCADCSampS2_GPADC1   = 0,    // Auto OPC Channel 2 Sample Signal = GPADC1
	halOPC_AOPCADCSampS2_CE       = 1,    // Auto OPC Channel 2 Sample Signal = CE
	halOPC_AOPCADCSampS2_BS       = 2,    // Auto OPC Channel 2 Sample Signal = BS
	halOPC_AOPCADCSampS2_RP       = 3,    // Auto OPC Channel 2 Sample Signal = RP
	halOPC_AOPCADCSampS2_GPADC2   = 4,    // Auto OPC Channel 2 Sample Signal = GPADC2
	halOPC_AOPCADCSampS2_TE5      = 5,    // Auto OPC Channel 2 Sample Signal = TE5
	halOPC_AOPCADCSampS2_FE6      = 6,    // Auto OPC Channel 2 Sample Signal = FE6
	halOPC_AOPCADCSampS2_MUXTOAD1 = 7,    // Auto OPC Channel 2 Sample Signal = MUXTOAD1
	halOPC_AOPCADCSampS2_VRPOW    = 8,    // Auto OPC Channel 2 Sample Signal = VRPOW
	halOPC_AOPCADCSampS2_VWPOW    = 9,    // Auto OPC Channel 2 Sample Signal = VWPOW
	halOPC_AOPCADCSampS2_PHSO     = 10,    // Auto OPC Channel 2 Sample Signal = PHSO
	halOPC_AOPCADCSampS2_BHSO     = 11,    // Auto OPC Channel 2 Sample Signal = BHSO
	halOPC_AOPCADCSampS2_MUXTOAD3 = 12,    // Auto OPC Channel 2 Sample Signal = MUXTOAD3
	halOPC_AOPCADCSampS2_TE13     = 13,    // Auto OPC Channel 2 Sample Signal = TE13
	halOPC_AOPCADCSampS2_FE14     = 14,    // Auto OPC Channel 2 Sample Signal = FE14
	halOPC_AOPCADCSampS2_MUXTOAD2 = 15     // Auto OPC Channel 2 Sample Signal = MUXTOAD2
} halOPC_AOPCADCSampS2_t;

#endif /* __REG_OPC_H__ */

