/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_sflash.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the SOC_AHB_SFLASH core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_SFLASH_H__
#define __REG_SFLASH_H__

// Core register map
#define HAL_AHB_SFLASH_VERSION 7.142
#define HAL_AHB_SFLASH_BaseAddress 0x31000000
#define HAL_AHB_SFLASHREG_MAP ((struct halAHB_SFLASHReg_Map*) (void *) HAL_AHB_SFLASH_BaseAddress)
__packed struct halAHB_SFLASHReg_Map
{
	HAL_Reg32 CMDREG;                         //00000000
	HAL_Reg8  STATEREG;                       //00000004
	HAL_Reg8  MANUFACTL;                      //00000005
	HAL_Reg16 IDREGL;                         //00000006
	HAL_Reg8  SFCTRL1;                        //00000008
	HAL_Reg8  SFCTRL2;                        //00000009
	HAL_Reg8  SFCTRL3;                        //0000000A
	HAL_Reg8  LOCKREG;                        //0000000B
	HAL_Reg8  INSTREG;                        //0000000C
	HAL_Reg8  WCMDREG;                        //0000000D
};
// Registers CMDREG/ADDRREGL/ADDRREGM/ADDRREGH
#define HAL_AHB_SFLASH_CMDREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->CMDREG)
#define HAL_AHB_SFLASH_CMDREG_LSB         0
#define HAL_AHB_SFLASH_CMDREG_MSB         7
#define HAL_AHB_SFLASH_CMDREG_MASK        0x000000FF
#define HAL_AHB_SFLASH_CMDREG_TYPE        halAHB_SFLASH_CMDREG_t
#define HAL_AHB_SFLASH_CMDREG             HAL_AHB_SFLASH_CMDREG_MASK
#define HAL_AHB_SFLASH_CMDREG_READABLE    1
#define HAL_AHB_SFLASH_CMDREG_WRITABLE    1
#define HAL_AHB_SFLASH_CMDREG_SIGNED      0
#define HAL_AHB_SFLASH_CMDREG_ADR         0x31000000

#define HAL_AHB_SFLASH_ADDRREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->CMDREG)
#define HAL_AHB_SFLASH_ADDRREG_LSB         8
#define HAL_AHB_SFLASH_ADDRREG_MSB         31
#define HAL_AHB_SFLASH_ADDRREG_MASK        0xFFFFFF00
#define HAL_AHB_SFLASH_ADDRREG_TYPE        UInt32
#define HAL_AHB_SFLASH_ADDRREG             HAL_AHB_SFLASH_ADDRREG_MASK
#define HAL_AHB_SFLASH_ADDRREG_READABLE    1
#define HAL_AHB_SFLASH_ADDRREG_WRITABLE    1
#define HAL_AHB_SFLASH_ADDRREG_SIGNED      0
#define HAL_AHB_SFLASH_ADDRREG_ADR         0x31000000

// Register STATEREG
#define HAL_AHB_SFLASH_SFSRP_REGISTER    (HAL_AHB_SFLASHREG_MAP->STATEREG)
#define HAL_AHB_SFLASH_SFSRP_LSB         7
#define HAL_AHB_SFLASH_SFSRP_MSB         7
#define HAL_AHB_SFLASH_SFSRP_MASK        0x00000080
#define HAL_AHB_SFLASH_SFSRP_TYPE        Bool
#define HAL_AHB_SFLASH_SFSRP             HAL_AHB_SFLASH_SFSRP_MASK
#define HAL_AHB_SFLASH_SFSRP_READABLE    1
#define HAL_AHB_SFLASH_SFSRP_WRITABLE    1
#define HAL_AHB_SFLASH_SFSRP_SIGNED      0
#define HAL_AHB_SFLASH_SFSRP_ADR         0x31000004

#define HAL_AHB_SFLASH_SFTB_REGISTER    (HAL_AHB_SFLASHREG_MAP->STATEREG)
#define HAL_AHB_SFLASH_SFTB_LSB         5
#define HAL_AHB_SFLASH_SFTB_MSB         5
#define HAL_AHB_SFLASH_SFTB_MASK        0x00000020
#define HAL_AHB_SFLASH_SFTB_TYPE        Bool
#define HAL_AHB_SFLASH_SFTB             HAL_AHB_SFLASH_SFTB_MASK
#define HAL_AHB_SFLASH_SFTB_READABLE    1
#define HAL_AHB_SFLASH_SFTB_WRITABLE    1
#define HAL_AHB_SFLASH_SFTB_SIGNED      0
#define HAL_AHB_SFLASH_SFTB_ADR         0x31000004

#define HAL_AHB_SFLASH_SFBP_REGISTER    (HAL_AHB_SFLASHREG_MAP->STATEREG)
#define HAL_AHB_SFLASH_SFBP_LSB         2
#define HAL_AHB_SFLASH_SFBP_MSB         4
#define HAL_AHB_SFLASH_SFBP_MASK        0x0000001C
#define HAL_AHB_SFLASH_SFBP_TYPE        UByte
#define HAL_AHB_SFLASH_SFBP             HAL_AHB_SFLASH_SFBP_MASK
#define HAL_AHB_SFLASH_SFBP_READABLE    1
#define HAL_AHB_SFLASH_SFBP_WRITABLE    1
#define HAL_AHB_SFLASH_SFBP_SIGNED      0
#define HAL_AHB_SFLASH_SFBP_ADR         0x31000004

#define HAL_AHB_SFLASH_SFWEL_REGISTER    (HAL_AHB_SFLASHREG_MAP->STATEREG)
#define HAL_AHB_SFLASH_SFWEL_LSB         1
#define HAL_AHB_SFLASH_SFWEL_MSB         1
#define HAL_AHB_SFLASH_SFWEL_MASK        0x00000002
#define HAL_AHB_SFLASH_SFWEL_TYPE        Bool
#define HAL_AHB_SFLASH_SFWEL             HAL_AHB_SFLASH_SFWEL_MASK
#define HAL_AHB_SFLASH_SFWEL_READABLE    1
#define HAL_AHB_SFLASH_SFWEL_WRITABLE    0
#define HAL_AHB_SFLASH_SFWEL_SIGNED      0
#define HAL_AHB_SFLASH_SFWEL_ADR         0x31000004

#define HAL_AHB_SFLASH_SFBUSY_REGISTER    (HAL_AHB_SFLASHREG_MAP->STATEREG)
#define HAL_AHB_SFLASH_SFBUSY_LSB         0
#define HAL_AHB_SFLASH_SFBUSY_MSB         0
#define HAL_AHB_SFLASH_SFBUSY_MASK        0x00000001
#define HAL_AHB_SFLASH_SFBUSY_TYPE        Bool
#define HAL_AHB_SFLASH_SFBUSY             HAL_AHB_SFLASH_SFBUSY_MASK
#define HAL_AHB_SFLASH_SFBUSY_READABLE    1
#define HAL_AHB_SFLASH_SFBUSY_WRITABLE    0
#define HAL_AHB_SFLASH_SFBUSY_SIGNED      0
#define HAL_AHB_SFLASH_SFBUSY_ADR         0x31000004

// Register MANUFACTL
#define HAL_AHB_SFLASH_MANUFACT_REGISTER    (HAL_AHB_SFLASHREG_MAP->MANUFACTL)
#define HAL_AHB_SFLASH_MANUFACT_LSB         0
#define HAL_AHB_SFLASH_MANUFACT_MSB         7
#define HAL_AHB_SFLASH_MANUFACT_MASK        0x000000FF
#define HAL_AHB_SFLASH_MANUFACT_TYPE        UByte
#define HAL_AHB_SFLASH_MANUFACT             HAL_AHB_SFLASH_MANUFACT_MASK
#define HAL_AHB_SFLASH_MANUFACT_READABLE    1
#define HAL_AHB_SFLASH_MANUFACT_WRITABLE    0
#define HAL_AHB_SFLASH_MANUFACT_SIGNED      0
#define HAL_AHB_SFLASH_MANUFACT_ADR         0x31000005

// Registers IDREGL/IDREGH
#define HAL_AHB_SFLASH_IDREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->IDREGL)
#define HAL_AHB_SFLASH_IDREG_LSB         0
#define HAL_AHB_SFLASH_IDREG_MSB         15
#define HAL_AHB_SFLASH_IDREG_MASK        0x0000FFFF
#define HAL_AHB_SFLASH_IDREG_TYPE        UInt16
#define HAL_AHB_SFLASH_IDREG             HAL_AHB_SFLASH_IDREG_MASK
#define HAL_AHB_SFLASH_IDREG_READABLE    1
#define HAL_AHB_SFLASH_IDREG_WRITABLE    0
#define HAL_AHB_SFLASH_IDREG_SIGNED      0
#define HAL_AHB_SFLASH_IDREG_ADR         0x31000006

// Register SFCTRL1
#define HAL_AHB_SFLASH_SFDIS_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL1)
#define HAL_AHB_SFLASH_SFDIS_LSB         0
#define HAL_AHB_SFLASH_SFDIS_MSB         0
#define HAL_AHB_SFLASH_SFDIS_MASK        0x00000001
#define HAL_AHB_SFLASH_SFDIS_TYPE        Bool
#define HAL_AHB_SFLASH_SFDIS             HAL_AHB_SFLASH_SFDIS_MASK
#define HAL_AHB_SFLASH_SFDIS_READABLE    1
#define HAL_AHB_SFLASH_SFDIS_WRITABLE    1
#define HAL_AHB_SFLASH_SFDIS_SIGNED      0
#define HAL_AHB_SFLASH_SFDIS_ADR         0x31000008

// Register SFCTRL2

#if (CHIP_REV >= 0xC0)

#define HAL_AHB_SFLASH_SF2IO_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SF2IO_LSB         7
#define HAL_AHB_SFLASH_SF2IO_MSB         7
#define HAL_AHB_SFLASH_SF2IO_MASK        0x00000080
#define HAL_AHB_SFLASH_SF2IO_TYPE        Bool
#define HAL_AHB_SFLASH_SF2IO             HAL_AHB_SFLASH_SF2IO_MASK
#define HAL_AHB_SFLASH_SF2IO_READABLE    1
#define HAL_AHB_SFLASH_SF2IO_WRITABLE    1
#define HAL_AHB_SFLASH_SF2IO_SIGNED      0
#define HAL_AHB_SFLASH_SF2IO_ADR         0x31000009

#define HAL_AHB_SFLASH_SFPOSLEN_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SFPOSLEN_LSB         6
#define HAL_AHB_SFLASH_SFPOSLEN_MSB         6
#define HAL_AHB_SFLASH_SFPOSLEN_MASK        0x00000040
#define HAL_AHB_SFLASH_SFPOSLEN_TYPE        Bool
#define HAL_AHB_SFLASH_SFPOSLEN             HAL_AHB_SFLASH_SFPOSLEN_MASK
#define HAL_AHB_SFLASH_SFPOSLEN_READABLE    1
#define HAL_AHB_SFLASH_SFPOSLEN_WRITABLE    1
#define HAL_AHB_SFLASH_SFPOSLEN_SIGNED      0
#define HAL_AHB_SFLASH_SFPOSLEN_ADR         0x31000009

#endif // #if (CHIP_REV >= 0xC0)

#define HAL_AHB_SFLASH_SFCHTEST_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SFCHTEST_LSB         5
#define HAL_AHB_SFLASH_SFCHTEST_MSB         5
#define HAL_AHB_SFLASH_SFCHTEST_MASK        0x00000020
#define HAL_AHB_SFLASH_SFCHTEST_TYPE        Bool
#define HAL_AHB_SFLASH_SFCHTEST             HAL_AHB_SFLASH_SFCHTEST_MASK
#define HAL_AHB_SFLASH_SFCHTEST_READABLE    1
#define HAL_AHB_SFLASH_SFCHTEST_WRITABLE    1
#define HAL_AHB_SFLASH_SFCHTEST_SIGNED      0
#define HAL_AHB_SFLASH_SFCHTEST_ADR         0x31000009

#define HAL_AHB_SFLASH_SFSLOWRD_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SFSLOWRD_LSB         4
#define HAL_AHB_SFLASH_SFSLOWRD_MSB         4
#define HAL_AHB_SFLASH_SFSLOWRD_MASK        0x00000010
#define HAL_AHB_SFLASH_SFSLOWRD_TYPE        Bool
#define HAL_AHB_SFLASH_SFSLOWRD             HAL_AHB_SFLASH_SFSLOWRD_MASK
#define HAL_AHB_SFLASH_SFSLOWRD_READABLE    1
#define HAL_AHB_SFLASH_SFSLOWRD_WRITABLE    1
#define HAL_AHB_SFLASH_SFSLOWRD_SIGNED      0
#define HAL_AHB_SFLASH_SFSLOWRD_ADR         0x31000009

#define HAL_AHB_SFLASH_SFTAGRST_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SFTAGRST_LSB         3
#define HAL_AHB_SFLASH_SFTAGRST_MSB         3
#define HAL_AHB_SFLASH_SFTAGRST_MASK        0x00000008
#define HAL_AHB_SFLASH_SFTAGRST_TYPE        Bool
#define HAL_AHB_SFLASH_SFTAGRST             HAL_AHB_SFLASH_SFTAGRST_MASK
#define HAL_AHB_SFLASH_SFTAGRST_READABLE    1
#define HAL_AHB_SFLASH_SFTAGRST_WRITABLE    1
#define HAL_AHB_SFLASH_SFTAGRST_SIGNED      0
#define HAL_AHB_SFLASH_SFTAGRST_ADR         0x31000009

#define HAL_AHB_SFLASH_SF2OUT_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SF2OUT_LSB         2
#define HAL_AHB_SFLASH_SF2OUT_MSB         2
#define HAL_AHB_SFLASH_SF2OUT_MASK        0x00000004
#define HAL_AHB_SFLASH_SF2OUT_TYPE        Bool
#define HAL_AHB_SFLASH_SF2OUT             HAL_AHB_SFLASH_SF2OUT_MASK
#define HAL_AHB_SFLASH_SF2OUT_READABLE    1
#define HAL_AHB_SFLASH_SF2OUT_WRITABLE    1
#define HAL_AHB_SFLASH_SF2OUT_SIGNED      0
#define HAL_AHB_SFLASH_SF2OUT_ADR         0x31000009

#define HAL_AHB_SFLASH_SF8KCACH_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SF8KCACH_LSB         1
#define HAL_AHB_SFLASH_SF8KCACH_MSB         1
#define HAL_AHB_SFLASH_SF8KCACH_MASK        0x00000002
#define HAL_AHB_SFLASH_SF8KCACH_TYPE        halAHB_SFLASH_SF8KCACH_t
#define HAL_AHB_SFLASH_SF8KCACH             HAL_AHB_SFLASH_SF8KCACH_MASK
#define HAL_AHB_SFLASH_SF8KCACH_READABLE    1
#define HAL_AHB_SFLASH_SF8KCACH_WRITABLE    1
#define HAL_AHB_SFLASH_SF8KCACH_SIGNED      0
#define HAL_AHB_SFLASH_SF8KCACH_ADR         0x31000009

#define HAL_AHB_SFLASH_SFENCACH_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL2)
#define HAL_AHB_SFLASH_SFENCACH_LSB         0
#define HAL_AHB_SFLASH_SFENCACH_MSB         0
#define HAL_AHB_SFLASH_SFENCACH_MASK        0x00000001
#define HAL_AHB_SFLASH_SFENCACH_TYPE        Bool
#define HAL_AHB_SFLASH_SFENCACH             HAL_AHB_SFLASH_SFENCACH_MASK
#define HAL_AHB_SFLASH_SFENCACH_READABLE    1
#define HAL_AHB_SFLASH_SFENCACH_WRITABLE    1
#define HAL_AHB_SFLASH_SFENCACH_SIGNED      0
#define HAL_AHB_SFLASH_SFENCACH_ADR         0x31000009

// Register SFCTRL3
#define HAL_AHB_SFLASH_SFCLKSEL_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL3)
#define HAL_AHB_SFLASH_SFCLKSEL_LSB         4
#define HAL_AHB_SFLASH_SFCLKSEL_MSB         6
#define HAL_AHB_SFLASH_SFCLKSEL_MASK        0x00000070
#define HAL_AHB_SFLASH_SFCLKSEL_TYPE        halAHB_SFLASH_SFCLKSEL_t
#define HAL_AHB_SFLASH_SFCLKSEL             HAL_AHB_SFLASH_SFCLKSEL_MASK
#define HAL_AHB_SFLASH_SFCLKSEL_READABLE    1
#define HAL_AHB_SFLASH_SFCLKSEL_WRITABLE    1
#define HAL_AHB_SFLASH_SFCLKSEL_SIGNED      0
#define HAL_AHB_SFLASH_SFCLKSEL_ADR         0x3100000A

#define HAL_AHB_SFLASH_SFEXTW_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL3)
#define HAL_AHB_SFLASH_SFEXTW_LSB         1
#define HAL_AHB_SFLASH_SFEXTW_MSB         1
#define HAL_AHB_SFLASH_SFEXTW_MASK        0x00000002
#define HAL_AHB_SFLASH_SFEXTW_TYPE        Bool
#define HAL_AHB_SFLASH_SFEXTW             HAL_AHB_SFLASH_SFEXTW_MASK
#define HAL_AHB_SFLASH_SFEXTW_READABLE    1
#define HAL_AHB_SFLASH_SFEXTW_WRITABLE    1
#define HAL_AHB_SFLASH_SFEXTW_SIGNED      0
#define HAL_AHB_SFLASH_SFEXTW_ADR         0x3100000A

#define HAL_AHB_SFLASH_SFEXTCMD_REGISTER    (HAL_AHB_SFLASHREG_MAP->SFCTRL3)
#define HAL_AHB_SFLASH_SFEXTCMD_LSB         0
#define HAL_AHB_SFLASH_SFEXTCMD_MSB         0
#define HAL_AHB_SFLASH_SFEXTCMD_MASK        0x00000001
#define HAL_AHB_SFLASH_SFEXTCMD_TYPE        Bool
#define HAL_AHB_SFLASH_SFEXTCMD             HAL_AHB_SFLASH_SFEXTCMD_MASK
#define HAL_AHB_SFLASH_SFEXTCMD_READABLE    1
#define HAL_AHB_SFLASH_SFEXTCMD_WRITABLE    1
#define HAL_AHB_SFLASH_SFEXTCMD_SIGNED      0
#define HAL_AHB_SFLASH_SFEXTCMD_ADR         0x3100000A

// Register LOCKREG
#define HAL_AHB_SFLASH_LOCKREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->LOCKREG)
#define HAL_AHB_SFLASH_LOCKREG_LSB         0
#define HAL_AHB_SFLASH_LOCKREG_MSB         7
#define HAL_AHB_SFLASH_LOCKREG_MASK        0x000000FF
#define HAL_AHB_SFLASH_LOCKREG_TYPE        UByte
#define HAL_AHB_SFLASH_LOCKREG             HAL_AHB_SFLASH_LOCKREG_MASK
#define HAL_AHB_SFLASH_LOCKREG_READABLE    1
#define HAL_AHB_SFLASH_LOCKREG_WRITABLE    1
#define HAL_AHB_SFLASH_LOCKREG_SIGNED      0
#define HAL_AHB_SFLASH_LOCKREG_ADR         0x3100000B

// Register INSTREG
#define HAL_AHB_SFLASH_INSTREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->INSTREG)
#define HAL_AHB_SFLASH_INSTREG_LSB         0
#define HAL_AHB_SFLASH_INSTREG_MSB         7
#define HAL_AHB_SFLASH_INSTREG_MASK        0x000000FF
#define HAL_AHB_SFLASH_INSTREG_TYPE        UByte
#define HAL_AHB_SFLASH_INSTREG             HAL_AHB_SFLASH_INSTREG_MASK
#define HAL_AHB_SFLASH_INSTREG_READABLE    1
#define HAL_AHB_SFLASH_INSTREG_WRITABLE    1
#define HAL_AHB_SFLASH_INSTREG_SIGNED      0
#define HAL_AHB_SFLASH_INSTREG_ADR         0x3100000C

// Register WCMDREG
#define HAL_AHB_SFLASH_WCMDREG_REGISTER    (HAL_AHB_SFLASHREG_MAP->WCMDREG)
#define HAL_AHB_SFLASH_WCMDREG_LSB         0
#define HAL_AHB_SFLASH_WCMDREG_MSB         7
#define HAL_AHB_SFLASH_WCMDREG_MASK        0x000000FF
#define HAL_AHB_SFLASH_WCMDREG_TYPE        UByte
#define HAL_AHB_SFLASH_WCMDREG             HAL_AHB_SFLASH_WCMDREG_MASK
#define HAL_AHB_SFLASH_WCMDREG_READABLE    1
#define HAL_AHB_SFLASH_WCMDREG_WRITABLE    1
#define HAL_AHB_SFLASH_WCMDREG_SIGNED      0
#define HAL_AHB_SFLASH_WCMDREG_ADR         0x3100000D

// Enumerations
typedef enum
{
	halAHB_SFLASH_CMDREG_Default    = 0,    // Instruction: Default - 00h
	halAHB_SFLASH_CMDREG_WStatus    = 1,    // Instruction: Write Status Register
	halAHB_SFLASH_CMDREG_PageP      = 2,    // Instruction: Page Program
	halAHB_SFLASH_CMDREG_RData      = 3,    // Instruction: Read Data
	halAHB_SFLASH_CMDREG_WDisable   = 4,    // Instruction: Write Disable
	halAHB_SFLASH_CMDREG_RStatus    = 5,    // Instruction: Read Status Register
	halAHB_SFLASH_CMDREG_WEnable    = 6,    // Instruction: Write Enable
	halAHB_SFLASH_CMDREG_PageWrite  = 10,    // Instruction: Page Write
	halAHB_SFLASH_CMDREG_FastRead   = 11,    // Instruction: Fast Read
	halAHB_SFLASH_CMDREG_SectorEra  = 32,    // Instruction: Sector Erase (4 kB)
	halAHB_SFLASH_CMDREG_FastRDOP   = 59,    // Instruction: Fast Read Dual Output
	halAHB_SFLASH_CMDREG_EnWStatus  = 80,    // Instruction: Enable Write Status Register
	halAHB_SFLASH_CMDREG_BlockErase = 82,    // Instruction: Block Erase (64 kB)
	halAHB_SFLASH_CMDREG_ManuID     = 144,    // Instruction: Manufacturer/DeviceID
	halAHB_SFLASH_CMDREG_JEDECID    = 159,    // Instruction: JEDECID
	halAHB_SFLASH_CMDREG_RelPDownID = 171,    // Instruction: Release Power-down and Device ID
	halAHB_SFLASH_CMDREG_PowerDown  = 185,    // Instruction: Power-down
	halAHB_SFLASH_CMDREG_ChipEra    = 199,    // Instruction: Chip Erase
	halAHB_SFLASH_CMDREG_BlockEra   = 216,    // Instruction: Block Erase (64 kB)
	halAHB_SFLASH_CMDREG_PageErase  = 219,    // Instruction: Page Erase (256 kB)
	halAHB_SFLASH_CMDREG_WLockReg   = 229,    // Instruction: Write to Lock Register
	halAHB_SFLASH_CMDREG_RLockReg   = 232     // Instruction: Read Lock Register
} halAHB_SFLASH_CMDREG_t;

typedef enum
{
	halAHB_SFLASH_SF8KCACH_Set4KB = 0,    // Set 4 kB cache
	halAHB_SFLASH_SF8KCACH_Set8KB = 1     // Set 8 kB cache
} halAHB_SFLASH_SF8KCACH_t;

typedef enum
{
	halAHB_SFLASH_SFCLKSEL_ClkRate_250MHz   = 0,    // Clock Rate: SYSCLK2X = 250.00 MHz (gated)
	halAHB_SFLASH_SFCLKSEL_ClkRate_125MHz   = 1,    // Clock Rate: SYSCLK2X / 2 = 125.00 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_83p33MHz = 2,    // Clock Rate: SYSCLK2X / 3 = 83.33 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_62p50MHz = 3,    // Clock Rate: SYSCLK2X / 4 = 62.50 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_50MHz    = 4,    // Clock Rate: SYSCLK2X / 5 = 50.00 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_41p67MHz = 5,    // Clock Rate: SYSCLK2X / 6 = 41.67 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_35p71MHz = 6,    // Clock Rate: SYSCLK2X / 7 = 35.71 MHz
	halAHB_SFLASH_SFCLKSEL_ClkRate_31p25MHz = 7     // Clock Rate: SYSCLK2X / 8 = 31.25 MHz
} halAHB_SFLASH_SFCLKSEL_t;

#endif /* __REG_SFLASH_H__ */

