/******************************************************************************
*               (c) Copyright 2003 - 2010 SUNEXT TECHNOLOGY CO., LTD.
*                        All Right Reserved
*
* FILENAME: REG_dvd_encoder.h
*
*
* DESCRIPTION: This file contains register, bit and enum definitions
*              for RegHAL analysis of the DVDE core.
*
* NOTE: This file is created automatically and should NOT be modified by hand.
*
**************************** SUNEXT CONFIDENTIAL *****************************/

#ifndef __REG_DVD_ENCODER_H__
#define __REG_DVD_ENCODER_H__

// Core register map
#define HAL_DVDE_VERSION 7.37
#define HAL_DVDE_BaseAddress 0x10000400
#define HAL_DVDEREG_MAP ((struct halDVDEReg_Map*) (void *) HAL_DVDE_BaseAddress)
__packed struct halDVDEReg_Map
{
	HAL_Reg8  DVDERST;                        //00000000
	HAL_Reg8  WPMEDA;                         //00000001
	HAL_Reg8  ReservedBlk0[2];                //00000002
	HAL_Reg8  DVDEIRQS0;                      //00000004
	HAL_Reg8  DVDEIRQS1;                      //00000005
	HAL_Reg8  DVDEIRQS2;                      //00000006
	HAL_Reg8  ReservedBlk1[1];                //00000007
	HAL_Reg8  DVDEIRQE0;                      //00000008
	HAL_Reg8  DVDEIRQE1;                      //00000009
	HAL_Reg8  DVDEIRQE2;                      //0000000A
	HAL_Reg8  ReservedBlk2[1];                //0000000B
	HAL_Reg8  BLKWIPRD;                       //0000000C
	HAL_Reg8  ReservedBlk3[3];                //0000000D
	HAL_Reg32 HEADERL;                        //00000010
	HAL_Reg8  CPRMAI5;                        //00000014
	HAL_Reg8  CPRMAI4;                        //00000015
	HAL_Reg8  CPRMAI3;                        //00000016
	HAL_Reg8  CPRMAI2;                        //00000017
	HAL_Reg8  CPRMAI1;                        //00000018
	HAL_Reg8  CPRMAI0;                        //00000019
	HAL_Reg16 DEBUFSPGL;                      //0000001A
	HAL_Reg16 DEBUFEPGL;                      //0000001C
	HAL_Reg16 DEBUFPGL;                       //0000001E
	HAL_Reg8  UNDRUNTH;                       //00000020
	HAL_Reg8  ReservedBlk4[3];                //00000021
	HAL_Reg32 DSASADL;                        //00000024
	HAL_Reg32 DSBSADL;                        //00000028
	HAL_Reg32 PADTGT1L;                       //0000002C
	HAL_Reg32 PADMAP1L;                       //00000030
	HAL_Reg32 PADTGT2L;                       //00000034
	HAL_Reg32 PADMAP2L;                       //00000038
	HAL_Reg32 PADTYP1L;                       //0000003C
	HAL_Reg32 PADTYP2L;                       //00000040
	HAL_Reg8  PADDATA;                        //00000044
	HAL_Reg8  ReservedBlk5[3];                //00000045
	HAL_Reg32 WSB1SADL;                       //00000048
	HAL_Reg32 WSB1EADL;                       //0000004C
	HAL_Reg32 WSB2SADL;                       //00000050
	HAL_Reg32 WSB2EADL;                       //00000054
	HAL_Reg16 LLSPGL;                         //00000058
	HAL_Reg16 LLEPGL;                         //0000005A
	HAL_Reg8  ReservedBlk6[1];                //0000005C
	HAL_Reg8  LLRPCNT;                        //0000005D
	HAL_Reg16 LLPGL;                          //0000005E
	HAL_Reg8  LINKLISTF;                      //00000060
	HAL_Reg8  WMCTRL;                         //00000061
	HAL_Reg8  WACTRL;                         //00000062
	HAL_Reg8  WRTCTRL;                        //00000063
	HAL_Reg8  WRSDSTAT;                       //00000064
	HAL_Reg8  ADDRCTRL;                       //00000065
	HAL_Reg8  ReservedBlk7[2];                //00000066
	HAL_Reg32 TGTADDRL;                       //00000068
	HAL_Reg8  TGTFRAME;                       //0000006C
	HAL_Reg8  ReservedBlk8[1];                //0000006D
	HAL_Reg16 TGTBITL;                        //0000006E
	HAL_Reg32 WRCNTL;                         //00000070
	HAL_Reg8  INCWRCNT;                       //00000074
	HAL_Reg8  ReservedBlk9[3];                //00000075
	HAL_Reg32 WRCNTTL;                        //00000078
	HAL_Reg32 STPADDRL;                       //0000007C
	HAL_Reg8  STPFRAME;                       //00000080
	HAL_Reg8  ReservedBlk10[1];               //00000081
	HAL_Reg16 STPBITL;                        //00000082
	HAL_Reg8  STRTATR;                        //00000084
	HAL_Reg8  STRTSTA;                        //00000085
	HAL_Reg8  STPATR0;                        //00000086
	HAL_Reg8  STPATR1;                        //00000087
	HAL_Reg8  STPSTA0;                        //00000088
	HAL_Reg8  STPSTA1;                        //00000089
	HAL_Reg8  DXCTRL;                         //0000008A
	HAL_Reg8  ReservedBlk11[1];               //0000008B
	HAL_Reg32 DXSTADDRL;                      //0000008C
	HAL_Reg8  DXSTFRAME;                      //00000090
	HAL_Reg8  ReservedBlk12[1];               //00000091
	HAL_Reg16 DXSTBITL;                       //00000092
	HAL_Reg8  DXSTPHASE;                      //00000094
	HAL_Reg8  ReservedBlk13[3];               //00000095
	HAL_Reg8  WGCTRL;                         //00000098
	HAL_Reg8  SWSTAT;                         //00000099
	HAL_Reg8  BACTRL1;                        //0000009A
	HAL_Reg8  ReservedBlk14[1];               //0000009B
	HAL_Reg16 BACTRL2L;                       //0000009C
	HAL_Reg8  LBCTRL;                         //0000009E
	HAL_Reg8  ReservedBlk15[1];               //0000009F
	HAL_Reg16 WGSSCNTL;                       //000000A0
	HAL_Reg8  DVDESPARE;                      //000000A2
	HAL_Reg8  ReservedBlk16[77];              //000000A3
	HAL_Reg8  DVDDBGBUS;                      //000000F0
	HAL_Reg8  ReservedBlk17[12];              //000000F1
	HAL_Reg8  DVDETST1;                       //000000FD
	HAL_Reg8  DVDETST2;                       //000000FE
	HAL_Reg8  DVDETST3;                       //000000FF
};
// Register DVDERST
#define HAL_DVDE_ENCRST_REGISTER    (HAL_DVDEREG_MAP->DVDERST)
#define HAL_DVDE_ENCRST_LSB         0
#define HAL_DVDE_ENCRST_MSB         0
#define HAL_DVDE_ENCRST_MASK        0x00000001
#define HAL_DVDE_ENCRST_TYPE        Bool
#define HAL_DVDE_ENCRST             HAL_DVDE_ENCRST_MASK
#define HAL_DVDE_ENCRST_READABLE    1
#define HAL_DVDE_ENCRST_WRITABLE    1
#define HAL_DVDE_ENCRST_SIGNED      0
#define HAL_DVDE_ENCRST_ADR         0x10000400

// Register WPMEDA
#define HAL_DVDE_HDTYP_REGISTER    (HAL_DVDEREG_MAP->WPMEDA)
#define HAL_DVDE_HDTYP_LSB         2
#define HAL_DVDE_HDTYP_MSB         3
#define HAL_DVDE_HDTYP_MASK        0x0000000C
#define HAL_DVDE_HDTYP_TYPE        halDVDE_HDDVDTypeSelect_t
#define HAL_DVDE_HDTYP             HAL_DVDE_HDTYP_MASK
#define HAL_DVDE_HDTYP_READABLE    1
#define HAL_DVDE_HDTYP_WRITABLE    1
#define HAL_DVDE_HDTYP_SIGNED      0
#define HAL_DVDE_HDTYP_ADR         0x10000401

#define HAL_DVDE_DVDETYP_REGISTER    (HAL_DVDEREG_MAP->WPMEDA)
#define HAL_DVDE_DVDETYP_LSB         0
#define HAL_DVDE_DVDETYP_MSB         1
#define HAL_DVDE_DVDETYP_MASK        0x00000003
#define HAL_DVDE_DVDETYP_TYPE        halDVDE_DVDTypeSelect_t
#define HAL_DVDE_DVDETYP             HAL_DVDE_DVDETYP_MASK
#define HAL_DVDE_DVDETYP_READABLE    1
#define HAL_DVDE_DVDETYP_WRITABLE    1
#define HAL_DVDE_DVDETYP_SIGNED      0
#define HAL_DVDE_DVDETYP_ADR         0x10000401

// Register DVDEIRQS0
#define HAL_DVDE_LLEMPTYI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS0)
#define HAL_DVDE_LLEMPTYI_LSB         5
#define HAL_DVDE_LLEMPTYI_MSB         5
#define HAL_DVDE_LLEMPTYI_MASK        0x00000020
#define HAL_DVDE_LLEMPTYI_TYPE        Bool
#define HAL_DVDE_LLEMPTYI             HAL_DVDE_LLEMPTYI_MASK
#define HAL_DVDE_LLEMPTYI_READABLE    1
#define HAL_DVDE_LLEMPTYI_WRITABLE    1
#define HAL_DVDE_LLEMPTYI_SIGNED      0
#define HAL_DVDE_LLEMPTYI_ADR         0x10000404

#define HAL_DVDE_LLOVRFI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS0)
#define HAL_DVDE_LLOVRFI_LSB         4
#define HAL_DVDE_LLOVRFI_MSB         4
#define HAL_DVDE_LLOVRFI_MASK        0x00000010
#define HAL_DVDE_LLOVRFI_TYPE        Bool
#define HAL_DVDE_LLOVRFI             HAL_DVDE_LLOVRFI_MASK
#define HAL_DVDE_LLOVRFI_READABLE    1
#define HAL_DVDE_LLOVRFI_WRITABLE    1
#define HAL_DVDE_LLOVRFI_SIGNED      0
#define HAL_DVDE_LLOVRFI_ADR         0x10000404

#define HAL_DVDE_LLENDI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS0)
#define HAL_DVDE_LLENDI_LSB         3
#define HAL_DVDE_LLENDI_MSB         3
#define HAL_DVDE_LLENDI_MASK        0x00000008
#define HAL_DVDE_LLENDI_TYPE        Bool
#define HAL_DVDE_LLENDI             HAL_DVDE_LLENDI_MASK
#define HAL_DVDE_LLENDI_READABLE    1
#define HAL_DVDE_LLENDI_WRITABLE    1
#define HAL_DVDE_LLENDI_SIGNED      0
#define HAL_DVDE_LLENDI_ADR         0x10000404

#define HAL_DVDE_BLKWRTNI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS0)
#define HAL_DVDE_BLKWRTNI_LSB         1
#define HAL_DVDE_BLKWRTNI_MSB         1
#define HAL_DVDE_BLKWRTNI_MASK        0x00000002
#define HAL_DVDE_BLKWRTNI_TYPE        Bool
#define HAL_DVDE_BLKWRTNI             HAL_DVDE_BLKWRTNI_MASK
#define HAL_DVDE_BLKWRTNI_READABLE    1
#define HAL_DVDE_BLKWRTNI_WRITABLE    1
#define HAL_DVDE_BLKWRTNI_SIGNED      0
#define HAL_DVDE_BLKWRTNI_ADR         0x10000404

#define HAL_DVDE_BLKENCI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS0)
#define HAL_DVDE_BLKENCI_LSB         0
#define HAL_DVDE_BLKENCI_MSB         0
#define HAL_DVDE_BLKENCI_MASK        0x00000001
#define HAL_DVDE_BLKENCI_TYPE        Bool
#define HAL_DVDE_BLKENCI             HAL_DVDE_BLKENCI_MASK
#define HAL_DVDE_BLKENCI_READABLE    1
#define HAL_DVDE_BLKENCI_WRITABLE    1
#define HAL_DVDE_BLKENCI_SIGNED      0
#define HAL_DVDE_BLKENCI_ADR         0x10000404

// Register DVDEIRQS1
#define HAL_DVDE_WSTOPI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_WSTOPI_LSB         6
#define HAL_DVDE_WSTOPI_MSB         6
#define HAL_DVDE_WSTOPI_MASK        0x00000040
#define HAL_DVDE_WSTOPI_TYPE        Bool
#define HAL_DVDE_WSTOPI             HAL_DVDE_WSTOPI_MASK
#define HAL_DVDE_WSTOPI_READABLE    1
#define HAL_DVDE_WSTOPI_WRITABLE    1
#define HAL_DVDE_WSTOPI_SIGNED      0
#define HAL_DVDE_WSTOPI_ADR         0x10000405

#define HAL_DVDE_WSTRTFI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_WSTRTFI_LSB         5
#define HAL_DVDE_WSTRTFI_MSB         5
#define HAL_DVDE_WSTRTFI_MASK        0x00000020
#define HAL_DVDE_WSTRTFI_TYPE        Bool
#define HAL_DVDE_WSTRTFI             HAL_DVDE_WSTRTFI_MASK
#define HAL_DVDE_WSTRTFI_READABLE    1
#define HAL_DVDE_WSTRTFI_WRITABLE    1
#define HAL_DVDE_WSTRTFI_SIGNED      0
#define HAL_DVDE_WSTRTFI_ADR         0x10000405

#define HAL_DVDE_LBI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_LBI_LSB         4
#define HAL_DVDE_LBI_MSB         4
#define HAL_DVDE_LBI_MASK        0x00000010
#define HAL_DVDE_LBI_TYPE        Bool
#define HAL_DVDE_LBI             HAL_DVDE_LBI_MASK
#define HAL_DVDE_LBI_READABLE    1
#define HAL_DVDE_LBI_WRITABLE    1
#define HAL_DVDE_LBI_SIGNED      0
#define HAL_DVDE_LBI_ADR         0x10000405

#define HAL_DVDE_BLNKAI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_BLNKAI_LSB         3
#define HAL_DVDE_BLNKAI_MSB         3
#define HAL_DVDE_BLNKAI_MASK        0x00000008
#define HAL_DVDE_BLNKAI_TYPE        Bool
#define HAL_DVDE_BLNKAI             HAL_DVDE_BLNKAI_MASK
#define HAL_DVDE_BLNKAI_READABLE    1
#define HAL_DVDE_BLNKAI_WRITABLE    1
#define HAL_DVDE_BLNKAI_SIGNED      0
#define HAL_DVDE_BLNKAI_ADR         0x10000405

#define HAL_DVDE_WSTRTOKI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_WSTRTOKI_LSB         1
#define HAL_DVDE_WSTRTOKI_MSB         1
#define HAL_DVDE_WSTRTOKI_MASK        0x00000002
#define HAL_DVDE_WSTRTOKI_TYPE        Bool
#define HAL_DVDE_WSTRTOKI             HAL_DVDE_WSTRTOKI_MASK
#define HAL_DVDE_WSTRTOKI_READABLE    1
#define HAL_DVDE_WSTRTOKI_WRITABLE    1
#define HAL_DVDE_WSTRTOKI_SIGNED      0
#define HAL_DVDE_WSTRTOKI_ADR         0x10000405

#define HAL_DVDE_WRDONI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS1)
#define HAL_DVDE_WRDONI_LSB         0
#define HAL_DVDE_WRDONI_MSB         0
#define HAL_DVDE_WRDONI_MASK        0x00000001
#define HAL_DVDE_WRDONI_TYPE        Bool
#define HAL_DVDE_WRDONI             HAL_DVDE_WRDONI_MASK
#define HAL_DVDE_WRDONI_READABLE    1
#define HAL_DVDE_WRDONI_WRITABLE    1
#define HAL_DVDE_WRDONI_SIGNED      0
#define HAL_DVDE_WRDONI_ADR         0x10000405

// Register DVDEIRQS2
#define HAL_DVDE_SERVOI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS2)
#define HAL_DVDE_SERVOI_LSB         4
#define HAL_DVDE_SERVOI_MSB         4
#define HAL_DVDE_SERVOI_MASK        0x00000010
#define HAL_DVDE_SERVOI_TYPE        Bool
#define HAL_DVDE_SERVOI             HAL_DVDE_SERVOI_MASK
#define HAL_DVDE_SERVOI_READABLE    1
#define HAL_DVDE_SERVOI_WRITABLE    1
#define HAL_DVDE_SERVOI_SIGNED      0
#define HAL_DVDE_SERVOI_ADR         0x10000406

#define HAL_DVDE_TGTMISI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS2)
#define HAL_DVDE_TGTMISI_LSB         3
#define HAL_DVDE_TGTMISI_MSB         3
#define HAL_DVDE_TGTMISI_MASK        0x00000008
#define HAL_DVDE_TGTMISI_TYPE        Bool
#define HAL_DVDE_TGTMISI             HAL_DVDE_TGTMISI_MASK
#define HAL_DVDE_TGTMISI_READABLE    1
#define HAL_DVDE_TGTMISI_WRITABLE    1
#define HAL_DVDE_TGTMISI_SIGNED      0
#define HAL_DVDE_TGTMISI_ADR         0x10000406

#define HAL_DVDE_DHUNDRI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS2)
#define HAL_DVDE_DHUNDRI_LSB         2
#define HAL_DVDE_DHUNDRI_MSB         2
#define HAL_DVDE_DHUNDRI_MASK        0x00000004
#define HAL_DVDE_DHUNDRI_TYPE        Bool
#define HAL_DVDE_DHUNDRI             HAL_DVDE_DHUNDRI_MASK
#define HAL_DVDE_DHUNDRI_READABLE    1
#define HAL_DVDE_DHUNDRI_WRITABLE    1
#define HAL_DVDE_DHUNDRI_SIGNED      0
#define HAL_DVDE_DHUNDRI_ADR         0x10000406

#define HAL_DVDE_ECCUNDRI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS2)
#define HAL_DVDE_ECCUNDRI_LSB         1
#define HAL_DVDE_ECCUNDRI_MSB         1
#define HAL_DVDE_ECCUNDRI_MASK        0x00000002
#define HAL_DVDE_ECCUNDRI_TYPE        Bool
#define HAL_DVDE_ECCUNDRI             HAL_DVDE_ECCUNDRI_MASK
#define HAL_DVDE_ECCUNDRI_READABLE    1
#define HAL_DVDE_ECCUNDRI_WRITABLE    1
#define HAL_DVDE_ECCUNDRI_SIGNED      0
#define HAL_DVDE_ECCUNDRI_ADR         0x10000406

#define HAL_DVDE_MDUNDRI_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQS2)
#define HAL_DVDE_MDUNDRI_LSB         0
#define HAL_DVDE_MDUNDRI_MSB         0
#define HAL_DVDE_MDUNDRI_MASK        0x00000001
#define HAL_DVDE_MDUNDRI_TYPE        Bool
#define HAL_DVDE_MDUNDRI             HAL_DVDE_MDUNDRI_MASK
#define HAL_DVDE_MDUNDRI_READABLE    1
#define HAL_DVDE_MDUNDRI_WRITABLE    1
#define HAL_DVDE_MDUNDRI_SIGNED      0
#define HAL_DVDE_MDUNDRI_ADR         0x10000406

// Register DVDEIRQE0
#define HAL_DVDE_LLEMPTYE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE0)
#define HAL_DVDE_LLEMPTYE_LSB         5
#define HAL_DVDE_LLEMPTYE_MSB         5
#define HAL_DVDE_LLEMPTYE_MASK        0x00000020
#define HAL_DVDE_LLEMPTYE_TYPE        Bool
#define HAL_DVDE_LLEMPTYE             HAL_DVDE_LLEMPTYE_MASK
#define HAL_DVDE_LLEMPTYE_READABLE    1
#define HAL_DVDE_LLEMPTYE_WRITABLE    1
#define HAL_DVDE_LLEMPTYE_SIGNED      0
#define HAL_DVDE_LLEMPTYE_ADR         0x10000408

#define HAL_DVDE_LLOVRFE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE0)
#define HAL_DVDE_LLOVRFE_LSB         4
#define HAL_DVDE_LLOVRFE_MSB         4
#define HAL_DVDE_LLOVRFE_MASK        0x00000010
#define HAL_DVDE_LLOVRFE_TYPE        Bool
#define HAL_DVDE_LLOVRFE             HAL_DVDE_LLOVRFE_MASK
#define HAL_DVDE_LLOVRFE_READABLE    1
#define HAL_DVDE_LLOVRFE_WRITABLE    1
#define HAL_DVDE_LLOVRFE_SIGNED      0
#define HAL_DVDE_LLOVRFE_ADR         0x10000408

#define HAL_DVDE_LLENDE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE0)
#define HAL_DVDE_LLENDE_LSB         3
#define HAL_DVDE_LLENDE_MSB         3
#define HAL_DVDE_LLENDE_MASK        0x00000008
#define HAL_DVDE_LLENDE_TYPE        Bool
#define HAL_DVDE_LLENDE             HAL_DVDE_LLENDE_MASK
#define HAL_DVDE_LLENDE_READABLE    1
#define HAL_DVDE_LLENDE_WRITABLE    1
#define HAL_DVDE_LLENDE_SIGNED      0
#define HAL_DVDE_LLENDE_ADR         0x10000408

#define HAL_DVDE_BLKWRTNE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE0)
#define HAL_DVDE_BLKWRTNE_LSB         1
#define HAL_DVDE_BLKWRTNE_MSB         1
#define HAL_DVDE_BLKWRTNE_MASK        0x00000002
#define HAL_DVDE_BLKWRTNE_TYPE        Bool
#define HAL_DVDE_BLKWRTNE             HAL_DVDE_BLKWRTNE_MASK
#define HAL_DVDE_BLKWRTNE_READABLE    1
#define HAL_DVDE_BLKWRTNE_WRITABLE    1
#define HAL_DVDE_BLKWRTNE_SIGNED      0
#define HAL_DVDE_BLKWRTNE_ADR         0x10000408

#define HAL_DVDE_BLKENCE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE0)
#define HAL_DVDE_BLKENCE_LSB         0
#define HAL_DVDE_BLKENCE_MSB         0
#define HAL_DVDE_BLKENCE_MASK        0x00000001
#define HAL_DVDE_BLKENCE_TYPE        Bool
#define HAL_DVDE_BLKENCE             HAL_DVDE_BLKENCE_MASK
#define HAL_DVDE_BLKENCE_READABLE    1
#define HAL_DVDE_BLKENCE_WRITABLE    1
#define HAL_DVDE_BLKENCE_SIGNED      0
#define HAL_DVDE_BLKENCE_ADR         0x10000408

// Register DVDEIRQE1
#define HAL_DVDE_WSTOPE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_WSTOPE_LSB         6
#define HAL_DVDE_WSTOPE_MSB         6
#define HAL_DVDE_WSTOPE_MASK        0x00000040
#define HAL_DVDE_WSTOPE_TYPE        Bool
#define HAL_DVDE_WSTOPE             HAL_DVDE_WSTOPE_MASK
#define HAL_DVDE_WSTOPE_READABLE    1
#define HAL_DVDE_WSTOPE_WRITABLE    1
#define HAL_DVDE_WSTOPE_SIGNED      0
#define HAL_DVDE_WSTOPE_ADR         0x10000409

#define HAL_DVDE_WSTRTFE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_WSTRTFE_LSB         5
#define HAL_DVDE_WSTRTFE_MSB         5
#define HAL_DVDE_WSTRTFE_MASK        0x00000020
#define HAL_DVDE_WSTRTFE_TYPE        Bool
#define HAL_DVDE_WSTRTFE             HAL_DVDE_WSTRTFE_MASK
#define HAL_DVDE_WSTRTFE_READABLE    1
#define HAL_DVDE_WSTRTFE_WRITABLE    1
#define HAL_DVDE_WSTRTFE_SIGNED      0
#define HAL_DVDE_WSTRTFE_ADR         0x10000409

#define HAL_DVDE_LBE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_LBE_LSB         4
#define HAL_DVDE_LBE_MSB         4
#define HAL_DVDE_LBE_MASK        0x00000010
#define HAL_DVDE_LBE_TYPE        Bool
#define HAL_DVDE_LBE             HAL_DVDE_LBE_MASK
#define HAL_DVDE_LBE_READABLE    1
#define HAL_DVDE_LBE_WRITABLE    1
#define HAL_DVDE_LBE_SIGNED      0
#define HAL_DVDE_LBE_ADR         0x10000409

#define HAL_DVDE_BLNKAE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_BLNKAE_LSB         3
#define HAL_DVDE_BLNKAE_MSB         3
#define HAL_DVDE_BLNKAE_MASK        0x00000008
#define HAL_DVDE_BLNKAE_TYPE        Bool
#define HAL_DVDE_BLNKAE             HAL_DVDE_BLNKAE_MASK
#define HAL_DVDE_BLNKAE_READABLE    1
#define HAL_DVDE_BLNKAE_WRITABLE    1
#define HAL_DVDE_BLNKAE_SIGNED      0
#define HAL_DVDE_BLNKAE_ADR         0x10000409

#define HAL_DVDE_WSTRTOKE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_WSTRTOKE_LSB         1
#define HAL_DVDE_WSTRTOKE_MSB         1
#define HAL_DVDE_WSTRTOKE_MASK        0x00000002
#define HAL_DVDE_WSTRTOKE_TYPE        Bool
#define HAL_DVDE_WSTRTOKE             HAL_DVDE_WSTRTOKE_MASK
#define HAL_DVDE_WSTRTOKE_READABLE    1
#define HAL_DVDE_WSTRTOKE_WRITABLE    1
#define HAL_DVDE_WSTRTOKE_SIGNED      0
#define HAL_DVDE_WSTRTOKE_ADR         0x10000409

#define HAL_DVDE_WRTDONE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE1)
#define HAL_DVDE_WRTDONE_LSB         0
#define HAL_DVDE_WRTDONE_MSB         0
#define HAL_DVDE_WRTDONE_MASK        0x00000001
#define HAL_DVDE_WRTDONE_TYPE        Bool
#define HAL_DVDE_WRTDONE             HAL_DVDE_WRTDONE_MASK
#define HAL_DVDE_WRTDONE_READABLE    1
#define HAL_DVDE_WRTDONE_WRITABLE    1
#define HAL_DVDE_WRTDONE_SIGNED      0
#define HAL_DVDE_WRTDONE_ADR         0x10000409

// Register DVDEIRQE2
#define HAL_DVDE_SERVOE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE2)
#define HAL_DVDE_SERVOE_LSB         4
#define HAL_DVDE_SERVOE_MSB         4
#define HAL_DVDE_SERVOE_MASK        0x00000010
#define HAL_DVDE_SERVOE_TYPE        Bool
#define HAL_DVDE_SERVOE             HAL_DVDE_SERVOE_MASK
#define HAL_DVDE_SERVOE_READABLE    1
#define HAL_DVDE_SERVOE_WRITABLE    1
#define HAL_DVDE_SERVOE_SIGNED      0
#define HAL_DVDE_SERVOE_ADR         0x1000040A

#define HAL_DVDE_TGTMISE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE2)
#define HAL_DVDE_TGTMISE_LSB         3
#define HAL_DVDE_TGTMISE_MSB         3
#define HAL_DVDE_TGTMISE_MASK        0x00000008
#define HAL_DVDE_TGTMISE_TYPE        Bool
#define HAL_DVDE_TGTMISE             HAL_DVDE_TGTMISE_MASK
#define HAL_DVDE_TGTMISE_READABLE    1
#define HAL_DVDE_TGTMISE_WRITABLE    1
#define HAL_DVDE_TGTMISE_SIGNED      0
#define HAL_DVDE_TGTMISE_ADR         0x1000040A

#define HAL_DVDE_DHUNDRE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE2)
#define HAL_DVDE_DHUNDRE_LSB         2
#define HAL_DVDE_DHUNDRE_MSB         2
#define HAL_DVDE_DHUNDRE_MASK        0x00000004
#define HAL_DVDE_DHUNDRE_TYPE        Bool
#define HAL_DVDE_DHUNDRE             HAL_DVDE_DHUNDRE_MASK
#define HAL_DVDE_DHUNDRE_READABLE    1
#define HAL_DVDE_DHUNDRE_WRITABLE    1
#define HAL_DVDE_DHUNDRE_SIGNED      0
#define HAL_DVDE_DHUNDRE_ADR         0x1000040A

#define HAL_DVDE_ECCUNDRE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE2)
#define HAL_DVDE_ECCUNDRE_LSB         1
#define HAL_DVDE_ECCUNDRE_MSB         1
#define HAL_DVDE_ECCUNDRE_MASK        0x00000002
#define HAL_DVDE_ECCUNDRE_TYPE        Bool
#define HAL_DVDE_ECCUNDRE             HAL_DVDE_ECCUNDRE_MASK
#define HAL_DVDE_ECCUNDRE_READABLE    1
#define HAL_DVDE_ECCUNDRE_WRITABLE    1
#define HAL_DVDE_ECCUNDRE_SIGNED      0
#define HAL_DVDE_ECCUNDRE_ADR         0x1000040A

#define HAL_DVDE_MDUNDRE_REGISTER    (HAL_DVDEREG_MAP->DVDEIRQE2)
#define HAL_DVDE_MDUNDRE_LSB         0
#define HAL_DVDE_MDUNDRE_MSB         0
#define HAL_DVDE_MDUNDRE_MASK        0x00000001
#define HAL_DVDE_MDUNDRE_TYPE        Bool
#define HAL_DVDE_MDUNDRE             HAL_DVDE_MDUNDRE_MASK
#define HAL_DVDE_MDUNDRE_READABLE    1
#define HAL_DVDE_MDUNDRE_WRITABLE    1
#define HAL_DVDE_MDUNDRE_SIGNED      0
#define HAL_DVDE_MDUNDRE_ADR         0x1000040A

// Register BLKWIPRD
#define HAL_DVDE_BLKWIPRD_REGISTER    (HAL_DVDEREG_MAP->BLKWIPRD)
#define HAL_DVDE_BLKWIPRD_LSB         0
#define HAL_DVDE_BLKWIPRD_MSB         7
#define HAL_DVDE_BLKWIPRD_MASK        0x000000FF
#define HAL_DVDE_BLKWIPRD_TYPE        UByte
#define HAL_DVDE_BLKWIPRD             HAL_DVDE_BLKWIPRD_MASK
#define HAL_DVDE_BLKWIPRD_READABLE    1
#define HAL_DVDE_BLKWIPRD_WRITABLE    1
#define HAL_DVDE_BLKWIPRD_SIGNED      0
#define HAL_DVDE_BLKWIPRD_ADR         0x1000040C

// Registers HEADERL/HEADERM/HEADERH/HEADERU
#define HAL_DVDE_HEADER_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_HEADER_LSB         0
#define HAL_DVDE_HEADER_MSB         23
#define HAL_DVDE_HEADER_MASK        0x00FFFFFF
#define HAL_DVDE_HEADER_TYPE        UInt32
#define HAL_DVDE_HEADER             HAL_DVDE_HEADER_MASK
#define HAL_DVDE_HEADER_READABLE    1
#define HAL_DVDE_HEADER_WRITABLE    1
#define HAL_DVDE_HEADER_SIGNED      0
#define HAL_DVDE_HEADER_ADR         0x10000410

#define HAL_DVDE_SECFMTYPE_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_SECFMTYPE_LSB         31
#define HAL_DVDE_SECFMTYPE_MSB         31
#define HAL_DVDE_SECFMTYPE_MASK        0x80000000
#define HAL_DVDE_SECFMTYPE_TYPE        Bool
#define HAL_DVDE_SECFMTYPE             HAL_DVDE_SECFMTYPE_MASK
#define HAL_DVDE_SECFMTYPE_READABLE    1
#define HAL_DVDE_SECFMTYPE_WRITABLE    1
#define HAL_DVDE_SECFMTYPE_SIGNED      0
#define HAL_DVDE_SECFMTYPE_ADR         0x10000410

#define HAL_DVDE_TRKMTHD_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_TRKMTHD_LSB         30
#define HAL_DVDE_TRKMTHD_MSB         30
#define HAL_DVDE_TRKMTHD_MASK        0x40000000
#define HAL_DVDE_TRKMTHD_TYPE        Bool
#define HAL_DVDE_TRKMTHD             HAL_DVDE_TRKMTHD_MASK
#define HAL_DVDE_TRKMTHD_READABLE    1
#define HAL_DVDE_TRKMTHD_WRITABLE    1
#define HAL_DVDE_TRKMTHD_SIGNED      0
#define HAL_DVDE_TRKMTHD_ADR         0x10000410

#define HAL_DVDE_REFLECT_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_REFLECT_LSB         29
#define HAL_DVDE_REFLECT_MSB         29
#define HAL_DVDE_REFLECT_MASK        0x20000000
#define HAL_DVDE_REFLECT_TYPE        Bool
#define HAL_DVDE_REFLECT             HAL_DVDE_REFLECT_MASK
#define HAL_DVDE_REFLECT_READABLE    1
#define HAL_DVDE_REFLECT_WRITABLE    1
#define HAL_DVDE_REFLECT_SIGNED      0
#define HAL_DVDE_REFLECT_ADR         0x10000410

#define HAL_DVDE_RECDTYP_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_RECDTYP_LSB         28
#define HAL_DVDE_RECDTYP_MSB         28
#define HAL_DVDE_RECDTYP_MASK        0x10000000
#define HAL_DVDE_RECDTYP_TYPE        Bool
#define HAL_DVDE_RECDTYP             HAL_DVDE_RECDTYP_MASK
#define HAL_DVDE_RECDTYP_READABLE    1
#define HAL_DVDE_RECDTYP_WRITABLE    1
#define HAL_DVDE_RECDTYP_SIGNED      0
#define HAL_DVDE_RECDTYP_ADR         0x10000410

#define HAL_DVDE_ZONETYP_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_ZONETYP_LSB         26
#define HAL_DVDE_ZONETYP_MSB         27
#define HAL_DVDE_ZONETYP_MASK        0x0C000000
#define HAL_DVDE_ZONETYP_TYPE        halDVDE_Zonetype_t
#define HAL_DVDE_ZONETYP             HAL_DVDE_ZONETYP_MASK
#define HAL_DVDE_ZONETYP_READABLE    1
#define HAL_DVDE_ZONETYP_WRITABLE    1
#define HAL_DVDE_ZONETYP_SIGNED      0
#define HAL_DVDE_ZONETYP_ADR         0x10000410

#define HAL_DVDE_DATATYPE_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_DATATYPE_LSB         25
#define HAL_DVDE_DATATYPE_MSB         25
#define HAL_DVDE_DATATYPE_MASK        0x02000000
#define HAL_DVDE_DATATYPE_TYPE        Bool
#define HAL_DVDE_DATATYPE             HAL_DVDE_DATATYPE_MASK
#define HAL_DVDE_DATATYPE_READABLE    1
#define HAL_DVDE_DATATYPE_WRITABLE    1
#define HAL_DVDE_DATATYPE_SIGNED      0
#define HAL_DVDE_DATATYPE_ADR         0x10000410

#define HAL_DVDE_LAYER_REGISTER    (HAL_DVDEREG_MAP->HEADERL)
#define HAL_DVDE_LAYER_LSB         24
#define HAL_DVDE_LAYER_MSB         24
#define HAL_DVDE_LAYER_MASK        0x01000000
#define HAL_DVDE_LAYER_TYPE        Bool
#define HAL_DVDE_LAYER             HAL_DVDE_LAYER_MASK
#define HAL_DVDE_LAYER_READABLE    1
#define HAL_DVDE_LAYER_WRITABLE    1
#define HAL_DVDE_LAYER_SIGNED      0
#define HAL_DVDE_LAYER_ADR         0x10000410

// Register CPRMAI5
#define HAL_DVDE_CPRMAI5_REGISTER    (HAL_DVDEREG_MAP->CPRMAI5)
#define HAL_DVDE_CPRMAI5_LSB         0
#define HAL_DVDE_CPRMAI5_MSB         7
#define HAL_DVDE_CPRMAI5_MASK        0x000000FF
#define HAL_DVDE_CPRMAI5_TYPE        UByte
#define HAL_DVDE_CPRMAI5             HAL_DVDE_CPRMAI5_MASK
#define HAL_DVDE_CPRMAI5_READABLE    1
#define HAL_DVDE_CPRMAI5_WRITABLE    1
#define HAL_DVDE_CPRMAI5_SIGNED      0
#define HAL_DVDE_CPRMAI5_ADR         0x10000414

// Register CPRMAI4
#define HAL_DVDE_CPRMAI4_REGISTER    (HAL_DVDEREG_MAP->CPRMAI4)
#define HAL_DVDE_CPRMAI4_LSB         0
#define HAL_DVDE_CPRMAI4_MSB         7
#define HAL_DVDE_CPRMAI4_MASK        0x000000FF
#define HAL_DVDE_CPRMAI4_TYPE        UByte
#define HAL_DVDE_CPRMAI4             HAL_DVDE_CPRMAI4_MASK
#define HAL_DVDE_CPRMAI4_READABLE    1
#define HAL_DVDE_CPRMAI4_WRITABLE    1
#define HAL_DVDE_CPRMAI4_SIGNED      0
#define HAL_DVDE_CPRMAI4_ADR         0x10000415

// Register CPRMAI3
#define HAL_DVDE_CPRMAI3_REGISTER    (HAL_DVDEREG_MAP->CPRMAI3)
#define HAL_DVDE_CPRMAI3_LSB         0
#define HAL_DVDE_CPRMAI3_MSB         7
#define HAL_DVDE_CPRMAI3_MASK        0x000000FF
#define HAL_DVDE_CPRMAI3_TYPE        UByte
#define HAL_DVDE_CPRMAI3             HAL_DVDE_CPRMAI3_MASK
#define HAL_DVDE_CPRMAI3_READABLE    1
#define HAL_DVDE_CPRMAI3_WRITABLE    1
#define HAL_DVDE_CPRMAI3_SIGNED      0
#define HAL_DVDE_CPRMAI3_ADR         0x10000416

// Register CPRMAI2
#define HAL_DVDE_CPRMAI2_REGISTER    (HAL_DVDEREG_MAP->CPRMAI2)
#define HAL_DVDE_CPRMAI2_LSB         0
#define HAL_DVDE_CPRMAI2_MSB         7
#define HAL_DVDE_CPRMAI2_MASK        0x000000FF
#define HAL_DVDE_CPRMAI2_TYPE        UByte
#define HAL_DVDE_CPRMAI2             HAL_DVDE_CPRMAI2_MASK
#define HAL_DVDE_CPRMAI2_READABLE    1
#define HAL_DVDE_CPRMAI2_WRITABLE    1
#define HAL_DVDE_CPRMAI2_SIGNED      0
#define HAL_DVDE_CPRMAI2_ADR         0x10000417

// Register CPRMAI1
#define HAL_DVDE_CPRMAI1_REGISTER    (HAL_DVDEREG_MAP->CPRMAI1)
#define HAL_DVDE_CPRMAI1_LSB         0
#define HAL_DVDE_CPRMAI1_MSB         7
#define HAL_DVDE_CPRMAI1_MASK        0x000000FF
#define HAL_DVDE_CPRMAI1_TYPE        UByte
#define HAL_DVDE_CPRMAI1             HAL_DVDE_CPRMAI1_MASK
#define HAL_DVDE_CPRMAI1_READABLE    1
#define HAL_DVDE_CPRMAI1_WRITABLE    1
#define HAL_DVDE_CPRMAI1_SIGNED      0
#define HAL_DVDE_CPRMAI1_ADR         0x10000418

// Register CPRMAI0
#define HAL_DVDE_CPRMAI0_REGISTER    (HAL_DVDEREG_MAP->CPRMAI0)
#define HAL_DVDE_CPRMAI0_LSB         0
#define HAL_DVDE_CPRMAI0_MSB         7
#define HAL_DVDE_CPRMAI0_MASK        0x000000FF
#define HAL_DVDE_CPRMAI0_TYPE        UByte
#define HAL_DVDE_CPRMAI0             HAL_DVDE_CPRMAI0_MASK
#define HAL_DVDE_CPRMAI0_READABLE    1
#define HAL_DVDE_CPRMAI0_WRITABLE    1
#define HAL_DVDE_CPRMAI0_SIGNED      0
#define HAL_DVDE_CPRMAI0_ADR         0x10000419

// Registers DEBUFSPGL/DEBUFSPGH
#define HAL_DVDE_DEBUFSPG_REGISTER    (HAL_DVDEREG_MAP->DEBUFSPGL)
#define HAL_DVDE_DEBUFSPG_LSB         0
#define HAL_DVDE_DEBUFSPG_MSB         12
#define HAL_DVDE_DEBUFSPG_MASK        0x00001FFF
#define HAL_DVDE_DEBUFSPG_TYPE        UInt16
#define HAL_DVDE_DEBUFSPG             HAL_DVDE_DEBUFSPG_MASK
#define HAL_DVDE_DEBUFSPG_READABLE    1
#define HAL_DVDE_DEBUFSPG_WRITABLE    1
#define HAL_DVDE_DEBUFSPG_SIGNED      0
#define HAL_DVDE_DEBUFSPG_ADR         0x1000041A

// Registers DEBUFEPGL/DEBUFEPGH
#define HAL_DVDE_DEBUFEPG_REGISTER    (HAL_DVDEREG_MAP->DEBUFEPGL)
#define HAL_DVDE_DEBUFEPG_LSB         0
#define HAL_DVDE_DEBUFEPG_MSB         12
#define HAL_DVDE_DEBUFEPG_MASK        0x00001FFF
#define HAL_DVDE_DEBUFEPG_TYPE        UInt16
#define HAL_DVDE_DEBUFEPG             HAL_DVDE_DEBUFEPG_MASK
#define HAL_DVDE_DEBUFEPG_READABLE    1
#define HAL_DVDE_DEBUFEPG_WRITABLE    1
#define HAL_DVDE_DEBUFEPG_SIGNED      0
#define HAL_DVDE_DEBUFEPG_ADR         0x1000041C

// Registers DEBUFPGL/DEBUFPGH
#define HAL_DVDE_DEBUFPG_REGISTER    (HAL_DVDEREG_MAP->DEBUFPGL)
#define HAL_DVDE_DEBUFPG_LSB         0
#define HAL_DVDE_DEBUFPG_MSB         12
#define HAL_DVDE_DEBUFPG_MASK        0x00001FFF
#define HAL_DVDE_DEBUFPG_TYPE        UInt16
#define HAL_DVDE_DEBUFPG             HAL_DVDE_DEBUFPG_MASK
#define HAL_DVDE_DEBUFPG_READABLE    1
#define HAL_DVDE_DEBUFPG_WRITABLE    1
#define HAL_DVDE_DEBUFPG_SIGNED      0
#define HAL_DVDE_DEBUFPG_ADR         0x1000041E

// Register UNDRUNTH
#define HAL_DVDE_UNDRUNTH_REGISTER    (HAL_DVDEREG_MAP->UNDRUNTH)
#define HAL_DVDE_UNDRUNTH_LSB         0
#define HAL_DVDE_UNDRUNTH_MSB         1
#define HAL_DVDE_UNDRUNTH_MASK        0x00000003
#define HAL_DVDE_UNDRUNTH_TYPE        UByte
#define HAL_DVDE_UNDRUNTH             HAL_DVDE_UNDRUNTH_MASK
#define HAL_DVDE_UNDRUNTH_READABLE    1
#define HAL_DVDE_UNDRUNTH_WRITABLE    1
#define HAL_DVDE_UNDRUNTH_SIGNED      0
#define HAL_DVDE_UNDRUNTH_ADR         0x10000420

// Registers DSASADL/DSASADM/DSASADH
#define HAL_DVDE_DSASADR_REGISTER    (HAL_DVDEREG_MAP->DSASADL)
#define HAL_DVDE_DSASADR_LSB         0
#define HAL_DVDE_DSASADR_MSB         23
#define HAL_DVDE_DSASADR_MASK        0x00FFFFFF
#define HAL_DVDE_DSASADR_TYPE        UInt32
#define HAL_DVDE_DSASADR             HAL_DVDE_DSASADR_MASK
#define HAL_DVDE_DSASADR_READABLE    1
#define HAL_DVDE_DSASADR_WRITABLE    1
#define HAL_DVDE_DSASADR_SIGNED      0
#define HAL_DVDE_DSASADR_ADR         0x10000424

// Registers DSBSADL/DSBSADM/DSBSADH
#define HAL_DVDE_DSBSADR_REGISTER    (HAL_DVDEREG_MAP->DSBSADL)
#define HAL_DVDE_DSBSADR_LSB         0
#define HAL_DVDE_DSBSADR_MSB         23
#define HAL_DVDE_DSBSADR_MASK        0x00FFFFFF
#define HAL_DVDE_DSBSADR_TYPE        UInt32
#define HAL_DVDE_DSBSADR             HAL_DVDE_DSBSADR_MASK
#define HAL_DVDE_DSBSADR_READABLE    1
#define HAL_DVDE_DSBSADR_WRITABLE    1
#define HAL_DVDE_DSBSADR_SIGNED      0
#define HAL_DVDE_DSBSADR_ADR         0x10000428

// Registers PADTGT1L/PADTGT1M/PADTGT1H
#define HAL_DVDE_PDTGT1_REGISTER    (HAL_DVDEREG_MAP->PADTGT1L)
#define HAL_DVDE_PDTGT1_LSB         0
#define HAL_DVDE_PDTGT1_MSB         23
#define HAL_DVDE_PDTGT1_MASK        0x00FFFFFF
#define HAL_DVDE_PDTGT1_TYPE        UInt32
#define HAL_DVDE_PDTGT1             HAL_DVDE_PDTGT1_MASK
#define HAL_DVDE_PDTGT1_READABLE    1
#define HAL_DVDE_PDTGT1_WRITABLE    1
#define HAL_DVDE_PDTGT1_SIGNED      0
#define HAL_DVDE_PDTGT1_ADR         0x1000042C

// Registers PADMAP1L/PADMAP1H/PADMAP1U/PADMAP1X
#define HAL_DVDE_PDMP1_REGISTER    (HAL_DVDEREG_MAP->PADMAP1L)
#define HAL_DVDE_PDMP1_LSB         0
#define HAL_DVDE_PDMP1_MSB         31
#define HAL_DVDE_PDMP1_MASK        0xFFFFFFFF
#define HAL_DVDE_PDMP1_TYPE        UInt32
#define HAL_DVDE_PDMP1             HAL_DVDE_PDMP1_MASK
#define HAL_DVDE_PDMP1_READABLE    1
#define HAL_DVDE_PDMP1_WRITABLE    1
#define HAL_DVDE_PDMP1_SIGNED      0
#define HAL_DVDE_PDMP1_ADR         0x10000430

// Registers PADTGT2L/PADTGT2M/PADTGT2H
#define HAL_DVDE_PDTGT2_REGISTER    (HAL_DVDEREG_MAP->PADTGT2L)
#define HAL_DVDE_PDTGT2_LSB         0
#define HAL_DVDE_PDTGT2_MSB         23
#define HAL_DVDE_PDTGT2_MASK        0x00FFFFFF
#define HAL_DVDE_PDTGT2_TYPE        UInt32
#define HAL_DVDE_PDTGT2             HAL_DVDE_PDTGT2_MASK
#define HAL_DVDE_PDTGT2_READABLE    1
#define HAL_DVDE_PDTGT2_WRITABLE    1
#define HAL_DVDE_PDTGT2_SIGNED      0
#define HAL_DVDE_PDTGT2_ADR         0x10000434

// Registers PADMAP2L/PADMAP2H/PADMAP2U/PADMAP2X
#define HAL_DVDE_PDMP2_REGISTER    (HAL_DVDEREG_MAP->PADMAP2L)
#define HAL_DVDE_PDMP2_LSB         0
#define HAL_DVDE_PDMP2_MSB         31
#define HAL_DVDE_PDMP2_MASK        0xFFFFFFFF
#define HAL_DVDE_PDMP2_TYPE        UInt32
#define HAL_DVDE_PDMP2             HAL_DVDE_PDMP2_MASK
#define HAL_DVDE_PDMP2_READABLE    1
#define HAL_DVDE_PDMP2_WRITABLE    1
#define HAL_DVDE_PDMP2_SIGNED      0
#define HAL_DVDE_PDMP2_ADR         0x10000438

// Registers PADTYP1L/PADTYP1H/PADTYP1U/PADTYP1X
#define HAL_DVDE_DATATYP1_REGISTER    (HAL_DVDEREG_MAP->PADTYP1L)
#define HAL_DVDE_DATATYP1_LSB         0
#define HAL_DVDE_DATATYP1_MSB         31
#define HAL_DVDE_DATATYP1_MASK        0xFFFFFFFF
#define HAL_DVDE_DATATYP1_TYPE        UInt32
#define HAL_DVDE_DATATYP1             HAL_DVDE_DATATYP1_MASK
#define HAL_DVDE_DATATYP1_READABLE    1
#define HAL_DVDE_DATATYP1_WRITABLE    1
#define HAL_DVDE_DATATYP1_SIGNED      0
#define HAL_DVDE_DATATYP1_ADR         0x1000043C

// Registers PADTYP2L/PADTYP2H/PADTYP2U/PADTYP2X
#define HAL_DVDE_DATATYP2_REGISTER    (HAL_DVDEREG_MAP->PADTYP2L)
#define HAL_DVDE_DATATYP2_LSB         0
#define HAL_DVDE_DATATYP2_MSB         31
#define HAL_DVDE_DATATYP2_MASK        0xFFFFFFFF
#define HAL_DVDE_DATATYP2_TYPE        UInt32
#define HAL_DVDE_DATATYP2             HAL_DVDE_DATATYP2_MASK
#define HAL_DVDE_DATATYP2_READABLE    1
#define HAL_DVDE_DATATYP2_WRITABLE    1
#define HAL_DVDE_DATATYP2_SIGNED      0
#define HAL_DVDE_DATATYP2_ADR         0x10000440

// Register PADDATA
#define HAL_DVDE_PDDAT_REGISTER    (HAL_DVDEREG_MAP->PADDATA)
#define HAL_DVDE_PDDAT_LSB         0
#define HAL_DVDE_PDDAT_MSB         7
#define HAL_DVDE_PDDAT_MASK        0x000000FF
#define HAL_DVDE_PDDAT_TYPE        UByte
#define HAL_DVDE_PDDAT             HAL_DVDE_PDDAT_MASK
#define HAL_DVDE_PDDAT_READABLE    1
#define HAL_DVDE_PDDAT_WRITABLE    1
#define HAL_DVDE_PDDAT_SIGNED      0
#define HAL_DVDE_PDDAT_ADR         0x10000444

// Registers WSB1SADL/WSB1SADM/WSB1SADH
#define HAL_DVDE_WSB1SAD_REGISTER    (HAL_DVDEREG_MAP->WSB1SADL)
#define HAL_DVDE_WSB1SAD_LSB         0
#define HAL_DVDE_WSB1SAD_MSB         23
#define HAL_DVDE_WSB1SAD_MASK        0x00FFFFFF
#define HAL_DVDE_WSB1SAD_TYPE        UInt32
#define HAL_DVDE_WSB1SAD             HAL_DVDE_WSB1SAD_MASK
#define HAL_DVDE_WSB1SAD_READABLE    1
#define HAL_DVDE_WSB1SAD_WRITABLE    1
#define HAL_DVDE_WSB1SAD_SIGNED      0
#define HAL_DVDE_WSB1SAD_ADR         0x10000448

// Registers WSB1EADL/WSB1EADM/WSB1EADH
#define HAL_DVDE_WSB1EAD_REGISTER    (HAL_DVDEREG_MAP->WSB1EADL)
#define HAL_DVDE_WSB1EAD_LSB         0
#define HAL_DVDE_WSB1EAD_MSB         23
#define HAL_DVDE_WSB1EAD_MASK        0x00FFFFFF
#define HAL_DVDE_WSB1EAD_TYPE        UInt32
#define HAL_DVDE_WSB1EAD             HAL_DVDE_WSB1EAD_MASK
#define HAL_DVDE_WSB1EAD_READABLE    1
#define HAL_DVDE_WSB1EAD_WRITABLE    1
#define HAL_DVDE_WSB1EAD_SIGNED      0
#define HAL_DVDE_WSB1EAD_ADR         0x1000044C

// Registers WSB2SADL/WSB2SADM/WSB2SADH
#define HAL_DVDE_WSB2SAD_REGISTER    (HAL_DVDEREG_MAP->WSB2SADL)
#define HAL_DVDE_WSB2SAD_LSB         0
#define HAL_DVDE_WSB2SAD_MSB         23
#define HAL_DVDE_WSB2SAD_MASK        0x00FFFFFF
#define HAL_DVDE_WSB2SAD_TYPE        UInt32
#define HAL_DVDE_WSB2SAD             HAL_DVDE_WSB2SAD_MASK
#define HAL_DVDE_WSB2SAD_READABLE    1
#define HAL_DVDE_WSB2SAD_WRITABLE    1
#define HAL_DVDE_WSB2SAD_SIGNED      0
#define HAL_DVDE_WSB2SAD_ADR         0x10000450

// Registers WSB2EADL/WSB2EADM/WSB2EADH
#define HAL_DVDE_WSB2EAD_REGISTER    (HAL_DVDEREG_MAP->WSB2EADL)
#define HAL_DVDE_WSB2EAD_LSB         0
#define HAL_DVDE_WSB2EAD_MSB         23
#define HAL_DVDE_WSB2EAD_MASK        0x00FFFFFF
#define HAL_DVDE_WSB2EAD_TYPE        UInt32
#define HAL_DVDE_WSB2EAD             HAL_DVDE_WSB2EAD_MASK
#define HAL_DVDE_WSB2EAD_READABLE    1
#define HAL_DVDE_WSB2EAD_WRITABLE    1
#define HAL_DVDE_WSB2EAD_SIGNED      0
#define HAL_DVDE_WSB2EAD_ADR         0x10000454

// Registers LLSPGL/LLSPGH
#define HAL_DVDE_LLSPG_REGISTER    (HAL_DVDEREG_MAP->LLSPGL)
#define HAL_DVDE_LLSPG_LSB         0
#define HAL_DVDE_LLSPG_MSB         12
#define HAL_DVDE_LLSPG_MASK        0x00001FFF
#define HAL_DVDE_LLSPG_TYPE        UInt16
#define HAL_DVDE_LLSPG             HAL_DVDE_LLSPG_MASK
#define HAL_DVDE_LLSPG_READABLE    1
#define HAL_DVDE_LLSPG_WRITABLE    1
#define HAL_DVDE_LLSPG_SIGNED      0
#define HAL_DVDE_LLSPG_ADR         0x10000458

// Registers LLEPGL/LLEPGH
#define HAL_DVDE_LLEPG_REGISTER    (HAL_DVDEREG_MAP->LLEPGL)
#define HAL_DVDE_LLEPG_LSB         0
#define HAL_DVDE_LLEPG_MSB         12
#define HAL_DVDE_LLEPG_MASK        0x00001FFF
#define HAL_DVDE_LLEPG_TYPE        UInt16
#define HAL_DVDE_LLEPG             HAL_DVDE_LLEPG_MASK
#define HAL_DVDE_LLEPG_READABLE    1
#define HAL_DVDE_LLEPG_WRITABLE    1
#define HAL_DVDE_LLEPG_SIGNED      0
#define HAL_DVDE_LLEPG_ADR         0x1000045A

// Register LLRPCNT
#define HAL_DVDE_LLRPCNT_REGISTER    (HAL_DVDEREG_MAP->LLRPCNT)
#define HAL_DVDE_LLRPCNT_LSB         0
#define HAL_DVDE_LLRPCNT_MSB         7
#define HAL_DVDE_LLRPCNT_MASK        0x000000FF
#define HAL_DVDE_LLRPCNT_TYPE        UByte
#define HAL_DVDE_LLRPCNT             HAL_DVDE_LLRPCNT_MASK
#define HAL_DVDE_LLRPCNT_READABLE    1
#define HAL_DVDE_LLRPCNT_WRITABLE    1
#define HAL_DVDE_LLRPCNT_SIGNED      0
#define HAL_DVDE_LLRPCNT_ADR         0x1000045D

// Registers LLPGL/LLPGH
#define HAL_DVDE_LLPG_REGISTER    (HAL_DVDEREG_MAP->LLPGL)
#define HAL_DVDE_LLPG_LSB         0
#define HAL_DVDE_LLPG_MSB         12
#define HAL_DVDE_LLPG_MASK        0x00001FFF
#define HAL_DVDE_LLPG_TYPE        UInt16
#define HAL_DVDE_LLPG             HAL_DVDE_LLPG_MASK
#define HAL_DVDE_LLPG_READABLE    1
#define HAL_DVDE_LLPG_WRITABLE    1
#define HAL_DVDE_LLPG_SIGNED      0
#define HAL_DVDE_LLPG_ADR         0x1000045E

#define HAL_DVDE_LASTENTRY_REGISTER    (HAL_DVDEREG_MAP->LLPGL)
#define HAL_DVDE_LASTENTRY_LSB         15
#define HAL_DVDE_LASTENTRY_MSB         15
#define HAL_DVDE_LASTENTRY_MASK        0x00008000
#define HAL_DVDE_LASTENTRY_TYPE        Bool
#define HAL_DVDE_LASTENTRY             HAL_DVDE_LASTENTRY_MASK
#define HAL_DVDE_LASTENTRY_READABLE    1
#define HAL_DVDE_LASTENTRY_WRITABLE    1
#define HAL_DVDE_LASTENTRY_SIGNED      0
#define HAL_DVDE_LASTENTRY_ADR         0x1000045E

#define HAL_DVDE_LLRPCNTSEL_REGISTER    (HAL_DVDEREG_MAP->LLPGL)
#define HAL_DVDE_LLRPCNTSEL_LSB         14
#define HAL_DVDE_LLRPCNTSEL_MSB         14
#define HAL_DVDE_LLRPCNTSEL_MASK        0x00004000
#define HAL_DVDE_LLRPCNTSEL_TYPE        Bool
#define HAL_DVDE_LLRPCNTSEL             HAL_DVDE_LLRPCNTSEL_MASK
#define HAL_DVDE_LLRPCNTSEL_READABLE    1
#define HAL_DVDE_LLRPCNTSEL_WRITABLE    1
#define HAL_DVDE_LLRPCNTSEL_SIGNED      0
#define HAL_DVDE_LLRPCNTSEL_ADR         0x1000045E

// Register LINKLISTF
#define HAL_DVDE_LL7STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL7STAT_LSB         7
#define HAL_DVDE_LL7STAT_MSB         7
#define HAL_DVDE_LL7STAT_MASK        0x00000080
#define HAL_DVDE_LL7STAT_TYPE        Bool
#define HAL_DVDE_LL7STAT             HAL_DVDE_LL7STAT_MASK
#define HAL_DVDE_LL7STAT_READABLE    1
#define HAL_DVDE_LL7STAT_WRITABLE    1
#define HAL_DVDE_LL7STAT_SIGNED      0
#define HAL_DVDE_LL7STAT_ADR         0x10000460

#define HAL_DVDE_LL6STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL6STAT_LSB         6
#define HAL_DVDE_LL6STAT_MSB         6
#define HAL_DVDE_LL6STAT_MASK        0x00000040
#define HAL_DVDE_LL6STAT_TYPE        Bool
#define HAL_DVDE_LL6STAT             HAL_DVDE_LL6STAT_MASK
#define HAL_DVDE_LL6STAT_READABLE    1
#define HAL_DVDE_LL6STAT_WRITABLE    1
#define HAL_DVDE_LL6STAT_SIGNED      0
#define HAL_DVDE_LL6STAT_ADR         0x10000460

#define HAL_DVDE_LL5STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL5STAT_LSB         5
#define HAL_DVDE_LL5STAT_MSB         5
#define HAL_DVDE_LL5STAT_MASK        0x00000020
#define HAL_DVDE_LL5STAT_TYPE        Bool
#define HAL_DVDE_LL5STAT             HAL_DVDE_LL5STAT_MASK
#define HAL_DVDE_LL5STAT_READABLE    1
#define HAL_DVDE_LL5STAT_WRITABLE    1
#define HAL_DVDE_LL5STAT_SIGNED      0
#define HAL_DVDE_LL5STAT_ADR         0x10000460

#define HAL_DVDE_LL4STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL4STAT_LSB         4
#define HAL_DVDE_LL4STAT_MSB         4
#define HAL_DVDE_LL4STAT_MASK        0x00000010
#define HAL_DVDE_LL4STAT_TYPE        Bool
#define HAL_DVDE_LL4STAT             HAL_DVDE_LL4STAT_MASK
#define HAL_DVDE_LL4STAT_READABLE    1
#define HAL_DVDE_LL4STAT_WRITABLE    1
#define HAL_DVDE_LL4STAT_SIGNED      0
#define HAL_DVDE_LL4STAT_ADR         0x10000460

#define HAL_DVDE_LL3STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL3STAT_LSB         3
#define HAL_DVDE_LL3STAT_MSB         3
#define HAL_DVDE_LL3STAT_MASK        0x00000008
#define HAL_DVDE_LL3STAT_TYPE        Bool
#define HAL_DVDE_LL3STAT             HAL_DVDE_LL3STAT_MASK
#define HAL_DVDE_LL3STAT_READABLE    1
#define HAL_DVDE_LL3STAT_WRITABLE    1
#define HAL_DVDE_LL3STAT_SIGNED      0
#define HAL_DVDE_LL3STAT_ADR         0x10000460

#define HAL_DVDE_LL2STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL2STAT_LSB         2
#define HAL_DVDE_LL2STAT_MSB         2
#define HAL_DVDE_LL2STAT_MASK        0x00000004
#define HAL_DVDE_LL2STAT_TYPE        Bool
#define HAL_DVDE_LL2STAT             HAL_DVDE_LL2STAT_MASK
#define HAL_DVDE_LL2STAT_READABLE    1
#define HAL_DVDE_LL2STAT_WRITABLE    1
#define HAL_DVDE_LL2STAT_SIGNED      0
#define HAL_DVDE_LL2STAT_ADR         0x10000460

#define HAL_DVDE_LL1STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL1STAT_LSB         1
#define HAL_DVDE_LL1STAT_MSB         1
#define HAL_DVDE_LL1STAT_MASK        0x00000002
#define HAL_DVDE_LL1STAT_TYPE        Bool
#define HAL_DVDE_LL1STAT             HAL_DVDE_LL1STAT_MASK
#define HAL_DVDE_LL1STAT_READABLE    1
#define HAL_DVDE_LL1STAT_WRITABLE    1
#define HAL_DVDE_LL1STAT_SIGNED      0
#define HAL_DVDE_LL1STAT_ADR         0x10000460

#define HAL_DVDE_LL0STAT_REGISTER    (HAL_DVDEREG_MAP->LINKLISTF)
#define HAL_DVDE_LL0STAT_LSB         0
#define HAL_DVDE_LL0STAT_MSB         0
#define HAL_DVDE_LL0STAT_MASK        0x00000001
#define HAL_DVDE_LL0STAT_TYPE        Bool
#define HAL_DVDE_LL0STAT             HAL_DVDE_LL0STAT_MASK
#define HAL_DVDE_LL0STAT_READABLE    1
#define HAL_DVDE_LL0STAT_WRITABLE    1
#define HAL_DVDE_LL0STAT_SIGNED      0
#define HAL_DVDE_LL0STAT_ADR         0x10000460

// Register WMCTRL
#define HAL_DVDE_DVDPLNK_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_DVDPLNK_LSB         7
#define HAL_DVDE_DVDPLNK_MSB         7
#define HAL_DVDE_DVDPLNK_MASK        0x00000080
#define HAL_DVDE_DVDPLNK_TYPE        Bool
#define HAL_DVDE_DVDPLNK             HAL_DVDE_DVDPLNK_MASK
#define HAL_DVDE_DVDPLNK_READABLE    1
#define HAL_DVDE_DVDPLNK_WRITABLE    1
#define HAL_DVDE_DVDPLNK_SIGNED      0
#define HAL_DVDE_DVDPLNK_ADR         0x10000461

#define HAL_DVDE_ENNRZI_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_ENNRZI_LSB         6
#define HAL_DVDE_ENNRZI_MSB         6
#define HAL_DVDE_ENNRZI_MASK        0x00000040
#define HAL_DVDE_ENNRZI_TYPE        Bool
#define HAL_DVDE_ENNRZI             HAL_DVDE_ENNRZI_MASK
#define HAL_DVDE_ENNRZI_READABLE    1
#define HAL_DVDE_ENNRZI_WRITABLE    1
#define HAL_DVDE_ENNRZI_SIGNED      0
#define HAL_DVDE_ENNRZI_ADR         0x10000461

#define HAL_DVDE_RCZE_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_RCZE_LSB         5
#define HAL_DVDE_RCZE_MSB         5
#define HAL_DVDE_RCZE_MASK        0x00000020
#define HAL_DVDE_RCZE_TYPE        Bool
#define HAL_DVDE_RCZE             HAL_DVDE_RCZE_MASK
#define HAL_DVDE_RCZE_READABLE    1
#define HAL_DVDE_RCZE_WRITABLE    1
#define HAL_DVDE_RCZE_SIGNED      0
#define HAL_DVDE_RCZE_ADR         0x10000461

#define HAL_DVDE_AUTOPAD_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_AUTOPAD_LSB         4
#define HAL_DVDE_AUTOPAD_MSB         4
#define HAL_DVDE_AUTOPAD_MASK        0x00000010
#define HAL_DVDE_AUTOPAD_TYPE        Bool
#define HAL_DVDE_AUTOPAD             HAL_DVDE_AUTOPAD_MASK
#define HAL_DVDE_AUTOPAD_READABLE    1
#define HAL_DVDE_AUTOPAD_WRITABLE    1
#define HAL_DVDE_AUTOPAD_SIGNED      0
#define HAL_DVDE_AUTOPAD_ADR         0x10000461

#define HAL_DVDE_WATT_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_WATT_LSB         2
#define HAL_DVDE_WATT_MSB         3
#define HAL_DVDE_WATT_MASK        0x0000000C
#define HAL_DVDE_WATT_TYPE        halDVDE_WrAttribute_t
#define HAL_DVDE_WATT             HAL_DVDE_WATT_MASK
#define HAL_DVDE_WATT_READABLE    1
#define HAL_DVDE_WATT_WRITABLE    1
#define HAL_DVDE_WATT_SIGNED      0
#define HAL_DVDE_WATT_ADR         0x10000461

#define HAL_DVDE_WMOD_REGISTER    (HAL_DVDEREG_MAP->WMCTRL)
#define HAL_DVDE_WMOD_LSB         0
#define HAL_DVDE_WMOD_MSB         1
#define HAL_DVDE_WMOD_MASK        0x00000003
#define HAL_DVDE_WMOD_TYPE        halDVDE_WrModeCtrl_t
#define HAL_DVDE_WMOD             HAL_DVDE_WMOD_MASK
#define HAL_DVDE_WMOD_READABLE    1
#define HAL_DVDE_WMOD_WRITABLE    1
#define HAL_DVDE_WMOD_SIGNED      0
#define HAL_DVDE_WMOD_ADR         0x10000461

// Register WACTRL
#define HAL_DVDE_SCRPTYP_REGISTER    (HAL_DVDEREG_MAP->WACTRL)
#define HAL_DVDE_SCRPTYP_LSB         0
#define HAL_DVDE_SCRPTYP_MSB         0
#define HAL_DVDE_SCRPTYP_MASK        0x00000001
#define HAL_DVDE_SCRPTYP_TYPE        Bool
#define HAL_DVDE_SCRPTYP             HAL_DVDE_SCRPTYP_MASK
#define HAL_DVDE_SCRPTYP_READABLE    1
#define HAL_DVDE_SCRPTYP_WRITABLE    1
#define HAL_DVDE_SCRPTYP_SIGNED      0
#define HAL_DVDE_SCRPTYP_ADR         0x10000462

// Register WRTCTRL
#define HAL_DVDE_ENDVDE_REGISTER    (HAL_DVDEREG_MAP->WRTCTRL)
#define HAL_DVDE_ENDVDE_LSB         1
#define HAL_DVDE_ENDVDE_MSB         1
#define HAL_DVDE_ENDVDE_MASK        0x00000002
#define HAL_DVDE_ENDVDE_TYPE        Bool
#define HAL_DVDE_ENDVDE             HAL_DVDE_ENDVDE_MASK
#define HAL_DVDE_ENDVDE_READABLE    1
#define HAL_DVDE_ENDVDE_WRITABLE    1
#define HAL_DVDE_ENDVDE_SIGNED      0
#define HAL_DVDE_ENDVDE_ADR         0x10000463

#define HAL_DVDE_WCMDST_REGISTER    (HAL_DVDEREG_MAP->WRTCTRL)
#define HAL_DVDE_WCMDST_LSB         0
#define HAL_DVDE_WCMDST_MSB         0
#define HAL_DVDE_WCMDST_MASK        0x00000001
#define HAL_DVDE_WCMDST_TYPE        Bool
#define HAL_DVDE_WCMDST             HAL_DVDE_WCMDST_MASK
#define HAL_DVDE_WCMDST_READABLE    1
#define HAL_DVDE_WCMDST_WRITABLE    1
#define HAL_DVDE_WCMDST_SIGNED      0
#define HAL_DVDE_WCMDST_ADR         0x10000463

// Register WRSDSTAT
#define HAL_DVDE_WSB2FLG_REGISTER    (HAL_DVDEREG_MAP->WRSDSTAT)
#define HAL_DVDE_WSB2FLG_LSB         1
#define HAL_DVDE_WSB2FLG_MSB         1
#define HAL_DVDE_WSB2FLG_MASK        0x00000002
#define HAL_DVDE_WSB2FLG_TYPE        Bool
#define HAL_DVDE_WSB2FLG             HAL_DVDE_WSB2FLG_MASK
#define HAL_DVDE_WSB2FLG_READABLE    1
#define HAL_DVDE_WSB2FLG_WRITABLE    0
#define HAL_DVDE_WSB2FLG_SIGNED      0
#define HAL_DVDE_WSB2FLG_ADR         0x10000464

#define HAL_DVDE_WSB1FLG_REGISTER    (HAL_DVDEREG_MAP->WRSDSTAT)
#define HAL_DVDE_WSB1FLG_LSB         0
#define HAL_DVDE_WSB1FLG_MSB         0
#define HAL_DVDE_WSB1FLG_MASK        0x00000001
#define HAL_DVDE_WSB1FLG_TYPE        Bool
#define HAL_DVDE_WSB1FLG             HAL_DVDE_WSB1FLG_MASK
#define HAL_DVDE_WSB1FLG_READABLE    1
#define HAL_DVDE_WSB1FLG_WRITABLE    0
#define HAL_DVDE_WSB1FLG_SIGNED      0
#define HAL_DVDE_WSB1FLG_ADR         0x10000464

// Register ADDRCTRL
#define HAL_DVDE_WRTBRKSEL_REGISTER    (HAL_DVDEREG_MAP->ADDRCTRL)
#define HAL_DVDE_WRTBRKSEL_LSB         2
#define HAL_DVDE_WRTBRKSEL_MSB         2
#define HAL_DVDE_WRTBRKSEL_MASK        0x00000004
#define HAL_DVDE_WRTBRKSEL_TYPE        Bool
#define HAL_DVDE_WRTBRKSEL             HAL_DVDE_WRTBRKSEL_MASK
#define HAL_DVDE_WRTBRKSEL_READABLE    1
#define HAL_DVDE_WRTBRKSEL_WRITABLE    1
#define HAL_DVDE_WRTBRKSEL_SIGNED      0
#define HAL_DVDE_WRTBRKSEL_ADR         0x10000465

#define HAL_DVDE_STPADRSEL_REGISTER    (HAL_DVDEREG_MAP->ADDRCTRL)
#define HAL_DVDE_STPADRSEL_LSB         1
#define HAL_DVDE_STPADRSEL_MSB         1
#define HAL_DVDE_STPADRSEL_MASK        0x00000002
#define HAL_DVDE_STPADRSEL_TYPE        Bool
#define HAL_DVDE_STPADRSEL             HAL_DVDE_STPADRSEL_MASK
#define HAL_DVDE_STPADRSEL_READABLE    1
#define HAL_DVDE_STPADRSEL_WRITABLE    1
#define HAL_DVDE_STPADRSEL_SIGNED      0
#define HAL_DVDE_STPADRSEL_ADR         0x10000465

#define HAL_DVDE_STRADRSEL_REGISTER    (HAL_DVDEREG_MAP->ADDRCTRL)
#define HAL_DVDE_STRADRSEL_LSB         0
#define HAL_DVDE_STRADRSEL_MSB         0
#define HAL_DVDE_STRADRSEL_MASK        0x00000001
#define HAL_DVDE_STRADRSEL_TYPE        Bool
#define HAL_DVDE_STRADRSEL             HAL_DVDE_STRADRSEL_MASK
#define HAL_DVDE_STRADRSEL_READABLE    1
#define HAL_DVDE_STRADRSEL_WRITABLE    1
#define HAL_DVDE_STRADRSEL_SIGNED      0
#define HAL_DVDE_STRADRSEL_ADR         0x10000465

// Registers TGTADDRL/TGTADDRM/TGTADDRH
#define HAL_DVDE_TGTHDR_REGISTER    (HAL_DVDEREG_MAP->TGTADDRL)
#define HAL_DVDE_TGTHDR_LSB         0
#define HAL_DVDE_TGTHDR_MSB         23
#define HAL_DVDE_TGTHDR_MASK        0x00FFFFFF
#define HAL_DVDE_TGTHDR_TYPE        UInt32
#define HAL_DVDE_TGTHDR             HAL_DVDE_TGTHDR_MASK
#define HAL_DVDE_TGTHDR_READABLE    1
#define HAL_DVDE_TGTHDR_WRITABLE    1
#define HAL_DVDE_TGTHDR_SIGNED      0
#define HAL_DVDE_TGTHDR_ADR         0x10000468

// Register TGTFRAME
#define HAL_DVDE_TGTFRAME_REGISTER    (HAL_DVDEREG_MAP->TGTFRAME)
#define HAL_DVDE_TGTFRAME_LSB         0
#define HAL_DVDE_TGTFRAME_MSB         4
#define HAL_DVDE_TGTFRAME_MASK        0x0000001F
#define HAL_DVDE_TGTFRAME_TYPE        UByte
#define HAL_DVDE_TGTFRAME             HAL_DVDE_TGTFRAME_MASK
#define HAL_DVDE_TGTFRAME_READABLE    1
#define HAL_DVDE_TGTFRAME_WRITABLE    1
#define HAL_DVDE_TGTFRAME_SIGNED      0
#define HAL_DVDE_TGTFRAME_ADR         0x1000046C

// Registers TGTBITL/TGTBITH
#define HAL_DVDE_TGTBIT_REGISTER    (HAL_DVDEREG_MAP->TGTBITL)
#define HAL_DVDE_TGTBIT_LSB         0
#define HAL_DVDE_TGTBIT_MSB         10
#define HAL_DVDE_TGTBIT_MASK        0x000007FF
#define HAL_DVDE_TGTBIT_TYPE        UInt16
#define HAL_DVDE_TGTBIT             HAL_DVDE_TGTBIT_MASK
#define HAL_DVDE_TGTBIT_READABLE    1
#define HAL_DVDE_TGTBIT_WRITABLE    1
#define HAL_DVDE_TGTBIT_SIGNED      0
#define HAL_DVDE_TGTBIT_ADR         0x1000046E

// Registers WRCNTL/WRCNTM/WRCNTH
#define HAL_DVDE_WRCNT_REGISTER    (HAL_DVDEREG_MAP->WRCNTL)
#define HAL_DVDE_WRCNT_LSB         0
#define HAL_DVDE_WRCNT_MSB         23
#define HAL_DVDE_WRCNT_MASK        0x00FFFFFF
#define HAL_DVDE_WRCNT_TYPE        UInt32
#define HAL_DVDE_WRCNT             HAL_DVDE_WRCNT_MASK
#define HAL_DVDE_WRCNT_READABLE    1
#define HAL_DVDE_WRCNT_WRITABLE    1
#define HAL_DVDE_WRCNT_SIGNED      0
#define HAL_DVDE_WRCNT_ADR         0x10000470

// Register INCWRCNT
#define HAL_DVDE_INCWRCNT_REGISTER    (HAL_DVDEREG_MAP->INCWRCNT)
#define HAL_DVDE_INCWRCNT_LSB         0
#define HAL_DVDE_INCWRCNT_MSB         7
#define HAL_DVDE_INCWRCNT_MASK        0x000000FF
#define HAL_DVDE_INCWRCNT_TYPE        UByte
#define HAL_DVDE_INCWRCNT             HAL_DVDE_INCWRCNT_MASK
#define HAL_DVDE_INCWRCNT_READABLE    0
#define HAL_DVDE_INCWRCNT_WRITABLE    1
#define HAL_DVDE_INCWRCNT_SIGNED      0
#define HAL_DVDE_INCWRCNT_ADR         0x10000474

// Registers WRCNTTL/WRCNTTM/WRCNTTH
#define HAL_DVDE_WRCNTT_REGISTER    (HAL_DVDEREG_MAP->WRCNTTL)
#define HAL_DVDE_WRCNTT_LSB         0
#define HAL_DVDE_WRCNTT_MSB         23
#define HAL_DVDE_WRCNTT_MASK        0x00FFFFFF
#define HAL_DVDE_WRCNTT_TYPE        UInt32
#define HAL_DVDE_WRCNTT             HAL_DVDE_WRCNTT_MASK
#define HAL_DVDE_WRCNTT_READABLE    1
#define HAL_DVDE_WRCNTT_WRITABLE    0
#define HAL_DVDE_WRCNTT_SIGNED      0
#define HAL_DVDE_WRCNTT_ADR         0x10000478

// Registers STPADDRL/STPADDRM/STPADDRH
#define HAL_DVDE_STPADDR_REGISTER    (HAL_DVDEREG_MAP->STPADDRL)
#define HAL_DVDE_STPADDR_LSB         0
#define HAL_DVDE_STPADDR_MSB         23
#define HAL_DVDE_STPADDR_MASK        0x00FFFFFF
#define HAL_DVDE_STPADDR_TYPE        UInt32
#define HAL_DVDE_STPADDR             HAL_DVDE_STPADDR_MASK
#define HAL_DVDE_STPADDR_READABLE    1
#define HAL_DVDE_STPADDR_WRITABLE    1
#define HAL_DVDE_STPADDR_SIGNED      0
#define HAL_DVDE_STPADDR_ADR         0x1000047C

// Register STPFRAME
#define HAL_DVDE_STPFRAME_REGISTER    (HAL_DVDEREG_MAP->STPFRAME)
#define HAL_DVDE_STPFRAME_LSB         0
#define HAL_DVDE_STPFRAME_MSB         4
#define HAL_DVDE_STPFRAME_MASK        0x0000001F
#define HAL_DVDE_STPFRAME_TYPE        UByte
#define HAL_DVDE_STPFRAME             HAL_DVDE_STPFRAME_MASK
#define HAL_DVDE_STPFRAME_READABLE    1
#define HAL_DVDE_STPFRAME_WRITABLE    1
#define HAL_DVDE_STPFRAME_SIGNED      0
#define HAL_DVDE_STPFRAME_ADR         0x10000480

// Registers STPBITL/STPBITH
#define HAL_DVDE_STPBIT_REGISTER    (HAL_DVDEREG_MAP->STPBITL)
#define HAL_DVDE_STPBIT_LSB         0
#define HAL_DVDE_STPBIT_MSB         10
#define HAL_DVDE_STPBIT_MASK        0x000007FF
#define HAL_DVDE_STPBIT_TYPE        UInt16
#define HAL_DVDE_STPBIT             HAL_DVDE_STPBIT_MASK
#define HAL_DVDE_STPBIT_READABLE    1
#define HAL_DVDE_STPBIT_WRITABLE    1
#define HAL_DVDE_STPBIT_SIGNED      0
#define HAL_DVDE_STPBIT_ADR         0x10000482

// Register STRTATR
#define HAL_DVDE_MDRDYSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_MDRDYSTR_LSB         7
#define HAL_DVDE_MDRDYSTR_MSB         7
#define HAL_DVDE_MDRDYSTR_MASK        0x00000080
#define HAL_DVDE_MDRDYSTR_TYPE        Bool
#define HAL_DVDE_MDRDYSTR             HAL_DVDE_MDRDYSTR_MASK
#define HAL_DVDE_MDRDYSTR_READABLE    1
#define HAL_DVDE_MDRDYSTR_WRITABLE    1
#define HAL_DVDE_MDRDYSTR_SIGNED      0
#define HAL_DVDE_MDRDYSTR_ADR         0x10000484

#define HAL_DVDE_SERVOSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_SERVOSTR_LSB         6
#define HAL_DVDE_SERVOSTR_MSB         6
#define HAL_DVDE_SERVOSTR_MASK        0x00000040
#define HAL_DVDE_SERVOSTR_TYPE        Bool
#define HAL_DVDE_SERVOSTR             HAL_DVDE_SERVOSTR_MASK
#define HAL_DVDE_SERVOSTR_READABLE    1
#define HAL_DVDE_SERVOSTR_WRITABLE    1
#define HAL_DVDE_SERVOSTR_SIGNED      0
#define HAL_DVDE_SERVOSTR_ADR         0x10000484

#define HAL_DVDE_ADOLKSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_ADOLKSTR_LSB         4
#define HAL_DVDE_ADOLKSTR_MSB         4
#define HAL_DVDE_ADOLKSTR_MASK        0x00000010
#define HAL_DVDE_ADOLKSTR_TYPE        Bool
#define HAL_DVDE_ADOLKSTR             HAL_DVDE_ADOLKSTR_MASK
#define HAL_DVDE_ADOLKSTR_READABLE    1
#define HAL_DVDE_ADOLKSTR_WRITABLE    1
#define HAL_DVDE_ADOLKSTR_SIGNED      0
#define HAL_DVDE_ADOLKSTR_ADR         0x10000484

#define HAL_DVDE_WDOLKSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_WDOLKSTR_LSB         3
#define HAL_DVDE_WDOLKSTR_MSB         3
#define HAL_DVDE_WDOLKSTR_MASK        0x00000008
#define HAL_DVDE_WDOLKSTR_TYPE        Bool
#define HAL_DVDE_WDOLKSTR             HAL_DVDE_WDOLKSTR_MASK
#define HAL_DVDE_WDOLKSTR_READABLE    1
#define HAL_DVDE_WDOLKSTR_WRITABLE    1
#define HAL_DVDE_WDOLKSTR_SIGNED      0
#define HAL_DVDE_WDOLKSTR_ADR         0x10000484

#define HAL_DVDE_TGTMISTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_TGTMISTR_LSB         2
#define HAL_DVDE_TGTMISTR_MSB         2
#define HAL_DVDE_TGTMISTR_MASK        0x00000004
#define HAL_DVDE_TGTMISTR_TYPE        Bool
#define HAL_DVDE_TGTMISTR             HAL_DVDE_TGTMISTR_MASK
#define HAL_DVDE_TGTMISTR_READABLE    1
#define HAL_DVDE_TGTMISTR_WRITABLE    1
#define HAL_DVDE_TGTMISTR_SIGNED      0
#define HAL_DVDE_TGTMISTR_ADR         0x10000484

#define HAL_DVDE_HROLKSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_HROLKSTR_LSB         1
#define HAL_DVDE_HROLKSTR_MSB         1
#define HAL_DVDE_HROLKSTR_MASK        0x00000002
#define HAL_DVDE_HROLKSTR_TYPE        Bool
#define HAL_DVDE_HROLKSTR             HAL_DVDE_HROLKSTR_MASK
#define HAL_DVDE_HROLKSTR_READABLE    1
#define HAL_DVDE_HROLKSTR_WRITABLE    1
#define HAL_DVDE_HROLKSTR_SIGNED      0
#define HAL_DVDE_HROLKSTR_ADR         0x10000484

#define HAL_DVDE_BTOLKSTR_REGISTER    (HAL_DVDEREG_MAP->STRTATR)
#define HAL_DVDE_BTOLKSTR_LSB         0
#define HAL_DVDE_BTOLKSTR_MSB         0
#define HAL_DVDE_BTOLKSTR_MASK        0x00000001
#define HAL_DVDE_BTOLKSTR_TYPE        Bool
#define HAL_DVDE_BTOLKSTR             HAL_DVDE_BTOLKSTR_MASK
#define HAL_DVDE_BTOLKSTR_READABLE    1
#define HAL_DVDE_BTOLKSTR_WRITABLE    1
#define HAL_DVDE_BTOLKSTR_SIGNED      0
#define HAL_DVDE_BTOLKSTR_ADR         0x10000484

// Register STRTSTA
#define HAL_DVDE_MDRDYSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_MDRDYSTRS_LSB         7
#define HAL_DVDE_MDRDYSTRS_MSB         7
#define HAL_DVDE_MDRDYSTRS_MASK        0x00000080
#define HAL_DVDE_MDRDYSTRS_TYPE        Bool
#define HAL_DVDE_MDRDYSTRS             HAL_DVDE_MDRDYSTRS_MASK
#define HAL_DVDE_MDRDYSTRS_READABLE    1
#define HAL_DVDE_MDRDYSTRS_WRITABLE    0
#define HAL_DVDE_MDRDYSTRS_SIGNED      0
#define HAL_DVDE_MDRDYSTRS_ADR         0x10000485

#define HAL_DVDE_SERVOSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_SERVOSTRS_LSB         6
#define HAL_DVDE_SERVOSTRS_MSB         6
#define HAL_DVDE_SERVOSTRS_MASK        0x00000040
#define HAL_DVDE_SERVOSTRS_TYPE        Bool
#define HAL_DVDE_SERVOSTRS             HAL_DVDE_SERVOSTRS_MASK
#define HAL_DVDE_SERVOSTRS_READABLE    1
#define HAL_DVDE_SERVOSTRS_WRITABLE    0
#define HAL_DVDE_SERVOSTRS_SIGNED      0
#define HAL_DVDE_SERVOSTRS_ADR         0x10000485

#define HAL_DVDE_ADOLKSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_ADOLKSTRS_LSB         4
#define HAL_DVDE_ADOLKSTRS_MSB         4
#define HAL_DVDE_ADOLKSTRS_MASK        0x00000010
#define HAL_DVDE_ADOLKSTRS_TYPE        Bool
#define HAL_DVDE_ADOLKSTRS             HAL_DVDE_ADOLKSTRS_MASK
#define HAL_DVDE_ADOLKSTRS_READABLE    1
#define HAL_DVDE_ADOLKSTRS_WRITABLE    0
#define HAL_DVDE_ADOLKSTRS_SIGNED      0
#define HAL_DVDE_ADOLKSTRS_ADR         0x10000485

#define HAL_DVDE_WDOLKSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_WDOLKSTRS_LSB         3
#define HAL_DVDE_WDOLKSTRS_MSB         3
#define HAL_DVDE_WDOLKSTRS_MASK        0x00000008
#define HAL_DVDE_WDOLKSTRS_TYPE        Bool
#define HAL_DVDE_WDOLKSTRS             HAL_DVDE_WDOLKSTRS_MASK
#define HAL_DVDE_WDOLKSTRS_READABLE    1
#define HAL_DVDE_WDOLKSTRS_WRITABLE    0
#define HAL_DVDE_WDOLKSTRS_SIGNED      0
#define HAL_DVDE_WDOLKSTRS_ADR         0x10000485

#define HAL_DVDE_TGTMISTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_TGTMISTRS_LSB         2
#define HAL_DVDE_TGTMISTRS_MSB         2
#define HAL_DVDE_TGTMISTRS_MASK        0x00000004
#define HAL_DVDE_TGTMISTRS_TYPE        Bool
#define HAL_DVDE_TGTMISTRS             HAL_DVDE_TGTMISTRS_MASK
#define HAL_DVDE_TGTMISTRS_READABLE    1
#define HAL_DVDE_TGTMISTRS_WRITABLE    0
#define HAL_DVDE_TGTMISTRS_SIGNED      0
#define HAL_DVDE_TGTMISTRS_ADR         0x10000485

#define HAL_DVDE_HROLKSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_HROLKSTRS_LSB         1
#define HAL_DVDE_HROLKSTRS_MSB         1
#define HAL_DVDE_HROLKSTRS_MASK        0x00000002
#define HAL_DVDE_HROLKSTRS_TYPE        Bool
#define HAL_DVDE_HROLKSTRS             HAL_DVDE_HROLKSTRS_MASK
#define HAL_DVDE_HROLKSTRS_READABLE    1
#define HAL_DVDE_HROLKSTRS_WRITABLE    0
#define HAL_DVDE_HROLKSTRS_SIGNED      0
#define HAL_DVDE_HROLKSTRS_ADR         0x10000485

#define HAL_DVDE_BTOLKSTRS_REGISTER    (HAL_DVDEREG_MAP->STRTSTA)
#define HAL_DVDE_BTOLKSTRS_LSB         0
#define HAL_DVDE_BTOLKSTRS_MSB         0
#define HAL_DVDE_BTOLKSTRS_MASK        0x00000001
#define HAL_DVDE_BTOLKSTRS_TYPE        Bool
#define HAL_DVDE_BTOLKSTRS             HAL_DVDE_BTOLKSTRS_MASK
#define HAL_DVDE_BTOLKSTRS_READABLE    1
#define HAL_DVDE_BTOLKSTRS_WRITABLE    0
#define HAL_DVDE_BTOLKSTRS_SIGNED      0
#define HAL_DVDE_BTOLKSTRS_ADR         0x10000485

// Register STPATR0
#define HAL_DVDE_SERVOSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_SERVOSTP_LSB         6
#define HAL_DVDE_SERVOSTP_MSB         6
#define HAL_DVDE_SERVOSTP_MASK        0x00000040
#define HAL_DVDE_SERVOSTP_TYPE        Bool
#define HAL_DVDE_SERVOSTP             HAL_DVDE_SERVOSTP_MASK
#define HAL_DVDE_SERVOSTP_READABLE    1
#define HAL_DVDE_SERVOSTP_WRITABLE    1
#define HAL_DVDE_SERVOSTP_SIGNED      0
#define HAL_DVDE_SERVOSTP_ADR         0x10000486

#define HAL_DVDE_ADOLKSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_ADOLKSTP_LSB         4
#define HAL_DVDE_ADOLKSTP_MSB         4
#define HAL_DVDE_ADOLKSTP_MASK        0x00000010
#define HAL_DVDE_ADOLKSTP_TYPE        Bool
#define HAL_DVDE_ADOLKSTP             HAL_DVDE_ADOLKSTP_MASK
#define HAL_DVDE_ADOLKSTP_READABLE    1
#define HAL_DVDE_ADOLKSTP_WRITABLE    1
#define HAL_DVDE_ADOLKSTP_SIGNED      0
#define HAL_DVDE_ADOLKSTP_ADR         0x10000486

#define HAL_DVDE_WDOLKSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_WDOLKSTP_LSB         3
#define HAL_DVDE_WDOLKSTP_MSB         3
#define HAL_DVDE_WDOLKSTP_MASK        0x00000008
#define HAL_DVDE_WDOLKSTP_TYPE        Bool
#define HAL_DVDE_WDOLKSTP             HAL_DVDE_WDOLKSTP_MASK
#define HAL_DVDE_WDOLKSTP_READABLE    1
#define HAL_DVDE_WDOLKSTP_WRITABLE    1
#define HAL_DVDE_WDOLKSTP_SIGNED      0
#define HAL_DVDE_WDOLKSTP_ADR         0x10000486

#define HAL_DVDE_TGTMISTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_TGTMISTP_LSB         2
#define HAL_DVDE_TGTMISTP_MSB         2
#define HAL_DVDE_TGTMISTP_MASK        0x00000004
#define HAL_DVDE_TGTMISTP_TYPE        Bool
#define HAL_DVDE_TGTMISTP             HAL_DVDE_TGTMISTP_MASK
#define HAL_DVDE_TGTMISTP_READABLE    1
#define HAL_DVDE_TGTMISTP_WRITABLE    1
#define HAL_DVDE_TGTMISTP_SIGNED      0
#define HAL_DVDE_TGTMISTP_ADR         0x10000486

#define HAL_DVDE_HROLKSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_HROLKSTP_LSB         1
#define HAL_DVDE_HROLKSTP_MSB         1
#define HAL_DVDE_HROLKSTP_MASK        0x00000002
#define HAL_DVDE_HROLKSTP_TYPE        Bool
#define HAL_DVDE_HROLKSTP             HAL_DVDE_HROLKSTP_MASK
#define HAL_DVDE_HROLKSTP_READABLE    1
#define HAL_DVDE_HROLKSTP_WRITABLE    1
#define HAL_DVDE_HROLKSTP_SIGNED      0
#define HAL_DVDE_HROLKSTP_ADR         0x10000486

#define HAL_DVDE_BTOLKSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR0)
#define HAL_DVDE_BTOLKSTP_LSB         0
#define HAL_DVDE_BTOLKSTP_MSB         0
#define HAL_DVDE_BTOLKSTP_MASK        0x00000001
#define HAL_DVDE_BTOLKSTP_TYPE        Bool
#define HAL_DVDE_BTOLKSTP             HAL_DVDE_BTOLKSTP_MASK
#define HAL_DVDE_BTOLKSTP_READABLE    1
#define HAL_DVDE_BTOLKSTP_WRITABLE    1
#define HAL_DVDE_BTOLKSTP_SIGNED      0
#define HAL_DVDE_BTOLKSTP_ADR         0x10000486

// Register STPATR1
#define HAL_DVDE_DHURSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR1)
#define HAL_DVDE_DHURSTP_LSB         2
#define HAL_DVDE_DHURSTP_MSB         2
#define HAL_DVDE_DHURSTP_MASK        0x00000004
#define HAL_DVDE_DHURSTP_TYPE        Bool
#define HAL_DVDE_DHURSTP             HAL_DVDE_DHURSTP_MASK
#define HAL_DVDE_DHURSTP_READABLE    1
#define HAL_DVDE_DHURSTP_WRITABLE    1
#define HAL_DVDE_DHURSTP_SIGNED      0
#define HAL_DVDE_DHURSTP_ADR         0x10000487

#define HAL_DVDE_ECCURSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR1)
#define HAL_DVDE_ECCURSTP_LSB         1
#define HAL_DVDE_ECCURSTP_MSB         1
#define HAL_DVDE_ECCURSTP_MASK        0x00000002
#define HAL_DVDE_ECCURSTP_TYPE        Bool
#define HAL_DVDE_ECCURSTP             HAL_DVDE_ECCURSTP_MASK
#define HAL_DVDE_ECCURSTP_READABLE    1
#define HAL_DVDE_ECCURSTP_WRITABLE    1
#define HAL_DVDE_ECCURSTP_SIGNED      0
#define HAL_DVDE_ECCURSTP_ADR         0x10000487

#define HAL_DVDE_MDURSTP_REGISTER    (HAL_DVDEREG_MAP->STPATR1)
#define HAL_DVDE_MDURSTP_LSB         0
#define HAL_DVDE_MDURSTP_MSB         0
#define HAL_DVDE_MDURSTP_MASK        0x00000001
#define HAL_DVDE_MDURSTP_TYPE        Bool
#define HAL_DVDE_MDURSTP             HAL_DVDE_MDURSTP_MASK
#define HAL_DVDE_MDURSTP_READABLE    1
#define HAL_DVDE_MDURSTP_WRITABLE    1
#define HAL_DVDE_MDURSTP_SIGNED      0
#define HAL_DVDE_MDURSTP_ADR         0x10000487

// Register STPSTA0
#define HAL_DVDE_SERVOSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_SERVOSTPS_LSB         6
#define HAL_DVDE_SERVOSTPS_MSB         6
#define HAL_DVDE_SERVOSTPS_MASK        0x00000040
#define HAL_DVDE_SERVOSTPS_TYPE        Bool
#define HAL_DVDE_SERVOSTPS             HAL_DVDE_SERVOSTPS_MASK
#define HAL_DVDE_SERVOSTPS_READABLE    1
#define HAL_DVDE_SERVOSTPS_WRITABLE    0
#define HAL_DVDE_SERVOSTPS_SIGNED      0
#define HAL_DVDE_SERVOSTPS_ADR         0x10000488

#define HAL_DVDE_ADOLKSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_ADOLKSTPS_LSB         4
#define HAL_DVDE_ADOLKSTPS_MSB         4
#define HAL_DVDE_ADOLKSTPS_MASK        0x00000010
#define HAL_DVDE_ADOLKSTPS_TYPE        Bool
#define HAL_DVDE_ADOLKSTPS             HAL_DVDE_ADOLKSTPS_MASK
#define HAL_DVDE_ADOLKSTPS_READABLE    1
#define HAL_DVDE_ADOLKSTPS_WRITABLE    0
#define HAL_DVDE_ADOLKSTPS_SIGNED      0
#define HAL_DVDE_ADOLKSTPS_ADR         0x10000488

#define HAL_DVDE_WDOLKSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_WDOLKSTPS_LSB         3
#define HAL_DVDE_WDOLKSTPS_MSB         3
#define HAL_DVDE_WDOLKSTPS_MASK        0x00000008
#define HAL_DVDE_WDOLKSTPS_TYPE        Bool
#define HAL_DVDE_WDOLKSTPS             HAL_DVDE_WDOLKSTPS_MASK
#define HAL_DVDE_WDOLKSTPS_READABLE    1
#define HAL_DVDE_WDOLKSTPS_WRITABLE    0
#define HAL_DVDE_WDOLKSTPS_SIGNED      0
#define HAL_DVDE_WDOLKSTPS_ADR         0x10000488

#define HAL_DVDE_TGTMISTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_TGTMISTPS_LSB         2
#define HAL_DVDE_TGTMISTPS_MSB         2
#define HAL_DVDE_TGTMISTPS_MASK        0x00000004
#define HAL_DVDE_TGTMISTPS_TYPE        Bool
#define HAL_DVDE_TGTMISTPS             HAL_DVDE_TGTMISTPS_MASK
#define HAL_DVDE_TGTMISTPS_READABLE    1
#define HAL_DVDE_TGTMISTPS_WRITABLE    0
#define HAL_DVDE_TGTMISTPS_SIGNED      0
#define HAL_DVDE_TGTMISTPS_ADR         0x10000488

#define HAL_DVDE_HROLKSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_HROLKSTPS_LSB         1
#define HAL_DVDE_HROLKSTPS_MSB         1
#define HAL_DVDE_HROLKSTPS_MASK        0x00000002
#define HAL_DVDE_HROLKSTPS_TYPE        Bool
#define HAL_DVDE_HROLKSTPS             HAL_DVDE_HROLKSTPS_MASK
#define HAL_DVDE_HROLKSTPS_READABLE    1
#define HAL_DVDE_HROLKSTPS_WRITABLE    0
#define HAL_DVDE_HROLKSTPS_SIGNED      0
#define HAL_DVDE_HROLKSTPS_ADR         0x10000488

#define HAL_DVDE_BTOLKSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA0)
#define HAL_DVDE_BTOLKSTPS_LSB         0
#define HAL_DVDE_BTOLKSTPS_MSB         0
#define HAL_DVDE_BTOLKSTPS_MASK        0x00000001
#define HAL_DVDE_BTOLKSTPS_TYPE        Bool
#define HAL_DVDE_BTOLKSTPS             HAL_DVDE_BTOLKSTPS_MASK
#define HAL_DVDE_BTOLKSTPS_READABLE    1
#define HAL_DVDE_BTOLKSTPS_WRITABLE    0
#define HAL_DVDE_BTOLKSTPS_SIGNED      0
#define HAL_DVDE_BTOLKSTPS_ADR         0x10000488

// Register STPSTA1
#define HAL_DVDE_DHURSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA1)
#define HAL_DVDE_DHURSTPS_LSB         2
#define HAL_DVDE_DHURSTPS_MSB         2
#define HAL_DVDE_DHURSTPS_MASK        0x00000004
#define HAL_DVDE_DHURSTPS_TYPE        Bool
#define HAL_DVDE_DHURSTPS             HAL_DVDE_DHURSTPS_MASK
#define HAL_DVDE_DHURSTPS_READABLE    1
#define HAL_DVDE_DHURSTPS_WRITABLE    0
#define HAL_DVDE_DHURSTPS_SIGNED      0
#define HAL_DVDE_DHURSTPS_ADR         0x10000489

#define HAL_DVDE_ECCURSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA1)
#define HAL_DVDE_ECCURSTPS_LSB         1
#define HAL_DVDE_ECCURSTPS_MSB         1
#define HAL_DVDE_ECCURSTPS_MASK        0x00000002
#define HAL_DVDE_ECCURSTPS_TYPE        Bool
#define HAL_DVDE_ECCURSTPS             HAL_DVDE_ECCURSTPS_MASK
#define HAL_DVDE_ECCURSTPS_READABLE    1
#define HAL_DVDE_ECCURSTPS_WRITABLE    0
#define HAL_DVDE_ECCURSTPS_SIGNED      0
#define HAL_DVDE_ECCURSTPS_ADR         0x10000489

#define HAL_DVDE_MDURSTPS_REGISTER    (HAL_DVDEREG_MAP->STPSTA1)
#define HAL_DVDE_MDURSTPS_LSB         0
#define HAL_DVDE_MDURSTPS_MSB         0
#define HAL_DVDE_MDURSTPS_MASK        0x00000001
#define HAL_DVDE_MDURSTPS_TYPE        Bool
#define HAL_DVDE_MDURSTPS             HAL_DVDE_MDURSTPS_MASK
#define HAL_DVDE_MDURSTPS_READABLE    1
#define HAL_DVDE_MDURSTPS_WRITABLE    0
#define HAL_DVDE_MDURSTPS_SIGNED      0
#define HAL_DVDE_MDURSTPS_ADR         0x10000489

// Register DXCTRL
#define HAL_DVDE_DSVEN_REGISTER    (HAL_DVDEREG_MAP->DXCTRL)
#define HAL_DVDE_DSVEN_LSB         0
#define HAL_DVDE_DSVEN_MSB         0
#define HAL_DVDE_DSVEN_MASK        0x00000001
#define HAL_DVDE_DSVEN_TYPE        Bool
#define HAL_DVDE_DSVEN             HAL_DVDE_DSVEN_MASK
#define HAL_DVDE_DSVEN_READABLE    1
#define HAL_DVDE_DSVEN_WRITABLE    1
#define HAL_DVDE_DSVEN_SIGNED      0
#define HAL_DVDE_DSVEN_ADR         0x1000048A

// Registers DXSTADDRL/DXSTADDRM/DXSTADDRH
#define HAL_DVDE_DXSTADDR_REGISTER    (HAL_DVDEREG_MAP->DXSTADDRL)
#define HAL_DVDE_DXSTADDR_LSB         0
#define HAL_DVDE_DXSTADDR_MSB         23
#define HAL_DVDE_DXSTADDR_MASK        0x00FFFFFF
#define HAL_DVDE_DXSTADDR_TYPE        UInt32
#define HAL_DVDE_DXSTADDR             HAL_DVDE_DXSTADDR_MASK
#define HAL_DVDE_DXSTADDR_READABLE    1
#define HAL_DVDE_DXSTADDR_WRITABLE    0
#define HAL_DVDE_DXSTADDR_SIGNED      0
#define HAL_DVDE_DXSTADDR_ADR         0x1000048C

// Register DXSTFRAME
#define HAL_DVDE_DXSTFRAME_REGISTER    (HAL_DVDEREG_MAP->DXSTFRAME)
#define HAL_DVDE_DXSTFRAME_LSB         0
#define HAL_DVDE_DXSTFRAME_MSB         4
#define HAL_DVDE_DXSTFRAME_MASK        0x0000001F
#define HAL_DVDE_DXSTFRAME_TYPE        UByte
#define HAL_DVDE_DXSTFRAME             HAL_DVDE_DXSTFRAME_MASK
#define HAL_DVDE_DXSTFRAME_READABLE    1
#define HAL_DVDE_DXSTFRAME_WRITABLE    0
#define HAL_DVDE_DXSTFRAME_SIGNED      0
#define HAL_DVDE_DXSTFRAME_ADR         0x10000490

// Registers DXSTBITL/DXSTBITH
#define HAL_DVDE_DXSTBIT_REGISTER    (HAL_DVDEREG_MAP->DXSTBITL)
#define HAL_DVDE_DXSTBIT_LSB         0
#define HAL_DVDE_DXSTBIT_MSB         10
#define HAL_DVDE_DXSTBIT_MASK        0x000007FF
#define HAL_DVDE_DXSTBIT_TYPE        UInt16
#define HAL_DVDE_DXSTBIT             HAL_DVDE_DXSTBIT_MASK
#define HAL_DVDE_DXSTBIT_READABLE    1
#define HAL_DVDE_DXSTBIT_WRITABLE    0
#define HAL_DVDE_DXSTBIT_SIGNED      0
#define HAL_DVDE_DXSTBIT_ADR         0x10000492

// Register DXSTPHASE
#define HAL_DVDE_DXSTPHASE_REGISTER    (HAL_DVDEREG_MAP->DXSTPHASE)
#define HAL_DVDE_DXSTPHASE_LSB         0
#define HAL_DVDE_DXSTPHASE_MSB         1
#define HAL_DVDE_DXSTPHASE_MASK        0x00000003
#define HAL_DVDE_DXSTPHASE_TYPE        UByte
#define HAL_DVDE_DXSTPHASE             HAL_DVDE_DXSTPHASE_MASK
#define HAL_DVDE_DXSTPHASE_READABLE    1
#define HAL_DVDE_DXSTPHASE_WRITABLE    0
#define HAL_DVDE_DXSTPHASE_SIGNED      0
#define HAL_DVDE_DXSTPHASE_ADR         0x10000494

// Register WGCTRL
#define HAL_DVDE_TGTMBYP_REGISTER    (HAL_DVDEREG_MAP->WGCTRL)
#define HAL_DVDE_TGTMBYP_LSB         1
#define HAL_DVDE_TGTMBYP_MSB         1
#define HAL_DVDE_TGTMBYP_MASK        0x00000002
#define HAL_DVDE_TGTMBYP_TYPE        Bool
#define HAL_DVDE_TGTMBYP             HAL_DVDE_TGTMBYP_MASK
#define HAL_DVDE_TGTMBYP_READABLE    1
#define HAL_DVDE_TGTMBYP_WRITABLE    1
#define HAL_DVDE_TGTMBYP_SIGNED      0
#define HAL_DVDE_TGTMBYP_ADR         0x10000498

#define HAL_DVDE_WGATEN_REGISTER    (HAL_DVDEREG_MAP->WGCTRL)
#define HAL_DVDE_WGATEN_LSB         0
#define HAL_DVDE_WGATEN_MSB         0
#define HAL_DVDE_WGATEN_MASK        0x00000001
#define HAL_DVDE_WGATEN_TYPE        Bool
#define HAL_DVDE_WGATEN             HAL_DVDE_WGATEN_MASK
#define HAL_DVDE_WGATEN_READABLE    1
#define HAL_DVDE_WGATEN_WRITABLE    1
#define HAL_DVDE_WGATEN_SIGNED      0
#define HAL_DVDE_WGATEN_ADR         0x10000498

// Register SWSTAT
#define HAL_DVDE_WRCUTOFF_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_WRCUTOFF_LSB         5
#define HAL_DVDE_WRCUTOFF_MSB         5
#define HAL_DVDE_WRCUTOFF_MASK        0x00000020
#define HAL_DVDE_WRCUTOFF_TYPE        Bool
#define HAL_DVDE_WRCUTOFF             HAL_DVDE_WRCUTOFF_MASK
#define HAL_DVDE_WRCUTOFF_READABLE    1
#define HAL_DVDE_WRCUTOFF_WRITABLE    0
#define HAL_DVDE_WRCUTOFF_SIGNED      0
#define HAL_DVDE_WRCUTOFF_ADR         0x10000499

#define HAL_DVDE_STARTERR_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_STARTERR_LSB         4
#define HAL_DVDE_STARTERR_MSB         4
#define HAL_DVDE_STARTERR_MASK        0x00000010
#define HAL_DVDE_STARTERR_TYPE        Bool
#define HAL_DVDE_STARTERR             HAL_DVDE_STARTERR_MASK
#define HAL_DVDE_STARTERR_READABLE    1
#define HAL_DVDE_STARTERR_WRITABLE    0
#define HAL_DVDE_STARTERR_SIGNED      0
#define HAL_DVDE_STARTERR_ADR         0x10000499

#define HAL_DVDE_STOPERR_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_STOPERR_LSB         3
#define HAL_DVDE_STOPERR_MSB         3
#define HAL_DVDE_STOPERR_MASK        0x00000008
#define HAL_DVDE_STOPERR_TYPE        Bool
#define HAL_DVDE_STOPERR             HAL_DVDE_STOPERR_MASK
#define HAL_DVDE_STOPERR_READABLE    1
#define HAL_DVDE_STOPERR_WRITABLE    0
#define HAL_DVDE_STOPERR_SIGNED      0
#define HAL_DVDE_STOPERR_ADR         0x10000499

#define HAL_DVDE_NORMSTOP_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_NORMSTOP_LSB         2
#define HAL_DVDE_NORMSTOP_MSB         2
#define HAL_DVDE_NORMSTOP_MASK        0x00000004
#define HAL_DVDE_NORMSTOP_TYPE        Bool
#define HAL_DVDE_NORMSTOP             HAL_DVDE_NORMSTOP_MASK
#define HAL_DVDE_NORMSTOP_READABLE    1
#define HAL_DVDE_NORMSTOP_WRITABLE    0
#define HAL_DVDE_NORMSTOP_SIGNED      0
#define HAL_DVDE_NORMSTOP_ADR         0x10000499

#define HAL_DVDE_SYSWRT_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_SYSWRT_LSB         1
#define HAL_DVDE_SYSWRT_MSB         1
#define HAL_DVDE_SYSWRT_MASK        0x00000002
#define HAL_DVDE_SYSWRT_TYPE        Bool
#define HAL_DVDE_SYSWRT             HAL_DVDE_SYSWRT_MASK
#define HAL_DVDE_SYSWRT_READABLE    1
#define HAL_DVDE_SYSWRT_WRITABLE    0
#define HAL_DVDE_SYSWRT_SIGNED      0
#define HAL_DVDE_SYSWRT_ADR         0x10000499

#define HAL_DVDE_SYSSEEK_REGISTER    (HAL_DVDEREG_MAP->SWSTAT)
#define HAL_DVDE_SYSSEEK_LSB         0
#define HAL_DVDE_SYSSEEK_MSB         0
#define HAL_DVDE_SYSSEEK_MASK        0x00000001
#define HAL_DVDE_SYSSEEK_TYPE        Bool
#define HAL_DVDE_SYSSEEK             HAL_DVDE_SYSSEEK_MASK
#define HAL_DVDE_SYSSEEK_READABLE    1
#define HAL_DVDE_SYSSEEK_WRITABLE    0
#define HAL_DVDE_SYSSEEK_SIGNED      0
#define HAL_DVDE_SYSSEEK_ADR         0x10000499

// Register BACTRL1
#define HAL_DVDE_BADTGT_REGISTER    (HAL_DVDEREG_MAP->BACTRL1)
#define HAL_DVDE_BADTGT_LSB         2
#define HAL_DVDE_BADTGT_MSB         2
#define HAL_DVDE_BADTGT_MASK        0x00000004
#define HAL_DVDE_BADTGT_TYPE        Bool
#define HAL_DVDE_BADTGT             HAL_DVDE_BADTGT_MASK
#define HAL_DVDE_BADTGT_READABLE    1
#define HAL_DVDE_BADTGT_WRITABLE    1
#define HAL_DVDE_BADTGT_SIGNED      0
#define HAL_DVDE_BADTGT_ADR         0x1000049A

#define HAL_DVDE_BAPOL_REGISTER    (HAL_DVDEREG_MAP->BACTRL1)
#define HAL_DVDE_BAPOL_LSB         1
#define HAL_DVDE_BAPOL_MSB         1
#define HAL_DVDE_BAPOL_MASK        0x00000002
#define HAL_DVDE_BAPOL_TYPE        Bool
#define HAL_DVDE_BAPOL             HAL_DVDE_BAPOL_MASK
#define HAL_DVDE_BAPOL_READABLE    1
#define HAL_DVDE_BAPOL_WRITABLE    1
#define HAL_DVDE_BAPOL_SIGNED      0
#define HAL_DVDE_BAPOL_ADR         0x1000049A

#define HAL_DVDE_BADIMODE_REGISTER    (HAL_DVDEREG_MAP->BACTRL1)
#define HAL_DVDE_BADIMODE_LSB         0
#define HAL_DVDE_BADIMODE_MSB         0
#define HAL_DVDE_BADIMODE_MASK        0x00000001
#define HAL_DVDE_BADIMODE_TYPE        Bool
#define HAL_DVDE_BADIMODE             HAL_DVDE_BADIMODE_MASK
#define HAL_DVDE_BADIMODE_READABLE    1
#define HAL_DVDE_BADIMODE_WRITABLE    1
#define HAL_DVDE_BADIMODE_SIGNED      0
#define HAL_DVDE_BADIMODE_ADR         0x1000049A

// Registers BACTRL2L/BACTRL2H
#define HAL_DVDE_BLADLT_REGISTER    (HAL_DVDEREG_MAP->BACTRL2L)
#define HAL_DVDE_BLADLT_LSB         0
#define HAL_DVDE_BLADLT_MSB         15
#define HAL_DVDE_BLADLT_MASK        0x0000FFFF
#define HAL_DVDE_BLADLT_TYPE        UInt16
#define HAL_DVDE_BLADLT             HAL_DVDE_BLADLT_MASK
#define HAL_DVDE_BLADLT_READABLE    1
#define HAL_DVDE_BLADLT_WRITABLE    1
#define HAL_DVDE_BLADLT_SIGNED      0
#define HAL_DVDE_BLADLT_ADR         0x1000049C

// Register LBCTRL
#define HAL_DVDE_LBCTREN_REGISTER    (HAL_DVDEREG_MAP->LBCTRL)
#define HAL_DVDE_LBCTREN_LSB         5
#define HAL_DVDE_LBCTREN_MSB         5
#define HAL_DVDE_LBCTREN_MASK        0x00000020
#define HAL_DVDE_LBCTREN_TYPE        Bool
#define HAL_DVDE_LBCTREN             HAL_DVDE_LBCTREN_MASK
#define HAL_DVDE_LBCTREN_READABLE    1
#define HAL_DVDE_LBCTREN_WRITABLE    1
#define HAL_DVDE_LBCTREN_SIGNED      0
#define HAL_DVDE_LBCTREN_ADR         0x1000049E

#define HAL_DVDE_LBPOS_REGISTER    (HAL_DVDEREG_MAP->LBCTRL)
#define HAL_DVDE_LBPOS_LSB         0
#define HAL_DVDE_LBPOS_MSB         4
#define HAL_DVDE_LBPOS_MASK        0x0000001F
#define HAL_DVDE_LBPOS_TYPE        halDVDE_LeadBlkPosition_t
#define HAL_DVDE_LBPOS             HAL_DVDE_LBPOS_MASK
#define HAL_DVDE_LBPOS_READABLE    1
#define HAL_DVDE_LBPOS_WRITABLE    1
#define HAL_DVDE_LBPOS_SIGNED      0
#define HAL_DVDE_LBPOS_ADR         0x1000049E

// Registers WGSSCNTL/WGSSCNTH
#define HAL_DVDE_WGSSKCT_REGISTER    (HAL_DVDEREG_MAP->WGSSCNTL)
#define HAL_DVDE_WGSSKCT_LSB         0
#define HAL_DVDE_WGSSKCT_MSB         15
#define HAL_DVDE_WGSSKCT_MASK        0x0000FFFF
#define HAL_DVDE_WGSSKCT_TYPE        UInt16
#define HAL_DVDE_WGSSKCT             HAL_DVDE_WGSSKCT_MASK
#define HAL_DVDE_WGSSKCT_READABLE    1
#define HAL_DVDE_WGSSKCT_WRITABLE    1
#define HAL_DVDE_WGSSKCT_SIGNED      0
#define HAL_DVDE_WGSSKCT_ADR         0x100004A0

// Register DVDESPARE
#define HAL_DVDE_BPIDSTR_REGISTER    (HAL_DVDEREG_MAP->DVDESPARE)
#define HAL_DVDE_BPIDSTR_LSB         0
#define HAL_DVDE_BPIDSTR_MSB         0
#define HAL_DVDE_BPIDSTR_MASK        0x00000001
#define HAL_DVDE_BPIDSTR_TYPE        Bool
#define HAL_DVDE_BPIDSTR             HAL_DVDE_BPIDSTR_MASK
#define HAL_DVDE_BPIDSTR_READABLE    1
#define HAL_DVDE_BPIDSTR_WRITABLE    0
#define HAL_DVDE_BPIDSTR_SIGNED      0
#define HAL_DVDE_BPIDSTR_ADR         0x100004A2

#if (CHIP_REV >= 0xC0)

// Register DVDDBGBUS
#define HAL_DVDE_DVDEDBGMD_REGISTER    (HAL_DVDEREG_MAP->DVDDBGBUS)
#define HAL_DVDE_DVDEDBGMD_LSB         3
#define HAL_DVDE_DVDEDBGMD_MSB         5
#define HAL_DVDE_DVDEDBGMD_MASK        0x00000038
#define HAL_DVDE_DVDEDBGMD_TYPE        halDVDE_DVDEDebugBusCtrl_t
#define HAL_DVDE_DVDEDBGMD             HAL_DVDE_DVDEDBGMD_MASK
#define HAL_DVDE_DVDEDBGMD_READABLE    1
#define HAL_DVDE_DVDEDBGMD_WRITABLE    1
#define HAL_DVDE_DVDEDBGMD_SIGNED      0
#define HAL_DVDE_DVDEDBGMD_ADR         0x100004F0

#define HAL_DVDE_DVDEDBGSL_REGISTER    (HAL_DVDEREG_MAP->DVDDBGBUS)
#define HAL_DVDE_DVDEDBGSL_LSB         0
#define HAL_DVDE_DVDEDBGSL_MSB         2
#define HAL_DVDE_DVDEDBGSL_MASK        0x00000007
#define HAL_DVDE_DVDEDBGSL_TYPE        halDVDE_DVDEDebugBusSel_t
#define HAL_DVDE_DVDEDBGSL             HAL_DVDE_DVDEDBGSL_MASK
#define HAL_DVDE_DVDEDBGSL_READABLE    1
#define HAL_DVDE_DVDEDBGSL_WRITABLE    1
#define HAL_DVDE_DVDEDBGSL_SIGNED      0
#define HAL_DVDE_DVDEDBGSL_ADR         0x100004F0

#endif // #if (CHIP_REV >= 0xC0)

// Register DVDETST1
#define HAL_DVDE_DVDETST1_REGISTER    (HAL_DVDEREG_MAP->DVDETST1)
#define HAL_DVDE_DVDETST1_LSB         0
#define HAL_DVDE_DVDETST1_MSB         7
#define HAL_DVDE_DVDETST1_MASK        0x000000FF
#define HAL_DVDE_DVDETST1_TYPE        UByte
#define HAL_DVDE_DVDETST1             HAL_DVDE_DVDETST1_MASK
#define HAL_DVDE_DVDETST1_READABLE    1
#define HAL_DVDE_DVDETST1_WRITABLE    1
#define HAL_DVDE_DVDETST1_SIGNED      0
#define HAL_DVDE_DVDETST1_ADR         0x100004FD

// Register DVDETST2
#define HAL_DVDE_ENCHPRI_REGISTER    (HAL_DVDEREG_MAP->DVDETST2)
#define HAL_DVDE_ENCHPRI_LSB         7
#define HAL_DVDE_ENCHPRI_MSB         7
#define HAL_DVDE_ENCHPRI_MASK        0x00000080
#define HAL_DVDE_ENCHPRI_TYPE        Bool
#define HAL_DVDE_ENCHPRI             HAL_DVDE_ENCHPRI_MASK
#define HAL_DVDE_ENCHPRI_READABLE    1
#define HAL_DVDE_ENCHPRI_WRITABLE    1
#define HAL_DVDE_ENCHPRI_SIGNED      0
#define HAL_DVDE_ENCHPRI_ADR         0x100004FE

// Register DVDETST3
#define HAL_DVDE_DVDEMUX_REGISTER    (HAL_DVDEREG_MAP->DVDETST3)
#define HAL_DVDE_DVDEMUX_LSB         0
#define HAL_DVDE_DVDEMUX_MSB         7
#define HAL_DVDE_DVDEMUX_MASK        0x000000FF
#define HAL_DVDE_DVDEMUX_TYPE        UByte
#define HAL_DVDE_DVDEMUX             HAL_DVDE_DVDEMUX_MASK
#define HAL_DVDE_DVDEMUX_READABLE    1
#define HAL_DVDE_DVDEMUX_WRITABLE    1
#define HAL_DVDE_DVDEMUX_SIGNED      0
#define HAL_DVDE_DVDEMUX_ADR         0x100004FF

// Enumerations
typedef enum
{
	halDVDE_HDDVDR     = 0,    // HD DVD-R media
	halDVDE_HDDVDRW    = 1,    // HD DVD-RW media
	halDVDE_HDDVDRAM   = 2,    // HD DVD-RAM media
	halDVDE_HDDVDChina = 3     // HD DVD China-only media
} halDVDE_HDDVDTypeSelect_t;

typedef enum
{
	halDVDE_DVDminus = 0,    // DVD-R or DVD-RW media
	halDVDE_DVDplus  = 1,    // DVD+R or DVD+RW media
	halDVDE_DVDRAM   = 2,    // DVD-RAM media
	halDVDE_HDDVD    = 3     // HD DVD media
} halDVDE_DVDTypeSelect_t;

typedef enum
{
	halDVDE_DataZone    = 0,    // Data Zone
	halDVDE_LeadinZone  = 1,    // Leadin Zone
	halDVDE_LeadoutZone = 2,    // Leadout Zone
	halDVDE_MiddleZone  = 3     // Middle Zone
} halDVDE_Zonetype_t;

typedef enum
{
	halDVDE_SeqeuntialWr = 0,    // Sequential Write Mode
	halDVDE_LinkList     = 1,    // Link List Operation
	halDVDE_ListListJump = 2     // Link List with Jump Operation
} halDVDE_WrAttribute_t;

typedef enum
{
	halDVDE_AutoMode      = 0,    // Automated Mode
	halDVDE_ModeA         = 1,    // Script Format Mode A; ECC and Modulation Bypass Mode
	halDVDE_ModeB         = 2,    // Script Format Mode B1 and B2
	halDVDE_OPCRandomData = 3     // OPC Random Data Write
} halDVDE_WrModeCtrl_t;

typedef enum
{
	halDVDE_BefTarget_0Sector  = 0,
	halDVDE_BefTarget_1Sector  = 1,
	halDVDE_BefTarget_2Sector  = 2,
	halDVDE_BefTarget_3Sector  = 3,
	halDVDE_BefTarget_4Sector  = 4,
	halDVDE_BefTarget_5Sector  = 5,
	halDVDE_BefTarget_6Sector  = 6,
	halDVDE_BefTarget_7Sector  = 7,
	halDVDE_BefTarget_8Sector  = 8,
	halDVDE_BefTarget_9Sector  = 9,
	halDVDE_BefTarget_10Sector = 10,
	halDVDE_BefTarget_11Sector = 11,
	halDVDE_BefTarget_12Sector = 12,
	halDVDE_BefTarget_13Sector = 13,
	halDVDE_BefTarget_14Sector = 14,
	halDVDE_BefTarget_15Sector = 15,
	halDVDE_BefTarget_16Sector = 16,
	halDVDE_BefTarget_17Sector = 17,
	halDVDE_BefTarget_18Sector = 18,
	halDVDE_BefTarget_19Sector = 19,
	halDVDE_BefTarget_20Sector = 20,
	halDVDE_BefTarget_21Sector = 21,
	halDVDE_BefTarget_22Sector = 22,
	halDVDE_BefTarget_23Sector = 23,
	halDVDE_BefTarget_24Sector = 24,
	halDVDE_BefTarget_25Sector = 25,
	halDVDE_BefTarget_26Sector = 26,
	halDVDE_BefTarget_27Sector = 27,
	halDVDE_BefTarget_28Sector = 28,
	halDVDE_BefTarget_29Sector = 29,
	halDVDE_BefTarget_30Sector = 30,
	halDVDE_BefTarget_31Sector = 31 
} halDVDE_LeadBlkPosition_t;

#if (CHIP_REV >= 0xC0)

typedef enum
{
	halDVDE_DVDEDbgMode_OFF      = 0,
	halDVDE_DVDEDbgMode_GENERIC1 = 1,
	halDVDE_DVDEDbgMode_GENERIC2 = 2,
	halDVDE_DVDEDbgMode_SYNC     = 3,
	halDVDE_DVDEDbgMode_MOD      = 4,
	halDVDE_DVDEDbgMode_ECC      = 5,
	halDVDE_DVDEDbgMode_BUF      = 6,
	halDVDE_DVDEDbgMode_GENERIC3 = 7 
} halDVDE_DVDEDebugBusCtrl_t;

typedef enum
{
	halDVDE_DVDEDbgSel_SLOT0 = 0,
	halDVDE_DVDEDbgSel_SLOT1 = 1,
	halDVDE_DVDEDbgSel_SLOT2 = 2,
	halDVDE_DVDEDbgSel_SLOT3 = 3,
	halDVDE_DVDEDbgSel_SLOT4 = 4,
	halDVDE_DVDEDbgSel_SLOT5 = 5 
} halDVDE_DVDEDebugBusSel_t;

#endif // #if (CHIP_REV >= 0xC0)

#endif /* __REG_DVD_ENCODER_H__ */

