/****************************************************************************
*                (c) Copyright 2001,2002, 2003, 2004 SUNEXT DESIGN, INC.
*                           All Right Reserved
*
*
* FILENAME:   at_int.h
*
* DESCRIPTION
*   This file contains the declaim of at_int.c service routines.
*
* NOTES:
*
**************************** SUNEXT  CONFIDENTIAL *******************************/
#ifndef __AT_INT1_H__
#define __AT_INT1_H__

#include ".\common\globtype.h"

extern void GetPacketCommand(void);

#endif /* __AT_INT1_H__ */
