/****************************************************************************
*                (c) Copyright 2001,2002,2003, 2004 SUNEXT DESIGN, INC.
*                           All Right Reserved
*
*
*
* FILENAME:   cstart.h
*
* DESCRIPTION
*   This file contains declarations for assembly functions defined
*   if file cstart.s
*
* NOTES:
*
*********************** SUNEXT CONFIDENTIAL *******************************/

#ifndef __CSTART_H__
#define __CSTART_H__

extern vULONG Iram_Knl_save_counter;

#endif /* __CSTART_H__ */
