/****************************************************************************
*                (c) Copyright 2001, 2002, 2003, 2004 SUNEXT DESIGN, INC.
*                           All Right Reserved
*
*
* FILENAME:   gp_rdsub.h
*
* DESCRIPTION:
*   This file contains command handler of read sub-channel command
*
* NOTES:
*
**************************** SUNEXT CONFIDENTIAL *******************************/

#ifndef __GP_RDSUB_H__
#define __GP_RDSUB_H__

extern void ReadSubChannelCommand(void);
extern vBOOL ReadSubChannelFormat1(BYTE flag);

#endif /* __GP_RDSUB_H__ */
