/******************************************************************************
*                (c) Copyright 2001, 2002, 2003, 2004 SUNEXT DESIGN, INC.
*                           All Right Reserved
*
*
* FILENAME:   gp_rhead.h
*
* DESCRIPTION:
*   This file contains read header command handler
*
* NOTES:
*
**************************** SUNEXT CONFIDENTIAL *******************************/

#ifndef __GP_RHEAD_H__
#define __GP_RHEAD_H__

extern void ReadHeaderCommand(void);

#endif /* __GP_RHEAD_H__ */
