/****************************************************************************
*                (c) Copyright 2001,2002,2003, 2004 SUNEXT DESIGN, INC
*                           All Rights Reserved
*
*
* FILENAME:   gp_seek.h
*
* DESCRIPTION:
*   This file contains command handler of ATAPI command
*
* NOTES:
*
**************************** SUNEXT CONFIDENTIAL *******************************/

#ifndef __GP_SEEK_H__
#define __GP_SEEK_H__

extern void CDSeek10Command(void);


#endif /* __GP_SEEK_H__ */
