/*******************************************************************************
*                (c) Copyright 2001, 2002, 2003, 2004 SUNEXT DESIGN, INC.
*                           All Right Reserved
*
*
* FILENAME:   s2b_main.h
*
* DESCRIPTION
*   This file contains Player interface.
*
* NOTES:
*
*
**************************** SUNEXT CONFIDENTIAL *******************************/

#ifndef __S2B_MAIN_H__
#define __S2B_MAIN_H__

extern void InitializePlayer(void);

#endif /* __S2B_MAIN_H__ */

